"""Pull the writing lesson out of each Empower unit.

Every unit ends with a "Skills for Writing" lesson whose objective is printed at
the top - "Learn to write a review of a restaurant or cafe" - and whose task is
the WRITING section at the end. Those two together are a better writing question
than anything invented, because they are the one the class has just prepared for.

    python3 extract_writing.py            report what it finds
    python3 extract_writing.py --write    write writing_bank.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pdfsplit
import pdftext

BOOKS = [
    ("Beginner", "~/Downloads/beginner A1 sb.pdf"),
    ("Elementary", "~/Downloads/Empower_A2_Elementary_SB.pdf"),
    ("Pre-Intermediate", "~/Downloads/Empower_B1_Pre_Intermediate_SB.pdf"),
    ("Intermediate", "~/Downloads/Empower Intermediate SB@EnglishReserve.pdf"),
]

LEARN = re.compile(r"(?i)\b(?:learn|leam)\s+to\s+(write[^.\n]{4,90})")
UNIT = re.compile(r"(?i)\bunit\s*(\d{1,2})\b")


def pages_text(path):
    doc = pdfsplit.Document(os.path.expanduser(path))
    out = []
    for pg in doc.pages():
        try:
            out.append([" ".join(l.split()) for l in pdftext.page_text(doc, pg)])
        except Exception:
            out.append([])
    return out


def clean(s):
    s = re.sub(r"\s+", " ", s).strip(" .:;-")
    s = s.replace("Leam", "Learn")
    # the objective runs straight into the lesson's language aim and the section
    # headings, none of which belongs in a question
    s = re.split(r"[©®\u0444\u041f\u25a1\u0416]|\(\u0444|\bD\s+SPEAKING|"
                 r"\bSPEAKING AND|\bLISTENING\b|\bREADING\b|\bWRITING\b", s)[0]
    s = re.sub(r"\s+[A-Z]{2,}.*$", "", s)
    # two objectives run on into the next heading in lower case, so cut at the
    # point where a second capitalised phrase starts
    s = re.split(r"\s(?=(?:Offering|Contrasting|Describing|Organising|Introducing|"
                 r"Summarising|Positive|The language)\b)", s)[0]
    s = re.sub(r"\s+\d+(\s+\d+)*$", "", s).strip(" .:;-")
    return s[0].upper() + s[1:] if s else s


def find(level, path):
    pages = pages_text(path)
    found, unit_now = [], None
    for i, page in enumerate(pages):
        blob = " ".join(page)
        m = UNIT.search(" ".join(page[:8]))
        if m and 1 <= int(m.group(1)) <= 16:
            unit_now = int(m.group(1))
        if "Skills for Writing" not in blob and "SKILLS FOR WRITING" not in blob:
            continue
        obj = LEARN.search(blob)
        if not obj:
            continue
        # the lesson number is often printed as "6D" beside the title
        lesson = re.search(r"\b(\d{1,2})\s*D\b", " ".join(page[:6]))
        unit = int(lesson.group(1)) if lesson else unit_now
        title = next((l for l in page[:4]
                      if len(l) > 8 and "Skills for Writing" not in l), "")
        found.append({"level": level, "unit": unit, "page": i + 1,
                      "title": clean(title), "task": clean(obj.group(1))})
    # one per unit, the first time it appears
    best = {}
    for f in found:
        if f["unit"] and f["unit"] not in best:
            best[f["unit"]] = f
    return [best[u] for u in sorted(best)]


def main():
    everything = []
    for level, path in BOOKS:
        if not os.path.exists(os.path.expanduser(path)):
            print("missing:", path)
            continue
        try:
            rows = find(level, path)
        except Exception as exc:
            print("\n=== %s: could not be read (%s)" % (level, exc))
            continue
        print("\n=== %s: %d writing lessons" % (level, len(rows)))
        for r in rows:
            print("   unit %-3s p%-4s %s" % (r["unit"], r["page"], r["task"][:70]))
        everything += rows
    if "--write" in sys.argv:
        with open("writing_bank.py", "w") as fh:
            fh.write('"""Writing lessons lifted from the Empower student books.\n\n'
                     'Generated by extract_writing.py - each unit\'s D lesson, which is\n'
                     'the writing one, with the objective the book states.\n"""\n\n')
            fh.write("LESSONS = [\n")
            for r in everything:
                fh.write("    %r,\n" % (r,))
            fh.write("]\n")
        print("\nwrote writing_bank.py with %d lessons" % len(everything))
    return 0


if __name__ == "__main__":
    sys.exit(main())
