"""Writing lessons lifted from the Empower student books.

Generated by extract_writing.py - each unit's D lesson, which is
the writing one, with the objective the book states.
"""

LESSONS = [
    {'level': 'Intermediate', 'unit': 1, 'page': 18, 'title': 'Visual learners', 'task': 'Write a guide'},
    {'level': 'Intermediate', 'unit': 3, 'page': 42, 'title': 'He wanted to see the world', 'task': 'Write about someone’s life'},
    {'level': 'Intermediate', 'unit': 4, 'page': 54, 'title': 'No experience needed', 'task': 'Write an informal online advert'},
    {'level': 'Intermediate', 'unit': 5, 'page': 66, 'title': 'THE', 'task': 'Write a discussion essay'},
    {'level': 'Intermediate', 'unit': 6, 'page': 78, 'title': 'It’s definitely worth a visit', 'task': 'Write a review of a restaurant or cafe'},
    {'level': 'Intermediate', 'unit': 7, 'page': 90, 'title': 'Make yourselves at home', 'task': 'Write a note with useful information'},
    {'level': 'Intermediate', 'unit': 8, 'page': 102, 'title': 'Fortunately, everything was all right', 'task': 'Write an email summary of a news story'},
    {'level': 'Intermediate', 'unit': 9, 'page': 114, 'title': 'I like going out, b u t', 'task': 'Write an article'},
]

# Elementary's book could not be read - its fonts carry no usable character map -
# so these are written to the unit topics from the teacher's own material bank,
# which are the Empower A2 unit titles.
LESSONS += [
    {"level": "Elementary", "unit": 1, "page": None, "title": "People",
     "task": "Write a short profile of someone in your family or a friend"},
    {"level": "Elementary", "unit": 2, "page": None, "title": "Work and study",
     "task": "Write an email about your job or your studies"},
    {"level": "Elementary", "unit": 3, "page": None, "title": "Daily life",
     "task": "Write about a typical day in your life"},
    {"level": "Elementary", "unit": 4, "page": None, "title": "Food",
     "task": "Write a review of a restaurant or a description of a meal you like"},
    {"level": "Elementary", "unit": 5, "page": None, "title": "Places",
     "task": "Write a description of a place you know well"},
    {"level": "Elementary", "unit": 6, "page": None, "title": "Family",
     "task": "Write an email telling a friend about your family"},
    {"level": "Elementary", "unit": 7, "page": None, "title": "Trips",
     "task": "Write about a trip you took, and what happened"},
    {"level": "Elementary", "unit": 8, "page": None, "title": "Fit and healthy",
     "task": "Write advice for a friend who wants to be healthier"},
    {"level": "Elementary", "unit": 9, "page": None, "title": "Clothes and shopping",
     "task": "Write an email about something you bought, and whether it was worth it"},
    {"level": "Elementary", "unit": 10, "page": None, "title": "Communication",
     "task": "Write about how you keep in touch with people, and which way you prefer"},
    {"level": "Elementary", "unit": 11, "page": None, "title": "Entertainment",
     "task": "Write a review of a film, a series or a concert"},
    {"level": "Elementary", "unit": 12, "page": None, "title": "Travel",
     "task": "Write an email planning a holiday with a friend"},
]

# How the lessons are grouped when taught. Writing is the D lesson, so at the
# levels where B and D are taught together it belongs to that slot.
GROUPS = {
    "Beginner": ["A", "B", "C"],
    "Elementary": ["A+C", "B+D", "Academic Skills + Reading Plus"],
    "Pre-Intermediate": ["A+C", "B+D", "Academic Skills + Reading Plus"],
    "Intermediate": ["A+C", "B+D", "Academic Skills + Reading Plus"],
}
WRITING_SLOT = {"Beginner": "C", "Elementary": "B+D",
                "Pre-Intermediate": "B+D", "Intermediate": "B+D"}
