"""A1 first words - the Beginner gap ladder, fifteen steps.

Cambridge publishes a vocabulary list for A2 Key but nothing below it, so
this is not a copy of an exam list. It is the floor under the course book:
the words a beginner needs in order to read a simple instruction, follow a
lesson, or say something about their own day.

It sits in its own door, the way the A2, B1 and B2 ladders do for the
higher levels, so a Beginner class can climb it alongside the units.

Meanings in Uzbek and Russian.
"""

LEVEL = "Beginner"
BOOK = "A1 first words"
PAST_FROM = 1          # these are single words, not sentences

NUMBERS = [
    ("one", "bir / один"),
    ("two", "ikki / два"),
    ("three", "uch / три"),
    ("four", "to'rt / четыре"),
    ("five", "besh / пять"),
    ("six", "olti / шесть"),
    ("seven", "yetti / семь"),
    ("eight", "sakkiz / восемь"),
    ("nine", "to'qqiz / девять"),
    ("ten", "o'n / десять"),
    ("eleven", "o'n bir / одиннадцать"),
    ("twelve", "o'n ikki / двенадцать"),
    ("thirteen", "o'n uch / тринадцать"),
    ("fifteen", "o'n besh / пятнадцать"),
    ("thirty", "o'ttiz / тридцать"),
    ("forty", "qirq / сорок"),
    ("sixty", "oltmish / шестьдесят"),
    ("seventy", "yetmish / семьдесят"),
    ("eighty", "sakson / восемьдесят"),
    ("ninety", "to'qson / девяносто"),
    ("a million", "million / миллион"),
    ("number", "raqam / номер"),
    ("half", "yarim / половина"),
    ("a few", "bir nechta / несколько"),
    ("a lot of", "ko'p / много"),
]

QUESTIONS = [
    ("what", "nima / что"),
    ("who", "kim / кто"),
    ("where", "qayerda / где"),
    ("when", "qachon / когда"),
    ("why", "nega / почему"),
    ("how", "qanday / как"),
    ("how much", "qancha (narx) / сколько (цена)"),
    ("how many", "nechta / сколько (количество)"),
    ("how old", "necha yosh / сколько лет"),
    ("how long", "qancha vaqt / как долго"),
    ("which", "qaysi / который"),
    ("whose", "kimniki / чей"),
    ("yes", "ha / да"),
    ("no", "yo'q / нет"),
    ("maybe", "balki / возможно"),
    ("please", "iltimos / пожалуйста"),
    ("thanks", "rahmat / спасибо"),
    ("sorry", "kechirasiz / извините"),
    ("of course", "albatta / конечно"),
    ("I think so", "menimcha shunday / думаю, да"),
    ("I don't know", "bilmayman / я не знаю"),
    ("again", "yana / снова"),
    ("also", "shuningdek / также"),
    ("too", "ham / тоже"),
    ("only", "faqat / только"),
]

VERBS1 = [
    ("be", "bo'lmoq / быть"),
    ("have", "ega bo'lmoq / иметь"),
    ("do", "qilmoq / делать"),
    ("go", "bormoq / идти"),
    ("come", "kelmoq / приходить"),
    ("see", "ko'rmoq / видеть"),
    ("look", "qaramoq / смотреть"),
    ("hear", "eshitmoq / слышать"),
    ("say", "aytmoq / говорить"),
    ("speak", "so'zlashmoq / разговаривать"),
    ("tell", "gapirib bermoq / рассказывать"),
    ("ask", "so'ramoq / спрашивать"),
    ("answer", "javob bermoq / отвечать"),
    ("know", "bilmoq / знать"),
    ("think", "o'ylamoq / думать"),
    ("want", "xohlamoq / хотеть"),
    ("need", "kerak bo'lmoq / нуждаться"),
    ("like", "yoqtirmoq / нравиться"),
    ("love", "sevmoq / любить"),
    ("give", "bermoq / давать"),
    ("take", "olmoq / брать"),
    ("get", "olmoq, erishmoq / получать"),
    ("make", "yasamoq / делать, создавать"),
    ("put", "qo'ymoq / класть"),
    ("find", "topmoq / находить"),
]

VERBS2 = [
    ("eat", "yemoq / есть"),
    ("drink", "ichmoq / пить"),
    ("sleep", "uxlamoq / спать"),
    ("wake up", "uyg'onmoq / просыпаться"),
    ("work", "ishlamoq / работать"),
    ("study", "o'qimoq / учиться"),
    ("read", "o'qib chiqmoq / читать"),
    ("write", "yozmoq / писать"),
    ("listen", "tinglamoq / слушать"),
    ("watch", "tomosha qilmoq / смотреть"),
    ("play", "o'ynamoq / играть"),
    ("run", "yugurmoq / бегать"),
    ("walk", "yurmoq / ходить пешком"),
    ("sit", "o'tirmoq / сидеть"),
    ("stand", "turmoq / стоять"),
    ("open", "ochmoq / открывать"),
    ("close", "yopmoq / закрывать"),
    ("start", "boshlamoq / начинать"),
    ("finish", "tugatmoq / заканчивать"),
    ("help", "yordam bermoq / помогать"),
    ("wait", "kutmoq / ждать"),
    ("buy", "sotib olmoq / покупать"),
    ("pay", "to'lamoq / платить"),
    ("live", "yashamoq / жить"),
    ("meet", "uchrashmoq / встречать"),
]

ADJ1 = [
    ("big", "katta / большой"),
    ("small", "kichik / маленький"),
    ("long", "uzun / длинный"),
    ("short", "qisqa / короткий"),
    ("new", "yangi / новый"),
    ("old", "eski / старый"),
    ("good", "yaxshi / хороший"),
    ("bad", "yomon / плохой"),
    ("hot", "issiq / горячий"),
    ("cold", "sovuq / холодный"),
    ("easy", "oson / лёгкий"),
    ("difficult", "qiyin / трудный"),
    ("fast", "tez / быстрый"),
    ("slow", "sekin / медленный"),
    ("happy", "baxtli / счастливый"),
    ("sad", "xafa / грустный"),
    ("beautiful", "go'zal / красивый"),
    ("ugly", "xunuk / некрасивый"),
    ("clean", "toza / чистый"),
    ("dirty", "iflos / грязный"),
    ("full", "to'la / полный"),
    ("empty", "bo'sh / пустой"),
    ("right", "to'g'ri / правильный"),
    ("wrong", "noto'g'ri / неправильный"),
    ("same", "bir xil / одинаковый"),
]

ADJ2 = [
    ("expensive", "qimmat / дорогой"),
    ("cheap", "arzon / дешёвый"),
    ("young", "yosh / молодой"),
    ("tall", "baland bo'yli / высокий"),
    ("heavy", "og'ir / тяжёлый"),
    ("light", "yengil / лёгкий по весу"),
    ("strong", "kuchli / сильный"),
    ("weak", "kuchsiz / слабый"),
    ("tired", "charchagan / уставший"),
    ("hungry", "och / голодный"),
    ("thirsty", "chanqagan / испытывающий жажду"),
    ("ready", "tayyor / готовый"),
    ("busy", "band / занятый"),
    ("free", "bo'sh / свободный"),
    ("open", "ochiq / открытый"),
    ("closed", "yopiq / закрытый"),
    ("important", "muhim / важный"),
    ("interesting", "qiziqarli / интересный"),
    ("boring", "zerikarli / скучный"),
    ("funny", "kulgili / смешной"),
    ("nice", "yoqimli / приятный"),
    ("kind", "mehribon / добрый"),
    ("quiet", "jim / тихий"),
    ("loud", "baland ovozli / громкий"),
    ("famous", "mashhur / известный"),
]

PEOPLE = [
    ("man", "erkak / мужчина"),
    ("woman", "ayol / женщина"),
    ("boy", "o'g'il bola / мальчик"),
    ("girl", "qiz bola / девочка"),
    ("child", "bola / ребёнок"),
    ("person", "shaxs / человек"),
    ("people", "odamlar / люди"),
    ("friend", "do'st / друг"),
    ("teacher", "o'qituvchi / учитель"),
    ("student", "o'quvchi / ученик"),
    ("doctor", "shifokor / врач"),
    ("driver", "haydovchi / водитель"),
    ("boss", "rahbar / начальник"),
    ("guest", "mehmon / гость"),
    ("stranger", "notanish odam / незнакомец"),
    ("group", "guruh / группа"),
    ("everybody", "hamma / все"),
    ("somebody", "kimdir / кто-то"),
    ("nobody", "hech kim / никто"),
    ("everything", "hamma narsa / всё"),
    ("something", "biror narsa / что-то"),
    ("nothing", "hech narsa / ничего"),
    ("anyone", "kimdir (savolda) / кто-нибудь"),
    ("each other", "bir-biri / друг друга"),
    ("myself", "o'zim / сам"),
]

SMALLWORDS = [
    ("in", "ichida / в"),
    ("on", "ustida / на"),
    ("under", "ostida / под"),
    ("at", "da (joy, vaqt) / у, в"),
    ("to", "ga (tomon) / к"),
    ("from", "dan / от"),
    ("with", "bilan / с"),
    ("without", "siz / без"),
    ("for", "uchun / для"),
    ("about", "haqida / о"),
    ("after", "keyin / после"),
    ("before", "oldin / до"),
    ("and", "va / и"),
    ("but", "lekin / но"),
    ("or", "yoki / или"),
    ("because", "chunki / потому что"),
    ("so", "shuning uchun / поэтому"),
    ("if", "agar / если"),
    ("here", "bu yerda / здесь"),
    ("there", "u yerda / там"),
    ("near", "yaqinida / около"),
    ("between", "o'rtasida / между"),
    ("over", "tepasidan / над"),
    ("up", "yuqoriga / вверх"),
    ("down", "pastga / вниз"),
]

CLASSROOM = [
    ("classroom", "sinfxona / класс"),
    ("lesson", "dars / урок"),
    ("homework", "uy vazifasi / домашнее задание"),
    ("exercise", "mashq / упражнение"),
    ("question", "savol / вопрос"),
    ("answer", "javob / ответ"),
    ("word", "so'z / слово"),
    ("sentence", "gap / предложение"),
    ("page", "sahifa / страница"),
    ("board", "doska / доска"),
    ("desk", "parta / парта"),
    ("dictionary", "lug'at / словарь"),
    ("test", "sinov / тест"),
    ("mistake", "xato / ошибка"),
    ("mark", "baho / оценка"),
    ("group work", "guruhda ishlash / работа в группе"),
    ("partner", "juftlik / партнёр"),
    ("repeat", "takrorlamoq / повторять"),
    ("spell", "harflab aytmoq / писать по буквам"),
    ("translate", "tarjima qilmoq / переводить"),
    ("understand", "tushunmoq / понимать"),
    ("remember", "eslab qolmoq / запоминать"),
    ("forget", "unutmoq / забывать"),
    ("practise", "mashq qilmoq / практиковать"),
    ("learn", "o'rganmoq / изучать"),
]

HOUSE = [
    ("home", "uy (o'z uyi) / дом (родной)"),
    ("door", "eshik / дверь"),
    ("window", "deraza / окно"),
    ("light", "chiroq / свет"),
    ("water", "suv / вода"),
    ("food", "ovqat / еда"),
    ("kitchen", "oshxona / кухня"),
    ("bathroom", "hammom / ванная"),
    ("bedroom", "yotoqxona / спальня"),
    ("table", "stol / стол"),
    ("chair", "stul / стул"),
    ("bed", "karavot / кровать"),
    ("clock", "soat / часы"),
    ("key", "kalit / ключ"),
    ("phone", "telefon / телефон"),
    ("television", "televizor / телевизор"),
    ("radio", "radio / радио"),
    ("plate", "tarelka / тарелка"),
    ("cup", "piyola / чашка"),
    ("towel", "sochiq / полотенце"),
    ("soap", "sovun / мыло"),
    ("clothes", "kiyim / одежда"),
    ("rubbish", "axlat / мусор"),
    ("floor", "pol / пол"),
    ("roof", "tom / крыша"),
]

CITY = [
    ("city", "shahar / город"),
    ("street", "ko'cha / улица"),
    ("shop", "do'kon / магазин"),
    ("market", "bozor / рынок"),
    ("bank", "bank / банк"),
    ("school", "maktab / школа"),
    ("hospital", "kasalxona / больница"),
    ("park", "bog' / парк"),
    ("bus", "avtobus / автобус"),
    ("car", "mashina / машина"),
    ("road", "yo'l / дорога"),
    ("bridge", "ko'prik / мост"),
    ("station", "bekat / станция"),
    ("airport", "aeroport / аэропорт"),
    ("hotel", "mehmonxona / гостиница"),
    ("restaurant", "restoran / ресторан"),
    ("cafe", "kafe / кафе"),
    ("cinema", "kinoteatr / кинотеатр"),
    ("museum", "muzey / музей"),
    ("library", "kutubxona / библиотека"),
    ("police", "politsiya / полиция"),
    ("post office", "pochta / почта"),
    ("pharmacy", "dorixona / аптека"),
    ("toilet", "hojatxona / туалет"),
    ("money", "pul / деньги"),
]

OPPOSITES = [
    ("open - close", "ochmoq - yopmoq / открывать - закрывать"),
    ("start - finish", "boshlamoq - tugatmoq / начинать - заканчивать"),
    ("buy - sell", "sotib olmoq - sotmoq / покупать - продавать"),
    ("come - go", "kelmoq - ketmoq / приходить - уходить"),
    ("give - take", "bermoq - olmoq / давать - брать"),
    ("win - lose", "yutmoq - yutqazmoq / выигрывать - проигрывать"),
    ("remember - forget", "eslamoq - unutmoq / помнить - забывать"),
    ("love - hate", "sevmoq - yomon ko'rmoq / любить - ненавидеть"),
    ("push - pull", "itarmoq - tortmoq / толкать - тянуть"),
    ("ask - answer", "so'ramoq - javob bermoq / спрашивать - отвечать"),
    ("big - small", "katta - kichik / большой - маленький"),
    ("hot - cold", "issiq - sovuq / горячий - холодный"),
    ("new - old", "yangi - eski / новый - старый"),
    ("fast - slow", "tez - sekin / быстрый - медленный"),
    ("easy - hard", "oson - qiyin / лёгкий - трудный"),
    ("early - late", "erta - kech / рано - поздно"),
    ("near - far", "yaqin - uzoq / близко - далеко"),
    ("first - last", "birinchi - oxirgi / первый - последний"),
    ("more - less", "ko'proq - kamroq / больше - меньше"),
    ("always - never", "doim - hech qachon / всегда - никогда"),
    ("everything - nothing", "hamma narsa - hech narsa / всё - ничего"),
    ("inside - outside", "ichkarida - tashqarida / внутри - снаружи"),
    ("up - down", "yuqoriga - pastga / вверх - вниз"),
    ("left - right", "chap - o'ng / левый - правый"),
    ("before - after", "oldin - keyin / до - после"),
]

TIMEWORDS = [
    ("now", "hozir / сейчас"),
    ("today", "bugun / сегодня"),
    ("tomorrow", "ertaga / завтра"),
    ("yesterday", "kecha / вчера"),
    ("morning", "ertalab / утро"),
    ("evening", "kechqurun / вечер"),
    ("night", "tun / ночь"),
    ("day", "kun / день"),
    ("week", "hafta / неделя"),
    ("month", "oy / месяц"),
    ("year", "yil / год"),
    ("hour", "soat (davomiylik) / час"),
    ("minute", "daqiqa / минута"),
    ("time", "vaqt / время"),
    ("always", "doim / всегда"),
    ("often", "tez-tez / часто"),
    ("sometimes", "ba'zan / иногда"),
    ("never", "hech qachon / никогда"),
    ("usually", "odatda / обычно"),
    ("early", "erta / рано"),
    ("late", "kech / поздно"),
    ("soon", "tez orada / скоро"),
    ("still", "hali ham / всё ещё"),
    ("already", "allaqachon / уже"),
    ("every day", "har kuni / каждый день"),
]

PHRASES = [
    ("How are you?", "Qalaysiz? / Как дела?"),
    ("Nice to meet you", "Tanishganimdan xursandman / Приятно познакомиться"),
    ("See you later", "Ko'rishguncha / Увидимся"),
    ("Excuse me", "Kechirasiz / Извините"),
    ("I'm sorry", "Uzr so'rayman / Мне жаль"),
    ("Thank you very much", "Katta rahmat / Большое спасибо"),
    ("You're welcome", "Arzimaydi / Пожалуйста"),
    ("Can you help me?", "Yordam bera olasizmi? / Можете помочь?"),
    ("I don't understand", "Tushunmayapman / Я не понимаю"),
    ("Can you repeat, please?", "Takrorlang, iltimos / Повторите, пожалуйста"),
    ("How do you say this?", "Buni qanday aytiladi? / Как это сказать?"),
    ("What does it mean?", "Bu nima degani? / Что это значит?"),
    ("Just a moment", "Bir daqiqa / Минутку"),
    ("Of course not", "Albatta yo'q / Конечно нет"),
    ("I agree", "Roziman / Я согласен"),
    ("No problem", "Muammo yo'q / Без проблем"),
    ("Good luck", "Omad / Удачи"),
    ("Take care", "O'zingizni asrang / Берегите себя"),
    ("Never mind", "Hechqisi yo'q / Ничего страшного"),
    ("Let's go", "Ketdik / Пойдём"),
    ("Come here", "Bu yerga keling / Идите сюда"),
    ("Wait a minute", "Bir daqiqa kuting / Подождите минуту"),
    ("I'm not sure", "Aniq bilmayman / Я не уверен"),
    ("That's right", "To'g'ri / Верно"),
    ("It doesn't matter", "Muhim emas / Это неважно"),
]

MANNERS = [
    ("happy", "xursand / радостный"),
    ("sad", "g'amgin / печальный"),
    ("angry", "jahli chiqqan / сердитый"),
    ("afraid", "qo'rqqan / напуганный"),
    ("surprised", "hayron / удивлённый"),
    ("worried", "xavotirda / встревоженный"),
    ("excited", "hayajonlangan / взволнованный"),
    ("bored", "zerikkan / скучающий"),
    ("proud", "faxrlanayotgan / гордый"),
    ("shy", "uyatchan / застенчивый"),
    ("polite", "odobli / вежливый"),
    ("rude", "qo'pol / грубый"),
    ("friendly", "do'stona / дружелюбный"),
    ("lazy", "dangasa / ленивый"),
    ("clever", "aqlli / умный"),
    ("honest", "halol / честный"),
    ("patient", "sabrli / терпеливый"),
    ("careful", "ehtiyotkor / осторожный"),
    ("lucky", "omadli / везучий"),
    ("sure", "ishonchi komil / уверенный"),
    ("smile", "tabassum qilmoq / улыбаться"),
    ("laugh", "kulmoq / смеяться"),
    ("cry", "yig'lamoq / плакать"),
    ("shout", "baqirmoq / кричать"),
    ("hug", "quchoqlamoq / обнимать"),
]

LISTS = [
    ("A1 first words 1 · Numbers", "exam", 1, NUMBERS),
    ("A1 first words 2 · Questions and answers", "exam", 2, QUESTIONS),
    ("A1 first words 3 · The commonest verbs 1", "exam", 3, VERBS1),
    ("A1 first words 4 · The commonest verbs 2", "exam", 4, VERBS2),
    ("A1 first words 5 · Describing things 1", "exam", 5, ADJ1),
    ("A1 first words 6 · Describing things 2", "exam", 6, ADJ2),
    ("A1 first words 7 · People", "exam", 7, PEOPLE),
    ("A1 first words 8 · Small words", "exam", 8, SMALLWORDS),
    ("A1 first words 9 · In the classroom", "exam", 9, CLASSROOM),
    ("A1 first words 10 · Around the house", "exam", 10, HOUSE),
    ("A1 first words 11 · In the city", "exam", 11, CITY),
    ("A1 first words 12 · Opposites", "exam", 12, OPPOSITES),
    ("A1 first words 13 · Time words", "exam", 13, TIMEWORDS),
    ("A1 first words 14 · Useful phrases", "exam", 14, PHRASES),
    ("A1 first words 15 · Feelings and manners", "exam", 15, MANNERS),
]
