"""The A2 Key words Empower Elementary never teaches - steps 1 to 6.

Cambridge publishes the A2 Key vocabulary list, and the exam is written from
it. Measured against the Elementary Student's Book, 734 of those words are
never taught there - they appear once in a reading text, or not at all. This
is the first of those, as its own book in the Exam words section.

Grouped by topic rather than alphabetically, because a step should be a
subject a student can hold in their head.
"""

FOOD = [
    ("biscuit", "a small hard sweet cake"),
    ("burger", "flat meat in a round bread roll"),
    ("cereal", "what many people eat with milk for breakfast"),
    ("dessert", "the sweet course at the end of a meal"),
    ("snack", "a small amount of food between meals"),
    ("chilli", "a small red vegetable that tastes very hot"),
    ("cream", "the thick part of milk"),
    ("flour", "the white powder you make bread with"),
    ("honey", "the sweet food bees make"),
    ("jam", "sweet fruit you spread on bread"),
    ("lemon", "a sour yellow fruit"),
    ("melon", "a large sweet fruit with many seeds"),
    ("mushroom", "a soft vegetable with a round top and a stem"),
    ("pepper", "a hollow red, green or yellow vegetable"),
    ("sausage", "meat in a long thin skin"),
    ("seafood", "fish and other food from the sea"),
    ("snack bar", "a small place selling quick food"),
    ("strawberry", "a small soft red fruit"),
    ("toast", "bread that has been made hot and brown"),
    ("vegetarian", "a person who does not eat meat"),
    ("bowl", "a deep round dish for soup"),
    ("fork", "you eat with it and it has points"),
    ("spoon", "you eat soup with it"),
    ("knife", "you cut your food with it"),
    ("plate", "the flat dish your dinner is served on"),
]

HOME = [
    ("apartment", "another word for a flat"),
    ("bathtub", "the long container you lie in to wash"),
    ("ceiling", "the surface above your head in a room"),
    ("cupboard", "a piece of furniture with doors and shelves"),
    ("curtain", "cloth you pull across a window"),
    ("drawer", "the part of a desk you pull out"),
    ("downstairs", "on a lower floor of a building"),
    ("upstairs", "on a higher floor of a building"),
    ("entrance", "the way into a building"),
    ("exit", "the way out of a building"),
    ("garage", "where you keep your car at home"),
    ("gate", "the door in a fence or wall outside"),
    ("heating", "the system that makes a house warm"),
    ("key", "you open a lock with it"),
    ("lift", "it carries you up between floors"),
    ("lock", "you turn a key in it"),
    ("neighbourhood", "the area around your home"),
    ("rent", "the money you pay to live in a place"),
    ("roof", "the top of a building, outside"),
    ("stairs", "you climb them inside a house"),
    ("switch", "you press it to turn a light on"),
    ("towel", "you dry yourself with it"),
    ("wall", "the side of a room"),
    ("floor", "you walk on it inside a building"),
    ("furniture", "tables, chairs and beds together"),
]

NATURE = [
    ("air", "what we breathe"),
    ("bee", "a small insect that makes honey"),
    ("butterfly", "an insect with large coloured wings"),
    ("camel", "a desert animal with one or two humps"),
    ("cow", "the farm animal that gives milk"),
    ("crocodile", "a long river animal with many teeth"),
    ("dolphin", "a clever sea animal that is not a fish"),
    ("donkey", "a small animal like a horse with long ears"),
    ("duck", "a bird that swims on a lake"),
    ("eagle", "a large bird that hunts"),
    ("elephant", "the biggest land animal, with a long nose"),
    ("goat", "a farm animal that climbs and eats almost anything"),
    ("insect", "a very small animal with six legs"),
    ("lion", "a big wild cat from Africa"),
    ("monkey", "an animal that climbs trees and has a tail"),
    ("sheep", "a farm animal covered in wool"),
    ("tiger", "a big wild cat with orange and black stripes"),
    ("whale", "the largest animal in the sea"),
    ("autumn", "the season when leaves fall"),
    ("branch", "the part of a tree that grows out of the trunk"),
    ("grass", "the short green plant covering a field"),
    ("leaf", "the flat green part of a plant"),
    ("plant", "any living green thing that grows in soil"),
    ("wood", "what trees are made of"),
    ("seed", "the small thing a plant grows from"),
]

SCHOOL = [
    ("advanced", "at a high level, for people who already know a lot"),
    ("beginner", "somebody who has just started learning"),
    ("biology", "the study of living things"),
    ("chemistry", "the study of what things are made of"),
    ("geography", "the study of countries and the land"),
    ("history", "the study of the past"),
    ("blackboard", "the dark board a teacher writes on"),
    ("classmate", "another student in your class"),
    ("classroom", "the room where lessons happen"),
    ("diploma", "a paper showing you completed a course"),
    ("dictionary", "a book of words and their meanings"),
    ("eraser", "you rub out pencil with it"),
    ("example", "one thing that shows what you mean"),
    ("experiment", "a test you do to find something out"),
    ("explain", "make something clear to somebody"),
    ("headteacher", "the person in charge of a school"),
    ("lesson", "one period of teaching"),
    ("notice", "a written message on a wall for everybody"),
    ("project", "a long piece of work on one subject"),
    ("pupil", "a child at school"),
    ("rule", "something you must or must not do"),
    ("secondary school", "the school you go to after primary"),
    ("student", "a person who is studying"),
    ("term", "one part of the school year"),
    ("university", "where you study after school"),
]

PEOPLE = [
    ("artist", "somebody who paints or draws"),
    ("assistant", "somebody who helps another person at work"),
    ("boss", "the person in charge of you at work"),
    ("career", "the working life you build over years"),
    ("celebrity", "a very famous person"),
    ("chemist", "the shop, or person, that sells medicine"),
    ("cleaner", "the person who cleans a building"),
    ("coach", "the person who trains a sports team"),
    ("colleague", "somebody you work with"),
    ("company", "a business that employs people"),
    ("customer", "a person who buys something"),
    ("dancer", "somebody who dances as a job"),
    ("dentist", "the person who looks after your teeth"),
    ("director", "the person in charge of a film or a company"),
    ("employee", "a person who works for a company"),
    ("engineer", "somebody who designs or repairs machines"),
    ("explorer", "somebody who travels to unknown places"),
    ("guest", "somebody invited to your home or hotel"),
    ("guide", "the person who shows visitors around"),
    ("hero", "somebody admired for a brave act"),
    ("manager", "the person who runs a team or a shop"),
    ("owner", "the person something belongs to"),
    ("passenger", "somebody travelling who is not driving"),
    ("politician", "somebody who works in government"),
    ("tourist", "a person visiting a place on holiday"),
]

ADJECTIVES = [
    ("able", "having the power to do something"),
    ("afraid", "feeling fear"),
    ("amazed", "very surprised"),
    ("angry", "feeling strong bad feeling about something"),
    ("attractive", "nice to look at"),
    ("awful", "extremely bad"),
    ("bored", "not interested, with nothing to do"),
    ("brave", "not afraid of danger"),
    ("broken", "in pieces, or not working"),
    ("clever", "quick to understand"),
    ("dangerous", "likely to hurt you"),
    ("deep", "going a long way down"),
    ("delicious", "tasting very good"),
    ("dirty", "needing to be cleaned"),
    ("empty", "with nothing inside"),
    ("excellent", "extremely good"),
    ("excited", "full of happy energy about something coming"),
    ("famous", "known by very many people"),
    ("lazy", "not wanting to work"),
    ("nervous", "worried about something that is going to happen"),
    ("noisy", "making a lot of sound"),
    ("proud", "pleased about something you did"),
    ("quiet", "making almost no sound"),
    ("strange", "not usual or normal"),
    ("tidy", "with everything in its place"),
]

LISTS = [
    ("A2 exam words 1 · Food and eating", "exam", 1, FOOD),
    ("A2 exam words 2 · The home", "exam", 2, HOME),
    ("A2 exam words 3 · Animals and nature", "exam", 3, NATURE),
    ("A2 exam words 4 · School and study", "exam", 4, SCHOOL),
    ("A2 exam words 5 · People and jobs", "exam", 5, PEOPLE),
    ("A2 exam words 6 · Describing people and things", "exam", 6, ADJECTIVES),
]
