"""A2 Key exam words, steps 19 to 30. Meanings in Uzbek and Russian."""

WEATHER = [
    ("cloud", "bulut / облако"),
    ("cloudy", "bulutli / облачный"),
    ("fog", "tuman / туман"),
    ("ice", "muz / лёд"),
    ("rain", "yomg'ir / дождь"),
    ("snow", "qor / снег"),
    ("storm", "bo'ron / буря"),
    ("sunny", "quyoshli / солнечный"),
    ("thunderstorm", "momaqaldiroq / гроза"),
    ("wet", "ho'l / мокрый"),
    ("wind", "shamol / ветер"),
    ("windy", "shamolli / ветреный"),
    ("dry", "quruq / сухой"),
    ("warm", "iliq / тёплый"),
    ("freezing", "juda sovuq / очень холодный"),
    ("temperature", "harorat / температура"),
    ("degree", "daraja / градус"),
    ("forecast", "ob-havo prognozi / прогноз"),
    ("shade", "soya / тень"),
    ("sunshine", "quyosh nuri / солнечный свет"),
    ("umbrella", "soyabon / зонт"),
    ("flood", "suv toshqini / наводнение"),
    ("season", "yil fasli / время года"),
    ("spring", "bahor / весна"),
    ("winter", "qish / зима"),
]

NATURE2 = [
    ("beach", "plyaj / пляж"),
    ("cave", "g'or / пещера"),
    ("coast", "sohil / побережье"),
    ("desert", "cho'l / пустыня"),
    ("earth", "yer / земля"),
    ("field", "dala / поле"),
    ("forest", "o'rmon / лес"),
    ("hill", "tepalik / холм"),
    ("island", "orol / остров"),
    ("lake", "ko'l / озеро"),
    ("moon", "oy / луна"),
    ("mountain", "tog' / гора"),
    ("north", "shimol / север"),
    ("south", "janub / юг"),
    ("east", "sharq / восток"),
    ("west", "g'arb / запад"),
    ("ocean", "okean / океан"),
    ("river", "daryo / река"),
    ("sky", "osmon / небо"),
    ("star", "yulduz / звезда"),
    ("sun", "quyosh / солнце"),
    ("valley", "vodiy / долина"),
    ("wave", "to'lqin / волна"),
    ("environment", "atrof-muhit / окружающая среда"),
    ("countryside", "qishloq joyi / сельская местность"),
]

WORK = [
    ("advertisement", "e'lon / объявление"),
    ("appointment", "uchrashuv, qabul / приём"),
    ("business", "biznes / бизнес"),
    ("businessman", "tadbirkor / бизнесмен"),
    ("conference", "konferensiya / конференция"),
    ("form", "ariza blankasi / бланк"),
    ("interview", "suhbat / собеседование"),
    ("job", "ish joyi / работа"),
    ("meeting", "yig'ilish / встреча"),
    ("office", "ofis / офис"),
    ("report", "hisobot / отчёт"),
    ("salary", "maosh / зарплата"),
    ("staff", "xodimlar / персонал"),
    ("secretary", "kotib / секретарь"),
    ("shift", "smena / смена"),
    ("skill", "ko'nikma / навык"),
    ("training", "o'qitish / обучение"),
    ("unemployed", "ishsiz / безработный"),
    ("uniform", "ish formasi / униформа"),
    ("work experience", "ish tajribasi / опыт работы"),
    ("employer", "ish beruvchi / работодатель"),
    ("full-time", "to'liq stavka / полная занятость"),
    ("part-time", "yarim stavka / частичная занятость"),
    ("retire", "nafaqaga chiqmoq / выходить на пенсию"),
    ("colleague", "ish yo'ldoshi / сослуживец"),
]

HOUSE2 = [
    ("balcony", "balkon / балкон"),
    ("basement", "yerto'la / подвал"),
    ("bedroom", "yotoqxona / спальня"),
    ("bell", "qo'ng'iroq / звонок"),
    ("blanket", "ko'rpa / одеяло"),
    ("bookcase", "kitob javoni / книжный шкаф"),
    ("brush", "cho'tka / щётка"),
    ("candle", "sham / свеча"),
    ("clock", "soat / часы"),
    ("comb", "taroq / расчёска"),
    ("cooker", "plita / плита"),
    ("cushion", "yostiqcha / подушка на диван"),
    ("fridge", "muzlatgich / холодильник"),
    ("kettle", "choynak / чайник"),
    ("lamp", "chiroq / лампа"),
    ("mirror", "oyna / зеркало"),
    ("pillow", "yostiq / подушка"),
    ("sink", "rakovina / раковина"),
    ("soap", "sovun / мыло"),
    ("toothbrush", "tish cho'tkasi / зубная щётка"),
    ("vase", "guldon / ваза"),
    ("washing machine", "kir yuvish mashinasi / стиральная машина"),
    ("bin", "axlat qutisi / мусорное ведро"),
    ("shelf", "tokcha / полка"),
    ("garden", "hovli bog'i / сад"),
]

PLACES2 = [
    ("airport", "aeroport / аэропорт"),
    ("bus station", "avtobus bekati / автовокзал"),
    ("cafe", "kafe / кафе"),
    ("campsite", "lager joyi / кемпинг"),
    ("cinema", "kinoteatr / кинотеатр"),
    ("flat", "kvartira / квартира"),
    ("hostel", "yotoqxona / хостел"),
    ("hotel", "mehmonxona / отель"),
    ("market", "bozor / базар"),
    ("office building", "ofis binosi / офисное здание"),
    ("palace", "saroy / дворец"),
    ("post office", "pochta / почта"),
    ("prison", "qamoqxona / тюрьма"),
    ("railway station", "temir yo'l vokzali / железнодорожный вокзал"),
    ("restaurant", "restoran / ресторан"),
    ("school", "maktab / школа"),
    ("shop", "do'kon / магазин"),
    ("stadium", "stadion / стадион"),
    ("swimming pool", "suzish havzasi / бассейн"),
    ("temple", "ibodatxona / храм"),
    ("university", "oliygoh / университет"),
    ("factory", "fabrika / фабрика"),
    ("farm", "ferma / ферма"),
    ("hospital", "shifoxona / больница"),
    ("bank", "bank bo'limi / отделение банка"),
]

ADJ2 = [
    ("busy", "band / занятый"),
    ("careful", "ehtiyotkor / осторожный"),
    ("cheerful", "xushchaqchaq / жизнерадостный"),
    ("comfortable", "qulay / удобный"),
    ("crowded", "gavjum / переполненный"),
    ("difficult", "qiyin / трудный"),
    ("exciting", "qiziqarli / захватывающий"),
    ("fantastic", "ajoyib / потрясающий"),
    ("friendly", "do'stona / дружелюбный"),
    ("generous", "saxiy / щедрый"),
    ("heavy", "og'ir / тяжёлый"),
    ("honest", "halol / честный"),
    ("important", "muhim / важный"),
    ("light", "yengil / лёгкий"),
    ("modern", "zamonaviy / современный"),
    ("polite", "odobli / вежливый"),
    ("popular", "ommabop / популярный"),
    ("powerful", "kuchli / мощный"),
    ("serious", "jiddiy / серьёзный"),
    ("similar", "o'xshash / похожий"),
    ("simple", "oddiy / простой"),
    ("terrible", "juda yomon / ужасный"),
    ("useful", "foydali / полезный"),
    ("wonderful", "ajoyib go'zal / чудесный"),
    ("wrong", "noto'g'ri / неправильный"),
]

ADV_PREP = [
    ("abroad", "chet elga / за границу"),
    ("actually", "aslida / на самом деле"),
    ("almost", "deyarli / почти"),
    ("along", "bo'ylab / вдоль"),
    ("among", "orasida / среди"),
    ("anywhere", "biror joyda / где-нибудь"),
    ("badly", "yomon / плохо"),
    ("below", "pastda / ниже"),
    ("beside", "yonida / рядом"),
    ("carefully", "ehtiyotkorlik bilan / осторожно"),
    ("certainly", "albatta / конечно"),
    ("clearly", "aniq / ясно"),
    ("easily", "oson / легко"),
    ("everywhere", "hamma joyda / везде"),
    ("exactly", "aynan / точно"),
    ("inside", "ichkarida / внутри"),
    ("outside", "tashqarida / снаружи"),
    ("probably", "ehtimol / вероятно"),
    ("quickly", "tez / быстро"),
    ("quietly", "sekin, jimgina / тихо"),
    ("slowly", "sekin / медленно"),
    ("together", "birga / вместе"),
    ("towards", "tomon / к"),
    ("upstairs", "yuqoriga / наверх"),
    ("without", "siz, yo'q holda / без"),
]

NOUNS1 = [
    ("area", "hudud / район"),
    ("birth", "tug'ilish / рождение"),
    ("bottom", "tag, pastki qism / низ"),
    ("choice", "tanlov / выбор"),
    ("crowd", "olomon / толпа"),
    ("danger", "xavf / опасность"),
    ("detail", "tafsilot / деталь"),
    ("difference", "farq / разница"),
    ("event", "tadbir / событие"),
    ("experience", "tajriba / опыт"),
    ("fact", "dalil / факт"),
    ("idea", "fikr / идея"),
    ("information", "ma'lumot / информация"),
    ("invitation", "taklifnoma / приглашение"),
    ("kind", "tur, xil / вид"),
    ("language", "til / язык"),
    ("noise", "shovqin / шум"),
    ("opinion", "fikr, qarash / мнение"),
    ("piece", "bo'lak / кусок"),
    ("place", "joy / место"),
    ("problem", "muammo / проблема"),
    ("reason", "sabab / причина"),
    ("result", "natija / результат"),
    ("situation", "vaziyat / ситуация"),
    ("way", "usul, yo'l / способ"),
]

NOUNS2 = [
    ("advice", "maslahat / совет"),
    ("age", "yosh / возраст"),
    ("answer", "javob / ответ"),
    ("beginning", "boshlanish / начало"),
    ("cost", "narx / стоимость"),
    ("end", "oxiri / конец"),
    ("example", "namuna / пример"),
    ("group", "guruh / группа"),
    ("half", "yarim / половина"),
    ("history", "tarix / история"),
    ("holiday", "ta'til / отпуск"),
    ("hour", "soat / час"),
    ("letter", "xat / письмо"),
    ("list", "ro'yxat / список"),
    ("mistake", "xato / ошибка"),
    ("news", "yangilik / новости"),
    ("number", "raqam / номер"),
    ("order", "buyurtma / заказ"),
    ("part", "qism / часть"),
    ("question", "savol / вопрос"),
    ("side", "tomon / сторона"),
    ("sound", "tovush / звук"),
    ("top", "tepa / верх"),
    ("word", "so'z / слово"),
    ("world", "dunyo / мир"),
]

FOOD2 = [
    ("beans", "loviya / фасоль"),
    ("beef", "mol go'shti / говядина"),
    ("cabbage", "karam / капуста"),
    ("chocolate", "shokolad / шоколад"),
    ("coffee", "qahva / кофе"),
    ("cucumber", "bodring / огурец"),
    ("fruit", "meva / фрукты"),
    ("garlic", "sarimsoq / чеснок"),
    ("grape", "uzum / виноград"),
    ("ice cream", "muzqaymoq / мороженое"),
    ("lamb", "qo'y go'shti / баранина"),
    ("mineral water", "mineral suv / минеральная вода"),
    ("noodles", "ugra / лапша"),
    ("nut", "yong'oq / орех"),
    ("olive", "zaytun / оливка"),
    ("onion", "piyoz / лук"),
    ("pasta", "makaron / паста"),
    ("peach", "shaftoli / персик"),
    ("pear", "nok / груша"),
    ("pie", "pirog / пирог"),
    ("salad", "salat / салат"),
    ("soup", "sho'rva / суп"),
    ("tea", "choy / чай"),
    ("vegetable", "sabzavot / овощ"),
    ("yoghurt", "yogurt / йогурт"),
]

PHRASES = [
    ("at last", "nihoyat / наконец"),
    ("at least", "hech bo'lmaganda / по крайней мере"),
    ("by accident", "tasodifan / случайно"),
    ("for example", "masalan / например"),
    ("go out", "sayr qilgani chiqmoq / выходить гулять"),
    ("get up", "o'rindan turmoq / вставать"),
    ("look after", "qaramoq / присматривать"),
    ("look for", "izlamoq / искать"),
    ("look forward to", "intiq bo'lmoq / с нетерпением ждать"),
    ("of course", "albatta / конечно"),
    ("on time", "o'z vaqtida / вовремя"),
    ("put on", "kiymoq / надевать"),
    ("take off", "yechmoq / снимать"),
    ("take part in", "ishtirok etmoq / участвовать"),
    ("turn off", "o'chirmoq / выключать"),
    ("turn on", "yoqmoq / включать"),
    ("wake up", "uyg'onmoq / просыпаться"),
    ("find out", "bilib olmoq / узнавать"),
    ("give up", "tashlab qo'ymoq / бросать"),
    ("grow up", "voyaga yetmoq / расти"),
    ("hurry up", "shoshilmoq / поторопиться"),
    ("pick up", "olib ketmoq / забирать"),
    ("run out of", "tugab qolmoq / заканчиваться"),
    ("get on with", "chiqishib ketmoq / ладить"),
    ("come back", "qaytib kelmoq / возвращаться"),
]

MEASURE = [
    ("centimetre", "santimetr / сантиметр"),
    ("metre", "metr / метр"),
    ("kilometre", "kilometr / километр"),
    ("gram", "gramm / грамм"),
    ("kilo", "kilogramm / килограмм"),
    ("litre", "litr / литр"),
    ("size", "o'lcham / размер"),
    ("weight", "og'irlik / вес"),
    ("height", "bo'y, balandlik / высота"),
    ("length", "uzunlik / длина"),
    ("width", "kenglik / ширина"),
    ("double", "ikki barobar / двойной"),
    ("dozen", "o'n ikkita / дюжина"),
    ("empty", "bo'shatmoq / опустошать"),
    ("enough", "yetarli / достаточно"),
    ("few", "kam / мало"),
    ("half a kilo", "yarim kilo / полкило"),
    ("hundred", "yuz / сто"),
    ("thousand", "ming / тысяча"),
    ("million", "million / миллион"),
    ("pair", "juft / пара"),
    ("quarter of an hour", "chorak soat / четверть часа"),
    ("several", "bir nechta / несколько"),
    ("single", "bitta, yakka / одиночный"),
    ("whole", "butun / целый"),
]

LISTS = [
    ("A2 exam words 19 · Weather", "exam", 19, WEATHER),
    ("A2 exam words 20 · The natural world", "exam", 20, NATURE2),
    ("A2 exam words 21 · Work", "exam", 21, WORK),
    ("A2 exam words 22 · Things in a house", "exam", 22, HOUSE2),
    ("A2 exam words 23 · Buildings and places", "exam", 23, PLACES2),
    ("A2 exam words 24 · More describing words", "exam", 24, ADJ2),
    ("A2 exam words 25 · How and where", "exam", 25, ADV_PREP),
    ("A2 exam words 26 · Common nouns 1", "exam", 26, NOUNS1),
    ("A2 exam words 27 · Common nouns 2", "exam", 27, NOUNS2),
    ("A2 exam words 28 · More food and drink", "exam", 28, FOOD2),
    ("A2 exam words 29 · Everyday phrases", "exam", 29, PHRASES),
    ("A2 exam words 30 · Numbers and measuring", "exam", 30, MEASURE),
]
