"""A2 Key exam words, steps 7 to 18. Meanings in Uzbek and Russian."""

TOWN = [
    ("bridge", "ko'prik / мост"),
    ("castle", "qal'a / замок"),
    ("corner", "burchak / угол"),
    ("crossing", "piyodalar o'tish joyi / переход"),
    ("factory", "zavod / завод"),
    ("fountain", "favvora / фонтан"),
    ("garden", "bog' / сад"),
    ("monument", "haykal, yodgorlik / памятник"),
    ("museum", "muzey / музей"),
    ("path", "so'qmoq / тропинка"),
    ("petrol station", "yoqilg'i shoxobchasi / заправка"),
    ("pool", "basseyn / бассейн"),
    ("roundabout", "aylanma yo'l / кольцевая развязка"),
    ("square", "maydon / площадь"),
    ("theatre", "teatr / театр"),
    ("traffic lights", "svetofor / светофор"),
    ("tower", "minora / башня"),
    ("village", "qishloq / деревня"),
    ("zoo", "hayvonot bog'i / зоопарк"),
    ("pavement", "piyodalar yo'lkasi / тротуар"),
    ("car park", "avtoturargoh / парковка"),
    ("church", "cherkov / церковь"),
    ("library", "kutubxona / библиотека"),
    ("bank", "bank / банк"),
    ("chemist's", "dorixona / аптека"),
]

TRAVEL = [
    ("aeroplane", "samolyot / самолёт"),
    ("bicycle", "velosiped / велосипед"),
    ("coach", "sayyohlik avtobusi / автобус дальнего следования"),
    ("ferry", "parom / паром"),
    ("helicopter", "vertolyot / вертолёт"),
    ("motorbike", "mototsikl / мотоцикл"),
    ("van", "furgon / фургон"),
    ("truck", "yuk mashinasi / грузовик"),
    ("engine", "dvigatel / двигатель"),
    ("wheel", "g'ildirak / колесо"),
    ("seatbelt", "xavfsizlik kamari / ремень безопасности"),
    ("journey", "safar / поездка"),
    ("trip", "sayohat / путешествие"),
    ("luggage", "yuk, jomadonlar / багаж"),
    ("suitcase", "jomadon / чемодан"),
    ("backpack", "ryukzak / рюкзак"),
    ("passport", "pasport / паспорт"),
    ("delay", "kechikish / задержка"),
    ("platform", "perron / платформа"),
    ("departure", "jo'nash / отправление"),
    ("arrival", "kelish / прибытие"),
    ("return ticket", "borib-kelish chiptasi / билет туда и обратно"),
    ("abroad", "chet elda / за границей"),
    ("tour", "ekskursiya / экскурсия"),
    ("map", "xarita / карта"),
]

SPORT = [
    ("athlete", "sportchi / спортсмен"),
    ("badminton", "badminton / бадминтон"),
    ("baseball", "beysbol / бейсбол"),
    ("champion", "chempion / чемпион"),
    ("climbing", "toqqa chiqish / скалолазание"),
    ("competition", "musobaqa / соревнование"),
    ("cycling", "velosport / велоспорт"),
    ("diving", "sho'ng'ish / дайвинг"),
    ("fishing", "baliq ovlash / рыбалка"),
    ("goal", "gol, darvoza / гол"),
    ("gym", "sport zali / спортзал"),
    ("jogging", "yugurish / бег трусцой"),
    ("match", "o'yin, matn / матч"),
    ("player", "o'yinchi / игрок"),
    ("race", "poyga / гонка"),
    ("referee", "hakam / судья"),
    ("skating", "konkida uchish / катание на коньках"),
    ("skiing", "chang'i uchish / катание на лыжах"),
    ("stadium", "stadion / стадион"),
    ("team", "jamoa / команда"),
    ("tennis", "tennis / теннис"),
    ("training", "mashg'ulot / тренировка"),
    ("volleyball", "voleybol / волейбол"),
    ("winner", "g'olib / победитель"),
    ("prize", "sovrin / приз"),
]

HEALTH = [
    ("accident", "baxtsiz hodisa / несчастный случай"),
    ("ache", "uzoq davom etadigan og'riq / ноющая боль"),
    ("ambulance", "tez yordam / скорая помощь"),
    ("blood", "qon / кровь"),
    ("chemist", "dorixona / аптека"),
    ("cough", "yo'tal / кашель"),
    ("dangerous", "xavfli / опасный"),
    ("earache", "quloq og'rig'i / боль в ухе"),
    ("fever", "isitma / жар"),
    ("headache", "bosh og'rig'i / головная боль"),
    ("healthy", "sog'lom / здоровый"),
    ("hospital", "kasalxona / больница"),
    ("ill", "kasal / больной"),
    ("medicine", "dori / лекарство"),
    ("nurse", "hamshira / медсестра"),
    ("operation", "operatsiya / операция"),
    ("pain", "og'riq / боль"),
    ("patient", "bemor / пациент"),
    ("pill", "tabletka / таблетка"),
    ("stomach ache", "qorin og'rig'i / боль в животе"),
    ("temperature", "harorat / температура"),
    ("toothache", "tish og'rig'i / зубная боль"),
    ("injury", "jarohat / травма"),
    ("rest", "dam olish / отдых"),
    ("exercise", "jismoniy mashq / упражнение"),
]

CLOTHES = [
    ("blouse", "bluzka / блузка"),
    ("boot", "etik / ботинок"),
    ("bracelet", "bilaguzuk / браслет"),
    ("cap", "kepka / кепка"),
    ("coat", "palto / пальто"),
    ("costume", "kostyum, libos / костюм"),
    ("earring", "isirg'a / серьга"),
    ("glove", "qo'lqop / перчатка"),
    ("handbag", "qo'l sumkasi / сумочка"),
    ("jacket", "kurtka / куртка"),
    ("jeans", "jinsi shim / джинсы"),
    ("necklace", "marjon / ожерелье"),
    ("pocket", "cho'ntak / карман"),
    ("ring", "uzuk / кольцо"),
    ("scarf", "sharf / шарф"),
    ("shirt", "ko'ylak / рубашка"),
    ("shorts", "shortik / шорты"),
    ("skirt", "yubka / юбка"),
    ("sock", "paypoq / носок"),
    ("suit", "kostyum / костюм"),
    ("sweater", "sviter / свитер"),
    ("trainers", "krossovka / кроссовки"),
    ("umbrella", "soyabon / зонт"),
    ("uniform", "forma / форма"),
    ("watch", "qo'l soati / наручные часы"),
]

SHOPPING = [
    ("advert", "reklama / реклама"),
    ("bargain", "arzon mol / выгодная покупка"),
    ("cash", "naqd pul / наличные"),
    ("cent", "sent / цент"),
    ("cheap", "arzon / дешёвый"),
    ("cheque", "chek / чек"),
    ("coin", "tanga / монета"),
    ("cost", "narx, turmoq / стоить"),
    ("discount", "chegirma / скидка"),
    ("dollar", "dollar / доллар"),
    ("euro", "yevro / евро"),
    ("expensive", "qimmat / дорогой"),
    ("market", "bozor / рынок"),
    ("money", "pul / деньги"),
    ("pay", "to'lamoq / платить"),
    ("price", "narx / цена"),
    ("receipt", "chek, kvitansiya / чек"),
    ("sale", "chegirma savdosi / распродажа"),
    ("shelf", "javon / полка"),
    ("shopping centre", "savdo markazi / торговый центр"),
    ("spend", "sarflamoq / тратить"),
    ("supermarket", "supermarket / супермаркет"),
    ("wallet", "hamyon / кошелёк"),
    ("change", "qaytim / сдача"),
    ("customer service", "mijozlarga xizmat / обслуживание клиентов"),
]

FREE_TIME = [
    ("album", "albom / альбом"),
    ("cartoon", "multfilm / мультфильм"),
    ("chess", "shaxmat / шахматы"),
    ("circus", "sirk / цирк"),
    ("club", "klub / клуб"),
    ("comedy", "komediya / комедия"),
    ("concert", "konsert / концерт"),
    ("dance", "raqs / танец"),
    ("drawing", "rasm / рисунок"),
    ("exhibition", "ko'rgazma / выставка"),
    ("festival", "festival / фестиваль"),
    ("guitar", "gitara / гитара"),
    ("hobby", "sevimli mashg'ulot / хобби"),
    ("magazine", "jurnal / журнал"),
    ("novel", "roman / роман"),
    ("painting", "kartina / картина"),
    ("photograph", "surat / фотография"),
    ("piano", "pianino / пианино"),
    ("play", "spektakl / спектакль"),
    ("programme", "dastur / программа"),
    ("singer", "qo'shiqchi / певец"),
    ("ticket", "chipta / билет"),
    ("video game", "video o'yin / видеоигра"),
    ("audience", "tomoshabinlar / зрители"),
    ("drum", "baraban / барабан"),
]

TECH = [
    ("app", "ilova / приложение"),
    ("battery", "batareya / батарея"),
    ("camera", "kamera / камера"),
    ("channel", "kanal / канал"),
    ("chatroom", "chat xonasi / чат"),
    ("click", "bosmoq / нажать"),
    ("copy", "nusxa / копия"),
    ("digital", "raqamli / цифровой"),
    ("document", "hujjat / документ"),
    ("download", "yuklab olmoq / скачать"),
    ("email", "elektron pochta / электронная почта"),
    ("file", "fayl / файл"),
    ("internet", "internet / интернет"),
    ("keyboard", "klaviatura / клавиатура"),
    ("laptop", "noutbuk / ноутбук"),
    ("message", "xabar / сообщение"),
    ("mobile phone", "mobil telefon / мобильный телефон"),
    ("mouse", "sichqoncha / мышь"),
    ("online", "onlayn / онлайн"),
    ("password", "parol / пароль"),
    ("printer", "printer / принтер"),
    ("screen", "ekran / экран"),
    ("website", "veb-sayt / сайт"),
    ("charger", "zaryadlovchi / зарядное устройство"),
    ("headphones", "quloqchin / наушники"),
]

FEELINGS = [
    ("believe", "ishonmoq / верить"),
    ("bother", "bezovta qilmoq / беспокоить"),
    ("care", "g'amxo'rlik qilmoq / заботиться"),
    ("cry", "yig'lamoq / плакать"),
    ("dream", "orzu, tush / мечта, сон"),
    ("enjoy", "zavqlanmoq / наслаждаться"),
    ("expect", "kutmoq / ожидать"),
    ("feeling", "his, tuyg'u / чувство"),
    ("forget", "unutmoq / забывать"),
    ("hate", "yomon ko'rmoq / ненавидеть"),
    ("hope", "umid qilmoq / надеяться"),
    ("laugh", "kulmoq / смеяться"),
    ("mind", "qarshi bo'lmoq / возражать"),
    ("miss", "sog'inmoq / скучать"),
    ("prefer", "afzal ko'rmoq / предпочитать"),
    ("promise", "va'da bermoq / обещать"),
    ("remember", "eslamoq / помнить"),
    ("smile", "jilmaymoq / улыбаться"),
    ("surprise", "ajablantirmoq / удивлять"),
    ("trust", "ishonmoq, tayanmoq / доверять"),
    ("wish", "tilamoq / желать"),
    ("worry", "xavotirlanmoq / волноваться"),
    ("agree", "rozi bo'lmoq / соглашаться"),
    ("mean", "anglatmoq / значить"),
    ("wonder", "qiziqmoq / интересоваться"),
]

VERBS1 = [
    ("allow", "ruxsat bermoq / разрешать"),
    ("arrive", "yetib kelmoq / прибывать"),
    ("belong", "tegishli bo'lmoq / принадлежать"),
    ("borrow", "qarzga olmoq / брать взаймы"),
    ("lend", "qarz bermoq / давать взаймы"),
    ("bring", "olib kelmoq / приносить"),
    ("build", "qurmoq / строить"),
    ("carry", "ko'tarib yurmoq / нести"),
    ("catch", "ushlamoq / ловить"),
    ("choose", "tanlamoq / выбирать"),
    ("climb", "chiqmoq / взбираться"),
    ("collect", "yig'moq / собирать"),
    ("continue", "davom ettirmoq / продолжать"),
    ("deliver", "yetkazib bermoq / доставлять"),
    ("discover", "kashf qilmoq / открывать"),
    ("drop", "tushirib yubormoq / ронять"),
    ("earn", "ishlab topmoq / зарабатывать"),
    ("fill", "to'ldirmoq / наполнять"),
    ("hurry", "shoshilmoq / торопиться"),
    ("invite", "taklif qilmoq / приглашать"),
    ("join", "qo'shilmoq / присоединяться"),
    ("keep", "saqlamoq / хранить"),
    ("lose", "yo'qotmoq / терять"),
    ("move", "ko'chmoq / переезжать"),
    ("offer", "taklif qilmoq / предлагать"),
]

VERBS2 = [
    ("prepare", "tayyorlamoq / готовить"),
    ("protect", "himoya qilmoq / защищать"),
    ("pull", "tortmoq / тянуть"),
    ("push", "itarmoq / толкать"),
    ("receive", "qabul qilmoq / получать"),
    ("repair", "ta'mirlamoq / чинить"),
    ("repeat", "takrorlamoq / повторять"),
    ("return", "qaytmoq / возвращаться"),
    ("save", "tejamoq, saqlamoq / экономить"),
    ("share", "bo'lishmoq / делиться"),
    ("shout", "baqirmoq / кричать"),
    ("sign", "imzolamoq / подписывать"),
    ("solve", "hal qilmoq / решать"),
    ("suggest", "taklif qilmoq / предлагать"),
    ("throw", "uloqtirmoq / бросать"),
    ("touch", "tegmoq / трогать"),
    ("travel", "sayohat qilmoq / путешествовать"),
    ("turn", "burilmoq / поворачивать"),
    ("visit", "tashrif buyurmoq / посещать"),
    ("wait", "kutmoq / ждать"),
    ("win", "yutmoq / выигрывать"),
    ("worry about", "xavotir olmoq / беспокоиться о"),
    ("check", "tekshirmoq / проверять"),
    ("clean", "tozalamoq / чистить"),
    ("close", "yopmoq / закрывать"),
]

TIME = [
    ("afternoon", "tushdan keyin / после полудня"),
    ("afterwards", "keyinroq / потом"),
    ("already", "allaqachon / уже"),
    ("century", "asr / век"),
    ("daily", "kunlik / ежедневный"),
    ("early", "erta / рано"),
    ("evening", "kechqurun / вечер"),
    ("future", "kelajak / будущее"),
    ("half an hour", "yarim soat / полчаса"),
    ("immediately", "darhol / немедленно"),
    ("later", "keyinroq / позже"),
    ("midnight", "yarim tun / полночь"),
    ("moment", "lahza / момент"),
    ("month", "oy / месяц"),
    ("past", "o'tmish / прошлое"),
    ("quarter", "chorak / четверть"),
    ("recently", "yaqinda / недавно"),
    ("season", "fasl / сезон"),
    ("soon", "tez orada / скоро"),
    ("suddenly", "birdan / вдруг"),
    ("tonight", "bugun kechqurun / сегодня вечером"),
    ("twice", "ikki marta / дважды"),
    ("weekend", "dam olish kunlari / выходные"),
    ("yesterday", "kecha / вчера"),
    ("yet", "hali / ещё"),
]

LISTS = [
    ("A2 exam words 7 · Town and buildings", "exam", 7, TOWN),
    ("A2 exam words 8 · Travel and transport", "exam", 8, TRAVEL),
    ("A2 exam words 9 · Sport", "exam", 9, SPORT),
    ("A2 exam words 10 · Health and the body", "exam", 10, HEALTH),
    ("A2 exam words 11 · Clothes", "exam", 11, CLOTHES),
    ("A2 exam words 12 · Shopping and money", "exam", 12, SHOPPING),
    ("A2 exam words 13 · Free time", "exam", 13, FREE_TIME),
    ("A2 exam words 14 · Phones and computers", "exam", 14, TECH),
    ("A2 exam words 15 · Feelings and thinking", "exam", 15, FEELINGS),
    ("A2 exam words 16 · Everyday verbs 1", "exam", 16, VERBS1),
    ("A2 exam words 17 · Everyday verbs 2", "exam", 17, VERBS2),
    ("A2 exam words 18 · Time", "exam", 18, TIME),
]
