"""The A2 Key words Empower Elementary never teaches - steps 1 to 6.

The meanings are in Uzbek and Russian, not in English. An Elementary student
who does not know "biscuit" does not know "a small hard sweet cake" either,
so an English definition tests the definition rather than the word.
"""

FOOD = [
    ("biscuit", "pechene / печенье"),
    ("burger", "burger, kotlet nonda / бургер"),
    ("cereal", "donli nonushta / хлопья"),
    ("dessert", "shirinlik / десерт"),
    ("snack", "yengil gazak / перекус"),
    ("chilli", "achchiq qalampir / острый перец"),
    ("cream", "qaymoq / сливки"),
    ("flour", "un / мука"),
    ("honey", "asal / мёд"),
    ("jam", "murabbo / варенье"),
    ("lemon", "limon / лимон"),
    ("melon", "qovun / дыня"),
    ("mushroom", "qo'ziqorin / гриб"),
    ("sausage", "kolbasa, hasip / сосиска"),
    ("seafood", "dengiz mahsulotlari / морепродукты"),
    ("strawberry", "qulupnay / клубника"),
    ("toast", "qovurilgan non / тост"),
    ("vegetarian", "vegetarian, go'sht yemaydigan / вегетарианец"),
    ("bowl", "kosa / миска"),
    ("fork", "sanchqi / вилка"),
    ("spoon", "qoshiq / ложка"),
    ("knife", "pichoq / нож"),
    ("plate", "tarelka, likopcha / тарелка"),
    ("meal", "ovqat, taom / приём пищи"),
    ("recipe", "retsept / рецепт"),
]

HOME = [
    ("apartment", "kvartira / квартира"),
    ("bathtub", "vanna / ванна"),
    ("ceiling", "shift / потолок"),
    ("cupboard", "shkaf / шкаф"),
    ("curtain", "parda / штора"),
    ("drawer", "tortma / выдвижной ящик"),
    ("downstairs", "pastda, pastki qavatda / внизу"),
    ("upstairs", "tepada, yuqori qavatda / наверху"),
    ("entrance", "kirish joyi / вход"),
    ("exit", "chiqish joyi / выход"),
    ("garage", "garaj / гараж"),
    ("gate", "darvoza / ворота"),
    ("heating", "isitish tizimi / отопление"),
    ("key", "kalit / ключ"),
    ("lift", "lift / лифт"),
    ("lock", "qulf / замок"),
    ("neighbourhood", "mahalla / район"),
    ("rent", "ijara haqi / аренда"),
    ("roof", "tom / крыша"),
    ("stairs", "zinapoya / лестница"),
    ("switch", "vyklyuchatel / выключатель"),
    ("towel", "sochiq / полотенце"),
    ("wall", "devor / стена"),
    ("floor", "pol, qavat / пол"),
    ("furniture", "mebel / мебель"),
]

NATURE = [
    ("air", "havo / воздух"),
    ("bee", "asalari / пчела"),
    ("butterfly", "kapalak / бабочка"),
    ("camel", "tuya / верблюд"),
    ("cow", "sigir / корова"),
    ("crocodile", "timsoh / крокодил"),
    ("dolphin", "delfin / дельфин"),
    ("donkey", "eshak / осёл"),
    ("duck", "o'rdak / утка"),
    ("eagle", "burgut / орёл"),
    ("elephant", "fil / слон"),
    ("goat", "echki / коза"),
    ("insect", "hasharot / насекомое"),
    ("lion", "sher / лев"),
    ("monkey", "maymun / обезьяна"),
    ("sheep", "qo'y / овца"),
    ("tiger", "yo'lbars / тигр"),
    ("whale", "kit / кит"),
    ("autumn", "kuz / осень"),
    ("branch", "shox / ветка"),
    ("grass", "o't, maysa / трава"),
    ("leaf", "barg / лист"),
    ("plant", "o'simlik / растение"),
    ("wood", "yog'och / дерево, древесина"),
    ("seed", "urug' / семя"),
]

SCHOOL = [
    ("advanced", "yuqori darajadagi / продвинутый"),
    ("beginner", "boshlovchi / начинающий"),
    ("biology", "biologiya / биология"),
    ("chemistry", "kimyo / химия"),
    ("geography", "geografiya / география"),
    ("history", "tarix / история"),
    ("blackboard", "doska / доска"),
    ("classmate", "sinfdosh / одноклассник"),
    ("classroom", "sinf xonasi / класс"),
    ("diploma", "diplom / диплом"),
    ("dictionary", "lug'at / словарь"),
    ("eraser", "o'chirg'ich / ластик"),
    ("example", "misol / пример"),
    ("experiment", "tajriba / эксперимент"),
    ("explain", "tushuntirmoq / объяснять"),
    ("headteacher", "maktab direktori / директор школы"),
    ("lesson", "dars / урок"),
    ("notice", "e'lon / объявление"),
    ("project", "loyiha / проект"),
    ("pupil", "o'quvchi / ученик"),
    ("rule", "qoida / правило"),
    ("student", "talaba / студент"),
    ("term", "chorak, semestr / четверть"),
    ("university", "universitet / университет"),
    ("mark", "baho / оценка"),
]

PEOPLE = [
    ("artist", "rassom / художник"),
    ("assistant", "yordamchi / помощник"),
    ("boss", "boshliq / начальник"),
    ("career", "karyera / карьера"),
    ("celebrity", "mashhur odam / знаменитость"),
    ("chemist", "dorixona / аптека"),
    ("cleaner", "farrosh / уборщик"),
    ("coach", "murabbiy / тренер"),
    ("colleague", "hamkasb / коллега"),
    ("company", "kompaniya / компания"),
    ("customer", "xaridor / покупатель"),
    ("dancer", "raqqosa / танцор"),
    ("dentist", "tish shifokori / стоматолог"),
    ("director", "direktor / директор"),
    ("employee", "xodim / сотрудник"),
    ("engineer", "muhandis / инженер"),
    ("explorer", "kashfiyotchi / исследователь"),
    ("guest", "mehmon / гость"),
    ("guide", "gid, yo'lboshchi / гид"),
    ("hero", "qahramon / герой"),
    ("manager", "menejer / менеджер"),
    ("owner", "egasi / владелец"),
    ("passenger", "yo'lovchi / пассажир"),
    ("politician", "siyosatchi / политик"),
    ("tourist", "turist / турист"),
]

ADJECTIVES = [
    ("able", "qodir / способный"),
    ("afraid", "qo'rqqan / испуганный"),
    ("amazed", "hayratlangan / изумлённый"),
    ("angry", "jahli chiqqan / сердитый"),
    ("attractive", "jozibali / привлекательный"),
    ("awful", "dahshatli / ужасный"),
    ("bored", "zerikkan / скучающий"),
    ("brave", "jasur / смелый"),
    ("broken", "singan, buzilgan / сломанный"),
    ("clever", "aqlli / умный"),
    ("dangerous", "xavfli / опасный"),
    ("deep", "chuqur / глубокий"),
    ("delicious", "mazali / вкусный"),
    ("dirty", "iflos / грязный"),
    ("empty", "bo'sh / пустой"),
    ("excellent", "a'lo / отличный"),
    ("excited", "hayajonlangan / взволнованный"),
    ("famous", "mashhur / известный"),
    ("lazy", "dangasa / ленивый"),
    ("nervous", "asabiy, hayajonda / нервный"),
    ("noisy", "shovqinli / шумный"),
    ("proud", "faxrlanadigan / гордый"),
    ("quiet", "tinch, jim / тихий"),
    ("strange", "g'alati / странный"),
    ("tidy", "tartibli / аккуратный"),
]

LISTS = [
    ("A2 exam words 1 · Food and eating", "exam", 1, FOOD),
    ("A2 exam words 2 · The home", "exam", 2, HOME),
    ("A2 exam words 3 · Animals and nature", "exam", 3, NATURE),
    ("A2 exam words 4 · School and study", "exam", 4, SCHOOL),
    ("A2 exam words 5 · People and jobs", "exam", 5, PEOPLE),
    ("A2 exam words 6 · Describing people and things", "exam", 6, ADJECTIVES),
]
