"""B1 Preliminary exam words, steps 27-39. Meanings in Uzbek and Russian."""

LEVEL = "Pre-Intermediate"
BOOK = "B1 Preliminary exam words"
PAST_FROM = 1

VERBS3 = [
    ("admit", "tan olmoq / признавать"),
    ("afford", "imkoni bo'lmoq / позволить себе"),
    ("apologise", "uzr so'ramoq / извиняться"),
    ("appear", "paydo bo'lmoq / появляться"),
    ("argue", "bahslashmoq / спорить"),
    ("arrange", "kelishib olmoq / договариваться"),
    ("attend", "qatnashmoq / посещать"),
    ("beg", "yalinmoq / умолять"),
    ("belong", "tegishli bo'lmoq / принадлежать"),
    ("bury", "ko'mmoq / хоронить"),
    ("celebrate", "nishonlamoq / отмечать"),
    ("challenge", "chaqiriq tashlamoq / бросать вызов"),
    ("cheat", "aldamoq / жульничать"),
    ("clap", "qarsak chalmoq / хлопать"),
    ("compare", "taqqoslamoq / сравнивать"),
    ("compete", "raqobatlashmoq / соревноваться"),
    ("complain", "shikoyat qilmoq / жаловаться"),
    ("count", "sanamoq / считать"),
    ("dig", "kavlamoq / копать"),
    ("dislike", "yoqtirmaslik / не любить"),
    ("divide", "bo'lmoq / делить"),
    ("drag", "sudramoq / тащить"),
    ("earn", "topmoq / зарабатывать"),
    ("expect", "kutmoq / ожидать"),
    ("explode", "portlamoq / взрываться"),
]

VERBS4 = [
    ("fetch", "olib kelmoq / приносить"),
    ("fight", "urishmoq / драться"),
    ("float", "suzib yurmoq / плавать на поверхности"),
    ("fold", "buklamoq / складывать"),
    ("gain", "qo'lga kiritmoq / получать"),
    ("glance", "ko'z tashlamoq / взглянуть"),
    ("grab", "changallab olmoq / хватать"),
    ("greet", "salomlashmoq / приветствовать"),
    ("hop", "sakramoq / прыгать"),
    ("inform", "xabardor qilmoq / сообщать"),
    ("inspire", "ilhomlantirmoq / вдохновлять"),
    ("intend", "niyat qilmoq / намереваться"),
    ("interrupt", "gapini bo'lmoq / перебивать"),
    ("introduce", "tanishtirmoq / представлять"),
    ("judge", "baho bermoq / судить"),
    ("knit", "to'qimoq / вязать"),
    ("lend", "qarz bermoq / одалживать"),
    ("melt", "eritmoq / плавить"),
    ("notice", "sezmoq / замечать"),
    ("obtain", "rasmiy yo'l bilan olmoq / получать официально"),
    ("offer", "taklif qilmoq / предлагать"),
    ("own", "egalik qilmoq / владеть"),
    ("pretend", "o'zini ko'rsatmoq / притворяться"),
    ("promise", "va'da bermoq / обещать"),
    ("pull", "tortmoq / тянуть"),
]

VERBS5 = [
    ("realise", "anglab yetmoq / осознавать"),
    ("recognise", "tanimoq / узнавать"),
    ("recommend", "tavsiya qilmoq / рекомендовать"),
    ("regret", "afsuslanmoq / сожалеть"),
    ("relax", "bo'shashmoq / расслабляться"),
    ("remain", "qolmoq / оставаться"),
    ("repair", "ta'mirlamoq / ремонтировать"),
    ("report", "xabar bermoq / докладывать"),
    ("respect", "hurmat qilmoq / уважать"),
    ("return", "qaytmoq / возвращаться"),
    ("shout", "baqirmoq / кричать"),
    ("sign", "imzo qo'ymoq / подписывать"),
    ("solve", "hal qilmoq / решать"),
    ("spill", "to'kmoq / проливать"),
    ("spread", "yoymoq / распространять"),
    ("suggest", "taklif qilmoq / предлагать"),
    ("support", "qo'llab-quvvatlamoq / поддерживать"),
    ("survive", "omon qolmoq / выживать"),
    ("swallow", "yutmoq / глотать"),
    ("tidy", "tartibga solmoq / убирать"),
    ("translate", "tarjima qilmoq / переводить"),
    ("treat", "muomala qilmoq, davolamoq / обращаться, лечить"),
    ("trust", "ishonmoq / доверять"),
    ("whisper", "shivirlamoq / шептать"),
    ("wrap", "o'ramoq / заворачивать"),
]

SHOPPING = [
    ("brand", "brend / бренд"),
    ("customer service", "mijoz xizmati / клиентская служба"),
    ("delivery", "yetkazib berish / доставка"),
    ("department store", "universal do'kon / универмаг"),
    ("faulty", "nosoz / неисправный"),
    ("guarantee", "kafolat / гарантия"),
    ("label", "yorliq / этикетка"),
    ("mall", "savdo markazi / торговый центр"),
    ("purchase", "xarid / покупка"),
    ("refund", "pulni qaytarish / возврат денег"),
    ("stall", "rasta / прилавок"),
    ("stock", "tovar zaxirasi / запас товара"),
    ("supply", "ta'minot / поставка"),
    ("trolley", "arava / тележка"),
    ("wrap up", "o'rab berish / упаковывать"),
    ("receipt", "chek / чек"),
    ("exchange", "almashtirish / обмен"),
    ("complaint", "shikoyat / жалоба"),
    ("queue", "navbat / очередь"),
    ("discount", "chegirma / скидка"),
    ("cashier", "kassir / кассир"),
    ("goods", "tovarlar / товары"),
    ("order", "buyurtma / заказ"),
    ("deliver", "yetkazib bermoq / доставлять"),
    ("bargain hunter", "arzon mol izlovchi / охотник за скидками"),
]

WORKPLACE = [
    ("application", "ariza / заявление"),
    ("appointment", "uchrashuv vaqti / назначенная встреча"),
    ("career", "kasbiy yo'l / карьера"),
    ("colleague", "hamkasb / коллега"),
    ("employer", "ish beruvchi / работодатель"),
    ("employee", "xodim / работник"),
    ("experience", "ish tajribasi / опыт"),
    ("interviewer", "suhbat oluvchi / интервьюер"),
    ("manager", "rahbar / руководитель"),
    ("occupation", "kasb / профессия"),
    ("office", "ofis / офис"),
    ("promotion", "ko'tarilish / повышение"),
    ("qualification", "malaka / квалификация"),
    ("responsibility", "vazifa / обязанность"),
    ("retire", "nafaqaga chiqmoq / выходить на пенсию"),
    ("salary", "maosh / оклад"),
    ("secretary", "kotib / секретарь"),
    ("shift", "smena / смена"),
    ("skill", "malaka, ko'nikma / навык"),
    ("staff", "jamoa, xodimlar / персонал"),
    ("trainee", "amaliyotchi / стажёр"),
    ("uniform", "ish kiyimi / форма"),
    ("workplace", "ish joyi / рабочее место"),
    ("assistant", "yordamchi / ассистент"),
    ("director", "direktor / директор"),
]

SCIENCE = [
    ("astronaut", "kosmonavt / космонавт"),
    ("atmosphere", "atmosfera / атмосфера"),
    ("chemical", "kimyoviy modda / химическое вещество"),
    ("continent", "qit'a / континент"),
    ("energy", "energiya / энергия"),
    ("environment", "atrof-muhit / окружающая среда"),
    ("environmental", "ekologik / экологический"),
    ("experiment", "tajriba / эксперимент"),
    ("expert", "mutaxassis / эксперт"),
    ("fuel", "yoqilg'i / топливо"),
    ("gas", "gaz / газ"),
    ("invention", "ixtiro / изобретение"),
    ("inventor", "ixtirochi / изобретатель"),
    ("liquid", "suyuqlik / жидкость"),
    ("metal", "metall / металл"),
    ("planet", "sayyora / планета"),
    ("pollution", "ifloslanish / загрязнение"),
    ("power", "quvvat / энергия, мощность"),
    ("research", "tadqiqot / исследование"),
    ("scientific", "ilmiy / научный"),
    ("space", "koinot / космос"),
    ("technology", "texnologiya / технология"),
    ("theory", "nazariya / теория"),
    ("recycle", "qayta ishlamoq / перерабатывать"),
    ("waste", "chiqindi / отходы"),
]

FEELINGS2 = [
    ("admiration", "qoyil qolish / восхищение"),
    ("affection", "mehr / привязанность"),
    ("annoyance", "g'ashlik / раздражение"),
    ("comfort", "tasalli / утешение"),
    ("confidence", "ishonch / уверенность"),
    ("curiosity", "qiziquvchanlik / любопытство"),
    ("desire", "istak / желание"),
    ("disappointment", "umidsizlik / разочарование"),
    ("embarrassment", "noqulaylik / смущение"),
    ("enthusiasm", "ishtiyoq / энтузиазм"),
    ("envy", "hasad / зависть"),
    ("gratitude", "minnatdorchilik / благодарность"),
    ("happiness", "baxt / счастье"),
    ("hatred", "nafrat / ненависть"),
    ("hope", "umid / надежда"),
    ("joy", "quvonch / радость"),
    ("loneliness", "yolg'izlik / одиночество"),
    ("nerves", "hayajon / нервы"),
    ("panic", "vahima / паника"),
    ("patience", "sabr / терпение"),
    ("pity", "achinish / жалость"),
    ("pride", "g'urur / гордость"),
    ("sadness", "g'amginlik / грусть"),
    ("shame", "uyat / стыд"),
    ("sympathy", "hamdardlik / сочувствие"),
]

HOMELIFE = [
    ("accommodation", "turar joy / жильё"),
    ("apartment block", "ko'p qavatli uy / многоквартирный дом"),
    ("basement", "yerto'la / подвал"),
    ("ceiling", "shift / потолок"),
    ("chimney", "mo'ri / дымоход"),
    ("cottage", "qishloq uyi / коттедж"),
    ("corridor", "yo'lak / коридор"),
    ("fence", "panjara / забор"),
    ("furnished", "mebellashtirilgan / меблированный"),
    ("garage", "garaj / гараж"),
    ("gate", "darvoza / ворота"),
    ("ground floor", "birinchi qavat / первый этаж"),
    ("hall", "dahliz / прихожая"),
    ("heating", "isitish / отопление"),
    ("housing", "uy-joy / жильё"),
    ("lift", "lift / лифт"),
    ("move house", "ko'chib o'tmoq / переезжать"),
    ("neighbour", "qo'shni / сосед"),
    ("rent", "ijaraga olmoq / снимать"),
    ("roof", "tom / крыша"),
    ("stair", "zina / ступенька"),
    ("study", "ish xonasi / кабинет"),
    ("upstairs", "yuqori qavat / верхний этаж"),
    ("view", "manzara / вид"),
    ("wall", "devor / стена"),
]

DAILY = [
    ("alarm", "signal, budilnik / сигнал, будильник"),
    ("appointment book", "kundalik daftar / ежедневник"),
    ("chore", "uy yumushi / домашняя обязанность"),
    ("commute", "ishga qatnamoq / ездить на работу"),
    ("errand", "yumush / поручение"),
    ("habit", "odat / привычка"),
    ("hobby", "mashg'ulot / хобби"),
    ("leisure", "bo'sh vaqt / досуг"),
    ("lunchtime", "tushlik vaqti / обеденное время"),
    ("nap", "kunduzgi uyqu / дневной сон"),
    ("routine", "kundalik tartib / распорядок"),
    ("schedule", "jadval / график"),
    ("shopping list", "xaridlar ro'yxati / список покупок"),
    ("spare time", "ortiqcha vaqt / свободное время"),
    ("timetable", "dars jadvali / расписание"),
    ("wake up", "uyg'onmoq / просыпаться"),
    ("get ready", "tayyorlanmoq / собираться"),
    ("run late", "kechikayotgan bo'lmoq / опаздывать"),
    ("oversleep", "uxlab qolmoq / проспать"),
    ("relaxation", "dam olish / отдых"),
    ("weekday", "ish kuni / будний день"),
    ("daily", "har kungi / ежедневный"),
    ("busy day", "band kun / насыщенный день"),
    ("free day", "bo'sh kun / свободный день"),
    ("plan ahead", "oldindan rejalashtirmoq / планировать заранее"),
]

PLACES = [
    ("abroad", "chet el / заграница"),
    ("border", "chegara / граница"),
    ("capital", "poytaxt / столица"),
    ("countryside", "qishloq joy / сельская местность"),
    ("desert", "cho'l / пустыня"),
    ("eastern", "sharqiy / восточный"),
    ("western", "g'arbiy / западный"),
    ("northern", "shimoliy / северный"),
    ("southern", "janubiy / южный"),
    ("island", "orol / остров"),
    ("region", "viloyat / регион"),
    ("rural", "qishloqqa oid / сельский"),
    ("urban", "shaharga oid / городской"),
    ("seaside", "dengiz bo'yi / морское побережье"),
    ("valley", "vodiy / долина"),
    ("volcano", "vulqon / вулкан"),
    ("waterfall", "sharshara / водопад"),
    ("jungle", "tropik o'rmon / джунгли"),
    ("path", "so'qmoq / тропа"),
    ("route", "yo'l / путь"),
    ("scenery", "manzara / пейзаж"),
    ("surroundings", "atrof / окрестности"),
    ("landscape", "tabiat manzarasi / ландшафт"),
    ("site", "joy, maydon / место, площадка"),
    ("territory", "hudud / территория"),
]

EVENTS = [
    ("anniversary", "yubiley / годовщина"),
    ("ceremony", "marosim / церемония"),
    ("conference", "konferensiya / конференция"),
    ("date", "sana, uchrashuv / дата, свидание"),
    ("event", "tadbir / мероприятие"),
    ("exhibition", "ko'rgazma / выставка"),
    ("festival", "bayram / фестиваль"),
    ("funeral", "dafn marosimi / похороны"),
    ("honeymoon", "asal oyi / медовый месяц"),
    ("meeting", "yig'ilish / собрание"),
    ("occasion", "munosabat / повод"),
    ("parade", "yurish / шествие"),
    ("party", "ziyofat / вечеринка"),
    ("reception", "qabul / приём"),
    ("rehearsal", "mashq / репетиция"),
    ("reunion", "uchrashuv kechasi / встреча выпускников"),
    ("celebration", "nishonlash / празднование"),
    ("guest list", "mehmonlar ro'yxati / список гостей"),
    ("invitation card", "taklifnoma / пригласительный"),
    ("speech", "nutq / речь"),
    ("toast", "qadah so'zi / тост"),
    ("host", "mezbon / хозяин мероприятия"),
    ("venue", "o'tkaziladigan joy / место проведения"),
    ("decorations", "bezaklar / украшения"),
    ("firework display", "mushakbozlik / фейерверк"),
]

MEASURE = [
    ("amount", "miqdor / количество"),
    ("average", "o'rtacha / средний"),
    ("bunch", "dasta / пучок"),
    ("depth", "chuqurlik / глубина"),
    ("distance", "masofa / расстояние"),
    ("dozen", "o'n ikki dona / дюжина"),
    ("height", "balandlik / высота"),
    ("inch", "dyuym / дюйм"),
    ("length", "uzunlik / длина"),
    ("majority", "ko'pchilik / большинство"),
    ("minority", "ozchilik / меньшинство"),
    ("percentage", "foiz / процент"),
    ("piece", "bo'lak / кусок"),
    ("quarter", "chorak / четверть"),
    ("rate", "stavka, tezlik / ставка, темп"),
    ("scale", "miqyos / масштаб"),
    ("size", "o'lcham / размер"),
    ("speed", "tezlik / скорость"),
    ("total", "jami / итого"),
    ("weight", "og'irlik / вес"),
    ("width", "kenglik / ширина"),
    ("plenty", "mo'l-ko'l / множество"),
    ("several", "bir nechta / несколько"),
    ("whole", "butun / целый"),
    ("double", "ikki karra / двойной"),
]

LISTS = [
    ("B1 exam words 27 · Common verbs 3", "exam", 27, VERBS3),
    ("B1 exam words 28 · Common verbs 4", "exam", 28, VERBS4),
    ("B1 exam words 29 · Common verbs 5", "exam", 29, VERBS5),
    ("B1 exam words 30 · Shopping", "exam", 30, SHOPPING),
    ("B1 exam words 31 · At work", "exam", 31, WORKPLACE),
    ("B1 exam words 32 · Science and the planet", "exam", 32, SCIENCE),
    ("B1 exam words 33 · Feelings as nouns", "exam", 33, FEELINGS2),
    ("B1 exam words 34 · Homes", "exam", 34, HOMELIFE),
    ("B1 exam words 35 · Daily life", "exam", 35, DAILY),
    ("B1 exam words 36 · Places and geography", "exam", 36, PLACES),
    ("B1 exam words 37 · Events", "exam", 37, EVENTS),
    ("B1 exam words 38 · Measuring", "exam", 38, MEASURE),
]
