"""B1 Preliminary exam words, steps 14-26. Meanings in Uzbek and Russian."""

LEVEL = "Pre-Intermediate"
BOOK = "B1 Preliminary exam words"
PAST_FROM = 1

VERBS2 = [
    ("invent", "ixtiro qilmoq / изобретать"),
    ("involve", "o'z ichiga olmoq / включать в себя"),
    ("knock", "taqillatmoq / стучать"),
    ("lay", "qo'ymoq, yotqizmoq / класть"),
    ("lead", "boshlab bormoq / вести"),
    ("locate", "joyini aniqlamoq / находить"),
    ("manage", "uddalamoq / справляться"),
    ("measure", "o'lchamoq / измерять"),
    ("mend", "tuzatmoq / чинить"),
    ("mention", "tilga olmoq / упоминать"),
    ("multiply", "ko'paytirmoq / умножать"),
    ("operate", "ishlatmoq, jarrohlik qilmoq / управлять, оперировать"),
    ("prevent", "oldini olmoq / предотвращать"),
    ("provide", "ta'minlamoq / обеспечивать"),
    ("reduce", "kamaytirmoq / сокращать"),
    ("refuse", "rad etmoq / отказываться"),
    ("remove", "olib tashlamoq / убирать"),
    ("replace", "almashtirmoq / заменять"),
    ("rescue", "qutqarmoq / спасать"),
    ("select", "tanlamoq / выбирать"),
    ("separate", "ajratmoq / разделять"),
    ("succeed", "muvaffaqiyat qozonmoq / преуспевать"),
    ("suffer", "azob chekmoq / страдать"),
    ("warn", "ogohlantirmoq / предупреждать"),
    ("waste", "isrof qilmoq / тратить впустую"),
]

TRAVEL = [
    ("airline", "aviakompaniya / авиакомпания"),
    ("baggage", "yuk / багаж"),
    ("backpacker", "ryukzakli sayyoh / турист с рюкзаком"),
    ("cab", "taksi / такси"),
    ("cabin", "kayut, salon / каюта, салон"),
    ("cruise", "kruiz / круиз"),
    ("harbour", "port / гавань"),
    ("hitchhike", "yo'lda mashina to'xtatib yurmoq / путешествовать автостопом"),
    ("jet", "reaktiv samolyot / реактивный самолёт"),
    ("lorry", "yuk mashinasi / грузовик"),
    ("motorcycle", "mototsikl / мотоцикл"),
    ("crossroads", "chorraha / перекрёсток"),
    ("route", "yo'nalish / маршрут"),
    ("traffic", "yo'l harakati / движение"),
    ("fasten", "mahkamlamoq / пристёгивать"),
    ("boarding pass", "chiqish taloni / посадочный талон"),
    ("terminal", "terminal / терминал"),
    ("hire", "ijaraga olmoq / брать напрокат"),
    ("insurance", "sug'urta / страховка"),
    ("motorway", "avtomagistral / автомагистраль"),
    ("pedestrian", "piyoda / пешеход"),
    ("petrol", "benzin / бензин"),
    ("rail", "temir yo'l / железная дорога"),
    ("voyage", "dengiz safari / морское путешествие"),
    ("abroad", "chet elda / за рубежом"),
]

TOWN = [
    ("cathedral", "bosh cherkov / собор"),
    ("college", "kollej / колледж"),
    ("embassy", "elchixona / посольство"),
    ("hall", "zal, dahliz / зал, холл"),
    ("nightclub", "tungi klub / ночной клуб"),
    ("district", "tuman, hudud / район"),
    ("central", "markaziy / центральный"),
    ("suburb", "shahar chekkasi / пригород"),
    ("neighbourhood", "mahalla / район проживания"),
    ("pavement", "yo'lka / тротуар"),
    ("fountain", "favvora / фонтан"),
    ("monument", "yodgorlik / памятник"),
    ("statue", "haykal / статуя"),
    ("tower", "minora / башня"),
    ("bridge", "ko'prik / мост"),
    ("canal", "kanal / канал"),
    ("landmark", "mashhur joy / достопримечательность"),
    ("residential", "turar joy / жилой"),
    ("public", "jamoat / общественный"),
    ("private", "shaxsiy / частный"),
    ("facility", "qulaylik, inshoot / объект, удобство"),
    ("construction", "qurilish / строительство"),
    ("architecture", "me'morchilik / архитектура"),
    ("capital city", "poytaxt / столица"),
    ("population", "aholi / население"),
]

MEDIA = [
    ("ballet", "balet / балет"),
    ("documentary", "hujjatli film / документальный фильм"),
    ("drama", "drama / драма"),
    ("episode", "qism / серия"),
    ("jazz", "jaz / джаз"),
    ("musical", "myuzikl / мюзикл"),
    ("opera", "opera / опера"),
    ("horror", "qo'rqinchli film / фильм ужасов"),
    ("guitarist", "gitarachi / гитарист"),
    ("novelist", "yozuvchi / романист"),
    ("celebrity", "mashhur shaxs / знаменитость"),
    ("channel", "telekanal / канал"),
    ("broadcast", "efir / трансляция"),
    ("headline", "sarlavha / заголовок"),
    ("journalism", "jurnalistika / журналистика"),
    ("audience", "tomoshabin / аудитория"),
    ("performance", "chiqish / выступление"),
    ("release", "chiqarmoq / выпускать"),
    ("script", "ssenariy / сценарий"),
    ("subtitle", "subtitr / субтитры"),
    ("soundtrack", "film musiqasi / саундтрек"),
    ("review", "taqriz / обзор"),
    ("fiction", "badiiy adabiyot / художественная литература"),
    ("biography", "tarjimai hol / биография"),
    ("bestseller", "eng ko'p sotilgan kitob / бестселлер"),
]

SPORT = [
    ("championship", "chempionat / чемпионат"),
    ("competitor", "raqobatchi / соперник"),
    ("contest", "tanlov / конкурс"),
    ("cricket", "kriket / крикет"),
    ("cyclist", "velosipedchi / велосипедист"),
    ("golf", "golf / гольф"),
    ("gymnastics", "gimnastika / гимнастика"),
    ("hockey", "xokkey / хоккей"),
    ("jockey", "chavandoz / жокей"),
    ("jog", "sekin yugurmoq / бегать трусцой"),
    ("kit", "sport kiyimi va jihozi / экипировка"),
    ("opponent", "raqib / противник"),
    ("coach", "murabbiy / тренер"),
    ("league", "liga / лига"),
    ("medal", "medal / медаль"),
    ("trophy", "kubok / трофей"),
    ("defeat", "mag'lub etmoq / побеждать кого-то"),
    ("score", "hisob / счёт"),
    ("penalty", "penalti / пенальти"),
    ("athletic", "sportchiga xos / атлетичный"),
    ("professional", "professional / профессиональный"),
    ("amateur", "havaskor / любитель"),
    ("spectator", "tomoshabin / зритель"),
    ("tournament", "turnir / турнир"),
    ("fitness", "jismoniy holat / физическая форма"),
]

CLOTHES = [
    ("collar", "yoqa / воротник"),
    ("cotton", "paxta mato / хлопок"),
    ("handkerchief", "ro'molcha / носовой платок"),
    ("hoodie", "kapyushonli kofta / худи"),
    ("jewellery", "zargarlik buyumlari / украшения"),
    ("leather", "charm / кожа"),
    ("wool", "jun / шерсть"),
    ("silk", "ipak / шёлк"),
    ("sleeve", "yeng / рукав"),
    ("button", "tugma / пуговица"),
    ("zip", "zamok / молния"),
    ("pocket", "cho'ntak / карман"),
    ("scarf", "sharf / шарф"),
    ("glove", "qo'lqop / перчатка"),
    ("sandal", "sandal / сандалия"),
    ("slipper", "shippak / тапочка"),
    ("swimsuit", "cho'milish kiyimi / купальник"),
    ("tights", "kolgotka / колготки"),
    ("tie", "galstuk / галстук"),
    ("apron", "fartuk / фартук"),
    ("casual clothes", "kundalik kiyim / повседневная одежда"),
    ("smart clothes", "rasmiy kiyim / нарядная одежда"),
    ("try on", "kiyib ko'rmoq / примерять"),
    ("fit", "o'lchamiga to'g'ri kelmoq / подходить по размеру"),
    ("suit somebody", "yarashmoq / идти кому-то"),
]

TECH = [
    ("cable", "kabel / кабель"),
    ("calculator", "kalkulyator / калькулятор"),
    ("connection", "ulanish / соединение"),
    ("data", "ma'lumotlar / данные"),
    ("disk", "disk / диск"),
    ("display", "ekranda ko'rsatish / дисплей"),
    ("hardware", "texnik qism / оборудование"),
    ("software", "dasturiy ta'minot / программное обеспечение"),
    ("homepage", "bosh sahifa / главная страница"),
    ("microphone", "mikrofon / микрофон"),
    ("microwave", "mikroto'lqinli pech / микроволновка"),
    ("network", "tarmoq / сеть"),
    ("device", "qurilma / устройство"),
    ("digital", "raqamli / цифровой"),
    ("electronic", "elektron / электронный"),
    ("install", "o'rnatmoq / устанавливать"),
    ("log in", "tizimga kirmoq / входить в систему"),
    ("search engine", "qidiruv tizimi / поисковик"),
    ("browse", "ko'rib chiqmoq / просматривать"),
    ("virus", "virus / вирус"),
    ("back up", "zaxira nusxa olmoq / делать резервную копию"),
    ("wireless", "simsiz / беспроводной"),
    ("satellite", "sun'iy yo'ldosh / спутник"),
    ("robot", "robot / робот"),
    ("engineering", "muhandislik / инженерное дело"),
]

TIME = [
    ("annual", "yillik / ежегодный"),
    ("fortnight", "ikki hafta / две недели"),
    ("frequently", "tez-tez / часто"),
    ("generally", "odatda / обычно"),
    ("immediately", "darhol / немедленно"),
    ("lately", "yaqinda / в последнее время"),
    ("latest", "eng so'nggi / новейший"),
    ("meanwhile", "shu orada / тем временем"),
    ("midday", "tush payti / полдень"),
    ("monthly", "oylik / ежемесячный"),
    ("noon", "peshin / полдень"),
    ("occasionally", "ba'zan / изредка"),
    ("eventually", "oxir-oqibat / в конце концов"),
    ("nowadays", "hozirgi vaqtda / в наши дни"),
    ("previously", "oldin / ранее"),
    ("recently", "yaqinda / недавно"),
    ("regularly", "muntazam / регулярно"),
    ("seldom", "kamdan-kam / редко"),
    ("temporary", "vaqtinchalik / временный"),
    ("permanent", "doimiy / постоянный"),
    ("deadline", "oxirgi muddat / крайний срок"),
    ("period", "davr / период"),
    ("stage", "bosqich / этап"),
    ("whenever", "qachon bo'lmasin / всякий раз когда"),
    ("overnight", "tun bo'yi / на ночь"),
]

LINKING = [
    ("actually", "aslida / на самом деле"),
    ("altogether", "umuman olganda / в целом"),
    ("apart from", "dan tashqari / кроме"),
    ("approximately", "taxminan / приблизительно"),
    ("besides", "bundan tashqari / кроме того"),
    ("despite", "qaramay / несмотря на"),
    ("directly", "to'g'ridan-to'g'ri / напрямую"),
    ("extremely", "nihoyatda / чрезвычайно"),
    ("fairly", "ancha / довольно"),
    ("finally", "nihoyat / наконец"),
    ("honestly", "rostini aytganda / честно говоря"),
    ("hopefully", "umid qilamanki / надеюсь"),
    ("indeed", "haqiqatan ham / действительно"),
    ("instead", "o'rniga / вместо этого"),
    ("mainly", "asosan / главным образом"),
    ("obviously", "ravshanki / очевидно"),
    ("otherwise", "aks holda / иначе"),
    ("probably", "ehtimol / вероятно"),
    ("rather", "ancha, ko'proq / довольно, скорее"),
    ("therefore", "shuning uchun / поэтому"),
    ("though", "garchi / хотя"),
    ("unless", "agar bo'lmasa / если не"),
    ("whereas", "holbuki / тогда как"),
    ("moreover", "bundan tashqari / более того"),
    ("nevertheless", "shunga qaramay / тем не менее"),
]

DESCRIBE2 = [
    ("amusing", "kulgili / забавный"),
    ("awesome", "zo'r / потрясающий"),
    ("bitter", "achchiq / горький"),
    ("blank", "bo'sh, yozilmagan / пустой"),
    ("cultural", "madaniy / культурный"),
    ("damaged", "shikastlangan / повреждённый"),
    ("disgusting", "jirkanch / отвратительный"),
    ("dusty", "changli / пыльный"),
    ("elderly", "keksa / пожилой"),
    ("empty", "bo'sh / пустой"),
    ("foreign", "chet el / иностранный"),
    ("global", "global / глобальный"),
    ("golden", "oltin rang / золотой"),
    ("historic", "tarixiy ahamiyatli / исторический"),
    ("incredible", "aql bovar qilmas / невероятный"),
    ("independent", "mustaqil / независимый"),
    ("indoor", "yopiq joydagi / закрытый, в помещении"),
    ("outdoor", "ochiq havodagi / на открытом воздухе"),
    ("international", "xalqaro / международный"),
    ("limited", "cheklangan / ограниченный"),
    ("lively", "jonli, shov-shuvli / оживлённый"),
    ("loud", "baland ovozli / громкий"),
    ("luxury", "hashamatli / роскошный"),
    ("medium", "o'rtacha / средний"),
    ("natural", "tabiiy / природный"),
]

PEOPLE = [
    ("bride", "kelin / невеста"),
    ("groom", "kuyov / жених"),
    ("boyfriend", "yigit / парень"),
    ("girlfriend", "qiz / девушка"),
    ("granddaughter", "nevara qiz / внучка"),
    ("grandson", "nevara o'g'il / внук"),
    ("grandparent", "buvi yoki bobo / дедушка или бабушка"),
    ("housewife", "uy bekasi / домохозяйка"),
    ("kid", "bola / ребёнок"),
    ("mate", "do'st / приятель"),
    ("member", "a'zo / член"),
    ("neighbour", "qo'shni / сосед"),
    ("owner", "egasi / владелец"),
    ("partner", "sherik / партнёр"),
    ("stranger", "notanish odam / незнакомец"),
    ("teenager", "o'smir / подросток"),
    ("adult", "katta yoshli / взрослый"),
    ("childhood", "bolalik / детство"),
    ("couple", "juftlik / пара"),
    ("marriage", "nikoh / брак"),
    ("friendship", "do'stlik / дружба"),
    ("relationship", "munosabat / отношения"),
    ("immigration", "immigratsiya / иммиграция"),
    ("nationality", "millat, fuqarolik / национальность"),
    ("identification", "shaxsni tasdiqlovchi hujjat / удостоверение личности"),
]

NOUNS1 = [
    ("advantage", "afzallik / преимущество"),
    ("disadvantage", "kamchilik / недостаток"),
    ("ambition", "orzu-maqsad / амбиция"),
    ("apology", "uzr / извинение"),
    ("appearance", "tashqi ko'rinish / внешность"),
    ("arrangement", "kelishuv, tartib / договорённость"),
    ("attention", "e'tibor / внимание"),
    ("attitude", "munosabat, qarash / отношение"),
    ("background", "kelib chiqish, orqa fon / происхождение, фон"),
    ("benefit", "foyda / польза"),
    ("choice", "tanlov / выбор"),
    ("comfort", "qulaylik / комфорт"),
    ("conclusion", "xulosa / вывод"),
    ("condition", "holat, shart / состояние, условие"),
    ("connection", "aloqa / связь"),
    ("courage", "jasorat / мужество"),
    ("culture", "madaniyat / культура"),
    ("custom", "urf-odat / обычай"),
    ("demand", "talab / спрос"),
    ("description", "tavsif / описание"),
    ("development", "rivojlanish / развитие"),
    ("difficulty", "qiyinchilik / трудность"),
    ("effect", "ta'sir / эффект"),
    ("effort", "harakat, urinish / усилие"),
    ("importance", "ahamiyat / важность"),
]

NOUNS2 = [
    ("imagination", "tasavvur / воображение"),
    ("improvement", "yaxshilanish / улучшение"),
    ("increase", "o'sish / увеличение"),
    ("industry", "sanoat / промышленность"),
    ("instance", "misol, holat / пример, случай"),
    ("issue", "masala / вопрос, проблема"),
    ("knowledge", "bilim / знание"),
    ("lack", "yetishmovchilik / нехватка"),
    ("level", "daraja / уровень"),
    ("location", "joylashuv / расположение"),
    ("material", "material / материал"),
    ("meaning", "ma'no / значение"),
    ("memory", "xotira / память"),
    ("method", "usul / метод"),
    ("mystery", "sir / загадка"),
    ("nature", "tabiat / природа"),
    ("occupation", "kasb / род занятий"),
    ("opportunity", "imkoniyat / возможность"),
    ("organisation", "tashkilot / организация"),
    ("pressure", "bosim / давление"),
    ("purpose", "maqsad / цель"),
    ("quality", "sifat / качество"),
    ("quantity", "miqdor / количество"),
    ("reason", "sabab / причина"),
    ("responsibility", "mas'uliyat / ответственность"),
]

LISTS = [
    ("B1 exam words 14 · Common verbs 2", "exam", 14, VERBS2),
    ("B1 exam words 15 · Travel and transport", "exam", 15, TRAVEL),
    ("B1 exam words 16 · Town and buildings", "exam", 16, TOWN),
    ("B1 exam words 17 · Films, music and books", "exam", 17, MEDIA),
    ("B1 exam words 18 · Sport", "exam", 18, SPORT),
    ("B1 exam words 19 · Clothes", "exam", 19, CLOTHES),
    ("B1 exam words 20 · Technology", "exam", 20, TECH),
    ("B1 exam words 21 · Time", "exam", 21, TIME),
    ("B1 exam words 22 · Linking words", "exam", 22, LINKING),
    ("B1 exam words 23 · More describing words", "exam", 23, DESCRIBE2),
    ("B1 exam words 24 · People and relationships", "exam", 24, PEOPLE),
    ("B1 exam words 25 · Common nouns 1", "exam", 25, NOUNS1),
    ("B1 exam words 26 · Common nouns 2", "exam", 26, NOUNS2),
]
