"""B1 Preliminary exam words, steps 39-50. The last of them."""

LEVEL = "Pre-Intermediate"
BOOK = "B1 Preliminary exam words"
PAST_FROM = 1

PHRASALS1 = [
    ("break down", "buzilib qolmoq / ломаться"),
    ("bring up", "tarbiyalamoq / воспитывать"),
    ("call off", "bekor qilmoq / отменять"),
    ("carry on", "davom ettirmoq / продолжать"),
    ("check in", "ro'yxatdan o'tmoq / регистрироваться"),
    ("come across", "duch kelmoq / натыкаться"),
    ("cut down on", "kamaytirmoq / сокращать"),
    ("deal with", "hal qilmoq / иметь дело с"),
    ("fill in", "to'ldirmoq / заполнять"),
    ("find out", "aniqlamoq / выяснять"),
    ("get along", "chiqishib ketmoq / ладить"),
    ("give up", "tashlab qo'ymoq / бросать"),
    ("go off", "buzilmoq, portlamoq / портиться, срабатывать"),
    ("grow up", "katta bo'lmoq / взрослеть"),
    ("hand in", "topshirmoq / сдавать"),
    ("hang up", "telefonni qo'ymoq / вешать трубку"),
    ("hold on", "kutib turmoq / подождать"),
    ("join in", "qo'shilmoq / присоединяться"),
    ("keep on", "davom etaverish / продолжать делать"),
    ("look up", "qidirib topmoq / искать в источнике"),
    ("make up", "o'ylab topmoq / выдумывать"),
    ("pick up", "olib ketmoq / забирать"),
    ("put off", "kechiktirmoq / откладывать"),
    ("run out", "tugamoq / заканчиваться"),
    ("set off", "yo'lga tushmoq / отправляться"),
]

PHRASALS2 = [
    ("show up", "kelib qolmoq / появляться"),
    ("sort out", "yo'lga qo'ymoq / улаживать"),
    ("stay up", "kech yotmoq / не ложиться спать"),
    ("switch off", "o'chirmoq / выключать"),
    ("take off", "uchmoq, yechmoq / взлетать, снимать"),
    ("take part", "ishtirok etmoq / участвовать"),
    ("take up", "boshlamoq / браться за"),
    ("throw away", "tashlab yubormoq / выбрасывать"),
    ("try on", "kiyib ko'rmoq / примерять"),
    ("turn down", "rad etmoq, pasaytirmoq / отклонять, убавлять"),
    ("turn up", "kelib qolmoq, kuchaytirmoq / появляться, прибавлять"),
    ("wake up", "uyg'onmoq / просыпаться"),
    ("warm up", "isitmoq, qizishmoq / разогревать"),
    ("work out", "hisoblab chiqmoq / вычислять"),
    ("write down", "yozib olmoq / записывать"),
    ("put on", "kiymoq / надевать"),
    ("get over", "tuzalib ketmoq / оправляться"),
    ("look forward to", "intiq bo'lmoq / с нетерпением ждать"),
    ("get rid of", "qutulmoq / избавляться"),
    ("go on", "davom etmoq / продолжаться"),
    ("come back", "qaytmoq / возвращаться"),
    ("go out", "sayr qilgani chiqmoq / выходить в свет"),
    ("get back", "qaytib olmoq / получать обратно"),
    ("look after", "parvarish qilmoq / ухаживать"),
    ("run into", "tasodifan uchratmoq / случайно встретить"),
]

OPINION = [
    ("agree", "rozi bo'lmoq / соглашаться"),
    ("disagree", "rozi bo'lmaslik / не соглашаться"),
    ("argument", "dalil, bahs / аргумент, спор"),
    ("belief", "e'tiqod / убеждение"),
    ("comment", "izoh / комментарий"),
    ("consider", "hisoblamoq / считать"),
    ("debate", "munozara / дебаты"),
    ("discussion", "muhokama / обсуждение"),
    ("doubt", "shubhalanmoq / сомневаться"),
    ("expect", "kutmoq, deb hisoblamoq / полагать"),
    ("explain", "izohlamoq / объяснять"),
    ("mention", "eslatib o'tmoq / упоминать"),
    ("opinion", "fikr / мнение"),
    ("persuade", "ko'ndirmoq / убеждать"),
    ("point of view", "nuqtai nazar / точка зрения"),
    ("prefer", "afzal bilmoq / предпочитать"),
    ("reason", "asos / основание"),
    ("statement", "bayonot / утверждение"),
    ("suppose", "taxmin qilmoq / предполагать"),
    ("suggestion", "taklif / предложение"),
    ("viewpoint", "qarash / взгляд"),
    ("admit", "e'tirof etmoq / признавать"),
    ("deny", "inkor qilmoq / отрицать"),
    ("claim", "da'vo qilmoq / заявлять"),
    ("convince", "ishontirmoq / убеждать"),
]

PROBLEMS = [
    ("accident", "baxtsiz hodisa / авария"),
    ("breakdown", "buzilish / поломка"),
    ("crash", "to'qnashuv / столкновение"),
    ("damage", "zarar / ущерб"),
    ("danger", "xavf / опасность"),
    ("delay", "kechikish / задержка"),
    ("difficulty", "qiyinchilik / затруднение"),
    ("disaster", "falokat / катастрофа"),
    ("emergency", "favqulodda vaziyat / чрезвычайная ситуация"),
    ("fault", "ayb, nuqson / вина, неисправность"),
    ("injury", "jarohat / травма"),
    ("mistake", "xato / ошибка"),
    ("problem", "muammo / проблема"),
    ("repair", "ta'mir / ремонт"),
    ("risk", "tavakkal / риск"),
    ("trouble", "tashvish / неприятность"),
    ("warning", "ogohlantirish / предупреждение"),
    ("solution", "yechim / решение"),
    ("advice", "maslahat / совет"),
    ("help", "yordam / помощь"),
    ("rescue", "qutqaruv / спасение"),
    ("safety", "xavfsizlik / безопасность"),
    ("careless", "beparvo / небрежный"),
    ("lost", "yo'qolgan / потерянный"),
    ("broken down", "ishdan chiqqan / сломавшийся"),
]

COMMUNICATE = [
    ("accent", "talaffuz ohangi / акцент"),
    ("announcement", "e'lon / объявление"),
    ("answerphone", "avtojavob beruvchi / автоответчик"),
    ("communication", "muloqot / общение"),
    ("conversation", "suhbat / разговор"),
    ("enquiry", "so'rov / запрос"),
    ("expression", "ibora / выражение"),
    ("gossip", "g'iybat / сплетни"),
    ("greeting", "salomlashish / приветствие"),
    ("handwriting", "qo'l yozuvi / почерк"),
    ("language", "til / язык"),
    ("letter", "xat, harf / письмо, буква"),
    ("mail", "pochta / почта"),
    ("message", "xabar / сообщение"),
    ("note", "eslatma / записка"),
    ("notice", "e'lon / уведомление"),
    ("phrase", "ibora / фраза"),
    ("postcard", "otkritka / открытка"),
    ("reply", "javob / ответ"),
    ("signature", "imzo / подпись"),
    ("spelling", "imlo / правописание"),
    ("translation", "tarjima / перевод"),
    ("voice", "ovoz / голос"),
    ("word processor", "matn muharriri / текстовый редактор"),
    ("chat", "suhbat / чат"),
]

MORE_ADJ = [
    ("active", "faol / активный"),
    ("annoyed", "g'ashi kelgan / раздражённый"),
    ("aware", "xabardor / осведомлённый"),
    ("brilliant", "ajoyib / блестящий"),
    ("calm", "tinch / спокойный"),
    ("complicated", "murakkab / сложный"),
    ("creative", "ijodiy / творческий"),
    ("crowded", "gavjum / многолюдный"),
    ("delicious", "mazali / вкусный"),
    ("energetic", "g'ayratli / энергичный"),
    ("fantastic", "zo'r / фантастический"),
    ("formal", "rasmiy / формальный"),
    ("informal", "norasmiy / неформальный"),
    ("generous", "saxovatli / щедрый"),
    ("helpful", "foydali, yordamchi / полезный"),
    ("honest", "halol / честный"),
    ("impressive", "ta'sirli / впечатляющий"),
    ("modern", "zamonaviy / современный"),
    ("nervous", "asabiy / нервный"),
    ("patient", "sabrli / терпеливый"),
    ("perfect", "mukammal / совершенный"),
    ("quiet", "sokin / тихий"),
    ("special", "maxsus / особенный"),
    ("typical", "odatiy / типичный"),
    ("useful", "asqotadigan / полезный"),
]

FOOD2 = [
    ("bake", "duxovkada pishirmoq / печь"),
    ("barbecue", "shashlik, mangal / барбекю"),
    ("beef", "mol go'shti / говядина"),
    ("biscuit", "pechene / печенье"),
    ("chef", "oshpaz / шеф-повар"),
    ("chips", "kartoshka fri / картофель фри"),
    ("chopsticks", "tayoqcha / палочки для еды"),
    ("cream", "qaymoq / сливки"),
    ("dessert", "shirinlik / десерт"),
    ("diet", "parhez / диета"),
    ("dish", "taom / блюдо"),
    ("fork", "sanchqi / вилка"),
    ("fresh", "yangi / свежий"),
    ("frozen", "muzlatilgan / замороженный"),
    ("ingredient", "masalliq / ингредиент"),
    ("kettle", "choynak / чайник"),
    ("meal", "ovqat / приём пищи"),
    ("menu", "menyu / меню"),
    ("mixture", "aralashma / смесь"),
    ("pan", "tova / сковорода"),
    ("recipe", "retsept / рецепт"),
    ("sauce", "sous / соус"),
    ("taste", "ta'mini bilmoq / пробовать"),
    ("vegetarian", "go'sht yemaydigan / вегетарианец"),
    ("waiter", "ofitsiant / официант"),
]

HEALTHY = [
    ("appointment", "shifokorga yozilish / запись к врачу"),
    ("chemist's", "dorixona / аптека"),
    ("cough", "yo'talmoq / кашлять"),
    ("dentist", "tish shifokori / стоматолог"),
    ("emergency room", "shoshilinch yordam bo'limi / приёмный покой"),
    ("exercise", "mashq / упражнение"),
    ("fever", "isitma / жар"),
    ("headache", "bosh og'rig'i / головная боль"),
    ("healthy", "sog'lom / здоровый"),
    ("hospital", "kasalxona / больница"),
    ("injection", "ukol / укол"),
    ("medicine", "dori / лекарство"),
    ("nurse", "hamshira / медсестра"),
    ("operation", "operatsiya / операция"),
    ("patient", "bemor / пациент"),
    ("pill", "dori tabletkasi / таблетка"),
    ("sore throat", "tomoq og'rig'i / боль в горле"),
    ("stomach ache", "qorin og'rig'i / боль в животе"),
    ("temperature", "tana harorati / температура"),
    ("toothache", "tish og'rig'i / зубная боль"),
    ("unhealthy", "sog'liqqa zararli / вредный для здоровья"),
    ("vitamin", "vitamin / витамин"),
    ("wound", "yara / рана"),
    ("x-ray", "rentgen / рентген"),
    ("check-up", "tibbiy ko'rik / медосмотр"),
]

NUMBERS = [
    ("billion", "milliard / миллиард"),
    ("couple", "ikkita, juft / пара"),
    ("decade", "o'n yillik / десятилетие"),
    ("digit", "raqam / цифра"),
    ("equal", "teng bo'lmoq / равняться"),
    ("figure", "raqam, son / цифра"),
    ("half", "yarim / половина"),
    ("least", "eng kam / наименьший"),
    ("minus", "minus / минус"),
    ("most", "eng ko'p / наибольший"),
    ("multiply", "ko'paytirmoq / умножать"),
    ("once", "bir marta / однажды"),
    ("pair", "juft / пара"),
    ("per cent", "foiz / процент"),
    ("plus", "qo'shuv / плюс"),
    ("quantity", "miqdor / количество"),
    ("single", "yakka / одиночный"),
    ("sum", "yig'indi / сумма"),
    ("thousand", "ming / тысяча"),
    ("thrice", "uch marta / трижды"),
    ("twice", "ikki marta / дважды"),
    ("zero", "nol / ноль"),
    ("count", "sanoq / счёт"),
    ("number", "son / число"),
    ("order", "tartib / порядок"),
]

SCHOOL2 = [
    ("absent", "yo'q, kelmagan / отсутствующий"),
    ("present", "hozir bo'lgan / присутствующий"),
    ("assignment", "topshiriq / задание"),
    ("break", "tanaffus / перемена"),
    ("classmate", "sinfdosh / одноклассник"),
    ("coursebook", "darslik / учебник"),
    ("desk", "parta / парта"),
    ("essay", "insho / эссе"),
    ("exam", "imtihon / экзамен"),
    ("fail", "yiqilmoq / провалить"),
    ("headmaster", "maktab direktori / директор школы"),
    ("homework", "uy vazifasi / домашняя работа"),
    ("mark", "baho / оценка"),
    ("notebook", "daftar / тетрадь"),
    ("pass", "o'tmoq / сдать"),
    ("pencil case", "ruchka qutisi / пенал"),
    ("primary school", "boshlang'ich maktab / начальная школа"),
    ("pupil", "o'quvchi / ученик"),
    ("result", "natija / результат"),
    ("subject", "fan / предмет"),
    ("teacher", "o'qituvchi / учитель"),
    ("term", "chorak / четверть"),
    ("test", "sinov / тест"),
    ("timetable", "jadval / расписание"),
    ("uniform", "maktab formasi / школьная форма"),
]

SMALL_WORDS = [
    ("anybody", "kimdir, hech kim / кто-нибудь"),
    ("anywhere", "biror joyda / где-либо"),
    ("everybody", "hamma / все"),
    ("everywhere", "hamma yerda / везде"),
    ("nobody", "hech kim / никто"),
    ("nothing", "hech narsa / ничего"),
    ("nowhere", "hech qayerda / нигде"),
    ("somebody", "kimdir / кто-то"),
    ("something", "nimadir / что-то"),
    ("somewhere", "qaerdadir / где-то"),
    ("each other", "bir-birini / друг друга"),
    ("herself", "o'zini (ayol) / себя (она)"),
    ("himself", "o'zini (erkak) / себя (он)"),
    ("myself", "o'zimni / себя (я)"),
    ("ourselves", "o'zimizni / себя (мы)"),
    ("itself", "o'zini (narsa) / себя (оно)"),
    ("themselves", "o'zlarini / себя (они)"),
    ("yourself", "o'zingizni / себя (вы)"),
    ("hers", "uniki (ayol) / её"),
    ("ours", "bizniki / наш"),
    ("theirs", "ularniki / их"),
    ("whose", "kimning / чей"),
    ("none", "hech biri / ни один"),
    ("either", "ikkisidan biri / любой из двух"),
    ("neither", "ikkisi ham emas / ни тот ни другой"),
]

OBJECTS = [
    ("bucket", "chelak / ведро"),
    ("chain", "zanjir / цепь"),
    ("clip", "qisqich / зажим"),
    ("cloth", "latta, mato / тряпка, ткань"),
    ("comb", "taroq / расчёска"),
    ("envelope", "konvert / конверт"),
    ("frame", "ramka / рамка"),
    ("glue", "yelim / клей"),
    ("hairdryer", "fen / фен"),
    ("hammer", "bolg'a / молоток"),
    ("handle", "dastak / ручка"),
    ("helmet", "dubulg'a / шлем"),
    ("ladder", "narvon / лестница-стремянка"),
    ("lighter", "chaqmoqtosh / зажигалка"),
    ("needle", "igna / игла"),
    ("rope", "arqon / верёвка"),
    ("scissors", "qaychi / ножницы"),
    ("string", "ip / бечёвка"),
    ("tape", "lenta / лента"),
    ("torch", "fonar / фонарик"),
    ("tray", "patnis / поднос"),
    ("umbrella", "soyabon / зонт"),
    ("wallet", "hamyon / бумажник"),
    ("whistle", "hushtak / свисток"),
    ("battery", "batareya / батарейка"),
]

LISTS = [
    ("B1 exam words 39 · Phrasal verbs 1", "exam", 39, PHRASALS1),
    ("B1 exam words 40 · Phrasal verbs 2", "exam", 40, PHRASALS2),
    ("B1 exam words 41 · Opinions and discussion", "exam", 41, OPINION),
    ("B1 exam words 42 · Problems and accidents", "exam", 42, PROBLEMS),
    ("B1 exam words 43 · Language and messages", "exam", 43, COMMUNICATE),
    ("B1 exam words 44 · Still more describing words", "exam", 44, MORE_ADJ),
    ("B1 exam words 45 · Food and restaurants", "exam", 45, FOOD2),
    ("B1 exam words 46 · Doctors and health", "exam", 46, HEALTHY),
    ("B1 exam words 47 · Numbers", "exam", 47, NUMBERS),
    ("B1 exam words 48 · School", "exam", 48, SCHOOL2),
    ("B1 exam words 49 · Small but important words", "exam", 49, SMALL_WORDS),
    ("B1 exam words 50 · Everyday objects", "exam", 50, OBJECTS),
]
