"""B1 Preliminary exam words the Pre-Intermediate book never teaches, 1-13.

Meanings in Uzbek and Russian, as with the A2 ladder.
"""

LEVEL = "Pre-Intermediate"
BOOK = "B1 Preliminary exam words"
PAST_FROM = 1

CHARACTER = [
    ("bossy", "buyruq berishni yaxshi ko'radigan / любящий командовать"),
    ("charming", "maftunkor / обаятельный"),
    ("cruel", "shafqatsiz / жестокий"),
    ("easygoing", "yuvosh, bemalol / лёгкий в общении"),
    ("gentle", "mayin, muloyim / мягкий"),
    ("jealous", "rashkchi / ревнивый"),
    ("keen", "ishtiyoqli / увлечённый"),
    ("lonely", "yolg'iz / одинокий"),
    ("miserable", "baxtsiz, g'amgin / несчастный"),
    ("nasty", "yoqimsiz, yomon / неприятный"),
    ("polite", "odobli / вежливый"),
    ("rude", "qo'pol / грубый"),
    ("selfish", "xudbin / эгоистичный"),
    ("sensible", "aqli raso / благоразумный"),
    ("sensitive", "ta'sirchan / чувствительный"),
    ("shy", "uyatchan / застенчивый"),
    ("strict", "qattiqqo'l / строгий"),
    ("stubborn", "qaysar / упрямый"),
    ("talkative", "gapdon / разговорчивый"),
    ("reliable", "ishonchli / надёжный"),
    ("ambitious", "intiluvchan / амбициозный"),
    ("cheerful", "xushchaqchaq / жизнерадостный"),
    ("confident", "o'ziga ishongan / уверенный"),
    ("curious", "qiziquvchan / любопытный"),
    ("loyal", "sodiq / преданный"),
]

BODY = [
    ("ankle", "to'piq / лодыжка"),
    ("bald", "kal / лысый"),
    ("beard", "soqol / борода"),
    ("cheek", "yonoq / щека"),
    ("chin", "iyak / подбородок"),
    ("curly", "jingalak / кудрявый"),
    ("straight hair", "tekis soch / прямые волосы"),
    ("handsome", "kelishgan / красивый (о мужчине)"),
    ("heel", "tovon / пятка"),
    ("lip", "lab / губа"),
    ("moustache", "mo'ylov / усы"),
    ("haircut", "soch turmagi / стрижка"),
    ("skin", "teri / кожа"),
    ("shoulder", "yelka / плечо"),
    ("knee", "tizza / колено"),
    ("elbow", "tirsak / локоть"),
    ("wrist", "bilak / запястье"),
    ("thumb", "bosh barmoq / большой палец"),
    ("toe", "oyoq barmog'i / палец ноги"),
    ("forehead", "peshona / лоб"),
    ("eyebrow", "qosh / бровь"),
    ("slim", "nozik, ozg'in / стройный"),
    ("overweight", "vazni ortiqcha / полный"),
    ("tall", "novcha / высокий"),
    ("medium height", "o'rta bo'yli / среднего роста"),
]

ILLNESS = [
    ("aspirin", "aspirin / аспирин"),
    ("bandage", "bint / бинт"),
    ("bleed", "qon oqmoq / кровоточить"),
    ("blind", "ko'r / слепой"),
    ("clinic", "poliklinika / клиника"),
    ("cure", "davolamoq / излечивать"),
    ("deaf", "kar / глухой"),
    ("disabled", "nogiron / с инвалидностью"),
    ("disease", "kasallik / болезнь"),
    ("flu", "gripp / грипп"),
    ("illness", "xastalik / болезнь"),
    ("injure", "jarohatlamoq / ранить"),
    ("painful", "og'riqli / болезненный"),
    ("prescription", "retsept / рецепт врача"),
    ("surgery", "qabulxona, operatsiya / приём врача, операция"),
    ("treatment", "davolash / лечение"),
    ("wound", "yara / рана"),
    ("swollen", "shishgan / опухший"),
    ("dizzy", "boshi aylanayotgan / с головокружением"),
    ("breathe", "nafas olmoq / дышать"),
    ("breath", "nafas / дыхание"),
    ("recover", "tuzalmoq / выздоравливать"),
    ("operation", "jarrohlik amaliyoti / операция"),
    ("ambulance", "tez yordam / скорая"),
    ("pharmacy", "dorixona / аптека"),
]

FEELINGS = [
    ("anxious", "tashvishli / тревожный"),
    ("ashamed", "uyalgan / пристыженный"),
    ("delighted", "juda xursand / восхищённый"),
    ("depressed", "tushkun / подавленный"),
    ("disappointment", "hafsala pir bo'lishi / разочарование"),
    ("doubt", "shubha / сомнение"),
    ("excitement", "hayajon / волнение"),
    ("fear", "qo'rquv / страх"),
    ("glad", "mamnun / рад"),
    ("hopeful", "umidvor / полный надежды"),
    ("hopeless", "umidsiz / безнадёжный"),
    ("jealousy", "rashk / ревность"),
    ("mood", "kayfiyat / настроение"),
    ("proud", "faxrlanuvchi / гордый"),
    ("relief", "yengillik / облегчение"),
    ("satisfied", "qoniqqan / довольный"),
    ("scared", "qo'rqqan / напуганный"),
    ("stressed", "asabiy zo'riqishda / в стрессе"),
    ("upset", "xafa / расстроенный"),
    ("grateful", "minnatdor / благодарный"),
    ("guilty", "aybdor / виноватый"),
    ("amused", "kulgisi kelgan / развеселённый"),
    ("bored stiff", "juda zerikkan / смертельно скучающий"),
    ("furious", "g'azablangan / в ярости"),
    ("calm", "xotirjam / спокойный"),
]

CRIME = [
    ("arrest", "hibsga olmoq / арестовывать"),
    ("blame", "aybdor deb bilmoq / винить"),
    ("crime", "jinoyat / преступление"),
    ("criminal", "jinoyatchi / преступник"),
    ("detective", "tergovchi / детектив"),
    ("forbidden", "taqiqlangan / запрещённый"),
    ("guard", "qo'riqchi / охранник"),
    ("jail", "qamoqxona / тюрьма"),
    ("judge", "sudya / судья"),
    ("law", "qonun / закон"),
    ("licence", "ruxsatnoma / лицензия"),
    ("prison", "qamoqda saqlash muassasasi / исправительное учреждение"),
    ("punish", "jazolamoq / наказывать"),
    ("steal", "o'g'irlamoq / красть"),
    ("thief", "o'g'ri / вор"),
    ("victim", "jabrlanuvchi / жертва"),
    ("witness", "guvoh / свидетель"),
    ("fine", "jarima / штраф"),
    ("illegal", "noqonuniy / незаконный"),
    ("legal", "qonuniy / законный"),
    ("rob", "talamoq / грабить"),
    ("suspect", "gumondor / подозреваемый"),
    ("court", "sud / суд"),
    ("evidence", "dalil / улика"),
    ("safety", "xavfsizlik / безопасность"),
]

ANIMALS = [
    ("ant", "chumoli / муравей"),
    ("bull", "buqa / бык"),
    ("bush", "buta / куст"),
    ("cattle", "qoramol / скот"),
    ("cliff", "qoya / утёс"),
    ("frog", "qurbaqa / лягушка"),
    ("giraffe", "jirafa / жираф"),
    ("horse", "ot / лошадь"),
    ("jungle", "jungli / джунгли"),
    ("kangaroo", "kenguru / кенгуру"),
    ("kitten", "mushukcha / котёнок"),
    ("nest", "uya / гнездо"),
    ("snake", "ilon / змея"),
    ("spider", "o'rgimchak / паук"),
    ("wildlife", "yovvoyi tabiat / дикая природа"),
    ("creature", "jonzot / существо"),
    ("feather", "pat / перо"),
    ("fur", "jun, mo'yna / мех"),
    ("paw", "panja / лапа"),
    ("tail", "dum / хвост"),
    ("wing", "qanot / крыло"),
    ("hunt", "ov qilmoq / охотиться"),
    ("farmland", "ekin yerlari / сельхозугодья"),
    ("crop", "hosil / урожай"),
    ("soil", "tuproq / почва"),
]

WEATHER = [
    ("breeze", "yengil shamol / лёгкий ветерок"),
    ("foggy", "tumanli / туманный"),
    ("freeze", "muzlamoq / замерзать"),
    ("gale", "kuchli shamol / шторм"),
    ("humid", "nam / влажный"),
    ("icy", "muzli / ледяной"),
    ("lightning", "chaqmoq / молния"),
    ("mild", "yumshoq (ob-havo) / мягкий"),
    ("thunder", "momaqaldiroq / гром"),
    ("shower", "qisqa yomg'ir / кратковременный дождь"),
    ("forecast", "prognoz / прогноз"),
    ("climate", "iqlim / климат"),
    ("flood", "suv toshqini / наводнение"),
    ("drought", "qurg'oqchilik / засуха"),
    ("earthquake", "zilzila / землетрясение"),
    ("storm", "bo'ron / шторм"),
    ("melt", "erimoq / таять"),
    ("pour", "quyib yog'moq / лить"),
    ("boiling", "juda issiq / очень жаркий"),
    ("freezing", "juda sovuq / очень холодный"),
    ("temperature", "harorat / температура"),
    ("degree", "daraja / градус"),
    ("sunrise", "quyosh chiqishi / восход"),
    ("sunset", "quyosh botishi / закат"),
    ("seasonal", "mavsumiy / сезонный"),
]

HOUSEHOLD = [
    ("bucket", "chelak / ведро"),
    ("bulb", "lampochka / лампочка"),
    ("cabinet", "javon / шкафчик"),
    ("cottage", "qishloq uyi / коттедж"),
    ("dishwasher", "idish yuvish mashinasi / посудомойка"),
    ("dustbin", "axlat qutisi / мусорный бак"),
    ("duvet", "ko'rpa / одеяло"),
    ("freezer", "muzlatkich / морозилка"),
    ("heater", "isitgich / обогреватель"),
    ("ironing", "dazmollash / глажка"),
    ("laundry", "kir yuvish / стирка"),
    ("locker", "shkafcha / шкафчик"),
    ("mattress", "matras / матрас"),
    ("sheet", "choyshab / простыня"),
    ("tap", "jo'mrak / кран"),
    ("vacuum cleaner", "changyutgich / пылесос"),
    ("housework", "uy yumushlari / домашние дела"),
    ("tidy up", "yig'ishtirmoq / прибираться"),
    ("mess", "tartibsizlik / беспорядок"),
    ("dust", "chang / пыль"),
    ("shelf", "tokcha / полка"),
    ("cupboard", "shkaf / шкаф"),
    ("stairs", "zinapoya / лестница"),
    ("rent", "ijara / аренда"),
    ("landlord", "uy egasi / арендодатель"),
]

FOOD = [
    ("boiled", "qaynatilgan / варёный"),
    ("broccoli", "brokkoli / брокколи"),
    ("butcher", "qassob / мясник"),
    ("canteen", "oshxona / столовая"),
    ("corn", "makkajo'xori / кукуруза"),
    ("curry", "karri / карри"),
    ("flavour", "ta'm / вкус"),
    ("fried", "qovurilgan / жареный"),
    ("grilled", "panjarada pishirilgan / приготовленный на гриле"),
    ("herb", "ko'kat, ziravor / трава, зелень"),
    ("jar", "banka / банка"),
    ("jug", "ko'za / кувшин"),
    ("lemonade", "limonad / лимонад"),
    ("lettuce", "salat bargi / салат-латук"),
    ("mango", "mango / манго"),
    ("mug", "katta piyola / кружка"),
    ("omelette", "omlet / омлет"),
    ("packet", "paket / пачка"),
    ("pepper", "qalampir / перец"),
    ("raw", "xom / сырой"),
    ("roast", "qovurilgan go'sht / жаркое"),
    ("slice", "bo'lak / ломтик"),
    ("snack", "gazak / перекус"),
    ("spice", "ziravor / специя"),
    ("tin", "konserva bankasi / консервная банка"),
]

MONEY = [
    ("account", "hisob raqami / счёт"),
    ("agency", "agentlik / агентство"),
    ("candidate", "nomzod / кандидат"),
    ("deposit", "oldindan to'lov / залог"),
    ("department", "bo'lim / отдел"),
    ("employment", "ish bilan bandlik / занятость"),
    ("fee", "to'lov / сбор"),
    ("financial", "moliyaviy / финансовый"),
    ("firm", "firma / фирма"),
    ("grant", "grant / грант"),
    ("loan", "qarz, kredit / заём"),
    ("income", "daromad / доход"),
    ("expenses", "xarajatlar / расходы"),
    ("profit", "foyda / прибыль"),
    ("tax", "soliq / налог"),
    ("budget", "byudjet / бюджет"),
    ("cashpoint", "bankomat / банкомат"),
    ("banking", "bank ishi / банковское дело"),
    ("invest", "sarmoya kiritmoq / инвестировать"),
    ("owe", "qarzdor bo'lmoq / быть должным"),
    ("bill", "hisob / счёт"),
    ("charge", "haq olmoq / взимать плату"),
    ("wealthy", "boy / состоятельный"),
    ("afford", "qurbi yetmoq / позволить себе"),
    ("bargain", "arzon xarid / выгодная покупка"),
]

STUDY = [
    ("alphabet", "alifbo / алфавит"),
    ("consonant", "undosh tovush / согласный"),
    ("vowel", "unli tovush / гласный"),
    ("curriculum", "o'quv dasturi / учебная программа"),
    ("diagram", "diagramma / диаграмма"),
    ("economics", "iqtisodiyot / экономика"),
    ("examiner", "imtihon oluvchi / экзаменатор"),
    ("grade", "baho, daraja / оценка"),
    ("grammar", "grammatika / грамматика"),
    ("knowledge", "bilim / знание"),
    ("lecture", "ma'ruza / лекция"),
    ("lecturer", "o'qituvchi, ma'ruzachi / преподаватель"),
    ("librarian", "kutubxonachi / библиотекарь"),
    ("mathematics", "matematika / математика"),
    ("composition", "insho / сочинение"),
    ("explanation", "tushuntirish / объяснение"),
    ("revision", "takrorlash / повторение"),
    ("intermediate", "o'rta daraja / средний уровень"),
    ("elementary", "boshlang'ich / начальный"),
    ("certificate", "sertifikat / сертификат"),
    ("degree", "diplom darajasi / степень"),
    ("correction", "tuzatish / исправление"),
    ("incorrect", "noto'g'ri / неверный"),
    ("identify", "aniqlamoq / определять"),
    ("include", "o'z ichiga olmoq / включать"),
]

DESCRIBING = [
    ("accurate", "aniq / точный"),
    ("basic", "asosiy, oddiy / базовый"),
    ("brief", "qisqa / краткий"),
    ("bright", "yorqin / яркий"),
    ("broad", "keng / широкий"),
    ("casual", "erkin, norasmiy / повседневный"),
    ("colourful", "rang-barang / яркий, цветной"),
    ("cosy", "shinam / уютный"),
    ("cute", "yoqimtoy / милый"),
    ("dull", "zerikarli, xira / тусклый, скучный"),
    ("efficient", "samarali / эффективный"),
    ("equal", "teng / равный"),
    ("exact", "to'liq mos, xuddi shu / в точности такой же"),
    ("extraordinary", "g'ayrioddiy / необыкновенный"),
    ("fashionable", "modaga mos / модный"),
    ("gorgeous", "juda chiroyli / великолепный"),
    ("magnificent", "muhtasham / величественный"),
    ("narrow", "tor / узкий"),
    ("neat", "ozoda / опрятный"),
    ("obvious", "ravshan / очевидный"),
    ("ordinary", "oddiy / обычный"),
    ("rough", "qo'pol, notekis / грубый, неровный"),
    ("smooth", "silliq / гладкий"),
    ("tight", "tor, qattiq / тесный"),
    ("loose", "keng, bo'sh / свободный"),
]

VERBS1 = [
    ("achieve", "erishmoq / достигать"),
    ("admire", "qoyil qolmoq / восхищаться"),
    ("advise", "maslahat bermoq / советовать"),
    ("affect", "ta'sir qilmoq / влиять"),
    ("annoy", "bezovta qilmoq / раздражать"),
    ("approach", "yaqinlashmoq / приближаться"),
    ("approve", "ma'qullamoq / одобрять"),
    ("attempt", "urinmoq / пытаться"),
    ("attract", "jalb qilmoq / привлекать"),
    ("avoid", "qochmoq / избегать"),
    ("behave", "o'zini tutmoq / вести себя"),
    ("consider", "o'ylab ko'rmoq / рассматривать"),
    ("contain", "ichida saqlamoq / содержать"),
    ("convince", "ishontirmoq / убеждать"),
    ("create", "yaratmoq / создавать"),
    ("declare", "e'lon qilmoq / заявлять"),
    ("destroy", "vayron qilmoq / разрушать"),
    ("disturb", "xalaqit bermoq / беспокоить"),
    ("encourage", "dalda bermoq / поощрять"),
    ("escape", "qochib qutulmoq / сбегать"),
    ("forgive", "kechirmoq / прощать"),
    ("hide", "yashirmoq / прятать"),
    ("ignore", "e'tibor bermaslik / игнорировать"),
    ("imagine", "tasavvur qilmoq / представлять"),
    ("insist", "turib olmoq / настаивать"),
]

LISTS = [
    ("B1 exam words 1 · What people are like", "exam", 1, CHARACTER),
    ("B1 exam words 2 · The body and appearance", "exam", 2, BODY),
    ("B1 exam words 3 · Illness and treatment", "exam", 3, ILLNESS),
    ("B1 exam words 4 · Feelings", "exam", 4, FEELINGS),
    ("B1 exam words 5 · Crime and the law", "exam", 5, CRIME),
    ("B1 exam words 6 · Animals and the land", "exam", 6, ANIMALS),
    ("B1 exam words 7 · Weather", "exam", 7, WEATHER),
    ("B1 exam words 8 · Around the house", "exam", 8, HOUSEHOLD),
    ("B1 exam words 9 · Food and cooking", "exam", 9, FOOD),
    ("B1 exam words 10 · Money and work", "exam", 10, MONEY),
    ("B1 exam words 11 · Studying", "exam", 11, STUDY),
    ("B1 exam words 12 · Describing things", "exam", 12, DESCRIBING),
    ("B1 exam words 13 · Common verbs 1", "exam", 13, VERBS1),
]
