"""B2 words for the Intermediate classes - the level above B1+, steps 1-15.

Cambridge publishes vocabulary lists for A2 Key and B1 Preliminary only:
there is no official B1+ list. B1+ students are climbing towards B2, so this
ladder is built from B2 vocabulary, with anything already taught in their own
book, or already on our A2 and B1 ladders, taken out.

Meanings in Uzbek and Russian.
"""

LEVEL = "Intermediate"
BOOK = "B2 words"
PAST_FROM = 1

CHARACTER = [
    ("assertive", "o'z fikrini qat'iy bildiradigan / напористый"),
    ("cautious", "ehtiyotkor / осторожный"),
    ("considerate", "boshqalarni o'ylaydigan / внимательный к другим"),
    ("decisive", "qat'iy qaror qiladigan / решительный"),
    ("determined", "qat'iyatli / целеустремлённый"),
    ("easy-going", "beg'am / покладистый"),
    ("flexible", "moslashuvchan / гибкий"),
    ("genuine", "samimiy / искренний"),
    ("humble", "kamtar / скромный"),
    ("impulsive", "o'ylamay ish qiladigan / импульсивный"),
    ("mature", "yetuk / зрелый"),
    ("open-minded", "yangilikka ochiq / непредвзятый"),
    ("perfectionist", "har narsani mukammal qilmoqchi / перфекционист"),
    ("persistent", "qat'iy turib oladigan / настойчивый"),
    ("reserved", "o'zini tiyadigan / сдержанный"),
    ("resourceful", "topqir / находчивый"),
    ("self-confident", "o'ziga ishongan / самоуверенный"),
    ("sincere", "chin ko'ngildan / искренний"),
    ("spontaneous", "o'z-o'zidan / спонтанный"),
    ("supportive", "qo'llab-quvvatlaydigan / поддерживающий"),
    ("sympathetic", "hamdard / сочувствующий"),
    ("tolerant", "bag'rikeng / терпимый"),
    ("trustworthy", "ishonchga loyiq / заслуживающий доверия"),
    ("unpredictable", "oldindan aytib bo'lmaydigan / непредсказуемый"),
    ("witty", "hozirjavob / остроумный"),
]

WORKLIFE = [
    ("apprenticeship", "shogirdlik / стажировка"),
    ("appraisal", "ish faoliyatini baholash / оценка работы"),
    ("candidate", "nomzod / кандидат"),
    ("commute", "ishga qatnov / поездка на работу"),
    ("deadline pressure", "muddat bosimi / давление сроков"),
    ("delegate", "vazifani topshirmoq / делегировать"),
    ("expertise", "chuqur bilim / экспертиза"),
    ("incentive", "rag'bat / стимул"),
    ("internship", "amaliyot / стажировка"),
    ("negotiate", "muzokara olib bormoq / вести переговоры"),
    ("network", "aloqalar o'rnatmoq / налаживать связи"),
    ("outsource", "tashqaridan buyurtma bermoq / передавать на аутсорс"),
    ("overtime pay", "qo'shimcha ish haqi / оплата сверхурочных"),
    ("perk", "qo'shimcha imtiyoz / бонус"),
    ("productivity", "unumdorlik / продуктивность"),
    ("promotion prospects", "ko'tarilish imkoniyati / перспективы роста"),
    ("recruit", "ishga jalb qilmoq / нанимать"),
    ("redundancy", "ishdan qisqartirish / сокращение"),
    ("resign", "iste'foga chiqmoq / подавать в отставку"),
    ("shortlist", "saralangan ro'yxat / короткий список"),
    ("supervise", "nazorat qilmoq / руководить"),
    ("vacancy", "bo'sh ish o'rni / вакансия"),
    ("workforce", "ishchi kuchi / рабочая сила"),
    ("job satisfaction", "ishdan qoniqish / удовлетворённость работой"),
    ("career path", "kasbiy yo'l / карьерный путь"),
]

MONEY = [
    ("budget", "byudjet tuzmoq / планировать бюджет"),
    ("debt", "qarz / долг"),
    ("mortgage", "ipoteka / ипотека"),
    ("interest rate", "foiz stavkasi / процентная ставка"),
    ("inflation", "inflyatsiya / инфляция"),
    ("investment", "sarmoya / инвестиция"),
    ("savings account", "jamg'arma hisobi / сберегательный счёт"),
    ("income tax", "daromad solig'i / подоходный налог"),
    ("expenditure", "xarajat / расходы"),
    ("afford", "imkoni yetmoq / позволить себе"),
    ("currency", "valyuta / валюта"),
    ("transaction", "pul o'tkazmasi / транзакция"),
    ("refundable", "qaytariladigan / возвратный"),
    ("bargain", "arzon xarid / выгодная сделка"),
    ("instalment", "bo'lib to'lash / рассрочка"),
    ("bankrupt", "bankrot / банкрот"),
    ("profitable", "foydali / прибыльный"),
    ("charge a fee", "haq undirmoq / взимать комиссию"),
    ("cut costs", "xarajatni qisqartirmoq / сокращать расходы"),
    ("make a profit", "foyda ko'rmoq / получать прибыль"),
    ("go into debt", "qarzga botmoq / влезать в долги"),
    ("pay in instalments", "bo'lib to'lamoq / платить в рассрочку"),
    ("worth a fortune", "juda qimmat / стоит целое состояние"),
    ("value for money", "narxiga arziydigan / стоит своих денег"),
    ("financial support", "moliyaviy yordam / финансовая поддержка"),
]

EDUCATION = [
    ("assignment", "topshiriq / задание"),
    ("assessment", "baholash / оценивание"),
    ("bachelor's degree", "bakalavr darajasi / степень бакалавра"),
    ("master's degree", "magistr darajasi / степень магистра"),
    ("curriculum", "o'quv reja / учебный план"),
    ("dissertation", "dissertatsiya / диссертация"),
    ("distance learning", "masofaviy ta'lim / дистанционное обучение"),
    ("drop out", "o'qishni tashlamoq / бросать учёбу"),
    ("enrol", "ro'yxatdan o'tmoq / записаться"),
    ("graduate", "bitirmoq / окончить"),
    ("lecture hall", "ma'ruza zali / лекционный зал"),
    ("plagiarism", "ko'chirmakashlik / плагиат"),
    ("research", "tadqiqot / исследование"),
    ("revise for", "imtihonga tayyorlanmoq / готовиться к"),
    ("scholarship", "stipendiya / стипендия"),
    ("seminar", "seminar / семинар"),
    ("semester", "semestr / семестр"),
    ("supervisor", "ilmiy rahbar / научный руководитель"),
    ("thesis", "ilmiy ish / диссертация"),
    ("tuition fees", "o'qish to'lovi / плата за обучение"),
    ("undergraduate", "bakalavriat talabasi / студент бакалавриата"),
    ("academic", "akademik / академический"),
    ("compulsory", "majburiy / обязательный"),
    ("optional", "ixtiyoriy / необязательный"),
    ("qualify for", "huquqqa ega bo'lmoq / иметь право на"),
]

HEALTH = [
    ("addiction", "qaramlik / зависимость"),
    ("allergy", "allergiya / аллергия"),
    ("anxiety", "tashvish holati / тревожность"),
    ("diagnosis", "tashxis / диагноз"),
    ("immune system", "immunitet tizimi / иммунная система"),
    ("infection", "yuqumli kasallik / инфекция"),
    ("mental health", "ruhiy salomatlik / психическое здоровье"),
    ("nutrition", "to'g'ri ovqatlanish / питание"),
    ("obesity", "semizlik / ожирение"),
    ("painkiller", "og'riq qoldiruvchi / обезболивающее"),
    ("prescription", "retsept / рецепт"),
    ("recovery", "sog'ayish / выздоровление"),
    ("side effect", "yon ta'sir / побочный эффект"),
    ("surgery", "jarrohlik / хирургия"),
    ("symptom", "alomat / симптом"),
    ("therapy", "terapiya / терапия"),
    ("treatment", "davolash usuli / лечение"),
    ("vaccination", "emlash / вакцинация"),
    ("wellbeing", "farovonlik / благополучие"),
    ("chronic", "surunkali / хронический"),
    ("contagious", "yuquvchan / заразный"),
    ("fatal", "halokatli / смертельный"),
    ("harmful", "zararli / вредный"),
    ("beneficial", "foydali / полезный"),
    ("balanced diet", "muvozanatli ovqatlanish / сбалансированное питание"),
]

ENVIRONMENT = [
    ("biodiversity", "biologik xilma-xillik / биоразнообразие"),
    ("carbon emissions", "uglerod chiqindilari / выбросы углерода"),
    ("conservation", "tabiatni asrash / охрана природы"),
    ("deforestation", "o'rmon kesilishi / вырубка лесов"),
    ("drought", "qurg'oqchilik / засуха"),
    ("ecosystem", "ekotizim / экосистема"),
    ("endangered species", "yo'qolayotgan tur / вымирающий вид"),
    ("fossil fuels", "qazilma yoqilg'ilar / ископаемое топливо"),
    ("greenhouse gas", "issiqxona gazi / парниковый газ"),
    ("landfill", "axlatxona / свалка"),
    ("natural resources", "tabiiy boyliklar / природные ресурсы"),
    ("ozone layer", "ozon qatlami / озоновый слой"),
    ("pesticide", "pestitsid / пестицид"),
    ("recycling plant", "qayta ishlash zavodi / перерабатывающий завод"),
    ("renewable energy", "qayta tiklanuvchi energiya / возобновляемая энергия"),
    ("sea level", "dengiz sathi / уровень моря"),
    ("sustainable", "barqaror / устойчивый"),
    ("wildlife reserve", "qo'riqxona / заповедник"),
    ("contaminate", "ifloslantirmoq / загрязнять"),
    ("preserve", "asrab qolmoq / сохранять"),
    ("dispose of", "chiqarib tashlamoq / утилизировать"),
    ("consume", "iste'mol qilmoq / потреблять"),
    ("run out", "tugab qolmoq / истощаться"),
    ("harvest", "hosil yig'moq / собирать урожай"),
    ("adapt", "moslashmoq / приспосабливаться"),
]

TECHNOLOGY = [
    ("algorithm", "algoritm / алгоритм"),
    ("artificial intelligence", "sun'iy intellekt / искусственный интеллект"),
    ("automation", "avtomatlashtirish / автоматизация"),
    ("cybersecurity", "kiberxavfsizlik / кибербезопасность"),
    ("database", "ma'lumotlar bazasi / база данных"),
    ("device driver", "qurilma dasturi / драйвер устройства"),
    ("digital literacy", "raqamli savodxonlik / цифровая грамотность"),
    ("encryption", "shifrlash / шифрование"),
    ("gadget", "qurilma / гаджет"),
    ("innovation", "innovatsiya / инновация"),
    ("interface", "interfeys / интерфейс"),
    ("malware", "zararli dastur / вредоносная программа"),
    ("platform", "platforma / платформа"),
    ("privacy settings", "maxfiylik sozlamalari / настройки приватности"),
    ("remote access", "masofadan kirish / удалённый доступ"),
    ("smart device", "aqlli qurilma / умное устройство"),
    ("software update", "dastur yangilanishi / обновление ПО"),
    ("storage capacity", "xotira hajmi / объём памяти"),
    ("streaming", "onlayn uzatish / стриминг"),
    ("subscription", "obuna / подписка"),
    ("user-friendly", "qulay interfeysli / удобный"),
    ("virtual reality", "virtual reallik / виртуальная реальность"),
    ("browse", "ko'rib chiqmoq / просматривать"),
    ("crash", "ishdan chiqmoq / сбоить"),
    ("upgrade", "yangilamoq / модернизировать"),
]

MEDIA = [
    ("advertising campaign", "reklama kampaniyasi / рекламная кампания"),
    ("broadcast", "efirga uzatmoq / транслировать"),
    ("censorship", "senzura / цензура"),
    ("coverage", "yoritilishi / освещение"),
    ("current affairs", "dolzarb voqealar / текущие события"),
    ("documentary series", "hujjatli turkum / документальный сериал"),
    ("editorial", "tahririyat maqolasi / редакционная статья"),
    ("exclusive", "faqat bitta manbada / эксклюзивный"),
    ("front-page story", "bosh maqola / статья на первой полосе"),
    ("headline news", "asosiy yangilik / главная новость"),
    ("influencer", "ta'sir ko'rsatuvchi blogger / инфлюенсер"),
    ("journalism", "jurnalistika / журналистика"),
    ("live stream", "jonli efir / прямая трансляция"),
    ("media coverage", "ommaviy axborot yoritilishi / освещение в СМИ"),
    ("misinformation", "noto'g'ri ma'lumot / дезинформация"),
    ("press conference", "matbuot anjumani / пресс-конференция"),
    ("publicity", "ommaga tanitish / огласка"),
    ("readership", "o'quvchilar auditoriyasi / читательская аудитория"),
    ("reliable source", "ishonchli manba / надёжный источник"),
    ("sensational", "shov-shuvli / сенсационный"),
    ("subscriber", "obunachi / подписчик"),
    ("tabloid", "arzon gazeta / таблоид"),
    ("viewpoint", "qarash nuqtasi / точка зрения"),
    ("go viral", "keng tarqalmoq / стать вирусным"),
    ("break a story", "yangilikni birinchi bo'lib bermoq / первым сообщить"),
]

SOCIETY = [
    ("authority", "hokimiyat / власть"),
    ("citizen", "fuqaro / гражданин"),
    ("community centre", "mahalla markazi / общественный центр"),
    ("crime rate", "jinoyatchilik darajasi / уровень преступности"),
    ("democracy", "demokratiya / демократия"),
    ("discrimination", "kamsitish / дискриминация"),
    ("equality", "tenglik / равенство"),
    ("government policy", "davlat siyosati / государственная политика"),
    ("homelessness", "uysizlik / бездомность"),
    ("immigration", "immigratsiya / иммиграция"),
    ("inequality", "tengsizlik / неравенство"),
    ("legislation", "qonunchilik / законодательство"),
    ("local council", "mahalliy kengash / местный совет"),
    ("minority", "ozchilik / меньшинство"),
    ("population growth", "aholi o'sishi / рост населения"),
    ("poverty line", "qashshoqlik chegarasi / черта бедности"),
    ("protest", "norozilik bildirmoq / протестовать"),
    ("public opinion", "jamoatchilik fikri / общественное мнение"),
    ("regulation", "qoida, tartib / регулирование"),
    ("taxpayer", "soliq to'lovchi / налогоплательщик"),
    ("unemployment", "ishsizlik / безработица"),
    ("volunteer work", "ko'ngilli ish / волонтёрская работа"),
    ("welfare", "ijtimoiy ta'minot / социальное обеспечение"),
    ("campaign for", "kurash olib bormoq / выступать за"),
    ("raise awareness", "xabardorlikni oshirmoq / повышать осведомлённость"),
]

TRAVEL = [
    ("accommodation", "joylashuv / размещение"),
    ("all-inclusive", "hammasi kiritilgan / всё включено"),
    ("boarding pass", "chiqish taloni / посадочный талон"),
    ("connecting flight", "ulanuvchi reys / стыковочный рейс"),
    ("customs", "bojxona / таможня"),
    ("departure lounge", "ketish zali / зал вылета"),
    ("destination", "manzil / пункт назначения"),
    ("excursion", "ekskursiya / экскурсия"),
    ("expedition", "ekspeditsiya / экспедиция"),
    ("guided tour", "gid bilan ekskursiya / экскурсия с гидом"),
    ("itinerary", "safar rejasi / маршрут поездки"),
    ("jet lag", "vaqt farqidan charchash / джетлаг"),
    ("landmark", "diqqatga sazovor joy / достопримечательность"),
    ("luggage allowance", "yuk normasi / норма багажа"),
    ("off the beaten track", "kam borilgan joy / вдали от туристических троп"),
    ("overbooked", "haddan ortiq band qilingan / перебронированный"),
    ("package holiday", "kompleks ta'til / пакетный тур"),
    ("passport control", "pasport nazorati / паспортный контроль"),
    ("peak season", "eng gavjum mavsum / высокий сезон"),
    ("resort", "kurort / курорт"),
    ("scenic route", "manzarali yo'l / живописный маршрут"),
    ("stopover", "oraliq to'xtash / пересадка"),
    ("travel insurance", "sayohat sug'urtasi / туристическая страховка"),
    ("breathtaking", "nafas oldiradigan / захватывающий дух"),
    ("wander", "sayr qilib yurmoq / бродить"),
]

FEELINGS = [
    ("apprehensive", "xavotirda / опасающийся"),
    ("astonished", "hayratda qolgan / поражённый"),
    ("content", "qanoatlangan / довольный"),
    ("devastated", "qattiq xafa bo'lgan / убитый горем"),
    ("frustrated", "ko'ngli to'lmagan / разочарованный"),
    ("grateful", "minnatdor / признательный"),
    ("guilty", "aybdorlik hissi / чувствующий вину"),
    ("homesick", "vatanini sog'ingan / тоскующий по дому"),
    ("indifferent", "befarq / равнодушный"),
    ("insecure", "o'ziga ishonchsiz / неуверенный"),
    ("overwhelmed", "bosim ostida qolgan / перегруженный"),
    ("reluctant", "istamaydigan / неохотный"),
    ("relieved", "yengil tortgan / испытавший облегчение"),
    ("resentful", "xafa va norozi / обиженный"),
    ("satisfied", "qoniqqan / удовлетворённый"),
    ("sceptical", "shubha bilan qaraydigan / скептичный"),
    ("self-conscious", "o'zidan uyaladigan / стеснительный"),
    ("startled", "cho'chib ketgan / вздрогнувший"),
    ("tense", "taranglashgan / напряжённый"),
    ("thrilled", "juda quvongan / в восторге"),
    ("uneasy", "notinch / беспокойный"),
    ("vulnerable", "himoyasiz / уязвимый"),
    ("bitter", "ranji ichida / озлобленный"),
    ("optimistic", "nekbin / оптимистичный"),
    ("pessimistic", "badbin / пессимистичный"),
]

VERBS1 = [
    ("acknowledge", "e'tirof etmoq / признавать"),
    ("adjust", "moslashtirmoq / регулировать"),
    ("allocate", "taqsimlamoq / выделять"),
    ("anticipate", "oldindan kutmoq / предвидеть"),
    ("assess", "baholamoq / оценивать"),
    ("assume", "deb hisoblamoq / предполагать"),
    ("attribute", "bog'lamoq / приписывать"),
    ("clarify", "aniqlik kiritmoq / прояснять"),
    ("compensate", "qoplamoq / компенсировать"),
    ("conduct", "o'tkazmoq / проводить"),
    ("confront", "yuzma-yuz kelmoq / противостоять"),
    ("contribute", "hissa qo'shmoq / вносить вклад"),
    ("demonstrate", "ko'rsatib bermoq / демонстрировать"),
    ("derive", "kelib chiqmoq / происходить"),
    ("distinguish", "farqlamoq / различать"),
    ("emphasise", "urg'u bermoq / подчёркивать"),
    ("establish", "tashkil etmoq / устанавливать"),
    ("evaluate", "baho bermoq / оценивать"),
    ("exceed", "oshib ketmoq / превышать"),
    ("generate", "hosil qilmoq / генерировать"),
    ("highlight", "ajratib ko'rsatmoq / выделять"),
    ("identify", "aniqlamoq / определять"),
    ("implement", "joriy etmoq / внедрять"),
    ("imply", "nazarda tutmoq / подразумевать"),
    ("indicate", "ishora qilmoq / указывать"),
]

VERBS2 = [
    ("interpret", "talqin qilmoq / интерпретировать"),
    ("justify", "asoslamoq / оправдывать"),
    ("maintain", "saqlab turmoq / поддерживать"),
    ("modify", "o'zgartirmoq / изменять"),
    ("monitor", "kuzatib bormoq / отслеживать"),
    ("obtain", "olmoq / получать"),
    ("outline", "qisqacha bayon qilmoq / излагать"),
    ("overcome", "yengib o'tmoq / преодолевать"),
    ("participate", "ishtirok etmoq / участвовать"),
    ("perceive", "idrok etmoq / воспринимать"),
    ("pursue", "intilmoq / преследовать цель"),
    ("regulate", "tartibga solmoq / регулировать"),
    ("reinforce", "mustahkamlamoq / укреплять"),
    ("reject", "rad etmoq / отвергать"),
    ("resolve", "hal qilmoq / разрешать"),
    ("restrict", "cheklamoq / ограничивать"),
    ("reveal", "oshkor qilmoq / раскрывать"),
    ("substitute", "o'rniga qo'ymoq / заменять"),
    ("sustain", "davom ettirmoq / поддерживать"),
    ("tackle", "hal qilishga kirishmoq / браться за"),
    ("transform", "tubdan o'zgartirmoq / преобразовывать"),
    ("undergo", "boshdan kechirmoq / проходить через"),
    ("undertake", "zimmasiga olmoq / браться за"),
    ("vary", "farq qilmoq / различаться"),
    ("withdraw", "qaytarib olmoq / отзывать"),
]

ADJECTIVES = [
    ("adequate", "yetarli / достаточный"),
    ("ambiguous", "ikki ma'noli / двусмысленный"),
    ("beneficial", "naf keltiradigan / выгодный"),
    ("complex", "murakkab / сложный"),
    ("consistent", "izchil / последовательный"),
    ("controversial", "bahsli / спорный"),
    ("crucial", "hal qiluvchi / решающий"),
    ("distinct", "aniq farqlanadigan / отчётливый"),
    ("diverse", "xilma-xil / разнообразный"),
    ("efficient", "samarali / эффективный"),
    ("essential", "muhim zarur / необходимый"),
    ("evident", "ko'rinib turgan / очевидный"),
    ("feasible", "amalga oshsa bo'ladigan / осуществимый"),
    ("inevitable", "muqarrar / неизбежный"),
    ("innovative", "yangilikchi / инновационный"),
    ("intensive", "jadal / интенсивный"),
    ("misleading", "adashtiradigan / вводящий в заблуждение"),
    ("noticeable", "sezilarli / заметный"),
    ("precise", "aniq / точный"),
    ("relevant", "tegishli / актуальный"),
    ("reliable", "ishonch qozongan / надёжный"),
    ("significant", "sezilarli darajada muhim / значительный"),
    ("substantial", "salmoqli / существенный"),
    ("thorough", "puxta / тщательный"),
    ("widespread", "keng tarqalgan / широко распространённый"),
]

ACADEMIC = [
    ("analysis", "tahlil / анализ"),
    ("approach", "yondashuv / подход"),
    ("aspect", "jihat / аспект"),
    ("assumption", "taxmin / предположение"),
    ("benefit", "naf / выгода"),
    ("concept", "tushuncha / понятие"),
    ("conclusion", "xulosa / заключение"),
    ("consequence", "oqibat / последствие"),
    ("context", "sharoit, kontekst / контекст"),
    ("criteria", "mezonlar / критерии"),
    ("data", "ma'lumotlar / данные"),
    ("evidence", "dalil / доказательство"),
    ("factor", "omil / фактор"),
    ("function", "vazifa / функция"),
    ("impact", "ta'sir / воздействие"),
    ("method", "usul / метод"),
    ("outcome", "natija / итог"),
    ("percentage", "foiz ulushi / процент"),
    ("principle", "tamoyil / принцип"),
    ("process", "jarayon / процесс"),
    ("range", "diapazon / диапазон"),
    ("role", "rol / роль"),
    ("source", "manba / источник"),
    ("structure", "tuzilma / структура"),
    ("trend", "yo'nalish, tendensiya / тенденция"),
]

LISTS = [
    ("B2 words 1 · Character", "exam", 1, CHARACTER),
    ("B2 words 2 · Working life", "exam", 2, WORKLIFE),
    ("B2 words 3 · Money and finance", "exam", 3, MONEY),
    ("B2 words 4 · Education", "exam", 4, EDUCATION),
    ("B2 words 5 · Health", "exam", 5, HEALTH),
    ("B2 words 6 · The environment", "exam", 6, ENVIRONMENT),
    ("B2 words 7 · Technology", "exam", 7, TECHNOLOGY),
    ("B2 words 8 · Media and news", "exam", 8, MEDIA),
    ("B2 words 9 · Society", "exam", 9, SOCIETY),
    ("B2 words 10 · Travel", "exam", 10, TRAVEL),
    ("B2 words 11 · Feelings", "exam", 11, FEELINGS),
    ("B2 words 12 · Academic verbs 1", "exam", 12, VERBS1),
    ("B2 words 13 · Academic verbs 2", "exam", 13, VERBS2),
    ("B2 words 14 · Describing things", "exam", 14, ADJECTIVES),
    ("B2 words 15 · Academic nouns", "exam", 15, ACADEMIC),
]
