"""B2 words for the Intermediate classes, steps 16-30.

Second half of the ladder: phrasal verbs, collocations, word-building and the
abstract nouns that turn up in B2 reading and writing. Meanings in Uzbek and
Russian.
"""

LEVEL = "Intermediate"
BOOK = "B2 words"
PAST_FROM = 1

PHRASAL1 = [
    ("bring about", "sodir qilmoq / вызывать"),
    ("carry out", "amalga oshirmoq / выполнять"),
    ("come across", "tasodifan uchratmoq / случайно наткнуться"),
    ("cut down on", "kamaytirmoq / сокращать"),
    ("draw up", "tuzib chiqmoq / составлять"),
    ("fall through", "barbod bo'lmoq / сорваться"),
    ("get around", "chetlab o'tmoq / обходить"),
    ("give in", "taslim bo'lmoq / уступать"),
    ("go through with", "oxiriga yetkazmoq / доводить до конца"),
    ("hold back", "to'sib turmoq / сдерживать"),
    ("keep up with", "teng qadam tashlamoq / поспевать за"),
    ("look into", "tekshirib ko'rmoq / изучать вопрос"),
    ("make up for", "o'rnini qoplamoq / компенсировать"),
    ("point out", "e'tiborni qaratmoq / указывать на"),
    ("put off", "keyinga qoldirmoq / откладывать"),
    ("rule out", "istisno qilmoq / исключать"),
    ("set up", "yo'lga qo'ymoq / основывать"),
    ("sort out", "tartibga solmoq / улаживать"),
    ("stand for", "anglatmoq / означать"),
    ("take on", "zimmasiga olmoq / брать на себя"),
    ("turn down", "rad javob bermoq / отклонять"),
    ("work out", "hisoblab chiqmoq / вычислять"),
    ("come up with", "o'ylab topmoq / придумывать"),
    ("catch on", "ommalashmoq / входить в моду"),
    ("back up", "tasdiqlamoq / подкреплять"),
]

PHRASAL2 = [
    ("account for", "izohlab bermoq / объяснять"),
    ("break down", "buzilib qolmoq / ломаться"),
    ("build up", "asta-sekin to'plamoq / накапливать"),
    ("call off", "bekor qilmoq / отменять"),
    ("clear up", "hal bo'lmoq / проясняться"),
    ("die out", "yo'q bo'lib ketmoq / вымирать"),
    ("end up", "oxir-oqibat bo'lmoq / оказаться в итоге"),
    ("figure out", "tushunib yetmoq / разобраться"),
    ("get by", "zo'rg'a kun ko'rmoq / перебиваться"),
    ("hand in", "topshirmoq / сдавать"),
    ("hang on", "kutib turmoq / подождать"),
    ("lay off", "ishdan bo'shatmoq / увольнять"),
    ("live up to", "umidni oqlamoq / оправдывать ожидания"),
    ("look up to", "hurmat qilmoq / уважать"),
    ("pass on", "boshqaga uzatmoq / передавать дальше"),
    ("pick up on", "sezib qolmoq / замечать"),
    ("pull off", "uddalamoq / провернуть"),
    ("put up with", "chidamoq / мириться с"),
    ("run into", "duch kelmoq / столкнуться с"),
    ("settle down", "joylashib olmoq / остепениться"),
    ("stick to", "sodiq qolmoq / придерживаться"),
    ("take over", "nazoratni qo'lga olmoq / брать под контроль"),
    ("turn out", "ma'lum bo'lmoq / оказываться"),
    ("wear off", "ta'siri o'tmoq / проходить"),
    ("wipe out", "butunlay yo'q qilmoq / уничтожать"),
]

COLLOC1 = [
    ("make an effort", "harakat qilmoq / прилагать усилие"),
    ("take responsibility", "javobgarlikni olmoq / брать ответственность"),
    ("meet a deadline", "muddatga ulgurmoq / уложиться в срок"),
    ("reach an agreement", "kelishuvga erishmoq / достичь соглашения"),
    ("draw a conclusion", "xulosa chiqarmoq / делать вывод"),
    ("raise a question", "savol ko'tarmoq / поднимать вопрос"),
    ("play a role", "rol o'ynamoq / играть роль"),
    ("pay attention", "e'tibor bermoq / обращать внимание"),
    ("take advantage of", "foydalanib qolmoq / воспользоваться"),
    ("keep in touch", "aloqada bo'lmoq / поддерживать связь"),
    ("make progress", "oldinga siljimoq / делать успехи"),
    ("do research", "tadqiqot olib bormoq / проводить исследование"),
    ("take steps", "chora ko'rmoq / принимать меры"),
    ("set a goal", "maqsad qo'ymoq / ставить цель"),
    ("break a habit", "odatdan voz kechmoq / избавиться от привычки"),
    ("gain experience", "tajriba orttirmoq / набираться опыта"),
    ("lose track of", "hisobdan chiqib ketmoq / потерять счёт"),
    ("bear in mind", "yodda tutmoq / иметь в виду"),
    ("take into account", "hisobga olmoq / принимать во внимание"),
    ("come to terms with", "ko'nikmoq / смириться с"),
    ("have an impact on", "ta'sir ko'rsatmoq / влиять на"),
    ("give rise to", "sababchi bo'lmoq / порождать"),
    ("take place", "bo'lib o'tmoq / происходить"),
    ("make a difference", "o'zgartira olmoq / изменить к лучшему"),
    ("run a risk", "xavfga bormoq / рисковать"),
]

COLLOC2 = [
    ("heavy traffic", "tirbandlik / плотное движение"),
    ("strong opinion", "qat'iy fikr / твёрдое мнение"),
    ("deep concern", "chuqur tashvish / глубокая обеспокоенность"),
    ("major issue", "jiddiy masala / серьёзная проблема"),
    ("close relationship", "yaqin munosabat / близкие отношения"),
    ("bitter argument", "achchiq janjal / острый спор"),
    ("vital role", "hayotiy muhim rol / жизненно важная роль"),
    ("common misconception", "keng tarqalgan xato fikr / распространённое заблуждение"),
    ("growing concern", "ortib borayotgan xavotir / растущая обеспокоенность"),
    ("mutual respect", "o'zaro hurmat / взаимное уважение"),
    ("narrow escape", "zo'rg'a qutulish / едва избежать"),
    ("rough estimate", "taxminiy hisob / примерная оценка"),
    ("sharp increase", "keskin o'sish / резкий рост"),
    ("slight difference", "arzimas farq / незначительная разница"),
    ("steady decline", "barqaror pasayish / постепенный спад"),
    ("utter failure", "to'liq muvaffaqiyatsizlik / полный провал"),
    ("valid point", "asosli fikr / справедливое замечание"),
    ("wide range", "keng tanlov / широкий выбор"),
    ("busy schedule", "zich jadval / плотный график"),
    ("firm decision", "qat'iy qaror / твёрдое решение"),
    ("high expectations", "katta umidlar / высокие ожидания"),
    ("long-term effect", "uzoq muddatli ta'sir / долгосрочный эффект"),
    ("short notice", "oldindan ogohlantirmasdan / в последний момент"),
    ("prime example", "yorqin misol / яркий пример"),
    ("urgent matter", "shoshilinch ish / срочное дело"),
]

WORDBUILD1 = [
    ("achievement", "yutuq / достижение"),
    ("agreement", "kelishuv / соглашение"),
    ("arrangement", "tartibga solish / договорённость"),
    ("commitment", "sodiqlik va majburiyat / обязательство"),
    ("development", "rivojlanish / развитие"),
    ("employment", "bandlik / занятость"),
    ("improvement", "yaxshilanish / улучшение"),
    ("involvement", "ishtirok / вовлечённость"),
    ("judgement", "mulohaza / суждение"),
    ("measurement", "o'lchov / измерение"),
    ("movement", "harakat / движение"),
    ("replacement", "almashtirish / замена"),
    ("requirement", "talab / требование"),
    ("retirement", "nafaqaga chiqish / выход на пенсию"),
    ("settlement", "hal qilish kelishuvi / урегулирование"),
    ("statement", "bayonot / заявление"),
    ("treatment of", "muomala / обращение"),
    ("adjustment", "moslashtirish / корректировка"),
    ("announcement", "e'lon / объявление"),
    ("encouragement", "dalda / поощрение"),
    ("enjoyment", "zavq / удовольствие"),
    ("engagement", "faol qatnashish / вовлечение"),
    ("entertainment", "ko'ngilochar / развлечение"),
    ("equipment", "jihoz / оборудование"),
    ("punishment", "jazo / наказание"),
]

WORDBUILD2 = [
    ("carelessness", "beparvolik / беспечность"),
    ("effectiveness", "samaradorlik / эффективность"),
    ("fairness", "adolat / справедливость"),
    ("fitness", "jismoniy tayyorgarlik / физическая форма"),
    ("happiness", "baxt / счастье"),
    ("illness", "kasallik / болезнь"),
    ("kindness", "mehribonlik / доброта"),
    ("laziness", "dangasalik / лень"),
    ("loneliness", "yolg'izlik / одиночество"),
    ("madness", "jinnilik / безумие"),
    ("politeness", "xushmuomalalik / вежливость"),
    ("sadness", "g'amginlik / грусть"),
    ("seriousness", "jiddiylik / серьёзность"),
    ("sickness", "bemorlik / недомогание"),
    ("tiredness", "charchoq / усталость"),
    ("usefulness", "foydalilik / полезность"),
    ("weakness", "zaiflik / слабость"),
    ("willingness", "xohish-istak / готовность"),
    ("awareness", "xabardorlik / осведомлённость"),
    ("darkness", "qorong'ilik / темнота"),
    ("eagerness", "intilish / рвение"),
    ("emptiness", "bo'shliq / пустота"),
    ("greatness", "buyuklik / величие"),
    ("openness", "ochiqlik / открытость"),
    ("readiness", "tayyorgarlik / готовность"),
]

PREFIXES = [
    ("disagree", "rozi bo'lmaslik / не соглашаться"),
    ("disappear", "ko'zdan yo'qolmoq / исчезать"),
    ("dishonest", "insofsiz / нечестный"),
    ("illegal", "noqonuniy / незаконный"),
    ("illogical", "mantiqsiz / нелогичный"),
    ("immature", "yetilmagan / незрелый"),
    ("impatient", "sabrsiz / нетерпеливый"),
    ("impossible", "imkonsiz / невозможный"),
    ("inaccurate", "xato / неточный"),
    ("inconvenient", "noqulay / неудобный"),
    ("independent", "mustaqil / независимый"),
    ("irregular", "qoidaga bo'ysunmaydigan / нерегулярный"),
    ("irresponsible", "mas'uliyatsiz / безответственный"),
    ("misjudge", "noto'g'ri baholamoq / неверно оценить"),
    ("misunderstand", "noto'g'ri tushunmoq / неправильно понять"),
    ("overcrowded", "haddan tashqari gavjum / переполненный"),
    ("overestimate", "ortiqcha baholamoq / переоценивать"),
    ("underestimate", "kam baholamoq / недооценивать"),
    ("underpaid", "kam maosh oladigan / низкооплачиваемый"),
    ("rearrange", "qayta tartiblamoq / переставлять"),
    ("rebuild", "qaytadan qurmoq / перестраивать"),
    ("unfair", "adolatsiz / несправедливый"),
    ("unlikely", "ehtimoldan yiroq / маловероятный"),
    ("unnecessary", "keraksiz / ненужный"),
    ("unreliable", "ishonib bo'lmaydigan / ненадёжный"),
]

LINKING = [
    ("nevertheless", "shunga qaramay / тем не менее"),
    ("furthermore", "bundan tashqari / более того"),
    ("moreover", "qolaversa / кроме того"),
    ("therefore", "shu sababli / поэтому"),
    ("consequently", "natijada / следовательно"),
    ("whereas", "holbuki / тогда как"),
    ("although", "garchi / хотя"),
    ("despite", "qaramay / несмотря на"),
    ("in addition", "qo'shimcha ravishda / в дополнение"),
    ("on the contrary", "aksincha / напротив"),
    ("in contrast", "farqli o'laroq / в противоположность"),
    ("for instance", "masalan / например"),
    ("in other words", "boshqacha aytganda / иными словами"),
    ("as a result", "oqibatida / в результате"),
    ("provided that", "shu shart bilan / при условии что"),
    ("unless", "agar bo'lmasa / если не"),
    ("in spite of", "e'tiborsiz qoldirib / вопреки"),
    ("meanwhile", "shu orada / тем временем"),
    ("otherwise", "aks holda / иначе"),
    ("regardless of", "qaramasdan / независимо от"),
    ("to sum up", "xulosa qilib aytganda / подводя итог"),
    ("overall", "umuman olganda / в целом"),
    ("admittedly", "tan olish kerak / надо признать"),
    ("arguably", "bahsli tarzda / возможно"),
    ("namely", "aniqrog'i / а именно"),
]

DESCRIBE_PLACES = [
    ("bustling", "gavjum va shovqinli / оживлённый"),
    ("charming", "maftunkor / очаровательный"),
    ("cramped", "tor / тесный"),
    ("deserted", "huvillab qolgan / безлюдный"),
    ("dull", "zerikarli / унылый"),
    ("historic", "tarixiy ahamiyatli / исторический"),
    ("isolated", "chekka / изолированный"),
    ("lively", "jonli / оживлённый"),
    ("luxurious", "hashamatli / роскошный"),
    ("neglected", "qarovsiz / запущенный"),
    ("peaceful", "osoyishta / спокойный"),
    ("picturesque", "ko'rkam / живописный"),
    ("polluted", "ifloslangan / загрязнённый"),
    ("remote", "olis / отдалённый"),
    ("run-down", "vayronaga aylangan / обветшалый"),
    ("rural", "qishloq joy / сельский"),
    ("spacious", "keng / просторный"),
    ("suburban", "shahar chekkasi / пригородный"),
    ("urban", "shahar / городской"),
    ("vibrant", "ranglarga boy / яркий"),
    ("overlooking", "manzarasiga qaragan / выходящий на"),
    ("within walking distance", "piyoda yurish masofasida / в шаговой доступности"),
    ("off-limits", "kirish taqiqlangan / закрытый для входа"),
    ("well-preserved", "yaxshi saqlangan / хорошо сохранившийся"),
    ("purpose-built", "maxsus qurilgan / специально построенный"),
]

SPEAKING = [
    ("claim", "da'vo qilmoq / утверждать"),
    ("complain", "shikoyat qilmoq / жаловаться"),
    ("confess", "iqror bo'lmoq / признаваться"),
    ("deny", "inkor etmoq / отрицать"),
    ("insist", "turib olmoq / настаивать"),
    ("mention", "tilga olmoq / упоминать"),
    ("mutter", "ming'irlamoq / бормотать"),
    ("object", "e'tiroz bildirmoq / возражать"),
    ("persuade", "ko'ndirmoq / убеждать"),
    ("protest against", "norozilik bildirmoq / протестовать против"),
    ("recommend", "tavsiya qilmoq / рекомендовать"),
    ("refuse", "bosh tortmoq / отказываться"),
    ("remind", "eslatmoq / напоминать"),
    ("suggest", "taklif qilmoq / предлагать"),
    ("threaten", "do'q qilmoq / угрожать"),
    ("warn", "ogohlantirmoq / предупреждать"),
    ("whisper", "shivirlamoq / шептать"),
    ("announce", "ochiq e'lon qilmoq / объявлять"),
    ("argue", "bahslashmoq / спорить"),
    ("apologise", "uzr so'ramoq / извиняться"),
    ("boast", "maqtanmoq / хвастаться"),
    ("interrupt", "gapini bo'lmoq / перебивать"),
    ("reply", "javob qaytarmoq / отвечать"),
    ("state", "rasmiy aytmoq / заявлять"),
    ("summarise", "qisqacha bayon etmoq / резюмировать"),
]

THINKING = [
    ("assume so", "shunday deb o'ylamoq / полагать"),
    ("bear in mind that", "esda tutmoq / учитывать"),
    ("consider", "ko'rib chiqmoq / рассматривать"),
    ("doubt", "shubhalanmoq / сомневаться"),
    ("expect", "kutmoq / ожидать"),
    ("guess", "taxmin qilmoq / догадываться"),
    ("imagine", "tasavvur qilmoq / представлять"),
    ("realise", "anglab yetmoq / осознавать"),
    ("recall", "esga olmoq / припоминать"),
    ("recognise", "tanib olmoq / узнавать"),
    ("reckon", "hisoblab qaramoq / считать"),
    ("reflect on", "mulohaza yuritmoq / размышлять о"),
    ("regret", "afsuslanmoq / сожалеть"),
    ("suspect", "gumon qilmoq / подозревать"),
    ("wonder", "qiziqib qolmoq / интересоваться"),
    ("bear with", "sabr qilmoq / потерпеть"),
    ("figure", "xulosaga kelmoq / прийти к выводу"),
    ("ponder", "chuqur o'ylamoq / обдумывать"),
    ("speculate", "farazlar qilmoq / строить догадки"),
    ("weigh up", "tarozida tortmoq / взвешивать"),
    ("bear a grudge", "kek saqlamoq / держать обиду"),
    ("change one's mind", "fikridan qaytmoq / передумать"),
    ("make up one's mind", "qaror qabul qilmoq / решиться"),
    ("keep an open mind", "xolis qarashda qolmoq / сохранять непредвзятость"),
    ("have second thoughts", "ikkilanmoq / засомневаться"),
]

TIME = [
    ("beforehand", "oldindan / заранее"),
    ("briefly", "qisqa vaqtga / ненадолго"),
    ("constantly", "doimo / постоянно"),
    ("currently", "hozirda / в настоящее время"),
    ("eventually", "oxir-oqibat / в конце концов"),
    ("frequently", "tez-tez / часто"),
    ("gradually", "asta-sekin / постепенно"),
    ("immediately", "darhol / немедленно"),
    ("initially", "dastlab / изначально"),
    ("instantly", "bir zumda / мгновенно"),
    ("meanwhile", "shu paytda / между тем"),
    ("occasionally", "ba'zan / изредка"),
    ("previously", "avvalroq / ранее"),
    ("promptly", "kechiktirmay / незамедлительно"),
    ("rarely", "kamdan-kam / редко"),
    ("recently", "yaqinda / недавно"),
    ("simultaneously", "bir vaqtning o'zida / одновременно"),
    ("subsequently", "keyinchalik / впоследствии"),
    ("temporarily", "vaqtinchalik / временно"),
    ("ultimately", "pirovardida / в итоге"),
    ("in the long run", "uzoq muddatda / в долгосрочной перспективе"),
    ("from time to time", "vaqti-vaqti bilan / время от времени"),
    ("for the time being", "hozircha / пока что"),
    ("sooner or later", "ertami-kechmi / рано или поздно"),
    ("at short notice", "tezkor ravishda / в сжатые сроки"),
]

MEASURE = [
    ("approximately", "taxminan / приблизительно"),
    ("considerably", "ancha / значительно"),
    ("dramatically", "keskin / резко"),
    ("entirely", "butunlay / полностью"),
    ("hardly", "deyarli emas / едва"),
    ("increasingly", "tobora ko'proq / всё больше"),
    ("marginally", "juda oz / незначительно"),
    ("moderately", "o'rtacha / умеренно"),
    ("partially", "qisman / частично"),
    ("precisely", "roppa-rosa / точно"),
    ("primarily", "asosan / преимущественно"),
    ("relatively", "nisbatan / относительно"),
    ("roughly", "chamasi / примерно"),
    ("severely", "og'ir tarzda / сильно"),
    ("slightly", "salgina / слегка"),
    ("steadily", "bir tekis / равномерно"),
    ("substantially", "sezilarli darajada / существенно"),
    ("virtually", "amalda / практически"),
    ("the vast majority", "aksariyat ko'pchilik / подавляющее большинство"),
    ("a significant minority", "salmoqli ozchilik / значительное меньшинство"),
    ("twice as many", "ikki baravar ko'p / вдвое больше"),
    ("a fraction of", "arzimas ulushi / малая доля"),
    ("on average", "o'rtacha hisobda / в среднем"),
    ("at its peak", "eng yuqori nuqtada / на пике"),
    ("at the bottom", "eng quyi nuqtada / на самом дне"),
]

IDIOMS = [
    ("a piece of cake", "juda oson ish / проще простого"),
    ("under the weather", "mazasi yo'q / нездоровится"),
    ("once in a blue moon", "juda kamdan-kam / очень редко"),
    ("out of the blue", "kutilmaganda / как гром среди ясного неба"),
    ("on the same page", "bir xil tushunishmoqda / понимать друг друга"),
    ("get the hang of", "uquvini olmoq / освоиться с"),
    ("break the ice", "muloqotni boshlab bermoq / растопить лёд"),
    ("call it a day", "ishni to'xtatmoq / закончить на сегодня"),
    ("cost an arm and a leg", "juda qimmatga tushmoq / стоить целое состояние"),
    ("hit the roof", "qattiq jahli chiqmoq / выйти из себя"),
    ("in the same boat", "bir xil ahvolda / в одинаковом положении"),
    ("keep your fingers crossed", "omad tilamoq / держать кулачки"),
    ("let the cat out of the bag", "sirni oshkor qilmoq / проболтаться"),
    ("miss the boat", "imkonni boy bermoq / упустить возможность"),
    ("pull someone's leg", "hazillashmoq / разыгрывать"),
    ("see eye to eye", "fikri mos kelmoq / сходиться во взглядах"),
    ("sit on the fence", "betaraf turmoq / занимать нейтральную позицию"),
    ("take with a pinch of salt", "shubha bilan qabul qilmoq / относиться скептически"),
    ("the last straw", "sabr kosasini to'ldirgan narsa / последняя капля"),
    ("tip of the iceberg", "muammoning kichik ko'rinadigan qismi / верхушка айсберга"),
    ("bite off more than you can chew", "kuchidan ortiqcha ish olmoq / переоценить свои силы"),
    ("burn the midnight oil", "tunda ishlamoq / работать допоздна"),
    ("face the music", "oqibatini ko'rmoq / отвечать за последствия"),
    ("go the extra mile", "qo'shimcha harakat qilmoq / делать больше положенного"),
    ("play it by ear", "vaziyatga qarab ish tutmoq / действовать по обстоятельствам"),
]

EXAMSKILLS = [
    ("state your opinion", "fikringizni bildirmoq / выразить своё мнение"),
    ("give an example", "misol keltirmoq / привести пример"),
    ("compare and contrast", "taqqoslamoq va farqlamoq / сравнить и противопоставить"),
    ("summarise the main points", "asosiy fikrlarni jamlamoq / обобщить главное"),
    ("support an argument", "dalil bilan quvvatlamoq / подкрепить довод"),
    ("draw attention to", "diqqatni tortmoq / привлечь внимание к"),
    ("refer to the text", "matnga murojaat qilmoq / сослаться на текст"),
    ("express a preference", "afzal ko'rishni bildirmoq / выразить предпочтение"),
    ("agree in part", "qisman rozi bo'lmoq / частично согласиться"),
    ("counter-argument", "qarshi dalil / контраргумент"),
    ("evidence suggests", "dalillar ko'rsatadi / данные показывают"),
    ("on the one hand", "bir tomondan / с одной стороны"),
    ("on the other hand", "ikkinchi tomondan / с другой стороны"),
    ("it could be argued that", "shunday deyish mumkin / можно утверждать, что"),
    ("as far as I am concerned", "menga kelsak / что касается меня"),
    ("in my view", "mening nazarimda / на мой взгляд"),
    ("to a certain extent", "ma'lum darajada / в определённой степени"),
    ("broadly speaking", "umumiy aytganda / вообще говоря"),
    ("strictly speaking", "aniq aytganda / строго говоря"),
    ("first and foremost", "eng avvalo / прежде всего"),
    ("last but not least", "va nihoyat, muhimi / и не менее важно"),
    ("in conclusion", "xulosa o'rnida / в заключение"),
    ("this raises the question", "bu savol tug'diradi / это поднимает вопрос"),
    ("there is no doubt that", "shubha yo'qki / нет сомнений, что"),
    ("it is worth noting", "qayd etish joiz / стоит отметить"),
]

LISTS = [
    ("B2 words 16 · Phrasal verbs 1", "exam", 16, PHRASAL1),
    ("B2 words 17 · Phrasal verbs 2", "exam", 17, PHRASAL2),
    ("B2 words 18 · Collocations 1", "exam", 18, COLLOC1),
    ("B2 words 19 · Collocations 2", "exam", 19, COLLOC2),
    ("B2 words 20 · Word-building -ment", "exam", 20, WORDBUILD1),
    ("B2 words 21 · Word-building -ness", "exam", 21, WORDBUILD2),
    ("B2 words 22 · Prefixes", "exam", 22, PREFIXES),
    ("B2 words 23 · Linking words", "exam", 23, LINKING),
    ("B2 words 24 · Describing places", "exam", 24, DESCRIBE_PLACES),
    ("B2 words 25 · Reporting speech", "exam", 25, SPEAKING),
    ("B2 words 26 · Thinking and opinions", "exam", 26, THINKING),
    ("B2 words 27 · Time expressions", "exam", 27, TIME),
    ("B2 words 28 · Amounts and changes", "exam", 28, MEASURE),
    ("B2 words 29 · Idioms", "exam", 29, IDIOMS),
    ("B2 words 30 · Exam phrases", "exam", 30, EXAMSKILLS),
]
