"""Empower Beginner Units 10-12, as Play steps, A / B / C taught separately.

    10A irregular past verbs; past questions    10C buying a ticket
    10B transport and holidays
    11A be going to; future plans               11C at a hotel
    11B months, seasons, weather; would like
    12A directions and prepositions             12C asking the way
    12B life events; comparatives

The last three units of the book. Topics follow the standard A1 progression
rather than Azamat's own scripts, which stop at 3A.

Meanings in Uzbek and Russian.
"""

LEVEL = "Beginner"
BOOK = "Empower Beginner"
PAST_FROM = 9

U10A_V = [
    ("went", "bordi / пошёл"),
    ("came", "keldi / пришёл"),
    ("saw", "ko'rdi / увидел"),
    ("ate", "yedi / съел"),
    ("drank", "ichdi / выпил"),
    ("bought", "sotib oldi / купил"),
    ("got", "oldi / получил"),
    ("made", "yasadi / сделал"),
    ("took", "oldi, olib ketdi / взял"),
    ("gave", "berdi / дал"),
    ("wrote", "yozdi / написал"),
    ("read", "o'qidi / прочитал"),
    ("met", "uchrashdi / встретил"),
    ("said", "aytdi / сказал"),
    ("told", "gapirib berdi / рассказал"),
    ("knew", "bilardi / знал"),
    ("thought", "o'yladi / думал"),
    ("found", "topdi / нашёл"),
    ("left", "ketdi / уехал"),
    ("slept", "uxladi / спал"),
    ("had", "bor edi / имел"),
    ("did", "qildi / делал"),
    ("was able to", "qila oldi / смог"),
    ("spent", "sarfladi / потратил"),
    ("won", "yutdi / выиграл"),
]

U10A_G = [
    ("I ___ to Samarkand last week.", "went", "goed", "go", "was go"),
    ("She ___ a new phone.", "bought", "buyed", "buy", "was buy"),
    ("We ___ pizza for dinner.", "ate", "eated", "eat", "was eat"),
    ("He ___ my brother yesterday.", "saw", "seed", "see", "was see"),
    ("They ___ home late.", "came", "comed", "come", "was come"),
    ("I ___ a letter to my friend.", "wrote", "writed", "write", "was write"),
    ("I ___ go to work yesterday.", "didn't", "don't", "wasn't", "not did"),
    ("She ___ see the film.", "didn't", "doesn't", "wasn't", "not did"),
    ("___ you go to the party?", "Did", "Do", "Were", "Was"),
    ("___ he take the bus?", "Did", "Do", "Was", "Were"),
    ("What ___ you eat?", "did", "do", "were", "was"),
    ("Where ___ she go?", "did", "do", "were", "was"),
    ("A: Did you see him? B: Yes, ___.", "I did", "I saw", "I was", "did I"),
    ("A: Did they come? B: No, ___.", "they didn't", "they don't", "they weren't", "didn't they"),
    ("He didn't ___ anything.", "say", "said", "saying", "says"),
    ("Did she ___ you the money?", "give", "gave", "giving", "gives"),
    ("We ___ a great time.", "had", "haved", "have", "was have"),
    ("I ___ my keys this morning.", "found", "finded", "find", "was find"),
    ("They ___ at seven o'clock.", "left", "leaved", "leave", "was leave"),
    ("She ___ eight hours last night.", "slept", "sleeped", "sleep", "was sleep"),
    ("I ___ a lot of money.", "spent", "spended", "spend", "was spend"),
    ("Our team ___ the match.", "won", "winned", "win", "was win"),
    ("He ___ me the truth.", "told", "telled", "tell", "was tell"),
    ("I ___ it was Monday.", "thought", "thinked", "think", "was think"),
    ("We ___ a taxi to the airport.", "took", "taked", "take", "was take"),
]

U10B_V = [
    ("bus", "avtobus / автобус"),
    ("train", "poyezd / поезд"),
    ("plane", "samolyot / самолёт"),
    ("car", "mashina / машина"),
    ("taxi", "taksi / такси"),
    ("bicycle", "velosiped / велосипед"),
    ("metro", "metro / метро"),
    ("ticket", "chipta / билет"),
    ("platform", "perron / платформа"),
    ("airport", "aeroport / аэропорт"),
    ("luggage", "yuk / багаж"),
    ("suitcase", "chamadon / чемодан"),
    ("passport", "pasport / паспорт"),
    ("holiday", "ta'til / отпуск"),
    ("trip", "sayohat / поездка"),
    ("tourist", "sayyoh / турист"),
    ("hotel", "mehmonxona / гостиница"),
    ("beach", "plyaj / пляж"),
    ("sea", "dengiz / море"),
    ("mountains", "tog'lar / горы"),
    ("map", "xarita / карта"),
    ("camera", "kamera / фотоаппарат"),
    ("book a room", "xona band qilmoq / забронировать номер"),
    ("arrive", "yetib bormoq / прибывать"),
    ("leave", "jo'nab ketmoq / уезжать"),
]

U10B_G = [
    ("I went to Tashkent ___ train.", "by", "with", "on the", "in"),
    ("She came here ___ foot.", "on", "by", "with", "in"),
    ("We travelled ___ plane.", "by", "with", "on the", "in"),
    ("I got ___ the bus at the station.", "on", "in", "to", "at"),
    ("She got ___ the taxi.", "into", "on", "at", "to"),
    ("The train ___ at nine o'clock.", "leaves", "leave", "leaving", "is leave"),
    ("We arrived ___ the airport late.", "at", "to", "in", "on"),
    ("We arrived ___ Bukhara on Friday.", "in", "at", "to", "on"),
    ("How ___ did the ticket cost?", "much", "many", "long", "often"),
    ("How ___ is the journey?", "long", "much", "many", "far time"),
    ("I'd like a ticket ___ Samarkand.", "to", "at", "in", "for to"),
    ("We stayed ___ a hotel.", "in", "on", "at the in", "to"),
    ("Last summer we ___ to the sea.", "went", "goed", "go", "was go"),
    ("They ___ a room for two nights.", "booked", "book", "booking", "was book"),
    ("Did you ___ a good time?", "have", "had", "having", "has"),
    ("The plane ___ at six this morning.", "arrived", "arrive", "arriving", "was arrive"),
    ("It's a long way. Let's take ___ taxi.", "a", "an", "the", "-"),
    ("I forgot ___ passport.", "my", "me", "mine", "I"),
    ("We were ___ holiday last week.", "on", "in", "at", "to"),
    ("There ___ a lot of tourists here.", "are", "is", "was", "be"),
    ("The hotel was ___ than I expected.", "better", "gooder", "more good", "best"),
    ("It's the ___ city I know.", "most beautiful", "beautifulest", "more beautiful", "beautifuler"),
    ("I want ___ to Turkey next year.", "to go", "go", "going", "goes"),
    ("How ___ you get there?", "did", "do was", "were", "was"),
    ("We ___ our luggage at the hotel.", "left", "leaved", "leave", "was leave"),
]

U10C_V = [
    ("A ticket to Samarkand, please", "Samarqandga bitta chipta / Один билет до Самарканда"),
    ("Single or return?", "Bir tomongami yoki qaytishi bilanmi? / В одну сторону или туда-обратно?"),
    ("A return ticket, please", "Borib-kelish chiptasi / Билет туда и обратно"),
    ("What time is the next train?", "Keyingi poyezd soat nechada? / Во сколько следующий поезд?"),
    ("Which platform?", "Qaysi perron? / Какая платформа?"),
    ("Platform three", "Uchinchi perron / Третья платформа"),
    ("How long does it take?", "Qancha vaqt oladi? / Сколько это занимает?"),
    ("About two hours", "Taxminan ikki soat / Около двух часов"),
    ("Is this seat taken?", "Bu joy bandmi? / Это место занято?"),
    ("Where do I change?", "Qayerda almashaman? / Где мне пересесть?"),
    ("The train is late", "Poyezd kechikyapti / Поезд опаздывает"),
    ("The flight is delayed", "Reys kechiktirildi / Рейс задерживается"),
    ("Your passport, please", "Pasportingiz, iltimos / Ваш паспорт, пожалуйста"),
    ("Do you have any luggage?", "Yukingiz bormi? / У вас есть багаж?"),
    ("Just this bag", "Faqat shu sumka / Только эта сумка"),
    ("Gate number five", "Beshinchi chiqish / Выход номер пять"),
    ("Have a good trip", "Yaxshi boring / Счастливого пути"),
    ("Where is the bus stop?", "Avtobus bekati qayerda? / Где автобусная остановка?"),
    ("How much is a taxi?", "Taksi qancha turadi? / Сколько стоит такси?"),
    ("Can you take me to the airport?", "Meni aeroportga olib borasizmi? / Отвезите меня в аэропорт"),
    ("Stop here, please", "Shu yerda to'xtating / Остановите здесь, пожалуйста"),
    ("I'd like to check in", "Ro'yxatdan o'tmoqchiman / Я хотел бы зарегистрироваться"),
    ("Is this the right bus?", "Bu kerakli avtobusmi? / Это нужный автобус?"),
    ("I missed my train", "Poyezdga kechikdim / Я опоздал на поезд"),
    ("Excuse me, is this seat free?", "Kechirasiz, bu joy bo'shmi? / Извините, это место свободно?"),
]

U11A_V = [
    ("plan", "reja / план"),
    ("future", "kelajak / будущее"),
    ("next week", "keyingi hafta / на следующей неделе"),
    ("next year", "keyingi yil / в следующем году"),
    ("tonight", "bugun kechqurun / сегодня вечером"),
    ("soon", "tez orada / скоро"),
    ("later", "keyinroq / позже"),
    ("learn", "o'rganmoq / учить"),
    ("study", "tahsil olmoq / учиться"),
    ("move", "ko'chib o'tmoq / переезжать"),
    ("get married", "turmush qurmoq / жениться"),
    ("find a job", "ish topmoq / найти работу"),
    ("save money", "pul yig'moq / копить деньги"),
    ("buy a house", "uy sotib olmoq / купить дом"),
    ("pass an exam", "imtihondan o'tmoq / сдать экзамен"),
    ("start university", "universitetga kirmoq / поступить в университет"),
    ("dream", "orzu / мечта"),
    ("hope", "umid qilmoq / надеяться"),
    ("want", "xohlamoq / хотеть"),
    ("decide", "qaror qilmoq / решать"),
    ("maybe", "ehtimol / может быть"),
    ("sure", "aminman / уверен"),
    ("busy", "band / занятый"),
    ("ready", "tayyor / готовый"),
    ("together", "birga / вместе"),
]

U11A_G = [
    ("I ___ study English next year.", "am going to", "go to", "going to", "am go to"),
    ("She ___ visit her family.", "is going to", "are going to", "going to", "is go to"),
    ("They ___ move to Tashkent.", "are going to", "is going to", "going to", "are go to"),
    ("We ___ buy a car.", "aren't going to", "not going to", "don't going to", "isn't going to"),
    ("He ___ work tomorrow.", "isn't going to", "aren't going to", "not going to", "doesn't going to"),
    ("___ you going to study tonight?", "Are", "Do", "Is", "Does"),
    ("___ she going to come?", "Is", "Are", "Does", "Do"),
    ("A: Are you going to help? B: Yes, ___.", "I am", "I do", "I going", "am I"),
    ("What ___ you going to do?", "are", "do", "is", "does"),
    ("Where ___ they going to live?", "are", "is", "do", "does"),
    ("I'm going to ___ a new job.", "find", "to find", "finding", "finds"),
    ("She's going ___ study medicine.", "to", "for", "-", "at"),
    ("I want ___ English well.", "to speak", "speak", "speaking", "speaks"),
    ("They hope ___ university.", "to start", "start", "starting", "starts"),
    ("We'd like ___ a house one day.", "to buy", "buy", "buying", "buys"),
    ("I'm going to save money ___ a car.", "for", "to", "of", "at"),
    ("Maybe I ___ go to Turkey.", "will", "am will", "wills", "will to"),
    ("I think it ___ rain tomorrow.", "will", "wills", "is will", "will to"),
    ("She ___ be here tomorrow.", "won't", "willn't", "don't will", "not will"),
    ("I'm not ___ to work on Sunday.", "going", "go", "goes", "went"),
    ("What are your plans ___ the weekend?", "for", "to", "at", "of"),
    ("He's going to get married ___ June.", "in", "on", "at", "to"),
    ("We're going to meet ___ Friday.", "on", "in", "at", "to"),
    ("I'm going to be a doctor ___ day.", "one", "a", "the", "some"),
    ("Are they going ___ come with us?", "to", "for", "-", "at"),
]

U11B_V = [
    ("January", "yanvar / январь"),
    ("February", "fevral / февраль"),
    ("March", "mart / март"),
    ("April", "aprel / апрель"),
    ("May", "may / май"),
    ("June", "iyun / июнь"),
    ("July", "iyul / июль"),
    ("August", "avgust / август"),
    ("September", "sentabr / сентябрь"),
    ("October", "oktabr / октябрь"),
    ("November", "noyabr / ноябрь"),
    ("December", "dekabr / декабрь"),
    ("spring", "bahor / весна"),
    ("summer", "yoz / лето"),
    ("autumn", "kuz / осень"),
    ("winter", "qish / зима"),
    ("weather", "ob-havo / погода"),
    ("sunny", "quyoshli / солнечно"),
    ("rainy", "yomg'irli / дождливо"),
    ("windy", "shamolli / ветрено"),
    ("cloudy", "bulutli / облачно"),
    ("snow", "qor / снег"),
    ("warm", "iliq / тёплый"),
    ("cool", "salqin / прохладный"),
    ("season", "fasl / время года"),
]

U11B_G = [
    ("___ you like a cup of tea?", "Would", "Do", "Are", "Will"),
    ("I ___ like a coffee, please.", "would", "will", "am", "do"),
    ("She'd like ___ to the cinema.", "to go", "go", "going", "goes"),
    ("A: Would you like some cake? B: Yes, ___.", "please", "I would like", "I like", "thanks you"),
    ("My birthday is ___ May.", "in", "on", "at", "to"),
    ("The party is ___ 5 June.", "on", "in", "at", "to"),
    ("It's very cold ___ winter.", "in", "on", "at", "to"),
    ("What's the weather ___ today?", "like", "as", "how", "same"),
    ("It ___ a lot in spring.", "rains", "rain", "raining", "is rain"),
    ("It's ___ today. Take an umbrella.", "raining", "rain", "rains", "rainy the"),
    ("Summer is ___ than winter.", "hotter", "hot", "hottest", "more hot"),
    ("July is the ___ month here.", "hottest", "hotter", "most hot", "hot"),
    ("It's ___ cold to go out.", "too", "very much", "so much", "enough"),
    ("It isn't warm ___ to swim.", "enough", "too", "very", "so"),
    ("I like autumn ___ than summer.", "better", "gooder", "more good", "best"),
    ("What ___ your favourite season?", "is", "are", "does", "do"),
    ("In winter it ___ a lot.", "snows", "snow", "snowing", "is snow"),
    ("Last winter ___ very cold.", "was", "were", "is", "did"),
    ("It's going ___ rain tomorrow.", "to", "for", "-", "at"),
    ("I'd like ___ visit Italy.", "to", "for", "-", "at"),
    ("We usually go on holiday ___ August.", "in", "on", "at", "to"),
    ("The weather ___ nice yesterday.", "was", "were", "is", "did"),
    ("Would you like ___ tea?", "some", "a", "any", "many"),
    ("There ___ a lot of snow last year.", "was", "were", "is", "did"),
    ("It's warmer today ___ yesterday.", "than", "then", "that", "as"),
]

U11C_V = [
    ("I'd like to book a room", "Xona band qilmoqchiman / Я хотел бы забронировать номер"),
    ("Have you got a room?", "Bo'sh xonangiz bormi? / У вас есть свободный номер?"),
    ("For how many nights?", "Necha kecha uchun? / На сколько ночей?"),
    ("For two nights", "Ikki kecha uchun / На две ночи"),
    ("A single room", "Bir kishilik xona / Одноместный номер"),
    ("A double room", "Ikki kishilik xona / Двухместный номер"),
    ("How much is it per night?", "Bir kechasi qancha? / Сколько за ночь?"),
    ("Breakfast is included", "Nonushta narxga kiradi / Завтрак включён"),
    ("What time is breakfast?", "Nonushta soat nechada? / Во сколько завтрак?"),
    ("Can I see the room?", "Xonani ko'rsam bo'ladimi? / Можно посмотреть номер?"),
    ("Here's your key", "Mana kalitingiz / Вот ваш ключ"),
    ("Room number twelve", "O'n ikkinchi xona / Номер двенадцать"),
    ("On the second floor", "Ikkinchi qavatda / На втором этаже"),
    ("Is there wifi?", "Wifi bormi? / Есть ли вайфай?"),
    ("What's the password?", "Parol nima? / Какой пароль?"),
    ("The air conditioning doesn't work", "Konditsioner ishlamayapti / Кондиционер не работает"),
    ("Could you help me?", "Yordam bera olasizmi? / Не могли бы вы помочь?"),
    ("What time is check-out?", "Qachon bo'shatish kerak? / Во сколько выезд?"),
    ("I'd like to check out", "Xonani bo'shatmoqchiman / Я хотел бы выехать"),
    ("Can I leave my bags here?", "Sumkalarimni shu yerda qoldirsam bo'ladimi? / Можно оставить сумки здесь?"),
    ("Is there a lift?", "Lift bormi? / Есть ли лифт?"),
    ("Enjoy your stay", "Yoqimli dam oling / Приятного пребывания"),
    ("Can you call a taxi?", "Taksi chaqira olasizmi? / Можете вызвать такси?"),
    ("The room is very nice", "Xona juda yaxshi / Номер очень хороший"),
    ("Thank you for everything", "Hamma narsa uchun rahmat / Спасибо за всё"),
]

U12A_V = [
    ("left", "chap / налево"),
    ("right", "o'ng / направо"),
    ("straight on", "to'g'riga / прямо"),
    ("corner", "burchak / угол"),
    ("opposite", "ro'parasida / напротив"),
    ("between", "orasida / между"),
    ("behind", "orqasida / позади"),
    ("in front of", "oldida / перед"),
    ("near", "yaqin / рядом"),
    ("far", "uzoq / далеко"),
    ("next to", "yonida / рядом с"),
    ("opposite side", "qarama-qarshi tomon / противоположная сторона"),
    ("traffic lights", "svetofor / светофор"),
    ("crossing", "o'tish joyi / переход"),
    ("bridge", "ko'prik / мост"),
    ("road", "yo'l / дорога"),
    ("turn", "burilmoq / поворачивать"),
    ("cross", "kesib o'tmoq / переходить"),
    ("go past", "yonidan o'tmoq / проходить мимо"),
    ("stop", "to'xtamoq / останавливаться"),
    ("centre", "markaz / центр"),
    ("north", "shimol / север"),
    ("south", "janub / юг"),
    ("east", "sharq / восток"),
    ("west", "g'arb / запад"),
]

U12A_G = [
    ("The bank is ___ the post office.", "opposite", "opposite of", "opposite to", "in opposite"),
    ("The shop is ___ the bank and the cafe.", "between", "among", "middle", "between of"),
    ("My house is ___ the school.", "next to", "next", "near to of", "beside of"),
    ("The car is ___ the house.", "in front of", "in front", "front of", "on front of"),
    ("The garden is ___ the house.", "behind", "back", "behind of", "back of"),
    ("___ left at the traffic lights.", "Turn", "You turn", "To turn", "Turning"),
    ("___ straight on for 200 metres.", "Go", "You go", "To go", "Going"),
    ("___ the road here.", "Cross", "You cross", "To cross", "Crossing"),
    ("It's ___ the corner.", "on", "in", "at", "to"),
    ("The hotel is ___ the left.", "on", "in", "at", "to"),
    ("Is it ___ from here?", "far", "far away of", "long", "much far"),
    ("It's about five minutes ___ foot.", "on", "by", "with", "in"),
    ("Excuse me, ___ is the station?", "where", "what", "which", "how"),
    ("How do I ___ to the museum?", "get", "go", "arrive", "come"),
    ("Take the ___ street on the right.", "first", "one", "onest", "firstly"),
    ("Go ___ the bridge.", "over", "on", "at", "of"),
    ("The cafe is ___ the second floor.", "on", "in", "at", "to"),
    ("Walk ___ the park.", "through", "trough", "across of", "in through"),
    ("It's ___ to the bank.", "next", "near of", "beside of", "close"),
    ("The bus stop is ___ there.", "over", "on", "at", "in"),
    ("Turn right ___ the corner.", "at", "in", "on", "to"),
    ("You ___ see it on your left.", "will", "wills", "are will", "will to"),
    ("Is there a bank ___ here?", "near", "nearly", "close", "next"),
    ("It's not far. It's ___ five minutes.", "only", "just only the", "alone", "single"),
    ("Thank you. ___ is very kind.", "That", "This is here", "It there", "Those"),
]

U12B_V = [
    ("be born", "tug'ilmoq / родиться"),
    ("grow up", "voyaga yetmoq / расти"),
    ("go to school", "maktabga bormoq / ходить в школу"),
    ("leave school", "maktabni tugatmoq / окончить школу"),
    ("go to university", "universitetga bormoq / поступить в университет"),
    ("get a job", "ishga kirmoq / устроиться на работу"),
    ("meet someone", "kimdir bilan tanishmoq / познакомиться"),
    ("fall in love", "sevib qolmoq / влюбиться"),
    ("get married", "uylanmoq / пожениться"),
    ("have children", "farzand ko'rmoq / завести детей"),
    ("move house", "uy almashtirmoq / переехать"),
    ("retire", "nafaqaga chiqmoq / выйти на пенсию"),
    ("life", "hayot / жизнь"),
    ("year", "yil / год"),
    ("month", "oy / месяц"),
    ("date", "sana / дата"),
    ("first", "birinchi / первый"),
    ("second", "ikkinchi / второй"),
    ("third", "uchinchi / третий"),
    ("important", "muhim / важный"),
    ("special", "alohida / особенный"),
    ("same", "bir xil / такой же"),
    ("different", "boshqacha / другой"),
    ("alone", "yolg'iz / один"),
    ("still", "hali ham / всё ещё"),
]

U12B_G = [
    ("My brother is ___ than me.", "older", "old", "oldest", "more old"),
    ("This book is ___ than that one.", "more interesting", "interestinger", "most interesting", "interesting"),
    ("She is the ___ student in the class.", "best", "gooder", "more good", "goodest"),
    ("Today is ___ than yesterday.", "worse", "bad", "worst", "more bad"),
    ("Tashkent is ___ city in Uzbekistan.", "the biggest", "biggest", "the bigger", "most big"),
    ("My flat is ___ than yours.", "smaller", "small", "smallest", "more small"),
    ("He runs ___ than me.", "faster", "fast", "fastest", "more fast"),
    ("This is the ___ day of my life.", "happiest", "happier", "most happy", "happyest"),
    ("English is ___ than Russian for me.", "easier", "easy", "easiest", "more easy"),
    ("She was born ___ 1998.", "in", "on", "at", "to"),
    ("He left school ___ the age of 17.", "at", "in", "on", "to"),
    ("They got married ___ 2020.", "in", "on", "at", "to"),
    ("I've got the ___ phone as you.", "same", "like", "equal", "similar of"),
    ("My life is ___ from hers.", "different", "difference", "differently", "differ"),
    ("He is ___ living in Bukhara.", "still", "yet", "already yet", "more"),
    ("She grew ___ in a small village.", "up", "on", "at", "in"),
    ("They ___ to a new house last year.", "moved", "moving", "move", "was move"),
    ("I ___ my wife at university.", "met", "meet", "meeted", "was meet"),
    ("He ___ a job in a bank in 2019.", "got", "get", "getted", "was get"),
    ("It was the ___ time I saw her.", "first", "one", "firstly", "once"),
    ("My grandfather ___ last year.", "retired", "retire", "retiring", "was retire"),
    ("She's ___ oldest in her family.", "the", "a", "an", "-"),
    ("This is ___ important day for me.", "an", "a", "the", "-"),
    ("I am not as tall ___ my brother.", "as", "than", "that", "like as"),
    ("He has ___ friends than me.", "more", "much", "most", "many more than"),
]

U12C_V = [
    ("Excuse me, can you help me?", "Kechirasiz, yordam bera olasizmi? / Извините, можете помочь?"),
    ("How do I get to the station?", "Bekatga qanday boraman? / Как добраться до вокзала?"),
    ("Is it far from here?", "Bu yerdan uzoqmi? / Это далеко отсюда?"),
    ("It's about ten minutes", "Taxminan o'n daqiqa / Примерно десять минут"),
    ("Go straight on", "To'g'riga yuring / Идите прямо"),
    ("Turn left at the corner", "Burchakdan chapga buriling / Поверните налево на углу"),
    ("Turn right after the bank", "Bankdan keyin o'ngga buriling / После банка поверните направо"),
    ("It's on your left", "U chap tomoningizda / Это слева от вас"),
    ("You can't miss it", "Adashmaysiz / Вы не пропустите"),
    ("I'm sorry, I don't know", "Kechirasiz, bilmayman / Извините, я не знаю"),
    ("I'm not from here", "Men bu yerlik emasman / Я не местный"),
    ("Ask that police officer", "Ana u politsiyachidan so'rang / Спросите у того полицейского"),
    ("Which bus goes there?", "U yerga qaysi avtobus boradi? / Какой автобус туда идёт?"),
    ("Take the number five", "Beshinchi raqamlisiga chiqing / Садитесь на пятый"),
    ("Where can I find a taxi?", "Taksini qayerdan topaman? / Где найти такси?"),
    ("Is there a bank near here?", "Yaqin atrofda bank bormi? / Есть ли поблизости банк?"),
    ("It's opposite the park", "U bog'ning ro'parasida / Это напротив парка"),
    ("Next to the post office", "Pochta yonida / Рядом с почтой"),
    ("Thanks a lot", "Katta rahmat / Большое спасибо"),
    ("You're welcome", "Arzimaydi / Пожалуйста"),
    ("Can you show me on the map?", "Xaritada ko'rsata olasizmi? / Можете показать на карте?"),
    ("Sorry, could you repeat that?", "Kechirasiz, takrorlaysizmi? / Извините, повторите, пожалуйста"),
    ("Speak more slowly, please", "Sekinroq gapiring / Говорите медленнее, пожалуйста"),
    ("I'm lost", "Adashib qoldim / Я заблудился"),
    ("Follow me", "Ortimdan yuring / Идите за мной"),
]

LISTS = [
    ("Unit 10A · Vocabulary — irregular past verbs", "vocab", 46, U10A_V),
    ("Unit 10A · Grammar — past simple: irregular", "grammar", 47, U10A_G),
    ("Unit 10B · Vocabulary — travel and transport", "vocab", 48, U10B_V),
    ("Unit 10B · Grammar — getting about in the past", "grammar", 49, U10B_G),
    ("Unit 10C · Everyday English — buying a ticket", "vocab", 50, U10C_V),
    ("Unit 11A · Vocabulary — plans and dreams", "vocab", 51, U11A_V),
    ("Unit 11A · Grammar — be going to", "grammar", 52, U11A_G),
    ("Unit 11B · Vocabulary — months, seasons, weather", "vocab", 53, U11B_V),
    ("Unit 11B · Grammar — would like, and comparing", "grammar", 54, U11B_G),
    ("Unit 11C · Everyday English — at a hotel", "vocab", 55, U11C_V),
    ("Unit 12A · Vocabulary — directions", "vocab", 56, U12A_V),
    ("Unit 12A · Grammar — where things are", "grammar", 57, U12A_G),
    ("Unit 12B · Vocabulary — a life", "vocab", 58, U12B_V),
    ("Unit 12B · Grammar — comparatives and superlatives", "grammar", 59, U12B_G),
    ("Unit 12C · Everyday English — asking the way", "vocab", 60, U12C_V),
]
