"""Empower Elementary Units 2-4, as Play steps, in Azamat's A&C / B&D pairing.

From the Teacher's Book:
    2A jobs; present simple positive and negative      2C asking for things
    2B studying; present simple questions              2D filling in a form
    3A daily routine; adverbs of frequency             3C making arrangements
    3B technology; have got                            3D inviting people
    4A food; countable and uncountable, a/an/some/any  4C in a restaurant
    4B cooking; much, many, a lot of                   4D talking about cooking
"""

U2_AC_V = [
    ("teacher", "works in a school and helps children learn"),
    ("doctor", "helps people who are ill"),
    ("nurse", "looks after people in a hospital"),
    ("engineer", "designs machines, roads or bridges"),
    ("driver", "takes people or things from place to place"),
    ("waiter", "brings food to your table in a restaurant"),
    ("chef", "cooks the food in a restaurant"),
    ("shop assistant", "helps customers to find things in a shop"),
    ("receptionist", "answers the phone at the front desk"),
    ("accountant", "works with a company's money and numbers"),
    ("lawyer", "helps people with the law"),
    ("journalist", "writes for a newspaper or a website"),
    ("photographer", "takes photos for a living"),
    ("farmer", "grows food and keeps animals"),
    ("builder", "makes houses and other buildings"),
    ("electrician", "works with electricity in buildings"),
    ("plumber", "repairs water pipes and taps"),
    ("hairdresser", "cuts people's hair"),
    ("dentist", "looks after people's teeth"),
    ("pilot", "flies a plane"),
    ("police officer", "stops crime and keeps people safe"),
    ("firefighter", "puts out fires"),
    ("scientist", "studies science and does experiments"),
    ("manager", "is in charge of a team at work"),
    ("cleaner", "keeps a building clean and tidy"),
]

U2_AC_G = [
    ("My sister ___ in a hospital.", "works", "work", "working", "is work"),
    ("I ___ English every evening.", "study", "studies", "am study", "studys"),
    ("He ___ breakfast at seven.", "has", "have", "haves", "is have"),
    ("She ___ to work by bus.", "goes", "gos", "go", "going"),
    ("My father ___ films at the weekend.", "watches", "watchs", "watch", "watching"),
    ("Aziz ___ two languages.", "speaks", "speak", "speakes", "is speak"),
    ("We ___ in Samarkand.", "live", "lives", "living", "are live"),
    ("The shop ___ at nine o'clock.", "opens", "open", "opening", "is open"),
    ("She ___ like coffee.", "doesn't", "don't", "isn't", "not"),
    ("They ___ work on Sunday.", "don't", "doesn't", "aren't", "not"),
    ("My brother ___ have a car.", "doesn't", "don't", "isn't", "hasn't"),
    ("I ___ understand this word.", "don't", "doesn't", "am not", "not"),
    ("Which sentence is correct?", "He teaches maths.", "He teach maths.",
     "He teachs maths.", "He is teach maths."),
    ("Which sentence is WRONG?", "She don't work here.", "She doesn't work here.",
     "She works here.", "Does she work here?"),
    ("Dilnoza ___ her homework every day.", "does", "do", "dos", "doing"),
    ("A good waiter ___ the customers quickly.", "serves", "serve", "servs",
     "is serve"),
    ("My friends ___ to university by taxi.", "travel", "travels", "travelling",
     "is travel"),
    ("It ___ a lot in winter here.", "snows", "snow", "snowing", "is snow"),
    ("In a shop: '___ I have a bag, please?'", "Can", "Do", "Am", "Have"),
    ("'Could you help me, please?' '___ course.'", "Of", "For", "In", "By"),
    ("The waiter gives you the menu and says '___ you are.'", "Here", "There",
     "This", "That"),
    ("'Can I have the bill, please?' '___ a moment.'", "Just", "One time",
     "Some", "Little"),
    ("A polite way to ask: '___ you pass me the salt?'", "Could", "Do", "Are",
     "Should"),
    ("'Thanks a lot.' 'No ___.'", "problem", "mind", "matter of", "thing"),
    ("Which is the most polite?", "Could I have a coffee, please?",
     "Give me a coffee.", "I want a coffee.", "Coffee, now."),
]

U2_BD_V = [
    ("study", "spend time learning a subject"),
    ("revise", "look at your notes again before a test"),
    ("exam", "an important test at the end of a course"),
    ("mark", "the score a teacher gives your work"),
    ("homework", "the work a teacher gives you to do at home"),
    ("notes", "the short things you write down in class"),
    ("dictionary", "a book that tells you what words mean"),
    ("degree", "what you get when you finish university"),
    ("course", "a set of lessons about one subject"),
    ("subject", "something you study, such as maths or history"),
    ("timetable", "a plan that shows when your lessons are"),
    ("library", "a quiet place with books you can borrow"),
    ("essay", "a long piece of writing about one question"),
    ("deadline", "the last day you can give work in"),
    ("break", "a short rest between lessons"),
    ("practise", "do something many times to get better"),
    ("concentrate", "think hard about one thing only"),
    ("stress", "the bad feeling when you have too much to do"),
    ("pass", "do well enough in an exam"),
    ("fail", "not do well enough in an exam"),
    ("term", "one of the parts the school year is divided into"),
    ("classmate", "another student in your class"),
    ("notebook", "the book you write your class notes in"),
    ("result", "what you get after the exam is marked"),
    ("certificate", "the paper that proves you finished a course"),
]

U2_BD_G = [
    ("___ you speak Russian?", "Do", "Are", "Does", "Is"),
    ("___ your sister work here?", "Does", "Do", "Is", "Are"),
    ("Where ___ you live?", "do", "are", "does", "is"),
    ("What time ___ the lesson start?", "does", "do", "is", "are"),
    ("'Do you like exams?' 'No, ___.'", "I don't", "I am not", "I doesn't",
     "don't I"),
    ("'Does he study English?' 'Yes, ___.'", "he does", "he do", "he is",
     "does he"),
    ("Which question is correct?", "Where does your friend study?",
     "Where studies your friend?", "Where do your friend study?",
     "Where your friend studies?"),
    ("How ___ students are there in your class?", "many", "much", "long", "lot"),
    ("Why ___ she revise at night?", "does", "do", "is", "has"),
    ("___ they have an exam tomorrow?", "Do", "Does", "Are", "Is"),
    ("Which is WRONG?", "Does she likes history?", "Does she like history?",
     "She likes history.", "She doesn't like history."),
    ("'What ___ you study?' 'Economics.'", "do", "does", "are", "is"),
    ("Put in order: you / do / where / study / ?", "Where do you study?",
     "Where you do study?", "Do where you study?", "Where study you do?"),
    ("'Do your parents work in Tashkent?' 'Yes, ___.'", "they do", "they are",
     "they does", "do they"),
    ("On a form, your family name goes in the box marked ___.", "surname",
     "first name", "address", "signature"),
    ("On a form, 'date of birth' means the day you ___.", "were born",
     "started school", "arrived", "signed"),
    ("A form asks for your postcode. That is part of your ___.", "address",
     "phone", "email", "name"),
    ("At the bottom of a form you write your ___.", "signature", "surname",
     "postcode", "subject"),
    ("'Sex' or 'gender' on a form means ___.", "male or female",
     "your age", "your job", "your country"),
    ("Which is a correct email address?", "aziz@mail.com", "aziz.mail.com",
     "aziz@mail@com", "aziz mail.com"),
    ("Write your name in ___ letters means use big letters.", "capital",
     "small", "thin", "long"),
    ("'Nationality' on a form means ___.", "the country you belong to",
     "the town you live in", "the school you go to", "your first language"),
    ("'Occupation' on a form means your ___.", "job", "hobby", "address",
     "age"),
    ("If a question does not apply to you, you write ___.", "N/A", "Yes",
     "No idea", "Maybe"),
    ("Please ___ in the form in black pen.", "fill", "make", "do", "put"),
]

U3_AC_V = [
    ("get up", "leave your bed in the morning"),
    ("wake up", "stop sleeping"),
    ("have a shower", "wash your whole body under water"),
    ("get dressed", "put your clothes on"),
    ("have breakfast", "eat your first meal of the day"),
    ("leave home", "go out of your house"),
    ("catch the bus", "get on the bus you need"),
    ("start work", "begin your working day"),
    ("have lunch", "eat your middle meal of the day"),
    ("finish work", "stop working for the day"),
    ("go home", "travel back to where you live"),
    ("cook dinner", "make the evening meal"),
    ("do the washing-up", "clean the plates after a meal"),
    ("tidy up", "put everything back in its place"),
    ("do homework", "do the work your teacher gave you"),
    ("meet friends", "spend time with people you know"),
    ("go to bed", "get into your bed at night"),
    ("fall asleep", "start sleeping"),
    ("have a rest", "stop working for a short time"),
    ("go for a walk", "walk outside because you want to"),
    ("brush your teeth", "clean your teeth"),
    ("get ready", "do the things you need before you go out"),
    ("take a nap", "sleep for a short time in the day"),
    ("stay in", "not go out in the evening"),
    ("go out", "leave home to enjoy yourself"),
]

U3_AC_G = [
    ("I ___ get up at six o'clock.", "always", "am always", "always am", "every"),
    ("She is ___ late for class.", "never", "never is", "not never", "no"),
    ("We ___ go to the cinema on Fridays.", "usually", "usually are",
     "are usually", "use"),
    ("Which is correct?", "He often plays football.", "He plays often football.",
     "Often he plays football often.", "He is often play football."),
    ("They are ___ at home in the evening.", "usually", "usually are",
     "use to", "usual"),
    ("Which is correct?", "I sometimes work late.", "I work sometimes late.",
     "Sometimes I am work late.", "I am sometimes work late."),
    ("Which is correct?", "She is always happy.", "She always is happy.",
     "She is happy always.", "Always she is happy."),
    ("How ___ do you go to the gym?", "often", "many", "much", "long"),
    ("'How often do you cook?' 'Twice ___ week.'", "a", "the", "in", "per the"),
    ("I ___ have breakfast. I'm never hungry in the morning.",
     "hardly ever", "hard ever", "ever hardly", "never ever"),
    ("Put in order: often / we / play / chess", "We often play chess.",
     "We play often chess.", "Often we play chess often.", "We play chess often we."),
    ("Which word means 100% of the time?", "always", "usually", "sometimes",
     "never"),
    ("Which word means 0% of the time?", "never", "rarely", "sometimes",
     "usually"),
    ("He ___ drinks coffee in the evening.", "rarely", "rare", "rarely is",
     "is rarely drink"),
    ("My parents ___ watch the news at nine.", "always", "are always",
     "always are", "all ways"),
    ("Which is the correct order?", "I am never tired in the morning.",
     "I never am tired in the morning.", "Never I am tired in the morning.",
     "I am tired never in the morning."),
    ("'___ you free on Saturday?' 'Yes, I am.'", "Are", "Do", "Is", "Have"),
    ("'How ___ meeting at six?' 'Perfect.'", "about", "for", "to", "of"),
    ("'Shall we meet at the cafe?' 'That ___ good.'", "sounds", "hears",
     "listens", "feels"),
    ("'Are you free on Monday?' 'Sorry, I ___.'", "can't", "don't can",
     "am not can", "no can"),
    ("'See you at seven.' '___!'", "Great", "Greatly", "Greater", "The great"),
    ("'Let's ___ at the bus stop.' 'OK.'", "meet", "to meet", "meeting",
     "we meet"),
    ("'What time ___ for you?' 'Six is fine.'", "is good", "are good",
     "does good", "is well"),
    ("'I'm sorry, I'm ___ on Sunday.'", "busy", "busily", "business", "busier"),
    ("'Can we make it half ___ eight?' 'Yes.'", "past", "to past", "after of",
     "over"),
]

U3_BD_V = [
    ("laptop", "a computer you can carry and open like a book"),
    ("tablet", "a flat computer you touch with your finger"),
    ("smartphone", "a phone you can also use for the internet"),
    ("screen", "the part you look at"),
    ("keyboard", "the part with the letters you press"),
    ("charger", "what you use to put power back in a battery"),
    ("battery", "the part that stores the power"),
    ("app", "a small program on your phone"),
    ("website", "pages on the internet at one address"),
    ("password", "the secret word that lets you in"),
    ("wifi", "the internet without a cable"),
    ("headphones", "what you wear to listen without noise"),
    ("speaker", "the part that the sound comes out of"),
    ("printer", "a machine that puts your work on paper"),
    ("file", "one piece of work saved on a computer"),
    ("folder", "a place on a computer that holds files"),
    ("download", "take something from the internet onto your device"),
    ("upload", "put something from your device onto the internet"),
    ("update", "make a program the newest version"),
    ("switch on", "make a machine start working"),
    ("charge", "fill the battery with power"),
    ("delete", "remove something for good"),
    ("search", "look for something on the internet"),
    ("message", "a short piece of writing you send"),
    ("camera", "the part that takes photos"),
]

U3_BD_G = [
    ("I ___ a new laptop.", "have got", "has got", "am got", "have get"),
    ("She ___ a car.", "has got", "have got", "is got", "has get"),
    ("They ___ got any wifi at home.", "haven't", "hasn't", "don't", "aren't"),
    ("He ___ got a charger.", "hasn't", "haven't", "doesn't", "isn't"),
    ("___ you got a tablet?", "Have", "Has", "Do", "Are"),
    ("___ your brother got a smartphone?", "Has", "Have", "Do", "Is"),
    ("'Have you got any headphones?' 'Yes, ___.'", "I have", "I've", "I got",
     "I am"),
    ("'Has she got a printer?' 'No, ___.'", "she hasn't", "she doesn't",
     "she haven't", "she isn't"),
    ("Which is correct?", "We've got two computers.", "We has got two computers.",
     "We got two computers have.", "We have get two computers."),
    ("Which is WRONG?", "He have got a new phone.", "He has got a new phone.",
     "He hasn't got a new phone.", "Has he got a new phone?"),
    ("My phone ___ got much battery left.", "hasn't", "haven't", "doesn't",
     "isn't"),
    ("How many apps ___ you got on your phone?", "have", "has", "do", "are"),
    ("The short form of 'I have got' is ___.", "I've got", "I'm got", "I'as got",
     "I got've"),
    ("Which sentence talks about something you own?", "I've got a bike.",
     "I'm a bike.", "I do a bike.", "I make a bike."),
    ("We ___ got time. The lesson starts now.", "haven't", "hasn't", "don't",
     "aren't"),
    ("In an invitation email you write: 'I'd ___ to invite you to my party.'",
     "like", "want", "wish", "hope"),
    ("'Please let me ___ if you can come.'", "know", "tell", "say", "speak"),
    ("An invitation often ends: 'Hope to ___ you there.'", "see", "look",
     "watch", "meet you to"),
    ("'The party ___ at seven on Saturday.'", "starts", "start", "starting",
     "is start"),
    ("Which is a good way to say yes to an invitation?",
     "Thanks, I'd love to come.", "Thanks, I come maybe.",
     "Thanks, I am come.", "Thanks, I will came."),
    ("Which is a polite way to say no?", "Sorry, I can't make it.",
     "No, I don't want.", "No, boring.", "I am not come."),
    ("'Can you bring ___ to eat?' 'Of course.'", "something", "anything not",
     "some thing of", "somewhat"),
    ("'What time ___ it finish?' 'About ten.'", "does", "do", "is", "has"),
    ("An email to a friend can begin ___.", "Hi Nodira,", "Dear Sir or Madam,",
     "To whom it may concern,", "Respected person,"),
    ("An email to a friend can end ___.", "See you soon,", "Yours faithfully,",
     "I remain yours,", "With respect and honour,"),
]

U4_AC_V = [
    ("bread", "you cut it into slices and make sandwiches with it"),
    ("rice", "small white grains you boil in water"),
    ("cheese", "a yellow food made from milk"),
    ("butter", "you put it on bread to make it softer"),
    ("milk", "the white drink that comes from cows"),
    ("egg", "a chicken lays it and you can fry or boil it"),
    ("chicken", "meat from a bird"),
    ("beef", "meat from a cow"),
    ("fish", "food that comes from the sea or a river"),
    ("potato", "a vegetable you can make chips from"),
    ("tomato", "a round red salad vegetable"),
    ("onion", "a strong vegetable that makes you cry"),
    ("carrot", "a long orange vegetable"),
    ("apple", "a round green or red fruit"),
    ("banana", "a long yellow fruit you peel"),
    ("grapes", "small round fruit that grow together"),
    ("sugar", "the sweet white thing you put in tea"),
    ("salt", "white grains that make food less plain"),
    ("pepper", "the black powder you shake on food"),
    ("oil", "you heat it in a pan before frying"),
    ("soup", "a hot liquid meal you eat with a spoon"),
    ("salad", "a cold dish of raw vegetables"),
    ("sandwich", "food between two pieces of bread"),
    ("cake", "a sweet food you eat on a birthday"),
    ("juice", "a drink made from fruit"),
]

U4_AC_G = [
    ("I'd like ___ apple, please.", "an", "a", "some", "any"),
    ("Can I have ___ water?", "some", "a", "an", "many"),
    ("There isn't ___ milk in the fridge.", "any", "some", "a", "many"),
    ("We need ___ eggs.", "some", "a", "an", "much"),
    ("Is there ___ bread left?", "any", "a", "an", "many"),
    ("She never eats ___ meat.", "any", "a", "an", "some of"),
    ("Which word is uncountable?", "rice", "apple", "sandwich", "egg"),
    ("Which word is countable?", "banana", "sugar", "water", "cheese"),
    ("We always buy ___ onions at the bazaar.", "some", "a", "an", "much"),
    ("Would you like ___ tea?", "some", "a", "an", "many"),
    ("There's ___ orange in the bag.", "an", "a", "some", "any"),
    ("He doesn't want ___ sugar in his coffee.", "any", "some", "a", "many"),
    ("Which is correct?", "I'd like some soup.", "I'd like a soup.",
     "I'd like an soup.", "I'd like many soup."),
    ("Which is WRONG?", "Can I have a rice?", "Can I have some rice?",
     "Can I have a sandwich?", "Can I have an apple?"),
    ("We haven't got ___ juice.", "any", "some", "a", "an"),
    ("In a restaurant: '___ for two, please.'", "A table", "A place",
     "A room", "A chair"),
    ("The waiter asks: 'Are you ready to ___?'", "order", "eat now", "choose it",
     "make"),
    ("'Can I ___ the menu, please?'", "see", "look", "watch", "read to"),
    ("'How ___ you like your steak?' 'Well done, please.'", "would", "do",
     "are", "will"),
    ("'Anything to ___?' 'Just water, thanks.'", "drink", "eat it", "have of",
     "take in"),
    ("At the end you ask for the ___.", "bill", "money", "paper", "price list"),
    ("'Is service ___?' 'Yes, it is.'", "included", "inside", "with", "paid"),
    ("'Enjoy your ___!' 'Thank you.'", "meal", "food time", "eat", "dish time"),
    ("'I'll have the soup ___ a starter.'", "as", "for to", "like of", "in"),
    ("Which is polite in a restaurant?", "Could we have the bill, please?",
     "Bring the bill.", "I want bill now.", "Bill!"),
]

U4_BD_V = [
    ("boil", "cook something in very hot water"),
    ("fry", "cook something in hot oil in a pan"),
    ("bake", "cook bread or cakes in an oven"),
    ("grill", "cook meat with heat from above or below"),
    ("roast", "cook meat or vegetables in the oven with oil"),
    ("mix", "put things together and move them around"),
    ("chop", "cut food into small pieces"),
    ("peel", "take the skin off a fruit or vegetable"),
    ("pour", "make a liquid flow into something"),
    ("add", "put one more thing in"),
    ("heat", "make something hot"),
    ("serve", "put the food in front of people"),
    ("taste", "try a little to see how it is"),
    ("spicy", "full of hot flavours that burn a little"),
    ("salty", "with a lot of salt"),
    ("sweet", "tasting of sugar"),
    ("sour", "tasting sharp, like a lemon"),
    ("fresh", "made or picked a very short time ago"),
    ("frozen", "kept very cold and hard"),
    ("delicious", "tasting extremely good"),
    ("raw", "not cooked at all"),
    ("recipe", "the instructions for making a dish"),
    ("ingredient", "one of the things you need to make a dish"),
    ("oven", "the hot box you bake things in"),
    ("pan", "the flat metal dish you fry things in"),
]

U4_BD_G = [
    ("How ___ sugar do you take?", "much", "many", "lot", "long"),
    ("How ___ eggs are in the box?", "many", "much", "lot", "long"),
    ("There isn't ___ milk left.", "much", "many", "lot", "a many"),
    ("There aren't ___ tomatoes in the fridge.", "many", "much", "lot",
     "a much"),
    ("We've got ___ rice at home.", "a lot of", "many", "much of", "lot of"),
    ("She drinks ___ water every day.", "a lot of", "many", "much of",
     "lots"),
    ("Which is correct?", "I don't eat much meat.", "I don't eat many meat.",
     "I don't eat a much meat.", "I don't eat lot meat."),
    ("Which is WRONG?", "How much apples do you want?",
     "How many apples do you want?", "How much bread do you want?",
     "I want a lot of apples."),
    ("There's ___ salt in this soup. I can't eat it.", "too much", "too many",
     "very many", "much too many"),
    ("He eats ___ vegetables. That's why he's healthy.",
     "a lot of", "much", "a much", "many of"),
    ("'Have we got ___ potatoes?' 'Yes, plenty.'", "enough", "enough of",
     "much enough", "many enough"),
    ("There are ___ people in the cafe today.", "a lot of", "much", "a much",
     "lot"),
    ("I only take a ___ sugar in my tea.", "little", "few", "lot", "many"),
    ("Add a ___ drops of oil to the pan.", "few", "little", "much", "lot"),
    ("Which word goes with uncountable nouns?", "much", "many", "few",
     "a number of"),
    ("Which word goes with countable nouns?", "many", "much", "a little",
     "a bit of"),
    ("First you ___ the onions, then you fry them.", "chop", "pour", "bake",
     "serve"),
    ("___ the water and then add the rice.", "Boil", "Peel", "Grill", "Chop"),
    ("You ___ a cake in the oven.", "bake", "fry", "boil", "chop"),
    ("Be careful, the soup is very ___ with pepper.", "spicy", "sour", "fresh",
     "raw"),
    ("You should ___ the potatoes before you cook them.", "peel", "pour",
     "serve", "taste"),
    ("This bread is very ___. It came out of the oven ten minutes ago.",
     "fresh", "frozen", "raw", "sour"),
    ("'Do you want to ___ it?' 'Yes, is there enough salt?'", "taste", "listen",
     "smell of", "watch"),
    ("A ___ tells you how to make a dish step by step.", "recipe", "menu",
     "bill", "timetable"),
    ("Milk, eggs and flour are the main ___ in this cake.", "ingredients",
     "recipes", "dishes", "courses"),
]

LISTS = [
    ("Unit 2A&C · Vocabulary — jobs", "vocab", 3, U2_AC_V),
    ("Unit 2A&C · Grammar — present simple, and asking for things", "grammar", 3, U2_AC_G),
    ("Unit 2B&D · Vocabulary — studying", "vocab", 4, U2_BD_V),
    ("Unit 2B&D · Grammar — present simple questions, and forms", "grammar", 4, U2_BD_G),
    ("Unit 3A&C · Vocabulary — your day", "vocab", 5, U3_AC_V),
    ("Unit 3A&C · Grammar — how often, and making arrangements", "grammar", 5, U3_AC_G),
    ("Unit 3B&D · Vocabulary — technology", "vocab", 6, U3_BD_V),
    ("Unit 3B&D · Grammar — have got, and inviting people", "grammar", 6, U3_BD_G),
    ("Unit 4A&C · Vocabulary — food", "vocab", 7, U4_AC_V),
    ("Unit 4A&C · Grammar — a, an, some, any, and in a restaurant", "grammar", 7, U4_AC_G),
    ("Unit 4B&D · Vocabulary — cooking", "vocab", 8, U4_BD_V),
    ("Unit 4B&D · Grammar — much, many, a lot of", "grammar", 8, U4_BD_G),
]
