"""Empower Pre-Intermediate Units 5-8, in the A&C / B&D pairing.

    5A work; must, have to, can            5C offers, suggestions, apologising
    5B jobs; will and might                5D job adverts
    6A devices; the imperative and should  6C asking for and giving advice
    6B -ed and -ing adjectives; uses of to 6D emails giving advice
    7A comparatives and superlatives       7C at the doctor
    7B used to                             7D a blog article
    8A art and music; the passive          8C keeping a conversation going
    8B sport; present perfect for and since  8D books and reviews
"""

LEVEL = "Pre-Intermediate"
BOOK = "Empower Pre-Intermediate"
PAST_FROM = 1

P5_AC_V = [
    ("apply for", "ask formally for a job"),
    ("employ", "give somebody a job"),
    ("staff", "all the people who work somewhere"),
    ("shift", "a set period of working hours"),
    ("overtime", "hours worked beyond the normal ones"),
    ("deadline", "the time by which work must be finished"),
    ("promotion", "moving up to a better position"),
    ("colleague", "a person you work with"),
    ("interview", "a formal meeting to get a job"),
    ("CV", "the document listing your education and jobs"),
    ("salary", "money paid monthly for your work"),
    ("wages", "money paid weekly or by the hour"),
    ("contract", "the written agreement about your job"),
    ("experience", "the time you have spent doing a kind of work"),
    ("qualification", "a certificate showing what you can do"),
    ("training", "teaching somebody the skills for a job"),
    ("workload", "the amount of work you have to do"),
    ("client", "somebody who pays for a service"),
    ("responsible for", "in charge of something"),
    ("resign", "leave your job by choice"),
    ("sack", "make somebody leave their job"),
    ("earn a living", "get the money you need by working"),
    ("self-employed", "working for yourself, not a company"),
    ("in charge", "having control of something"),
    ("day off", "a day when you do not work"),
]

P5_AC_G = [
    ("I ___ wear a uniform at work. It's a rule.", "have to", "have", "must to",
     "am have to"),
    ("You ___ smoke here. It's forbidden.", "mustn't", "don't have to",
     "haven't to", "not must"),
    ("We ___ work on Sunday. It's our day off.", "don't have to", "mustn't",
     "haven't to", "don't must"),
    ("She ___ speak three languages.", "can", "cans", "can to", "is can"),
    ("___ you have to start early?", "Do", "Are", "Have", "Must do"),
    ("He ___ finish the report today. The deadline is Friday.",
     "doesn't have to", "mustn't", "hasn't to", "don't have to"),
    ("Which sentence means it is forbidden?", "You mustn't park here.",
     "You don't have to park here.", "You can park here.",
     "You needn't park here."),
    ("Which sentence means it is not necessary?", "You don't have to come.",
     "You mustn't come.", "You can't come.", "You shouldn't come."),
    ("Staff ___ wear ID badges at all times.", "must", "must to", "have",
     "are must"),
    ("Which is WRONG?", "I must to leave now.", "I must leave now.",
     "I have to leave now.", "I don't have to leave now."),
    ("When I was a student I ___ work at weekends.", "had to", "must",
     "have to then", "must to"),
    ("___ I use your phone?", "Can", "Do can", "Am can", "Have can"),
    ("Applicants ___ send a CV and a letter.", "must", "must to", "are must",
     "have must"),
    ("She ___ drive, but she hasn't got a car.", "can", "can to", "cans",
     "is can"),
    ("We ___ book a table. It's never full.", "don't have to", "mustn't",
     "can't", "haven't"),
    ("You ___ be late for an interview.", "mustn't", "don't have to",
     "haven't to", "not must"),
    ("'___ I help you with those boxes?'", "Shall", "Do", "Am", "Will I"),
    ("'Would you like me ___ call a taxi?'", "to", "(nothing)", "for", "that I"),
    ("'Why ___ we ask the manager?' 'Good idea.'", "don't", "not", "aren't",
     "no"),
    ("'I'm really sorry ___ the delay.'", "about", "of", "for the", "with"),
    ("'Don't worry, it's not your ___.'", "fault", "mistake of you",
     "problem of fault", "guilty"),
    ("'These things ___ .' 'Thanks for understanding.'", "happen", "happened of",
     "are happen", "happening"),
    ("'Let me ___ it up to you.'", "make", "do", "take", "put"),
    ("'How ___ I asked my boss first?'", "about", "if", "would", "should of"),
    ("Which is the best apology at work?",
     "I'm sorry, it was my mistake and I'll fix it today.",
     "Sorry, but it wasn't really me.", "Sorry about that, anyway.",
     "It happened, sorry."),
]

P5_BD_V = [
    ("accountant", "somebody who works with a company's money"),
    ("architect", "somebody who designs buildings"),
    ("chef", "the person in charge of a kitchen"),
    ("electrician", "somebody who works with electrical systems"),
    ("journalist", "somebody who writes news reports"),
    ("lawyer", "somebody who advises people about the law"),
    ("mechanic", "somebody who repairs vehicles"),
    ("nurse", "somebody who cares for patients"),
    ("pharmacist", "somebody who prepares and sells medicine"),
    ("programmer", "somebody who writes computer code"),
    ("receptionist", "somebody who greets visitors at a desk"),
    ("scientist", "somebody who does research"),
    ("surgeon", "a doctor who operates on people"),
    ("translator", "somebody who turns writing into another language"),
    ("vet", "a doctor for animals"),
    ("waiter", "somebody who serves food in a restaurant"),
    ("well-paid", "giving a good salary"),
    ("part-time", "for fewer hours than a full job"),
    ("full-time", "for the whole normal working week"),
    ("permanent", "with no end date"),
    ("temporary", "only for a limited time"),
    ("freelance", "working for different clients, not one employer"),
    ("night shift", "the working hours during the night"),
    ("skilled", "having special training or ability"),
    ("demanding", "requiring a lot of effort"),
]

P5_BD_G = [
    ("I think prices ___ next year.", "will rise", "will to rise", "rise will",
     "are will rise"),
    ("She ___ get the job. She's very qualified.", "will probably",
     "probably will to", "will to probably", "is probably will"),
    ("They ___ arrive before six. The traffic is terrible.", "might not",
     "mightn't to", "don't might", "aren't might"),
    ("It ___ snow tonight, but I'm not sure.", "might", "might to", "will to",
     "is might"),
    ("He ___ be at the office. He usually leaves at five.", "might not",
     "mustn't", "don't might", "not might"),
    ("Which sentence is less certain?", "She might come.", "She will come.",
     "She is coming.", "She comes."),
    ("Which sentence is a firm prediction?", "Robots will do many jobs.",
     "Robots might do many jobs.", "Robots may possibly do jobs.",
     "Robots could do jobs perhaps."),
    ("___ you think they will accept?", "Do", "Will", "Are", "Have"),
    ("I don't think it ___ be easy.", "will", "won't", "will to", "is will"),
    ("Which is WRONG?", "It will to rain.", "It will rain.", "It might rain.",
     "It won't rain."),
    ("Perhaps he ___ apply for the manager's job.", "will", "wills", "will to",
     "is will"),
    ("We ___ need more staff in summer.", "might", "might to", "are might",
     "do might"),
    ("'Do you think she'll pass?' 'She ___ .'", "might", "might to",
     "will might", "is might"),
    ("In ten years, most shops ___ online.", "will be", "will to be",
     "are will be", "will being"),
    ("There ___ be a meeting tomorrow, but nobody has confirmed it.", "might",
     "might to", "will might", "are might"),
    ("Which shows a possibility, not a plan?", "I might take that job.",
     "I'm taking that job.", "I take that job.", "I am going to take it, decided."),
    ("A job advert says 'excellent communication ___ required'.", "skills",
     "skill of", "skilful of", "skilled of"),
    ("'Previous ___ is essential.'", "experience", "experiences of",
     "experienced of", "experiencing"),
    ("'Please send your CV and a covering ___ .'", "letter", "paper of",
     "note of apply", "form of cover"),
    ("'The ___ date is 30 June.'", "closing", "close of", "closed of",
     "closure to"),
    ("'Applicants must be ___ to work weekends.'", "able", "can", "possible of",
     "capable for"),
    ("'The post is ___ immediately.'", "available", "able of", "possible to",
     "free to take of"),
    ("'Salary ___ on experience.'", "depends", "depend of", "is depend",
     "depending of"),
    ("'We ___ applications from all backgrounds.'", "welcome", "welcoming of",
     "are welcome of", "welcomed of"),
    ("Which sentence belongs in a job application?",
     "I am writing to apply for the position of receptionist.",
     "Hi, I want this job.", "Give me the job please.",
     "I saw your advert and here I am."),
]

P6_AC_V = [
    ("device", "a piece of equipment made for a purpose"),
    ("screen", "the surface you look at"),
    ("button", "you press it to make something happen"),
    ("switch on", "make a machine start"),
    ("switch off", "make a machine stop"),
    ("plug in", "connect to electricity"),
    ("charge", "put power into a battery"),
    ("press", "push something briefly"),
    ("hold down", "keep pressing something"),
    ("restart", "stop and start again"),
    ("settings", "where you change how it works"),
    ("volume", "how loud the sound is"),
    ("instructions", "the steps telling you what to do"),
    ("manual", "the book explaining how something works"),
    ("wireless", "working without cables"),
    ("portable", "easy to carry"),
    ("rechargeable", "able to be charged again"),
    ("broken", "not working"),
    ("repair", "make something work again"),
    ("replace", "put a new one in place of the old"),
    ("warranty", "the promise to repair it free for a time"),
    ("out of order", "not working, for a public machine"),
    ("touchscreen", "a screen you control with your finger"),
    ("remote control", "the handset for a TV"),
    ("socket", "the hole in the wall for a plug"),
]

P6_AC_G = [
    ("___ the red button to start.", "Press", "To press", "Pressing",
     "You press to"),
    ("___ touch the screen with wet hands.", "Don't", "Not", "No", "Doesn't"),
    ("You ___ read the instructions first.", "should", "should to",
     "are should", "shoulds"),
    ("He ___ leave it charging all night.", "shouldn't", "not should",
     "don't should", "shouldn't to"),
    ("___ I turn it off and on again?", "Should", "Do should", "Am should",
     "Shall should"),
    ("Which is an imperative?", "Turn it off.", "You turn it off.",
     "You should turn it off.", "Turning it off."),
    ("Which gives advice?", "You should back up your files.",
     "Back up your files.", "You back up your files.", "Backing up files."),
    ("First ___ the device, then wait ten seconds.", "unplug", "to unplug",
     "unplugging", "you unplug to"),
    ("Which is WRONG?", "You should to call the shop.", "You should call the shop.",
     "Call the shop.", "Don't call the shop."),
    ("___ forget to save your work.", "Don't", "Not", "No", "Doesn't"),
    ("It's broken. You ___ take it back to the shop.", "should", "should to",
     "are should", "shoulds"),
    ("Please ___ quiet during the presentation.", "be", "are", "being", "to be"),
    ("Which sentence is the strongest instruction?", "Never open the battery.",
     "You should not open the battery.", "Maybe don't open the battery.",
     "It is better not to open it possibly."),
    ("We ___ buy a new one. This one is fine.", "shouldn't", "not should",
     "don't should", "mustn't to"),
    ("___ let children use it alone.", "Never", "Not never", "No never",
     "Don't never"),
    ("You ___ keep the receipt for the warranty.", "should", "should to",
     "are should", "should of"),
    ("Asking for advice: 'What ___ I do?'", "should", "shall to", "must to",
     "should to"),
    ("'If I ___ you, I'd take it back.'", "were", "was to be", "am", "be"),
    ("'Have you ___ turning it off and on?'", "tried", "try", "trying of",
     "tried to trying"),
    ("'It might be ___ idea to call the shop.'", "a good", "good", "the best of",
     "better of"),
    ("'Why ___ you ask for a refund?'", "don't", "not", "aren't", "no"),
    ("'Thanks, that's really ___ advice.'", "helpful", "helping of", "helped",
     "help of"),
    ("Giving advice gently: 'You ___ want to check the warranty.'", "might",
     "will", "must to", "should to"),
    ("'I'd ___ waiting until tomorrow.'", "suggest", "advise to", "recommend to",
     "propose to be"),
    ("Which is the least bossy?", "Perhaps you could try the shop first.",
     "Go to the shop.", "You must go to the shop.", "Go now to the shop."),
]

P6_BD_V = [
    ("amazed", "feeling great surprise"),
    ("amazing", "causing great surprise"),
    ("bored", "feeling no interest"),
    ("boring", "causing no interest"),
    ("confused", "unable to understand something"),
    ("confusing", "hard to understand"),
    ("disappointed", "feeling let down"),
    ("disappointing", "not as good as hoped"),
    ("excited", "feeling eager and happy"),
    ("exciting", "causing eagerness"),
    ("frightened", "feeling fear"),
    ("frightening", "causing fear"),
    ("interested", "wanting to know more"),
    ("interesting", "making you want to know more"),
    ("relaxed", "feeling calm"),
    ("relaxing", "making you calm"),
    ("surprised", "feeling that you did not expect it"),
    ("surprising", "not expected"),
    ("tired", "needing rest"),
    ("tiring", "making you need rest"),
    ("worried", "feeling anxious"),
    ("worrying", "causing anxiety"),
    ("embarrassed", "feeling ashamed in front of others"),
    ("embarrassing", "causing shame in front of others"),
    ("shocked", "feeling sudden upset surprise"),
]

P6_BD_G = [
    ("I was ___ by the ending of the film.", "surprised", "surprising",
     "surprise of", "surprisingly of it"),
    ("The ending was ___ .", "surprising", "surprised", "surprise", "surprisingly"),
    ("She felt ___ after the long journey.", "exhausted", "exhausting",
     "exhaust of", "exhaustion of"),
    ("The journey was ___ .", "exhausting", "exhausted", "exhaust",
     "exhaustion"),
    ("I'm ___ in learning Chinese.", "interested", "interesting", "interest of",
     "interestingly"),
    ("Which describes how a person feels?", "He was bored.", "He was boring.",
     "He is a boring person always.", "He bores."),
    ("Which describes the thing itself?", "The lesson was boring.",
     "The lesson was bored.", "The lesson felt bored.",
     "The lesson is a bored one."),
    ("She was ___ to hear the news.", "shocked", "shocking", "shock of",
     "shockingly of"),
    ("He wants ___ a new language.", "to learn", "learning", "learn",
     "for learn"),
    ("I enjoy ___ films in English.", "watching", "to watch", "watch",
     "for watching"),
    ("We decided ___ early.", "to leave", "leaving", "leave", "for leaving"),
    ("She finished ___ the report.", "writing", "to write", "write",
     "for write"),
    ("They hope ___ next summer.", "to travel", "travelling", "travel",
     "for travel"),
    ("Which is WRONG?", "I enjoy to swim.", "I enjoy swimming.",
     "I want to swim.", "I like swimming."),
    ("He went to the shop ___ some milk.", "to buy", "for buy", "buying",
     "for to buy"),
    ("It's difficult ___ early on Mondays.", "to get up", "getting up of",
     "get up", "for get up"),
    ("An email asking for advice starts: 'I'm writing ___ some advice.'",
     "to ask for", "for ask", "asking of", "to ask of for"),
    ("'I don't know what ___ .'", "to do", "do", "doing of", "for do"),
    ("'Do you have any ___ ?'", "suggestions", "suggests of", "suggesting of",
     "suggested of"),
    ("'If I were you, I ___ talk to your manager.'", "would", "will", "should to",
     "would to"),
    ("'It ___ to me that you need a break.'", "seems", "seem", "seeming of",
     "is seem"),
    ("'Let me know ___ it goes.'", "how", "what", "which", "that"),
    ("'Hope this ___ .'", "helps", "help", "helping of", "is help"),
    ("'Whatever you decide, ___ yourself first.'", "look after",
     "look for", "look of", "look at for"),
    ("Which is warmest in an advice email?", "Whatever happens, I'm here.",
     "Do it or don't.", "Your problem is simple.", "Just fix it."),
]

P7_AC_V = [
    ("fit", "in good physical condition"),
    ("unfit", "in poor physical condition"),
    ("diet", "what a person usually eats"),
    ("nutrition", "the food your body needs to stay well"),
    ("calorie", "a unit of energy in food"),
    ("vitamin", "a substance in food your body needs"),
    ("protein", "the part of food that builds muscle"),
    ("sugar-free", "with no sugar added"),
    ("organic", "grown without chemicals"),
    ("processed", "changed from its natural state in a factory"),
    ("portion", "the amount of food for one person"),
    ("appetite", "the wish to eat"),
    ("overweight", "heavier than is healthy"),
    ("lose weight", "become lighter"),
    ("put on weight", "become heavier"),
    ("energy", "the power to be active"),
    ("stress", "the strain of having too much to deal with"),
    ("relax", "rest and stop being tense"),
    ("sleep pattern", "the way you usually sleep"),
    ("habit", "something you do regularly"),
    ("lifestyle", "the way a person lives"),
    ("cut down on", "do or eat less of something"),
    ("give up", "stop doing something completely"),
    ("take up", "start a new activity"),
    ("keep fit", "stay in good condition"),
]

P7_AC_G = [
    ("This gym is ___ than the old one.", "better", "gooder", "more good",
     "best"),
    ("Walking is ___ than running for your knees.", "safer", "more safe",
     "safest", "more safer"),
    ("It's the ___ exercise I know.", "most effective", "effectivest",
     "more effective", "most effectivest"),
    ("He is ___ person in the team.", "the fittest", "the fitter",
     "the most fit", "fittest"),
    ("Today's class was ___ than yesterday's.", "harder", "more hard",
     "hardest", "more harder"),
    ("Which is correct?", "This is the healthiest option.",
     "This is the most healthy option of all healthiest.",
     "This is healthier option of all.", "This is most healthy option."),
    ("She runs ___ than me.", "faster", "more fast", "fastest", "more faster"),
    ("Her diet is ___ mine.", "better than", "better that", "more good than",
     "the best than"),
    ("This is by far ___ gym in the city.", "the best", "best", "the better",
     "more best"),
    ("Which is WRONG?", "It is more cheaper.", "It is cheaper.",
     "It is much cheaper.", "It is the cheapest."),
    ("I sleep ___ than I used to.", "worse", "badder", "more bad", "worst"),
    ("He's not as fit ___ his brother.", "as", "than", "that", "like"),
    ("This class is ___ more difficult than that one.", "much", "very",
     "so much of", "too much of"),
    ("Swimming is one of ___ sports for your back.", "the best", "best of",
     "the better", "most best"),
    ("The ___ you exercise, the better you feel.", "more", "much", "most",
     "many"),
    ("Which compares three or more?", "It's the most popular class here.",
     "It's more popular than that one.", "It's as popular as that one.",
     "It's popular."),
    ("At the doctor's: 'What seems to be the ___ ?'", "problem", "wrong of",
     "matter of you", "illness of"),
    ("'I've got a ___ in my back.'", "pain", "hurt of", "ache of pain",
     "painful of"),
    ("'How long ___ you been feeling like this?'", "have", "did", "are", "do"),
    ("'Does it ___ when I press here?'", "hurt", "pain", "ache of",
     "hurting of"),
    ("'I'll ___ you some antibiotics.'", "prescribe", "give of recipe",
     "order of", "write of"),
    ("'Take one tablet ___ meals.'", "before", "in front", "ahead of time of",
     "pre of"),
    ("'You should ___ more rest.'", "get", "take of it", "do of", "make of"),
    ("'Come back if it doesn't ___ in a week.'", "improve", "better of",
     "improving of", "improvement of"),
    ("Which is the patient's line?", "I've had a sore throat for three days.",
     "Take this twice a day.", "Let me examine you.",
     "I'll write a prescription."),
]

P7_BD_V = [
    ("in the past", "at an earlier time in history"),
    ("nowadays", "at the present time"),
    ("these days", "in the current period"),
    ("back then", "at that time in the past"),
    ("generation", "all the people born around the same time"),
    ("century", "a period of a hundred years"),
    ("decade", "a period of ten years"),
    ("ancestor", "a member of your family long ago"),
    ("tradition", "a custom passed down over time"),
    ("modern", "of the present time"),
    ("ancient", "from a very long time ago"),
    ("historical", "connected with history"),
    ("invention", "something new that somebody created"),
    ("discovery", "finding something that already existed"),
    ("progress", "movement towards something better"),
    ("change", "become different"),
    ("develop", "grow or improve over time"),
    ("disappear", "stop existing or being seen"),
    ("survive", "continue to live through difficulty"),
    ("improve", "become better"),
    ("old-fashioned", "in a style from the past"),
    ("common", "happening often"),
    ("rare", "not happening often"),
    ("used to", "did regularly in the past but not now"),
    ("no longer", "not any more"),
]

P7_BD_G = [
    ("I ___ play football every day when I was young.", "used to", "use to",
     "am used to", "used"),
    ("She ___ like coffee, but now she loves it.", "didn't use to",
     "didn't used to", "doesn't used to", "wasn't used to"),
    ("___ you use to live here?", "Did", "Do", "Have", "Were"),
    ("People ___ write letters more often.", "used to", "use to", "are used to",
     "were used"),
    ("Which is correct?", "He used to smoke.", "He use to smoke.",
     "He used smoke.", "He is used to smoke."),
    ("Which is WRONG?", "I didn't used to like it.", "I didn't use to like it.",
     "I used to like it.", "Did you use to like it?"),
    ("We ___ have a dog when I was a child.", "used to", "use to", "were used",
     "are used to"),
    ("There ___ be a cinema here.", "used to", "use to", "is used to",
     "was used"),
    ("'Did you use to walk to school?' 'Yes, ___ .'", "I did", "I used",
     "I use", "I was"),
    ("My grandmother ___ tell us stories every evening.", "used to", "use to",
     "is used to", "was use to"),
    ("Which sentence talks about a past habit that has stopped?",
     "I used to cycle to work.", "I am used to cycling to work.",
     "I cycle to work.", "I will cycle to work."),
    ("Which sentence means you are familiar with something?",
     "I'm used to getting up early.", "I used to get up early.",
     "I use to get up early.", "I used get up early."),
    ("People ___ think the earth was flat.", "used to", "use to", "are used to",
     "were use to"),
    ("Life ___ be harder without machines.", "used to", "use to", "is used to",
     "was used"),
    ("He ___ be very shy, but now he's confident.", "used to", "use to",
     "is used to", "was use"),
    ("Which is the negative of 'used to'?", "didn't use to",
     "didn't used to", "don't use to", "wasn't used to"),
    ("A blog article usually opens with ___.", "something that catches attention",
     "your address", "a list of sources", "the word Introduction"),
    ("'In this post I'm going to ___ three simple changes.'", "suggest",
     "suggestion of", "suggesting of", "suggested of"),
    ("'___ , our grandparents ate less sugar.'", "Back then", "Back time of",
     "In back of", "Then back of"),
    ("'The ___ thing is that it costs nothing.'", "best", "most best",
     "goodest", "better of"),
    ("'Give it a ___ for two weeks and see.'", "try", "trial of do", "test of",
     "go of try"),
    ("'What do you ___ ? Leave a comment below.'", "think", "thinking of",
     "thought of", "believe of it"),
    ("Which is a good blog ending?", "Try it this week and tell me how it goes.",
     "This is the end of my article.", "I have written enough.",
     "Thank you for the reading of this."),
    ("'These days people ___ far less than they used to.'", "walk", "walked",
     "are walk", "walking"),
    ("Which sentence mixes past and present well?",
     "People used to cook at home; now they order online.",
     "People used to cook at home; now they used to order online.",
     "People cook at home; now they used to order.",
     "People are used to cook; now they order."),
]

P8_AC_V = [
    ("novel", "a long story in a book"),
    ("author", "the person who wrote a book"),
    ("poet", "somebody who writes poems"),
    ("painting", "a picture made with paint"),
    ("sculpture", "art made by shaping stone or metal"),
    ("gallery", "a place where art is shown"),
    ("exhibition", "a public show of art or objects"),
    ("composer", "somebody who writes music"),
    ("conductor", "the person who leads an orchestra"),
    ("orchestra", "a large group of musicians"),
    ("lyrics", "the words of a song"),
    ("album", "a collection of recorded songs"),
    ("concert", "a live musical performance"),
    ("performance", "the act of playing or acting for an audience"),
    ("actor", "somebody who performs in plays or films"),
    ("director", "the person who guides a film or play"),
    ("audience", "the people watching or listening"),
    ("review", "a written opinion about a work"),
    ("masterpiece", "an artist's greatest work"),
    ("classical", "of the serious European musical tradition"),
    ("portrait", "a picture of a person"),
    ("landscape", "a picture of the countryside"),
    ("chapter", "one part of a book"),
    ("plot", "the story of a book or film"),
    ("character", "a person in a story"),
]

P8_AC_G = [
    ("This bridge ___ in 1935.", "was built", "built", "is built then",
     "was build"),
    ("The paintings ___ every year.", "are shown", "show", "are showing",
     "shows"),
    ("English ___ in many countries.", "is spoken", "speaks", "is speaking",
     "spoken"),
    ("The book ___ by a famous author.", "was written", "wrote", "is writing",
     "was wrote"),
    ("These cars ___ in Japan.", "are made", "make", "are making", "is made"),
    ("Which is passive?", "The song was recorded last year.",
     "They recorded the song last year.", "The song is recording.",
     "Somebody records songs."),
    ("Which is WRONG?", "The museum was build in 1900.",
     "The museum was built in 1900.", "They built the museum in 1900.",
     "The museum is open."),
    ("The concert ___ because of the weather.", "was cancelled", "cancelled",
     "is cancel", "was cancel"),
    ("Millions of copies ___ every year.", "are sold", "sell", "are selling",
     "is sold"),
    ("The film ___ in Uzbekistan.", "was filmed", "filmed", "is filming",
     "was filming"),
    ("Who ___ this picture painted by?", "was", "did", "is", "were"),
    ("The tickets ___ online only.", "are sold", "sell", "are selling",
     "sold"),
    ("When ___ the theatre built?", "was", "did", "is", "were"),
    ("Which sentence keeps the doer unimportant?",
     "The palace was restored last year.",
     "Workers restored the palace last year.",
     "They restored it, the workers.", "Somebody did the restoring."),
    ("The letters ___ by the author's family.", "were kept", "kept",
     "are keeping", "was kept"),
    ("Coffee ___ in Brazil.", "is grown", "grows by", "is growing",
     "grown"),
    ("Keeping a conversation going: 'Really? ___ happened next?'", "What",
     "Which", "That", "How that"),
    ("'That sounds ___ .'", "interesting", "interested", "interest of",
     "interestingly of"),
    ("'___ me more about it.'", "Tell", "Say", "Speak", "Talk of"),
    ("'Mm, I ___ .' 'Do you?'", "see", "seeing", "sees", "am see"),
    ("'And then ___ ?'", "what", "how", "which of", "that"),
    ("'I know what you ___ .'", "mean", "meaning of", "means of", "meant of it"),
    ("Which reply invites the speaker to continue?", "Go on.", "Stop there.",
     "That's enough.", "Anyway, moving on."),
    ("'Anyway, ___ were you saying?'", "what", "which", "that", "how of"),
    ("Which shows you are listening?", "Right, and what did you do then?",
     "Yes.", "Mm.", "I don't care."),
]

P8_BD_V = [
    ("athletics", "the sport of running, jumping and throwing"),
    ("coach", "the person who trains a team"),
    ("opponent", "the person you play against"),
    ("tournament", "a competition with many matches"),
    ("league", "a group of teams that play each other"),
    ("score", "the number of points in a game"),
    ("draw", "a result where neither side wins"),
    ("beat", "defeat somebody"),
    ("defend", "stop the other team scoring"),
    ("injury", "harm to your body"),
    ("training", "regular practice to improve"),
    ("warm up", "prepare your body before exercise"),
    ("fitness", "how healthy and strong you are"),
    ("teammate", "somebody on the same side as you"),
    ("supporter", "somebody who follows a team"),
    ("stadium", "the large ground where matches happen"),
    ("equipment", "the things you need for a sport"),
    ("referee", "the official who applies the rules"),
    ("goalkeeper", "the player who guards the goal"),
    ("captain", "the player who leads the team"),
    ("champion", "the winner of a competition"),
    ("record", "the best result ever achieved"),
    ("amateur", "doing a sport without being paid"),
    ("professional", "doing a sport as a paid job"),
    ("be into", "be very interested in something"),
]

P8_BD_G = [
    ("I've played tennis ___ five years.", "for", "since", "from", "during"),
    ("She's been in the team ___ 2021.", "since", "for", "from", "during"),
    ("We've known each other ___ we were children.", "since", "for", "from",
     "during"),
    ("He's had that bike ___ ages.", "for", "since", "from", "along"),
    ("How long ___ you been training?", "have", "did", "are", "do"),
    ("They ___ won a match this season.", "haven't", "didn't", "don't",
     "aren't"),
    ("Which is correct?", "I have lived here since March.",
     "I have lived here for March.", "I live here since March.",
     "I am living here since March."),
    ("Which is WRONG?", "She has been a member since two years.",
     "She has been a member for two years.",
     "She has been a member since 2022.", "She joined two years ago."),
    ("I ___ him since the tournament.", "haven't seen", "didn't see",
     "don't see", "am not seeing"),
    ("This is the first time I ___ here.", "have been", "was", "am", "been"),
    ("He ___ for the club since he was sixteen.", "has played", "plays since",
     "played since", "is playing since"),
    ("'___ you ever broken a bone?' 'Once.'", "Have", "Did", "Do", "Are"),
    ("We've been waiting ___ half an hour.", "for", "since", "from", "during"),
    ("Which time expression goes with 'since'?", "last Monday", "two hours",
     "a long time", "ages"),
    ("Which time expression goes with 'for'?", "three weeks", "2020",
     "last summer", "I was a child"),
    ("The team ___ much better lately.", "has been playing", "plays since",
     "played since", "is play"),
    ("A book review usually says ___.", "what it is about and whether to read it",
     "only the number of pages", "the price alone", "the author's address"),
    ("'The story is ___ in Tashkent in the 1920s.'", "set", "put of", "placed of",
     "made of"),
    ("'The characters are ___ drawn.'", "well", "good", "goodly of",
     "well of it"),
    ("'I couldn't ___ it down.'", "put", "take", "place of", "leave of"),
    ("'It's a bit ___ in the middle.'", "slow", "slowly", "slowness of",
     "slower of it"),
    ("'I'd ___ it to anyone who likes history.'", "recommend", "advise of",
     "suggest of", "propose of it"),
    ("Which sentence is a criticism?", "The ending felt rushed.",
     "The ending was there.", "The ending ended.", "The ending is an ending."),
    ("'Overall, it's ___ reading.'", "worth", "worthy to", "value of",
     "worthwhile of it"),
    ("Which is the most useful line in a review?",
     "If you enjoyed her first novel, you'll like this one.",
     "I read a book.", "The book has pages.", "Books are good things."),
]

LISTS = [
    ("Unit 5A&C · Vocabulary — work", "vocab", 9, P5_AC_V),
    ("Unit 5A&C · Grammar — must and have to, and apologising", "grammar", 9, P5_AC_G),
    ("Unit 5B&D · Vocabulary — jobs", "vocab", 10, P5_BD_V),
    ("Unit 5B&D · Grammar — will and might, and job adverts", "grammar", 10, P5_BD_G),
    ("Unit 6A&C · Vocabulary — devices", "vocab", 11, P6_AC_V),
    ("Unit 6A&C · Grammar — instructions and advice", "grammar", 11, P6_AC_G),
    ("Unit 6B&D · Vocabulary — -ed and -ing adjectives", "vocab", 12, P6_BD_V),
    ("Unit 6B&D · Grammar — verb patterns, and advice emails", "grammar", 12, P6_BD_G),
    ("Unit 7A&C · Vocabulary — health and fitness", "vocab", 13, P7_AC_V),
    ("Unit 7A&C · Grammar — comparing, and at the doctor", "grammar", 13, P7_AC_G),
    ("Unit 7B&D · Vocabulary — then and now", "vocab", 14, P7_BD_V),
    ("Unit 7B&D · Grammar — used to, and writing a blog", "grammar", 14, P7_BD_G),
    ("Unit 8A&C · Vocabulary — art, music and books", "vocab", 15, P8_AC_V),
    ("Unit 8A&C · Grammar — the passive, and keeping a conversation going", "grammar", 15, P8_AC_G),
    ("Unit 8B&D · Vocabulary — sport", "vocab", 16, P8_BD_V),
    ("Unit 8B&D · Grammar — for and since, and reviews", "grammar", 16, P8_BD_G),
]
