"""Empower Beginner Units 4-6, as Play steps, A / B / C taught separately.

    4A  jobs; present simple - he, she          4C on the phone
    4B  days and times; questions
    5A  family; possessive 's and have got      5C at someone's home
    5B  rooms and furniture; there is / there are
    6A  free time; can and can't                6C making arrangements
    6B  sports and hobbies; how often

A note on where this comes from: Azamat's own Beginner lesson scripts run
from 1A to 3A only, and the Empower Beginner Student's Book is not on this
Mac. Units 1-3 follow his scripts; from Unit 4 the topics and the order
follow the standard A1 progression the book uses. Tell me if a unit sits
somewhere else in your copy and I will re-title and re-step it.

Meanings in Uzbek and Russian.
"""

LEVEL = "Beginner"
BOOK = "Empower Beginner"
PAST_FROM = 9

U4A_V = [
    ("teacher", "o'qituvchi / учитель"),
    ("doctor", "shifokor / врач"),
    ("nurse", "hamshira / медсестра"),
    ("engineer", "muhandis / инженер"),
    ("driver", "haydovchi / водитель"),
    ("waiter", "ofitsiant / официант"),
    ("cook", "oshpaz / повар"),
    ("farmer", "fermer / фермер"),
    ("builder", "quruvchi / строитель"),
    ("shop assistant", "sotuvchi / продавец"),
    ("police officer", "politsiyachi / полицейский"),
    ("student", "talaba / студент"),
    ("manager", "menejer / менеджер"),
    ("accountant", "buxgalter / бухгалтер"),
    ("lawyer", "yurist / юрист"),
    ("dentist", "tish shifokori / стоматолог"),
    ("hairdresser", "sartarosh / парикмахер"),
    ("mechanic", "usta, mexanik / механик"),
    ("journalist", "jurnalist / журналист"),
    ("programmer", "dasturchi / программист"),
    ("office", "ofis / офис"),
    ("factory", "zavod / завод"),
    ("job", "ish o'rni / работа"),
    ("work", "ishlamoq / работать"),
    ("salary", "maosh / зарплата"),
]

U4A_G = [
    ("She ___ in a hospital.", "works", "work", "working", "is work"),
    ("He ___ English.", "teaches", "teach", "teaching", "is teach"),
    ("My father ___ a taxi.", "drives", "drive", "driving", "is drive"),
    ("She ___ work on Sunday.", "doesn't", "don't", "isn't", "not"),
    ("He ___ like his job.", "doesn't", "don't", "isn't", "not"),
    ("___ she work in an office?", "Does", "Do", "Is", "Are"),
    ("___ he a teacher?", "Is", "Does", "Do", "Are"),
    ("A: Does he work here? B: Yes, ___.", "he does", "he do", "he is", "does he"),
    ("A: Does she like it? B: No, ___.", "she doesn't", "she don't", "she isn't", "doesn't she"),
    ("What ___ she do?", "does", "do", "is", "are"),
    ("Where ___ he work?", "does", "do", "is", "are"),
    ("My mother ___ a nurse.", "is", "are", "does", "has"),
    ("He ___ at 8 o'clock every day.", "starts", "start", "starting", "is start"),
    ("She ___ home at 6.", "goes", "go", "going", "is go"),
    ("My brother ___ in a bank.", "works", "work", "working", "are work"),
    ("He ___ his job very much.", "likes", "like", "liking", "is like"),
    ("She ___ English and Russian.", "speaks", "speak", "speaking", "is speak"),
    ("A doctor works in a ___.", "hospital", "school", "factory", "shop"),
    ("A teacher works in a ___.", "school", "hospital", "bank", "cafe"),
    ("He's ___ engineer.", "an", "a", "the", "-"),
    ("She's ___ teacher.", "a", "an", "the", "-"),
    ("What ___ your job?", "is", "are", "does", "do"),
    ("They ___ in a factory.", "work", "works", "working", "is work"),
    ("He ___ very hard.", "works", "work", "working", "are work"),
    ("My sister ___ want to be a doctor.", "doesn't", "don't", "isn't", "not"),
]

U4B_V = [
    ("Monday", "dushanba / понедельник"),
    ("Tuesday", "seshanba / вторник"),
    ("Wednesday", "chorshanba / среда"),
    ("Thursday", "payshanba / четверг"),
    ("Friday", "juma / пятница"),
    ("Saturday", "shanba / суббота"),
    ("Sunday", "yakshanba / воскресенье"),
    ("morning", "ertalab / утро"),
    ("afternoon", "tushdan keyin / день"),
    ("evening", "kechqurun / вечер"),
    ("night", "tun / ночь"),
    ("today", "bugun / сегодня"),
    ("tomorrow", "ertaga / завтра"),
    ("week", "hafta / неделя"),
    ("weekend", "dam olish kunlari / выходные"),
    ("every day", "har kuni / каждый день"),
    ("o'clock", "soat (rosa) / ровно (о времени)"),
    ("half past", "yarim o'tgan / половина"),
    ("quarter past", "chorak o'tgan / четверть после"),
    ("quarter to", "chorak kam / без четверти"),
    ("early", "erta / рано"),
    ("late", "kech / поздно"),
    ("get up", "uyg'onib turmoq / вставать"),
    ("go to bed", "uxlashga yotmoq / ложиться спать"),
    ("start", "boshlamoq / начинать"),
]

U4B_G = [
    ("What time ___ you get up?", "do", "does", "are", "is"),
    ("What time ___ she finish work?", "does", "do", "is", "are"),
    ("When ___ they have lunch?", "do", "does", "is", "are"),
    ("___ you work on Saturday?", "Do", "Does", "Are", "Is"),
    ("I get up ___ 7 o'clock.", "at", "in", "on", "to"),
    ("I work ___ Monday.", "on", "in", "at", "to"),
    ("I study ___ the evening.", "in", "on", "at", "to"),
    ("She works ___ night.", "at", "in", "on", "to"),
    ("It's half ___ six.", "past", "to", "of", "after"),
    ("It's quarter ___ nine. (8:45)", "to", "past", "of", "before"),
    ("I ___ get up early on Sunday.", "don't", "doesn't", "am not", "not"),
    ("He ___ go to work on Friday.", "doesn't", "don't", "isn't", "not"),
    ("How ___ do you go to the gym?", "often", "much", "many", "long"),
    ("I ___ go to bed late.", "never", "not", "no", "don't never"),
    ("She is ___ late for class.", "always", "all time", "every", "much"),
    ("We ___ watch TV in the evening.", "usually", "usual", "usualy", "use"),
    ("___ day do you study?", "Which", "What time", "How", "When"),
    ("I have breakfast ___ 7 and 8.", "between", "from", "in", "on"),
    ("The lesson is ___ 9 to 11.", "from", "at", "in", "on"),
    ("A: What time is it? B: ___ three o'clock.", "It's", "Its", "There's", "That's"),
    ("I'm free ___ the weekend.", "at", "in", "on", "to"),
    ("He works ___ Monday to Friday.", "from", "at", "in", "on"),
    ("She ___ up at six every day.", "gets", "get", "getting", "is get"),
    ("Do you work ___ Sundays?", "on", "in", "at", "to"),
    ("I go to bed ___ eleven.", "at", "in", "on", "to"),
]

U4C_V = [
    ("Hello, this is Azamat", "Allo, bu Azamat / Здравствуйте, это Азамат"),
    ("Can I speak to Sophia?", "Sofiya bilan gaplashsam bo'ladimi? / Можно поговорить с Софией?"),
    ("Who's calling?", "Kim qo'ng'iroq qilyapti? / Кто звонит?"),
    ("Just a minute", "Bir daqiqa / Минутку"),
    ("Hold on, please", "Kutib turing, iltimos / Подождите, пожалуйста"),
    ("She's not here", "U bu yerda yo'q / Её здесь нет"),
    ("Can I leave a message?", "Xabar qoldirsam bo'ladimi? / Можно оставить сообщение?"),
    ("I'll call back later", "Keyinroq qayta qo'ng'iroq qilaman / Я перезвоню позже"),
    ("Sorry, wrong number", "Kechirasiz, noto'g'ri raqam / Извините, неправильный номер"),
    ("What's your number?", "Telefon raqamingiz nima? / Какой у вас номер?"),
    ("Can you repeat that?", "Takrorlay olasizmi? / Можете повторить?"),
    ("Speak slowly, please", "Sekinroq gapiring / Говорите медленнее, пожалуйста"),
    ("I can't hear you", "Sizni eshitmayapman / Я вас не слышу"),
    ("The line is bad", "Aloqa yomon / Плохая связь"),
    ("See you at six", "Soat oltida ko'rishamiz / Увидимся в шесть"),
    ("Are you free tomorrow?", "Ertaga bo'shmisiz? / Вы завтра свободны?"),
    ("I'm busy now", "Hozir bandman / Я сейчас занят"),
    ("What time is good for you?", "Sizga qaysi vaqt qulay? / Во сколько вам удобно?"),
    ("That's fine", "Yaxshi, bo'ladi / Хорошо, подходит"),
    ("Let's meet at the cafe", "Kafeda uchrashaylik / Давайте встретимся в кафе"),
    ("I'm on my way", "Yo'ldaman / Я уже еду"),
    ("Sorry, I'm late", "Kechirasiz, kechikdim / Извините, я опоздал"),
    ("No problem", "Muammo yo'q / Без проблем"),
    ("Thanks for calling", "Qo'ng'iroq uchun rahmat / Спасибо за звонок"),
    ("Talk to you soon", "Tez orada gaplashamiz / До скорого"),
]

U5A_V = [
    ("family", "oila / семья"),
    ("mother", "ona / мать"),
    ("father", "ota / отец"),
    ("parents", "ota-ona / родители"),
    ("sister", "opa-singil / сестра"),
    ("brother", "aka-uka / брат"),
    ("son", "o'g'il / сын"),
    ("daughter", "qiz farzand / дочь"),
    ("children", "bolalar / дети"),
    ("baby", "chaqaloq / младенец"),
    ("husband", "er / муж"),
    ("wife", "xotin / жена"),
    ("grandmother", "buvi / бабушка"),
    ("grandfather", "bobo / дедушка"),
    ("aunt", "xola, amma / тётя"),
    ("uncle", "tog'a, amaki / дядя"),
    ("cousin", "amakivachcha / двоюродный брат"),
    ("friend", "do'st / друг"),
    ("neighbour", "qo'shni / сосед"),
    ("married", "turmush qurgan / женат, замужем"),
    ("single", "yolg'iz, turmush qurmagan / холост, не замужем"),
    ("young", "yosh / молодой"),
    ("old", "keksa / пожилой"),
    ("name", "ism / имя"),
    ("age", "yosh (necha yoshda) / возраст"),
]

U5A_G = [
    ("This is ___ sister.", "my", "me", "mine", "I"),
    ("That's ___ car.", "his", "he", "him", "he's"),
    ("It's ___ book. (she)", "her", "she", "hers", "she's"),
    ("They are ___ parents.", "our", "us", "ours", "we"),
    ("This is Ali___ brother.", "'s", "s", "s'", "es"),
    ("These are my parents___ names.", "'", "'s", "s", "s's"),
    ("I ___ two brothers.", "have got", "has got", "am got", "have get"),
    ("She ___ one sister.", "has got", "have got", "is got", "has get"),
    ("___ you got any children?", "Have", "Has", "Do", "Are"),
    ("___ she got a car?", "Has", "Have", "Does", "Is"),
    ("A: Have you got a brother? B: Yes, ___.", "I have", "I has", "I am", "have I"),
    ("I ___ got a sister.", "haven't", "hasn't", "don't", "am not"),
    ("He ___ got a job.", "hasn't", "haven't", "doesn't", "isn't"),
    ("How ___ brothers have you got?", "many", "much", "long", "old"),
    ("How ___ are you?", "old", "many", "much", "long"),
    ("She ___ 25 years old.", "is", "has", "have", "does"),
    ("My brother's name ___ Bek.", "is", "are", "has", "does"),
    ("___ is your mother?", "Who", "What", "Which", "How"),
    ("My parents ___ in Samarkand.", "live", "lives", "living", "is live"),
    ("My sister ___ in Tashkent.", "lives", "live", "living", "are live"),
    ("This is my friend. ___ name is Malika.", "Her", "She", "Hers", "His"),
    ("Those are ___ books. (they)", "their", "they", "theirs", "them"),
    ("Is this ___ bag? (you)", "your", "you", "yours", "you're"),
    ("My grandmother ___ 80.", "is", "has", "have", "does"),
    ("We ___ got a big family.", "have", "has", "are", "do"),
]

U5B_V = [
    ("house", "uy / дом"),
    ("flat", "kvartira / квартира"),
    ("room", "xona / комната"),
    ("kitchen", "oshxona / кухня"),
    ("bedroom", "yotoqxona / спальня"),
    ("bathroom", "hammom / ванная"),
    ("living room", "mehmonxona / гостиная"),
    ("garden", "bog'cha / сад"),
    ("balcony", "balkon / балкон"),
    ("floor", "qavat / этаж"),
    ("wall", "devor / стена"),
    ("bed", "karavot / кровать"),
    ("sofa", "divan / диван"),
    ("armchair", "kreslo / кресло"),
    ("fridge", "muzlatgich / холодильник"),
    ("cooker", "plita / плита"),
    ("cupboard", "shkaf / шкаф"),
    ("shelf", "javon / полка"),
    ("mirror", "oyna / зеркало"),
    ("carpet", "gilam / ковёр"),
    ("curtains", "parda / шторы"),
    ("lamp", "chiroq / лампа"),
    ("TV", "televizor / телевизор"),
    ("washing machine", "kir yuvish mashinasi / стиральная машина"),
    ("stairs", "zinapoya / лестница"),
]

U5B_G = [
    ("There ___ a sofa in the living room.", "is", "are", "am", "be"),
    ("There ___ two bedrooms.", "are", "is", "am", "be"),
    ("There ___ any chairs here.", "aren't", "isn't", "not are", "no are"),
    ("There ___ a TV in my room.", "isn't", "aren't", "not is", "no is"),
    ("___ there a garden?", "Is", "Are", "Am", "Does"),
    ("___ there any shops near here?", "Are", "Is", "Am", "Does"),
    ("A: Is there a fridge? B: Yes, ___.", "there is", "there's", "it is", "is there"),
    ("A: Are there any beds? B: No, ___.", "there aren't", "there isn't", "they aren't", "no"),
    ("The book is ___ the table.", "on", "in", "at", "to"),
    ("The keys are ___ the bag.", "in", "on", "at", "to"),
    ("The lamp is ___ the bed.", "next to", "next", "near to", "beside of"),
    ("The carpet is ___ the floor.", "on", "in", "at", "under"),
    ("The cat is ___ the table. (below it)", "under", "on", "over", "in"),
    ("There are some pictures ___ the wall.", "on", "in", "at", "to"),
    ("How ___ rooms are there?", "many", "much", "long", "old"),
    ("There is ___ milk in the fridge.", "some", "a", "many", "any"),
    ("There aren't ___ eggs.", "any", "some", "a", "much"),
    ("Is there ___ bread?", "any", "a", "many", "an"),
    ("My flat is ___ the third floor.", "on", "in", "at", "to"),
    ("I live ___ a small flat.", "in", "on", "at", "to"),
    ("The bathroom is ___ the kitchen.", "next to", "next", "near of", "beside to"),
    ("There's a mirror ___ the bathroom.", "in", "on", "at", "to"),
    ("There ___ a big garden behind the house.", "is", "are", "am", "be"),
    ("Where ___ the curtains?", "are", "is", "am", "does"),
    ("There are a lot ___ books on the shelf.", "of", "for", "in", "with"),
]

U5C_V = [
    ("Come in, please", "Kiring, marhamat / Проходите, пожалуйста"),
    ("Make yourself at home", "O'zingizni uyingizdek his qiling / Чувствуйте себя как дома"),
    ("Take a seat", "O'tiring / Присаживайтесь"),
    ("Would you like some tea?", "Choy ichasizmi? / Хотите чаю?"),
    ("Yes, please", "Ha, iltimos / Да, пожалуйста"),
    ("No, thank you", "Yo'q, rahmat / Нет, спасибо"),
    ("Help yourself", "O'zingiz oling / Угощайтесь"),
    ("It's delicious", "Juda mazali / Очень вкусно"),
    ("Can I use your bathroom?", "Hammomdan foydalansam bo'ladimi? / Можно воспользоваться ванной?"),
    ("Of course", "Albatta / Конечно"),
    ("Where's the kitchen?", "Oshxona qayerda? / Где кухня?"),
    ("It's over there", "U ana u yerda / Вон там"),
    ("What a nice flat!", "Qanday chiroyli kvartira! / Какая хорошая квартира!"),
    ("Thanks for coming", "Kelganingiz uchun rahmat / Спасибо, что пришли"),
    ("Thanks for having me", "Chaqirganingiz uchun rahmat / Спасибо за приглашение"),
    ("I must go now", "Endi ketishim kerak / Мне пора идти"),
    ("Stay a bit longer", "Yana biroz o'tiring / Побудьте ещё немного"),
    ("See you soon", "Tez orada ko'rishamiz / До скорой встречи"),
    ("Have a good evening", "Kechangiz xayrli bo'lsin / Хорошего вечера"),
    ("Let me take your coat", "Paltongizni olay / Давайте я возьму ваше пальто"),
    ("Sit down, please", "Marhamat, o'tiring / Садитесь, пожалуйста"),
    ("Do you need anything?", "Sizga biror narsa kerakmi? / Вам что-нибудь нужно?"),
    ("I'm fine, thanks", "Hammasi yaxshi, rahmat / Всё хорошо, спасибо"),
    ("Happy birthday!", "Tug'ilgan kuningiz bilan! / С днём рождения!"),
    ("This is for you", "Bu sizga / Это вам"),
]

U6A_V = [
    ("free time", "bo'sh vaqt / свободное время"),
    ("hobby", "sevimli mashg'ulot / хобби"),
    ("read", "o'qimoq / читать"),
    ("write", "yozmoq / писать"),
    ("draw", "rasm chizmoq / рисовать"),
    ("sing", "qo'shiq aytmoq / петь"),
    ("dance", "raqsga tushmoq / танцевать"),
    ("swim", "suzmoq / плавать"),
    ("run", "yugurmoq / бегать"),
    ("ride a bike", "velosiped haydamoq / кататься на велосипеде"),
    ("drive", "mashina haydamoq / водить машину"),
    ("cook", "taom tayyorlamoq / готовить"),
    ("play the guitar", "gitara chalmoq / играть на гитаре"),
    ("play football", "futbol o'ynamoq / играть в футбол"),
    ("listen to music", "musiqa tinglamoq / слушать музыку"),
    ("watch films", "film ko'rmoq / смотреть фильмы"),
    ("take photos", "surat olmoq / фотографировать"),
    ("go shopping", "xarid qilgani bormoq / ходить по магазинам"),
    ("meet friends", "do'stlar bilan uchrashmoq / встречаться с друзьями"),
    ("travel", "sayohat qilmoq / путешествовать"),
    ("speak English", "ingliz tilida gapirmoq / говорить по-английски"),
    ("use a computer", "kompyuterdan foydalanmoq / пользоваться компьютером"),
    ("relax", "dam olmoq / отдыхать"),
    ("sleep", "uxlamoq / спать"),
    ("go out", "sayr qilgani chiqmoq / выходить куда-то"),
]

U6A_G = [
    ("I ___ swim very well.", "can", "can to", "cans", "am can"),
    ("She ___ drive a car.", "can", "cans", "can to", "is can"),
    ("He ___ speak French.", "can't", "doesn't can", "not can", "cann't"),
    ("___ you play the guitar?", "Can", "Do", "Are", "Does"),
    ("___ she cook?", "Can", "Do", "Is", "Does"),
    ("A: Can you swim? B: Yes, ___.", "I can", "I can swim to", "I am", "can I"),
    ("A: Can he dance? B: No, ___.", "he can't", "he doesn't", "he isn't", "can't he"),
    ("I can ___ English.", "speak", "to speak", "speaking", "speaks"),
    ("She can't ___ a bike.", "ride", "to ride", "riding", "rides"),
    ("We can ___ here.", "sit", "to sit", "sitting", "sits"),
    ("Can I ___ your pen?", "use", "to use", "using", "uses"),
    ("I like ___ books.", "reading", "read", "to reading", "reads"),
    ("She loves ___ to music.", "listening", "listen", "to listening", "listens"),
    ("They enjoy ___ football.", "playing", "play", "to playing", "plays"),
    ("He hates ___ shopping.", "going", "go", "to going", "goes"),
    ("I ___ play chess, but I want to learn.", "can't", "don't can", "not can", "cann't"),
    ("My sister can ___ very well.", "sing", "to sing", "singing", "sings"),
    ("___ they speak Russian?", "Can", "Do they can", "Are", "Does"),
    ("I can't ___ you. Speak louder.", "hear", "to hear", "hearing", "hears"),
    ("We can meet ___ Saturday.", "on", "in", "at", "to"),
    ("He can play the ___.", "piano", "a piano", "pianos", "piano's"),
    ("I go ___ every weekend.", "swimming", "swim", "to swimming", "swims"),
    ("She's good ___ cooking.", "at", "in", "on", "with"),
    ("I'm not very good ___ football.", "at", "in", "on", "with"),
    ("Can you help me, ___?", "please", "pleasing", "to please", "pleased"),
]

U6B_V = [
    ("football", "futbol / футбол"),
    ("basketball", "basketbol / баскетбол"),
    ("volleyball", "voleybol / волейбол"),
    ("tennis", "tennis / теннис"),
    ("swimming", "suzish / плавание"),
    ("running", "yugurish / бег"),
    ("cycling", "velosport / велоспорт"),
    ("chess", "shaxmat / шахматы"),
    ("boxing", "boks / бокс"),
    ("wrestling", "kurash / борьба"),
    ("team", "jamoa / команда"),
    ("player", "o'yinchi / игрок"),
    ("match", "o'yin, uchrashuv / матч"),
    ("win", "yutmoq / выигрывать"),
    ("lose", "yutqazmoq / проигрывать"),
    ("gym", "sport zali / спортзал"),
    ("stadium", "stadion / стадион"),
    ("always", "doim / всегда"),
    ("usually", "odatda / обычно"),
    ("often", "tez-tez / часто"),
    ("sometimes", "ba'zan / иногда"),
    ("never", "hech qachon / никогда"),
    ("once a week", "haftada bir marta / раз в неделю"),
    ("twice a week", "haftada ikki marta / дважды в неделю"),
    ("every weekend", "har dam olish kunlari / каждые выходные"),
]

U6B_G = [
    ("I ___ play football on Sunday.", "always", "am always", "always am", "the always"),
    ("She ___ late.", "is never", "never is", "is not never", "never"),
    ("We ___ go to the gym.", "sometimes", "sometime", "some time", "the sometimes"),
    ("He ___ watches TV in the evening.", "usually", "usual", "is usually watch", "usualy"),
    ("How ___ do you play tennis?", "often", "much", "many", "long"),
    ("I play football ___ a week.", "twice", "two", "two time", "second"),
    ("She goes swimming ___ Mondays.", "on", "in", "at", "to"),
    ("They ___ to the stadium every weekend.", "go", "goes", "going", "are go"),
    ("My brother ___ football very well.", "plays", "play", "playing", "is play"),
    ("We ___ basketball on Fridays.", "play", "plays", "playing", "are play"),
    ("I ___ go to the gym. I don't like it.", "never", "not", "no", "don't never"),
    ("___ do you go running?", "How often", "How much", "How many", "How long"),
    ("Our team ___ the match.", "won't lose", "don't lose", "doesn't lost", "not lose"),
    ("He is a good ___.", "player", "play", "playing", "plays"),
    ("She plays ___ tennis.", "-", "the", "a", "an"),
    ("He plays ___ guitar.", "the", "-", "a", "an"),
    ("I go ___ every morning.", "running", "run", "to running", "runs"),
    ("Do you ___ do sport?", "ever", "never", "always not", "sometime"),
    ("I'm ___ tired after the match.", "always", "all ways", "the always", "always the"),
    ("We ___ win, but we enjoy it.", "don't always", "always don't", "not always do", "always not"),
    ("She goes to the gym ___ a week.", "three times", "three time", "third time", "three"),
    ("Our lessons ___ at nine.", "start", "starts", "starting", "are start"),
    ("He ___ plays chess with his father.", "often", "oftenly", "the often", "often the"),
    ("They ___ never late.", "are", "is", "do", "have"),
    ("I ___ have time at the weekend.", "usually", "usual", "am usually", "usualy"),
]

U6C_V = [
    ("What are you doing tonight?", "Bugun kechqurun nima qilasiz? / Что делаешь сегодня вечером?"),
    ("Are you free on Saturday?", "Shanbada bo'shmisiz? / Ты свободен в субботу?"),
    ("Would you like to come?", "Kelishni xohlaysizmi? / Хочешь прийти?"),
    ("Let's go to the cinema", "Kinoga boraylik / Пойдём в кино"),
    ("Good idea!", "Zo'r fikr! / Хорошая идея!"),
    ("Sounds great", "Ajoyib eshitilyapti / Звучит отлично"),
    ("Sorry, I can't", "Kechirasiz, bo'lmaydi / Извини, не могу"),
    ("Maybe another time", "Balki boshqa safar / Может, в другой раз"),
    ("What time shall we meet?", "Soat nechada uchrashamiz? / Во сколько встретимся?"),
    ("Where shall we meet?", "Qayerda uchrashamiz? / Где встретимся?"),
    ("Let's meet at seven", "Yettida uchrashaylik / Давай встретимся в семь"),
    ("In front of the cinema", "Kinoteatr oldida / Перед кинотеатром"),
    ("See you there", "O'sha yerda ko'rishamiz / Увидимся там"),
    ("I'll be there", "Men boraman / Я буду там"),
    ("Don't be late", "Kechikmang / Не опаздывай"),
    ("I'm busy on Friday", "Jumada bandman / В пятницу я занят"),
    ("How about Sunday?", "Yakshanba-chi? / А как насчёт воскресенья?"),
    ("That works for me", "Menga to'g'ri keladi / Мне подходит"),
    ("Can we make it later?", "Kechroq qilsak bo'ladimi? / Можно попозже?"),
    ("I'd love to", "Juda xursand bo'lardim / С удовольствием"),
    ("Who else is coming?", "Yana kim keladi? / Кто ещё придёт?"),
    ("Let's take a taxi", "Taksi olaylik / Давай возьмём такси"),
    ("It starts at eight", "U sakkizda boshlanadi / Начинается в восемь"),
    ("I'm looking forward to it", "Intiqlik bilan kutyapman / С нетерпением жду"),
    ("Text me later", "Keyinroq yozing / Напиши мне позже"),
]

LISTS = [
    ("Unit 4A · Vocabulary — jobs", "vocab", 16, U4A_V),
    ("Unit 4A · Grammar — present simple: he, she", "grammar", 17, U4A_G),
    ("Unit 4B · Vocabulary — days and times", "vocab", 18, U4B_V),
    ("Unit 4B · Grammar — questions and the time", "grammar", 19, U4B_G),
    ("Unit 4C · Everyday English — on the phone", "vocab", 20, U4C_V),
    ("Unit 5A · Vocabulary — family", "vocab", 21, U5A_V),
    ("Unit 5A · Grammar — possessives and have got", "grammar", 22, U5A_G),
    ("Unit 5B · Vocabulary — rooms and furniture", "vocab", 23, U5B_V),
    ("Unit 5B · Grammar — there is and there are", "grammar", 24, U5B_G),
    ("Unit 5C · Everyday English — at someone's home", "vocab", 25, U5C_V),
    ("Unit 6A · Vocabulary — free time", "vocab", 26, U6A_V),
    ("Unit 6A · Grammar — can and can't", "grammar", 27, U6A_G),
    ("Unit 6B · Vocabulary — sport and how often", "vocab", 28, U6B_V),
    ("Unit 6B · Grammar — how often, word order", "grammar", 29, U6B_G),
    ("Unit 6C · Everyday English — making plans", "vocab", 30, U6C_V),
]
