"""Pre-Intermediate vocabulary, Units 7-12, with Uzbek and Russian meanings."""

LEVEL = "Pre-Intermediate"
BOOK = "Empower Pre-Intermediate"
PAST_FROM = 1

V7_AC = [
    ("fit", "sog'lom va baquvvat / в хорошей форме"),
    ("unfit", "chiniqmagan / не в форме"),
    ("diet", "parhez, ovqatlanish tartibi / питание, диета"),
    ("nutrition", "ozuqaviylik / питание"),
    ("calorie", "kaloriya / калория"),
    ("vitamin", "vitamin / витамин"),
    ("protein", "oqsil / белок"),
    ("sugar-free", "shakarsiz / без сахара"),
    ("organic", "organik / органический"),
    ("processed", "qayta ishlangan / обработанный"),
    ("portion", "bir kishilik ulush / порция"),
    ("appetite", "ishtaha / аппетит"),
    ("overweight", "ortiqcha vaznli / с лишним весом"),
    ("lose weight", "vazn tashlamoq / худеть"),
    ("put on weight", "vazn olmoq / полнеть"),
    ("energy", "quvvat / энергия"),
    ("stress", "ruhiy zo'riqish / стресс"),
    ("relax", "dam olmoq / расслабляться"),
    ("sleep pattern", "uyqu tartibi / режим сна"),
    ("habit", "odat / привычка"),
    ("lifestyle", "turmush tarzi / образ жизни"),
    ("cut down on", "kamaytirmoq / сокращать"),
    ("give up", "butunlay tashlamoq / бросать"),
    ("take up", "shug'ullana boshlamoq / начинать заниматься"),
    ("keep fit", "formani saqlamoq / поддерживать форму"),
]

V7_BD = [
    ("in the past", "o'tmishda / в прошлом"),
    ("nowadays", "hozirgi kunda / в наши дни"),
    ("these days", "shu kunlarda / в эти дни"),
    ("back then", "o'sha paytda / тогда"),
    ("generation", "avlod / поколение"),
    ("century", "asr / век"),
    ("decade", "o'n yillik / десятилетие"),
    ("ancestor", "ajdod / предок"),
    ("tradition", "an'ana / традиция"),
    ("modern", "zamonaviy / современный"),
    ("ancient", "qadimiy / древний"),
    ("historical", "tarixiy / исторический"),
    ("invention", "ixtiro / изобретение"),
    ("discovery", "kashfiyot / открытие"),
    ("progress", "taraqqiyot / прогресс"),
    ("change", "o'zgarmoq / меняться"),
    ("develop", "rivojlanmoq / развиваться"),
    ("disappear", "yo'qolmoq / исчезать"),
    ("survive", "omon qolmoq / выживать"),
    ("improve", "yaxshilanmoq / улучшаться"),
    ("old-fashioned", "eskicha / старомодный"),
    ("common", "keng tarqalgan / распространённый"),
    ("rare", "kam uchraydigan / редкий"),
    ("used to", "ilgari qilardi / раньше делал"),
    ("no longer", "endi emas / больше не"),
]

V8_AC = [
    ("novel", "roman / роман"),
    ("author", "muallif / автор"),
    ("poet", "shoir / поэт"),
    ("painting", "kartina / картина"),
    ("sculpture", "haykal / скульптура"),
    ("gallery", "galereya / галерея"),
    ("exhibition", "ko'rgazma / выставка"),
    ("composer", "bastakor / композитор"),
    ("conductor", "dirijyor / дирижёр"),
    ("orchestra", "orkestr / оркестр"),
    ("lyrics", "qo'shiq matni / текст песни"),
    ("album", "albom / альбом"),
    ("concert", "konsert / концерт"),
    ("performance", "chiqish / выступление"),
    ("actor", "aktyor / актёр"),
    ("director", "rejissyor / режиссёр"),
    ("audience", "tomoshabinlar / зрители"),
    ("review", "taqriz / рецензия"),
    ("masterpiece", "shoh asar / шедевр"),
    ("classical", "klassik / классический"),
    ("portrait", "portret / портрет"),
    ("landscape", "manzara rasmi / пейзаж"),
    ("chapter", "bob / глава"),
    ("plot", "syujet / сюжет"),
    ("character", "qahramon / персонаж"),
]

V8_BD = [
    ("athletics", "yengil atletika / лёгкая атлетика"),
    ("coach", "murabbiy / тренер"),
    ("opponent", "raqib / соперник"),
    ("tournament", "turnir / турнир"),
    ("league", "liga / лига"),
    ("score", "hisob / счёт"),
    ("draw", "durang / ничья"),
    ("beat", "yutmoq, mag'lub etmoq / побеждать"),
    ("defend", "himoya qilmoq / защищать"),
    ("injury", "jarohat / травма"),
    ("training", "mashg'ulot / тренировка"),
    ("warm up", "qizdirish mashqlari / разминка"),
    ("fitness", "jismoniy tayyorgarlik / физическая форма"),
    ("teammate", "jamoadosh / товарищ по команде"),
    ("supporter", "muxlis / болельщик"),
    ("stadium", "stadion / стадион"),
    ("equipment", "jihozlar / снаряжение"),
    ("referee", "hakam / судья"),
    ("goalkeeper", "darvozabon / вратарь"),
    ("captain", "jamoa sardori / капитан"),
    ("champion", "chempion / чемпион"),
    ("record", "rekord / рекорд"),
    ("amateur", "havaskor / любитель"),
    ("professional", "professional / профессионал"),
    ("be into", "qiziqmoq / увлекаться"),
]

V9_AC = [
    ("ingredient", "masalliq / ингредиент"),
    ("recipe", "retsept / рецепт"),
    ("bake", "pishirmoq (duxovkada) / печь"),
    ("roast", "qovurmoq (duxovkada) / жарить в духовке"),
    ("grill", "panjarada pishirmoq / готовить на гриле"),
    ("boil", "qaynatmoq / варить"),
    ("fry", "yog'da qovurmoq / жарить"),
    ("steam", "bug'da pishirmoq / готовить на пару"),
    ("chop", "maydalab to'g'ramoq / рубить"),
    ("slice", "yupqa to'g'ramoq / нарезать ломтиками"),
    ("peel", "po'stini archmoq / чистить"),
    ("stir", "aralashtirmoq / помешивать"),
    ("mix", "qo'shib aralashtirmoq / смешивать"),
    ("season", "ziravor qo'shmoq / приправлять"),
    ("serve", "dasturxonga tortmoq / подавать"),
    ("dish", "taom / блюдо"),
    ("starter", "birinchi taom / закуска"),
    ("main course", "asosiy taom / основное блюдо"),
    ("side dish", "garnir / гарнир"),
    ("leftovers", "ortib qolgan ovqat / остатки еды"),
    ("tasty", "mazali / вкусный"),
    ("bland", "bemaza / пресный"),
    ("homemade", "uyda tayyorlangan / домашний"),
    ("takeaway", "olib ketiladigan ovqat / еда навынос"),
    ("vegetarian", "vegetarian / вегетарианский"),
]

V9_BD = [
    ("fame", "shuhrat / слава"),
    ("privacy", "shaxsiy hayot daxlsizligi / личное пространство"),
    ("pressure", "bosim / давление"),
    ("paparazzi", "papparatsi / папарацци"),
    ("rumour", "mish-mish / слух"),
    ("scandal", "janjal, mojaro / скандал"),
    ("interview", "intervyu / интервью"),
    ("fan", "muxlis / поклонник"),
    ("talent", "iste'dod / талант"),
    ("career", "karyera / карьера"),
    ("success", "muvaffaqiyat / успех"),
    ("failure", "muvaffaqiyatsizlik / неудача"),
    ("achievement", "yutuq / достижение"),
    ("opportunity", "imkoniyat / возможность"),
    ("motivation", "turtki / мотивация"),
    ("confidence", "ishonch / уверенность"),
    ("criticism", "tanqid / критика"),
    ("praise", "maqtov / похвала"),
    ("role model", "ibrat bo'ladigan shaxs / пример для подражания"),
    ("lifestyle", "turmush tarzi / образ жизни"),
    ("earn", "topmoq / зарабатывать"),
    ("deserve", "loyiq bo'lmoq / заслуживать"),
    ("cope with", "uddasidan chiqmoq / справляться"),
    ("give up", "voz kechmoq / сдаваться"),
    ("take up", "boshlamoq / браться за"),
]

V10_AC = [
    ("look after", "qaramoq / присматривать"),
    ("look for", "izlamoq / искать"),
    ("look into", "tekshirmoq / разбираться"),
    ("look up", "qidirib topmoq / искать в справочнике"),
    ("take off", "yechmoq / снимать"),
    ("take back", "qaytarib bermoq / возвращать"),
    ("take over", "nazoratni olmoq / брать под контроль"),
    ("put off", "keyinga surmoq / откладывать"),
    ("put up with", "chidamoq / мириться с"),
    ("give back", "qaytarmoq / отдавать"),
    ("give in", "taslim bo'lmoq / уступать"),
    ("get on with", "chiqishmoq / ладить"),
    ("get over", "o'zini o'nglamoq / преодолевать"),
    ("get rid of", "qutulmoq / избавляться"),
    ("turn down", "rad etmoq / отклонять"),
    ("turn up", "kelib qolmoq / появляться"),
    ("run out of", "tugab qolmoq / заканчиваться"),
    ("come across", "tasodifan topmoq / наткнуться"),
    ("bring up", "tarbiyalamoq / воспитывать"),
    ("work out", "hisoblamoq, mashq qilmoq / вычислять, тренироваться"),
    ("carry on", "davom ettirmoq / продолжать"),
    ("set off", "yo'lga chiqmoq / отправляться"),
    ("sort out", "hal qilmoq / улаживать"),
    ("deal with", "shug'ullanmoq / разбираться с"),
    ("find out", "bilib olmoq / выяснять"),
]

V10_BD = [
    ("bargain", "arzonga olingan narsa / выгодная покупка"),
    ("brand", "brend / бренд"),
    ("customer service", "mijozlarga xizmat / обслуживание клиентов"),
    ("delivery", "yetkazib berish / доставка"),
    ("faulty", "nuqsonli / бракованный"),
    ("guarantee", "kafolat / гарантия"),
    ("purchase", "xarid / покупка"),
    ("queue", "navbat / очередь"),
    ("refund", "pul qaytarish / возврат средств"),
    ("stock", "do'kondagi tovar / товарный запас"),
    ("out of stock", "tugagan / нет в наличии"),
    ("trolley", "arava / тележка"),
    ("receipt", "chek / чек"),
    ("checkout", "kassa / касса"),
    ("online shopping", "onlayn xarid / покупки онлайн"),
    ("special offer", "maxsus taklif / специальное предложение"),
    ("advertisement", "reklama / реклама"),
    ("consumer", "iste'molchi / потребитель"),
    ("value for money", "puliga arziydigan / стоит своих денег"),
    ("second-hand", "ishlatilgan / подержанный"),
    ("shopping list", "xaridlar ro'yxati / список покупок"),
    ("spend", "sarflamoq / тратить"),
    ("save up", "pul yig'moq / копить"),
    ("afford", "sotib olishga qurbi yetmoq / позволить себе"),
    ("waste", "behuda sarflamoq / тратить впустую"),
]

V11_AC = [
    ("traffic jam", "tirbandlik / пробка"),
    ("rush hour", "eng gavjum soat / час пик"),
    ("car park", "avtoturargoh / парковка"),
    ("city centre", "shahar markazi / центр города"),
    ("railway station", "temir yo'l vokzali / вокзал"),
    ("bus stop", "avtobus bekati / автобусная остановка"),
    ("post office", "pochta bo'limi / почта"),
    ("police station", "politsiya bo'limi / отделение полиции"),
    ("shopping centre", "savdo markazi / торговый центр"),
    ("swimming pool", "suzish havzasi / бассейн"),
    ("football pitch", "futbol maydoni / футбольное поле"),
    ("credit card", "kredit kartasi / кредитная карта"),
    ("mobile phone", "uyali telefon / мобильный телефон"),
    ("text message", "SMS xabar / смс-сообщение"),
    ("headache", "bosh og'rig'i / головная боль"),
    ("sunglasses", "quyosh ko'zoynagi / солнечные очки"),
    ("toothbrush", "tish cho'tkasi / зубная щётка"),
    ("newspaper", "gazeta / газета"),
    ("timetable", "jadval / расписание"),
    ("alarm clock", "budilnik / будильник"),
    ("washing machine", "kir yuvish mashinasi / стиральная машина"),
    ("living room", "mehmonxona / гостиная"),
    ("dining room", "ovqatlanish xonasi / столовая"),
    ("homework", "uy vazifasi / домашнее задание"),
    ("weekend", "dam olish kunlari / выходные"),
]

V11_BD = [
    ("luck", "omad / удача"),
    ("lucky", "omadli / везучий"),
    ("unlucky", "omadsiz / невезучий"),
    ("chance", "imkoniyat, ehtimol / шанс"),
    ("coincidence", "tasodif / совпадение"),
    ("fortunately", "yaxshiyamki / к счастью"),
    ("unfortunately", "afsuski / к сожалению"),
    ("by chance", "tasodifan / случайно"),
    ("on purpose", "atayin / нарочно"),
    ("luckily", "baxtga qarshi yaxshi / по счастью"),
    ("miss out on", "imkoniyatni boy bermoq / упустить"),
    ("opportunity", "qulay imkoniyat / возможность"),
    ("risk", "xavf / риск"),
    ("take a risk", "tavakkal qilmoq / рисковать"),
    ("succeed", "erishmoq / добиваться успеха"),
    ("fail", "uddalay olmaslik / терпеть неудачу"),
    ("win", "yutmoq / выигрывать"),
    ("lose", "yutqazmoq / проигрывать"),
    ("prize", "sovrin / приз"),
    ("lottery", "lotereya / лотерея"),
    ("guess", "taxmin qilmoq / угадывать"),
    ("predict", "bashorat qilmoq / предсказывать"),
    ("certain", "aniq ishonchli / уверенный"),
    ("probably", "ehtimol / вероятно"),
    ("possibly", "balki / возможно"),
]

V12_AC = [
    ("relative", "qarindosh / родственник"),
    ("generation", "avlod / поколение"),
    ("ancestor", "ajdod / предок"),
    ("cousin", "amaki yoki xola bolasi / двоюродный брат или сестра"),
    ("niece", "jiyan qiz / племянница"),
    ("nephew", "jiyan o'g'il / племянник"),
    ("in-laws", "qaynona-qaynotalar / родня супруга"),
    ("grandchild", "nabira / внук"),
    ("adopt", "farzandlikka olmoq / усыновлять"),
    ("inherit", "meros olmoq / наследовать"),
    ("resemble", "o'xshamoq / быть похожим"),
    ("take after", "kattalarga o'xshamoq / пойти в кого-то"),
    ("bring up", "tarbiyalamoq / воспитывать"),
    ("get married", "turmush qurmoq / жениться, выходить замуж"),
    ("get divorced", "ajrashmoq / разводиться"),
    ("argue", "janjallashmoq / спорить"),
    ("make up", "yarashmoq / мириться"),
    ("support", "qo'llab-quvvatlamoq / поддерживать"),
    ("close", "yaqin / близкий"),
    ("distant", "uzoq / дальний"),
    ("family tree", "nasabnoma / родословная"),
    ("only child", "yolg'iz farzand / единственный ребёнок"),
    ("twin", "egizak / близнец"),
    ("household", "bir uydagilar / домохозяйство"),
    ("upbringing", "tarbiya / воспитание"),
]

V12_BD = [
    ("news report", "yangiliklar reportaji / новостной репортаж"),
    ("headline", "sarlavha / заголовок"),
    ("journalist", "jurnalist / журналист"),
    ("witness", "guvoh / свидетель"),
    ("source", "manba / источник"),
    ("evidence", "dalil / доказательство"),
    ("investigate", "tergov qilmoq / расследовать"),
    ("announce", "e'lon qilmoq / объявлять"),
    ("claim", "da'vo qilmoq / утверждать"),
    ("deny", "rad etmoq / отрицать"),
    ("admit", "tan olmoq / признавать"),
    ("report", "xabar bermoq / сообщать"),
    ("broadcast", "efirga uzatmoq / транслировать"),
    ("update", "yangilangan ma'lumot / обновление"),
    ("rumour", "mish-mish / слух"),
    ("front page", "birinchi sahifa / первая полоса"),
    ("article", "maqola / статья"),
    ("editor", "muharrir / редактор"),
    ("interview", "suhbat / интервью"),
    ("statement", "bayonot / заявление"),
    ("emergency", "favqulodda holat / чрезвычайная ситуация"),
    ("rescue", "qutqarmoq / спасать"),
    ("injured", "jarohatlangan / раненый"),
    ("survivor", "omon qolgan / выживший"),
    ("eyewitness", "voqea guvohi / очевидец"),
]

LISTS = [
    ("Unit 7A&C · Vocabulary — health and fitness", "vocab", 13, V7_AC),
    ("Unit 7B&D · Vocabulary — then and now", "vocab", 14, V7_BD),
    ("Unit 8A&C · Vocabulary — art, music and books", "vocab", 15, V8_AC),
    ("Unit 8B&D · Vocabulary — sport", "vocab", 16, V8_BD),
    ("Unit 9A&C · Vocabulary — cooking and eating", "vocab", 17, V9_AC),
    ("Unit 9B&D · Vocabulary — fame and success", "vocab", 18, V9_BD),
    ("Unit 10A&C · Vocabulary — multi-word verbs", "vocab", 19, V10_AC),
    ("Unit 10B&D · Vocabulary — shopping", "vocab", 20, V10_BD),
    ("Unit 11A&C · Vocabulary — compound nouns", "vocab", 21, V11_AC),
    ("Unit 11B&D · Vocabulary — luck and chance", "vocab", 22, V11_BD),
    ("Unit 12A&C · Vocabulary — family", "vocab", 23, V12_AC),
    ("Unit 12B&D · Vocabulary — the news", "vocab", 24, V12_BD),
]
