"""Empower Intermediate Units 5-7, in the A&C / B&D pairing.

    5A environment; future forms          5C talking about problems
    5B the natural world; zero and first conditionals   5D a news report
    6A compound nouns; modals of obligation  6C asking for and offering
    6B describing food; comparatives and superlatives  6D places you go
    7A buildings; modals of deduction     7C visiting people
    7B verbs and prepositions; quantifiers  7D a recent holiday
"""

LEVEL = "Intermediate"
BOOK = "Empower Intermediate"
PAST_FROM = 1

I5_AC_V = [
    ("pollution", "ifloslanish / загрязнение"),
    ("climate change", "iqlim o'zgarishi / изменение климата"),
    ("global warming", "global isish / глобальное потепление"),
    ("recycling", "qayta ishlash / переработка"),
    ("waste", "chiqindi / отходы"),
    ("litter", "ko'cha axlati / мусор"),
    ("renewable", "qayta tiklanadigan / возобновляемый"),
    ("solar power", "quyosh energiyasi / солнечная энергия"),
    ("wind farm", "shamol elektr stansiyasi / ветропарк"),
    ("fossil fuel", "qazilma yoqilg'i / ископаемое топливо"),
    ("emissions", "chiqindi gazlar / выбросы"),
    ("carbon footprint", "uglerod izi / углеродный след"),
    ("deforestation", "o'rmonlarning kesilishi / вырубка лесов"),
    ("endangered", "yo'qolib ketish xavfidagi / под угрозой исчезновения"),
    ("conservation", "muhofaza qilish / охрана природы"),
    ("sustainable", "barqaror / устойчивый"),
    ("energy-efficient", "energiya tejamkor / энергоэффективный"),
    ("plastic-free", "plastiksiz / без пластика"),
    ("drought", "qurg'oqchilik / засуха"),
    ("flooding", "suv bosishi / затопление"),
    ("environmentalist", "ekolog faol / эколог"),
    ("protect", "himoya qilmoq / защищать"),
    ("reduce", "kamaytirmoq / сокращать"),
    ("reuse", "qayta ishlatmoq / использовать повторно"),
    ("throw away", "tashlab yubormoq / выбрасывать"),
]

I5_AC_G = [
    ("I ___ visit my cousin tomorrow. It's arranged.", "am visiting",
     "will visit surely", "visit", "am visit"),
    ("Look at the sky! It ___ rain.", "is going to", "will", "goes to",
     "going to"),
    ("The train ___ at 6.15.", "leaves", "is leaving always", "will leave",
     "leave"),
    ("I think prices ___ next year.", "will rise", "are rising then",
     "rise will", "will to rise"),
    ("We ___ discuss this at the meeting on Monday.", "are going to",
     "will going to", "go to", "are go to"),
    ("This time next week I ___ on a beach.", "will be lying", "will lie then",
     "am lying then", "will be lie"),
    ("By 2030 they ___ the new line.", "will have finished",
     "will finish already by then", "finish", "are finishing"),
    ("Which shows a prediction based on evidence?", "She's going to win.",
     "She will win, I think.", "She wins.", "She is winning always."),
    ("Which shows an arrangement?", "I'm meeting the team at four.",
     "I'll meet the team at four.", "I meet the team at four.",
     "I am meet the team at four."),
    ("Which is WRONG?", "I will to call you tomorrow.",
     "I'll call you tomorrow.", "I'm calling you tomorrow.",
     "I'm going to call you tomorrow."),
    ("___ you be at home this evening?", "Will", "Do", "Are going", "Shall"),
    ("Perhaps we ___ take the bus.", "will", "shall of", "are will",
     "do will"),
    ("The conference ___ place in June.", "takes", "is taking place always",
     "will taking", "take"),
    ("If nothing changes, the situation ___ worse.", "will get",
     "gets will", "is getting then", "will to get"),
    ("Which is a spontaneous decision?", "I'll get it!",
     "I'm getting it, it's arranged.", "I get it.", "I am going to get it."),
    ("They ___ move abroad next year. They've already sold the house.",
     "are going to", "will maybe", "go to", "are go"),
    ("Talking about a problem: 'Something needs ___ about it.'",
     "doing", "to doing", "do", "done of"),
    ("'We should ___ action before it's too late.'", "take", "make", "do",
     "give of"),
    ("'The main ___ is plastic.'", "issue", "issues of it", "issued of",
     "issuing of"),
    ("'It's having a serious ___ on wildlife.'", "effect", "affect",
     "effecting of", "affection of"),
    ("'We could at least ___ down on packaging.'", "cut", "take", "put",
     "give of"),
    ("'That would make a real ___ .'", "difference", "different of",
     "differ of", "differently of"),
    ("'What ___ be done?'", "can", "could to", "is can", "do can"),
    ("'If everyone did a little, it ___ add up.'", "would", "will", "would to",
     "does"),
    ("Which sentence proposes a practical step?",
     "We could start by collecting the plastic in the school yard.",
     "Pollution is bad.", "Somebody should do something.",
     "The world has problems."),
]

I5_BD_V = [
    ("wildlife", "yovvoyi tabiat / дикая природа"),
    ("species", "tur / вид"),
    ("habitat", "yashash muhiti / среда обитания"),
    ("rainforest", "tropik o'rmon / тропический лес"),
    ("desert", "cho'l / пустыня"),
    ("glacier", "muzlik / ледник"),
    ("coral reef", "marjon rifi / коралловый риф"),
    ("ocean", "okean / океан"),
    ("soil", "tuproq / почва"),
    ("crop", "ekin / урожай"),
    ("harvest", "hosil yig'imi / сбор урожая"),
    ("predator", "yirtqich / хищник"),
    ("insect", "hasharot / насекомое"),
    ("mammal", "sut emizuvchi / млекопитающее"),
    ("reptile", "sudralib yuruvchi / рептилия"),
    ("extinct", "yo'q bo'lib ketgan / вымерший"),
    ("survive", "omon qolmoq / выживать"),
    ("migrate", "ko'chib o'tmoq / мигрировать"),
    ("breed", "ko'paymoq / размножаться"),
    ("hunt", "ov qilmoq / охотиться"),
    ("landscape", "tabiat manzarasi / ландшафт"),
    ("volcano", "vulqon / вулкан"),
    ("earthquake", "zilzila / землетрясение"),
    ("shore", "qirg'oq / берег"),
    ("stream", "soy / ручей"),
]

I5_BD_G = [
    ("If you heat ice, it ___ .", "melts", "will melt then", "melt",
     "is melting"),
    ("If it ___ tomorrow, we'll cancel the trip.", "rains", "will rain",
     "rained", "is raining then"),
    ("Plants die if they ___ water.", "don't get", "won't get", "didn't get",
     "aren't getting"),
    ("We'll miss the bus if we ___ now.", "don't leave", "won't leave",
     "didn't leave", "aren't leave"),
    ("If you ___ this button, the machine stops.", "press", "will press",
     "pressed", "are pressing"),
    ("Which is the zero conditional?", "If you mix blue and yellow, you get green.",
     "If you mix them, you will get green paint tomorrow.",
     "If you mixed them, you would get green.",
     "If you had mixed them, you would have got green."),
    ("Which is the first conditional?", "If it snows, we'll stay at home.",
     "If it snows, we stay at home every year.",
     "If it snowed, we would stay.", "If it had snowed, we would have stayed."),
    ("Which is WRONG?", "If it will rain, we'll go inside.",
     "If it rains, we'll go inside.", "We'll go inside if it rains.",
     "If it rains, we go inside every time."),
    ("She won't pass ___ she studies.", "unless", "if not of", "except of",
     "without that"),
    ("Water boils ___ you heat it to 100 degrees.", "when", "will when",
     "unless", "if not"),
    ("If the temperature ___ , the ice melts.", "rises", "will rise", "rose",
     "is rise"),
    ("I'll call you as soon as I ___ .", "arrive", "will arrive", "arrived",
     "am arriving then"),
    ("Don't touch it ___ it's cool.", "until", "since", "while of",
     "by the time of"),
    ("If we don't act, the species ___ .", "will disappear", "disappears will",
     "would disappear", "disappeared"),
    ("Which half never takes 'will'?", "the if half", "the result half",
     "both halves", "neither half"),
    ("If you ___ a plant in the dark, it dies.", "keep", "will keep", "kept",
     "are keeping"),
    ("A live news report often begins: 'I'm ___ here at the scene.'",
     "standing", "stand", "stood of", "to stand"),
    ("'We're ___ reports of flooding in the area.'", "getting", "taking of",
     "making of", "having of it"),
    ("'Police ___ people to avoid the road.'", "are advising", "advice of",
     "advise of it that", "advised will"),
    ("'The situation ___ developing.'", "is still", "still is of",
     "stills", "is stilling"),
    ("'No injuries ___ so far.'", "have been reported", "reported have",
     "are report", "were reporting"),
    ("'We'll bring you more as soon as we ___ it.'", "have", "will have",
     "had", "are having"),
    ("'Back ___ you in the studio.'", "to", "at", "for", "with"),
    ("'That's all ___ now.'", "for", "from", "of", "by"),
    ("Which sentence belongs in a news report?",
     "Emergency services arrived within twenty minutes.",
     "It was so scary for everyone there honestly.",
     "I think the council is useless.", "Everything is terrible today."),
]

I6_AC_V = [
    ("traffic jam", "tirbandlik / пробка"),
    ("rush hour", "eng band soat / час пик"),
    ("car park", "avtoturargoh / парковка"),
    ("crossroads", "chorraha / перекрёсток"),
    ("speed limit", "tezlik chegarasi / ограничение скорости"),
    ("public transport", "jamoat transporti / общественный транспорт"),
    ("season ticket", "abonement / проездной"),
    ("city centre", "shahar markazi / центр города"),
    ("traffic lights", "svetofor / светофор"),
    ("pedestrian crossing", "piyodalar o'tish joyi / пешеходный переход"),
    ("underground station", "metro bekati / станция метро"),
    ("bus lane", "avtobus yo'lagi / полоса для автобусов"),
    ("cycle path", "velosiped yo'li / велодорожка"),
    ("road works", "yo'l ta'miri / дорожные работы"),
    ("petrol station", "yoqilg'i quyish shoxobchasi / заправка"),
    ("shopping centre", "savdo markazi / торговый центр"),
    ("housing estate", "turar joy massivi / жилой массив"),
    ("street lights", "ko'cha chiroqlari / уличные фонари"),
    ("noise pollution", "shovqin ifloslanishi / шумовое загрязнение"),
    ("air quality", "havo sifati / качество воздуха"),
    ("green space", "yashil hudud / зелёная зона"),
    ("town hall", "shahar hokimiyati binosi / мэрия"),
    ("post box", "pochta qutisi / почтовый ящик"),
    ("bus route", "avtobus yo'nalishi / автобусный маршрут"),
    ("car share", "mashinani birga ishlatish / совместные поездки"),
]

I6_AC_G = [
    ("You ___ wear a helmet on a building site.", "have to", "have", "must to",
     "are have to"),
    ("You ___ park here. It's not allowed.", "mustn't", "don't have to",
     "haven't to", "not must"),
    ("We ___ pay. It's free for students.", "don't have to", "mustn't",
     "haven't to", "don't must"),
    ("Drivers ___ stop at a red light.", "must", "must to", "are must",
     "have must"),
    ("___ I fill in this form?", "Do I have to", "Have I to do",
     "Must I to", "Am I have to"),
    ("Which means it is forbidden?", "You mustn't smoke here.",
     "You don't have to smoke here.", "You needn't smoke here.",
     "You can smoke here."),
    ("Which means it isn't necessary?", "You don't have to wait.",
     "You mustn't wait.", "You can't wait.", "You shouldn't wait."),
    ("When I was a student we ___ wear a uniform.", "had to", "must",
     "have to then", "must to"),
    ("Visitors ___ report to reception.", "are supposed to",
     "are supposed", "suppose to", "are supposing to"),
    ("Which is WRONG?", "I must to leave now.", "I must leave now.",
     "I have to leave now.", "I had to leave then."),
    ("You ___ to bring your passport. It's essential.", "need", "must",
     "should to", "ought"),
    ("You ___ not to tell anyone.", "ought", "must", "should to", "have"),
    ("We ___ better hurry.", "had", "have", "would", "should of"),
    ("Passengers ___ keep their tickets.", "are required to", "require to",
     "are requiring", "requires to"),
    ("Which is the strongest rule?", "You must not use the exit.",
     "You needn't use the exit.", "You don't have to use the exit.",
     "You could use the exit."),
    ("He ___ work weekends in that job.", "had to", "must", "have to then",
     "was must"),
    ("Offering: '___ I carry that for you?'", "Shall", "Do", "Am", "Would"),
    ("'Would you like me ___ help?'", "to", "(nothing)", "for", "that I"),
    ("'Do you ___ a hand?'", "want", "wanting of", "wanted of", "wish of it"),
    ("Asking for a favour: 'Could you ___ me a favour?'", "do", "make", "give",
     "take of"),
    ("'Would you ___ opening the window?'", "mind", "mind to", "minding of",
     "be mind"),
    ("'That's very ___ of you.'", "kind", "kindly", "kindness of",
     "kinder of it"),
    ("'Don't worry, it's no ___ .'", "trouble", "troubles of", "problem of it",
     "matter of it"),
    ("'I'd rather you ___ , if that's OK.'", "didn't", "don't", "not",
     "won't"),
    ("Which is the politest request?",
     "I was wondering if you could help me for a moment.",
     "Help me now.", "You must help me.", "Give me help."),
]

I6_BD_V = [
    ("bitter", "achchiq / горький"),
    ("sour", "nordon / кислый"),
    ("salty", "sho'r / солёный"),
    ("spicy", "achchiq ziravorli / острый"),
    ("bland", "bemaza / пресный"),
    ("rich", "to'yimli, yog'li / насыщенный"),
    ("creamy", "qaymoqsimon / сливочный"),
    ("crunchy", "qarsildoq / хрустящий"),
    ("tender", "yumshoq / нежный"),
    ("tough", "qattiq / жёсткий"),
    ("raw", "xom / сырой"),
    ("overcooked", "haddan tashqari pishgan / переваренный"),
    ("undercooked", "chala pishgan / недоваренный"),
    ("fresh", "yangi / свежий"),
    ("stale", "eskirgan, qotgan / чёрствый"),
    ("frozen", "muzlatilgan / замороженный"),
    ("tinned", "konservalangan / консервированный"),
    ("roast", "qovurilgan / жареный в духовке"),
    ("grilled", "panjarada pishirilgan / на гриле"),
    ("steamed", "bug'da pishirilgan / на пару"),
    ("boiled", "qaynatilgan / варёный"),
    ("chopped", "to'g'ralgan / нарезанный"),
    ("sliced", "yupqa kesilgan / нарезанный ломтиками"),
    ("mashed", "ezilgan / пюре"),
    ("seasoning", "ziravorlar / приправы"),
]

I6_BD_G = [
    ("This restaurant is ___ than that one.", "better", "gooder", "more good",
     "best"),
    ("It's the ___ meal I've ever eaten.", "best", "goodest", "most good",
     "better"),
    ("This dish is ___ spicy than I expected.", "more", "much", "many",
     "most"),
    ("The soup is ___ salty.", "far too", "too much", "very too",
     "much too many"),
    ("It's not ___ as the other place.", "as good", "so better", "as better",
     "good as"),
    ("Which is correct?", "This is slightly more expensive.",
     "This is slightly expensiver.", "This is slight more expensive.",
     "This is more expensiver slightly."),
    ("Which is WRONG?", "It's the most tastiest.", "It's the tastiest.",
     "It's tastier than that.", "It's by far the tastiest."),
    ("The queue is getting ___ .", "longer and longer", "more and more long",
     "longer and long", "long and longer"),
    ("The ___ you cook it, the tougher it gets.", "longer", "more long",
     "longest", "most long"),
    ("This is by ___ the best cafe here.", "far", "much of", "very of",
     "most of"),
    ("It's nearly ___ good as homemade.", "as", "so", "than", "like"),
    ("The second course was ___ better.", "much", "very", "too", "so much of"),
    ("Which compares two things?", "Mine is spicier than yours.",
     "Mine is the spiciest of all.", "Mine is spicy.",
     "Mine is the most spicy one here."),
    ("It was ___ expensive meal of the trip.", "the most", "most", "more",
     "the more"),
    ("This bread isn't ___ fresh as yesterday's.", "as", "so more", "than",
     "such"),
    ("Which intensifies a comparative?", "considerably cheaper",
     "very cheaper", "too cheaper", "much more cheaper"),
    ("Describing a place: 'It's ___ for its grilled fish.'", "known", "know of",
     "knowing of", "knew of"),
    ("'The portions are ___ .'", "generous", "generously", "generosity of",
     "generous of it"),
    ("'The service was quick ___ friendly.'", "and", "but", "so", "or"),
    ("'It gets ___ at weekends.'", "busy", "busily", "business of",
     "busier of it"),
    ("'I'd book a table ___ advance.'", "in", "on", "at", "for"),
    ("'It's ___ the price.'", "worth", "worthy to", "value of",
     "worthwhile of it"),
    ("'The atmosphere is really ___ .'", "relaxed", "relaxing of it",
     "relax of", "relaxation of"),
    ("'I'll definitely be going ___ .'", "back", "again back", "return of",
     "backwards of"),
    ("Which recommendation is most useful?",
     "Go early: after eight there's usually a wait.",
     "It is a restaurant.", "Food is served there.",
     "People eat in this place sometimes."),
]

I7_AC_V = [
    ("skyscraper", "osmono'par bino / небоскрёб"),
    ("cottage", "qishloq uyi / коттедж"),
    ("block of flats", "ko'p qavatli uy / многоквартирный дом"),
    ("detached house", "alohida turgan uy / отдельный дом"),
    ("terraced house", "qator uylar / дом в ряду"),
    ("outskirts", "shahar chekkasi / окраина"),
    ("suburb", "shahar atrofi / пригород"),
    ("brick", "g'isht / кирпич"),
    ("concrete", "beton / бетон"),
    ("wooden", "yog'ochdan / деревянный"),
    ("roof", "tom / крыша"),
    ("balcony", "balkon / балкон"),
    ("basement", "yerto'la / подвал"),
    ("staircase", "zinapoya / лестница"),
    ("corridor", "yo'lak / коридор"),
    ("ceiling", "shift / потолок"),
    ("gate", "darvoza / ворота"),
    ("fence", "devor, panjara / забор"),
    ("view", "manzara / вид"),
    ("spacious", "keng / просторный"),
    ("cramped", "tor / тесный"),
    ("run-down", "vayronaga aylangan / запущенный"),
    ("renovated", "ta'mirlangan / отремонтированный"),
    ("historic building", "tarixiy bino / историческое здание"),
    ("construction site", "qurilish maydoni / стройплощадка"),
]

I7_AC_G = [
    ("He ___ be at home. His car is outside.", "must", "must to", "can to",
     "is must"),
    ("She ___ be at work. It's Sunday.", "can't", "mustn't", "don't can",
     "isn't can"),
    ("They ___ be on holiday, but I'm not sure.", "might", "must", "can't",
     "should of"),
    ("That ___ be John. He's in Turkey.", "can't", "mustn't", "doesn't can",
     "isn't"),
    ("It ___ rain later.", "could", "must to", "can to", "is could"),
    ("Which shows you are almost certain it is true?", "She must be tired.",
     "She might be tired.", "She can't be tired.", "She could be tired."),
    ("Which shows you are almost certain it is not true?",
     "He can't be serious.", "He must be serious.", "He might be serious.",
     "He could be serious."),
    ("The lights are off, so they ___ have gone out.", "must", "can't",
     "mustn't", "should of"),
    ("Which is WRONG?", "He must to be tired.", "He must be tired.",
     "He might be tired.", "He can't be tired."),
    ("She ___ have forgotten. She never forgets.", "can't", "mustn't",
     "doesn't", "isn't"),
    ("They ___ be arriving now. The plane landed an hour ago.", "must",
     "can't", "mustn't", "shouldn't"),
    ("That building ___ be very old.", "looks like it must",
     "must to be look", "is must", "can to be"),
    ("Which is the least certain?", "It may be empty.", "It must be empty.",
     "It can't be empty.", "It is definitely empty."),
    ("The door's open, so somebody ___ be inside.", "must", "can't",
     "mustn't", "shouldn't"),
    ("You ___ have seen him. He left yesterday.", "can't", "mustn't",
     "don't", "aren't"),
    ("This ___ be the right address. The number matches.", "must", "can't",
     "mustn't", "isn't must"),
    ("Visiting: 'Come ___ , make yourself at home.'", "in", "on", "at", "of"),
    ("'Can I ___ you anything to drink?'", "get", "give of you", "take of",
     "make to"),
    ("'Make yourself ___ .'", "comfortable", "comfort of", "comfortably of it",
     "comforted of"),
    ("'Sorry about the ___ .'", "mess", "messy of", "messing of",
     "mistake of it"),
    ("'Thanks for ___ me.'", "having", "have", "to have of", "had of"),
    ("'Shall I take my ___ off?'", "shoes", "shoe of", "shoeing of",
     "shoes of me"),
    ("'Help ___ to the biscuits.'", "yourself", "you", "yours of",
     "your own of"),
    ("'I should get going. Thanks for a lovely ___ .'", "evening", "evening of",
     "night of it", "time of evening"),
    ("Which is the warmest goodbye to a host?",
     "Thanks so much, it was lovely to see you both.",
     "OK, bye.", "I go now.", "Goodbye, that is all."),
]

I7_BD_V = [
    ("depend on", "bog'liq bo'lmoq / зависеть от"),
    ("belong to", "tegishli bo'lmoq / принадлежать"),
    ("apologise for", "uchun uzr so'ramoq / извиняться за"),
    ("apply for", "uchun ariza bermoq / подавать на"),
    ("believe in", "ishonmoq / верить в"),
    ("complain about", "shikoyat qilmoq / жаловаться на"),
    ("concentrate on", "diqqatni qaratmoq / сосредоточиться на"),
    ("deal with", "shug'ullanmoq / иметь дело с"),
    ("insist on", "turib olmoq / настаивать на"),
    ("laugh at", "ustidan kulmoq / смеяться над"),
    ("listen to", "tinglamoq / слушать"),
    ("look after", "qaramoq / заботиться о"),
    ("pay for", "to'lamoq / платить за"),
    ("rely on", "tayanmoq / полагаться на"),
    ("succeed in", "muvaffaqiyat qozonmoq / преуспевать в"),
    ("suffer from", "azob chekmoq / страдать от"),
    ("talk about", "haqida gaplashmoq / говорить о"),
    ("think about", "o'ylamoq / думать о"),
    ("wait for", "kutmoq / ждать"),
    ("worry about", "xavotirlanmoq / беспокоиться о"),
    ("agree with", "rozi bo'lmoq / соглашаться с"),
    ("argue about", "bahslashmoq / спорить о"),
    ("borrow from", "qarz olmoq / занимать у"),
    ("spend on", "sarflamoq / тратить на"),
    ("translate into", "tarjima qilmoq / переводить на"),
]

I7_BD_G = [
    ("There isn't ___ time left.", "much", "many", "a lot", "few"),
    ("There aren't ___ seats free.", "many", "much", "a little", "a lot"),
    ("We've got ___ of time.", "plenty", "plenty much", "many", "much of"),
    ("Only a ___ people came.", "few", "little", "much", "bit of"),
    ("There's very ___ information about it.", "little", "few", "many",
     "a number of"),
    ("___ of my friends live abroad.", "Several", "Much", "A little",
     "A great deal"),
    ("I've got ___ money to pay for it.", "enough", "enough of the",
     "too much of", "quite of"),
    ("There are ___ people here that we can't move.", "so many", "so much",
     "such many", "too many that"),
    ("Which goes with uncountable nouns?", "a great deal of", "a number of",
     "several", "a few"),
    ("Which goes with countable nouns?", "a number of", "a great deal of",
     "a bit of", "much"),
    ("Which is WRONG?", "There were too much cars.",
     "There were too many cars.", "There was too much traffic.",
     "There weren't many cars."),
    ("Hardly ___ shops were open.", "any", "none", "no any", "some"),
    ("___ the students passed.", "Most of", "The most of", "Most from",
     "Almost of"),
    ("He spends ___ his salary on rent.", "most of", "the most of",
     "most from", "almost of"),
    ("Which means 'not enough'?", "too little", "too much", "plenty of",
     "a great deal of"),
    ("There's ___ milk left, but not much.", "a little", "a few", "little of",
     "few of"),
    ("Talking about a holiday: 'We ___ a week in the mountains.'", "spent",
     "passed of", "took of", "made of"),
    ("'The weather ___ out to be perfect.'", "turned", "came of", "went of",
     "got of"),
    ("'It was ___ what we needed.'", "exactly", "exact of", "exactness of",
     "just exact of"),
    ("'The best ___ was the food.'", "part", "half of it", "piece of",
     "side of"),
    ("'We didn't ___ to see everything.'", "manage", "manage of it",
     "managed of", "manages of"),
    ("'Next time we'll stay ___ .'", "longer", "more long", "longest",
     "more longer"),
    ("'I'd ___ recommend going out of season.'", "definitely", "definite of",
     "definitive of", "definitely of it"),
    ("'It's somewhere I'd love to go ___ to.'", "back", "again back of",
     "return of", "returning of"),
    ("Which sentence gives a reader something useful?",
     "Take cash: many of the small cafes don't take cards.",
     "We went on holiday.", "Holidays are enjoyable.",
     "The place existed and we saw it."),
]

LISTS = [
    ("Unit 5A&C · Vocabulary — the environment", "vocab", 9, I5_AC_V),
    ("Unit 5A&C · Grammar — talking about the future, and problems", "grammar", 9, I5_AC_G),
    ("Unit 5B&D · Vocabulary — the natural world", "vocab", 10, I5_BD_V),
    ("Unit 5B&D · Grammar — zero and first conditionals, and the news", "grammar", 10, I5_BD_G),
    ("Unit 6A&C · Vocabulary — compound nouns in a city", "vocab", 11, I6_AC_V),
    ("Unit 6A&C · Grammar — what you must and needn't do", "grammar", 11, I6_AC_G),
    ("Unit 6B&D · Vocabulary — describing food", "vocab", 12, I6_BD_V),
    ("Unit 6B&D · Grammar — comparing, and describing a place", "grammar", 12, I6_BD_G),
    ("Unit 7A&C · Vocabulary — buildings", "vocab", 13, I7_AC_V),
    ("Unit 7A&C · Grammar — modals of deduction, and visiting", "grammar", 13, I7_AC_G),
    ("Unit 7B&D · Vocabulary — verbs and their prepositions", "vocab", 14, I7_BD_V),
    ("Unit 7B&D · Grammar — quantifiers, and a recent holiday", "grammar", 14, I7_BD_G),
]
