"""Pre-Intermediate vocabulary, Units 1-6, with Uzbek and Russian meanings.

Same words as the lists already on the site; only the meanings change, so
the lists are swapped rather than made again and no progress is lost.
"""

LEVEL = "Pre-Intermediate"
BOOK = "Empower Pre-Intermediate"
PAST_FROM = 1

V1_AC = [
    ("annoying", "jahlni chiqaradigan / раздражающий"),
    ("boring", "zerikarli / скучный"),
    ("confusing", "chalkash / запутанный"),
    ("disappointing", "umidni puchga chiqaradigan / разочаровывающий"),
    ("embarrassing", "uyaltiradigan / неловкий"),
    ("exhausting", "juda charchatadigan / изнурительный"),
    ("fascinating", "o'ta qiziqarli / увлекательный"),
    ("frightening", "qo'rqinchli / пугающий"),
    ("impressive", "taassurot qoldiradigan / впечатляющий"),
    ("relaxing", "orom beradigan / расслабляющий"),
    ("stressful", "asabni buzadigan / напряжённый"),
    ("surprising", "kutilmagan / удивительный"),
    ("challenging", "qiyin, sinovli / сложный"),
    ("enjoyable", "yoqimli / приятный"),
    ("essential", "juda zarur / необходимый"),
    ("brilliant", "zo'r, ajoyib / блестящий"),
    ("awkward", "noqulay / неудобный, неловкий"),
    ("unusual", "g'ayrioddiy / необычный"),
    ("worrying", "tashvishga soladigan / тревожный"),
    ("rewarding", "qoniqish beradigan / приносящий удовлетворение"),
    ("complicated", "murakkab / сложный"),
    ("practical", "amaliy / практичный"),
    ("reliable", "ishonchli / надёжный"),
    ("popular", "ommabop / популярный"),
    ("weird", "g'alati / странный"),
]

V1_BD = [
    ("get in touch", "bog'lanmoq / связаться"),
    ("keep in touch", "aloqada bo'lib turmoq / поддерживать связь"),
    ("lose touch", "aloqani yo'qotmoq / потерять связь"),
    ("catch up", "yangiliklarni bilib olmoq / наверстать новости"),
    ("chat", "suhbatlashmoq / болтать"),
    ("text", "SMS yozmoq / писать сообщение"),
    ("call back", "qayta qo'ng'iroq qilmoq / перезвонить"),
    ("post", "internetga joylamoq / выложить"),
    ("reply", "javob bermoq / отвечать"),
    ("forward", "boshqaga yubormoq / пересылать"),
    ("share", "ulashmoq / делиться"),
    ("follow", "kuzatib bormoq / подписаться"),
    ("block", "to'sib qo'ymoq / заблокировать"),
    ("comment", "izoh yozmoq / комментировать"),
    ("video call", "video qo'ng'iroq / видеозвонок"),
    ("voice message", "ovozli xabar / голосовое сообщение"),
    ("notification", "bildirishnoma / уведомление"),
    ("group chat", "guruh suhbati / групповой чат"),
    ("emoji", "kulgichlar / эмодзи"),
    ("attachment", "ilova fayl / вложение"),
    ("face to face", "yuzma-yuz / лицом к лицу"),
    ("get on well", "chiqishib ketmoq / хорошо ладить"),
    ("hang out", "birga vaqt o'tkazmoq / проводить время"),
    ("drop somebody a line", "qisqa xabar yozmoq / черкнуть пару строк"),
    ("stay in contact", "aloqani uzmaslik / оставаться на связи"),
]

V2_AC = [
    ("abroad", "chet elda / за границей"),
    ("accommodation", "turar joy / жильё"),
    ("book", "oldindan band qilmoq / бронировать"),
    ("check in", "ro'yxatdan o'tmoq / регистрироваться"),
    ("check out", "hisob-kitob qilib chiqmoq / выселяться"),
    ("delayed", "kechiktirilgan / задержанный"),
    ("destination", "boradigan joy / пункт назначения"),
    ("guest house", "kichik mehmon uyi / гостевой дом"),
    ("hostel", "arzon yotoqxona / хостел"),
    ("journey", "safar / поездка"),
    ("luggage", "yuk / багаж"),
    ("passenger", "yo'lovchi / пассажир"),
    ("resort", "dam olish maskani / курорт"),
    ("sightseeing", "diqqatga sazovor joylarni ko'rish / осмотр достопримечательностей"),
    ("souvenir", "esdalik sovg'a / сувенир"),
    ("tour guide", "yo'lboshchi / экскурсовод"),
    ("trip", "sayohat / путешествие"),
    ("visa", "viza / виза"),
    ("flight", "parvoz / рейс"),
    ("crowded", "gavjum / переполненный"),
    ("local", "mahalliy / местный"),
    ("scenery", "manzara / пейзаж"),
    ("coast", "sohil / побережье"),
    ("adventure", "sarguzasht / приключение"),
    ("backpacking", "ryukzak bilan sayohat / путешествие с рюкзаком"),
]

V2_BD = [
    ("catch a flight", "samolyotga ulgurmoq / успеть на рейс"),
    ("miss a train", "poyezdga kechikmoq / опоздать на поезд"),
    ("get on", "chiqmoq, minmoq / садиться"),
    ("get off", "tushmoq / выходить"),
    ("set off", "yo'lga chiqmoq / отправляться"),
    ("pick somebody up", "olib ketmoq / забирать"),
    ("drop somebody off", "tashlab ketmoq / подвозить и высаживать"),
    ("hire a car", "mashina ijaraga olmoq / арендовать машину"),
    ("get lost", "adashmoq / заблудиться"),
    ("run out of", "tugab qolmoq / заканчиваться"),
    ("take off", "uchib ko'tarilmoq / взлетать"),
    ("land", "qo'nmoq / приземляться"),
    ("change trains", "poyezd almashtirmoq / пересаживаться"),
    ("go through customs", "bojxonadan o'tmoq / проходить таможню"),
    ("check in luggage", "yukni topshirmoq / сдавать багаж"),
    ("board", "bortga chiqmoq / садиться на борт"),
    ("depart", "jo'namoq / отправляться"),
    ("arrive", "yetib kelmoq / прибывать"),
    ("queue", "navbatda turmoq / стоять в очереди"),
    ("stop over", "yo'l-yo'lakay to'xtamoq / делать остановку"),
    ("travel light", "kam yuk bilan yurmoq / путешествовать налегке"),
    ("book in advance", "oldindan band qilmoq / бронировать заранее"),
    ("go camping", "chodirda dam olmoq / ехать в поход"),
    ("see the sights", "diqqatga sazovor joylarni ko'rmoq / осматривать достопримечательности"),
    ("cross the border", "chegarani kesib o'tmoq / пересекать границу"),
]

V3_AC = [
    ("afford", "pulini ko'tara olmoq / позволить себе"),
    ("bargain", "arzon mol / выгодная покупка"),
    ("bill", "hisob / счёт"),
    ("borrow", "qarz olmoq / брать в долг"),
    ("lend", "qarz bermoq / давать в долг"),
    ("cash", "naqd pul / наличные"),
    ("charge", "haq olmoq / брать плату"),
    ("cost", "turmoq, narxi / стоить"),
    ("discount", "chegirma / скидка"),
    ("earn", "ishlab topmoq / зарабатывать"),
    ("owe", "qarzdor bo'lmoq / быть должным"),
    ("refund", "pulni qaytarish / возврат денег"),
    ("save", "jamg'armoq / копить"),
    ("spend", "sarflamoq / тратить"),
    ("receipt", "chek / чек"),
    ("salary", "oylik maosh / зарплата"),
    ("value", "qiymat / ценность"),
    ("waste", "behuda sarflamoq / тратить впустую"),
    ("expensive", "qimmat / дорогой"),
    ("reasonable", "narxi o'rinli / приемлемый"),
    ("worth it", "arziydi / стоит того"),
    ("in advance", "oldindan / заранее"),
    ("second-hand", "ishlatilgan / бывший в употреблении"),
    ("customer", "xaridor / покупатель"),
    ("pay back", "qarzni qaytarmoq / возвращать долг"),
]

V3_BD = [
    ("charity", "xayriya tashkiloti / благотворительность"),
    ("donate", "xayriya qilmoq / жертвовать"),
    ("raise money", "mablag' yig'moq / собирать деньги"),
    ("volunteer", "ko'ngilli / волонтёр"),
    ("generous", "saxiy / щедрый"),
    ("mean", "xasis / скупой"),
    ("support", "qo'llab-quvvatlamoq / поддерживать"),
    ("fundraiser", "mablag' yig'ish tadbiri / сбор средств"),
    ("sponsor", "homiylik qilmoq / спонсировать"),
    ("collection", "yig'ilgan mablag' / сбор"),
    ("homeless", "uysiz / бездомный"),
    ("poverty", "qashshoqlik / бедность"),
    ("aid", "yordam / помощь"),
    ("give away", "bepul bermoq / раздавать"),
    ("look after", "qaramoq / заботиться"),
    ("take part", "qatnashmoq / участвовать"),
    ("set up", "tashkil qilmoq / основать"),
    ("get involved", "ishtirok eta boshlamoq / включиться"),
    ("make a difference", "o'zgarish keltirmoq / изменить ситуацию"),
    ("needy", "muhtoj / нуждающийся"),
    ("grateful", "minnatdor / благодарный"),
    ("kindness", "mehribonlik / доброта"),
    ("community", "jamoa / сообщество"),
    ("campaign", "kampaniya / кампания"),
    ("cause", "maqsad, ish / дело"),
]

V4_AC = [
    ("celebration", "bayram, nishonlash / празднование"),
    ("anniversary", "yubiley sanasi / годовщина"),
    ("ceremony", "marosim / церемония"),
    ("decorate", "bezamoq / украшать"),
    ("fireworks", "mushakbozlik / фейерверк"),
    ("guest", "mehmon / гость"),
    ("host", "mezbon / хозяин"),
    ("invitation", "taklifnoma / приглашение"),
    ("occasion", "tadbir, munosabat / случай, событие"),
    ("parade", "yurish, parad / парад"),
    ("present", "sovg'a / подарок"),
    ("tradition", "an'ana / традиция"),
    ("wedding", "to'y marosimi / свадьба"),
    ("birthday", "tug'ilgan kun / день рождения"),
    ("graduation", "bitiruv / выпускной"),
    ("festival", "festival / фестиваль"),
    ("candle", "sham / свеча"),
    ("cake", "tort / торт"),
    ("speech", "nutq / речь"),
    ("toast", "qadah so'zi / тост"),
    ("costume", "maxsus libos / костюм"),
    ("gathering", "yig'in / собрание"),
    ("celebrate", "nishonlamoq / праздновать"),
    ("congratulate", "tabriklamoq / поздравлять"),
    ("religious holiday", "diniy bayram / религиозный праздник"),
]

V4_BD = [
    ("accept", "qabul qilmoq / принимать"),
    ("refuse", "rad etmoq / отказываться"),
    ("reply", "javob bermoq / отвечать"),
    ("attend", "qatnashmoq / посещать"),
    ("apologise", "uzr so'ramoq / извиняться"),
    ("arrange", "uyushtirmoq / организовывать"),
    ("cancel", "bekor qilmoq / отменять"),
    ("postpone", "keyinga surmoq / откладывать"),
    ("confirm", "tasdiqlamoq / подтверждать"),
    ("remind", "eslatmoq / напоминать"),
    ("look forward to", "intiqlik bilan kutmoq / с нетерпением ждать"),
    ("free", "bo'sh / свободный"),
    ("busy", "band / занятый"),
    ("available", "mavjud, bo'sh / доступный"),
    ("suit", "qulay kelmoq / подходить"),
    ("meet up", "uchrashmoq / встречаться"),
    ("put off", "kechiktirmoq / откладывать"),
    ("turn down", "rad qilmoq / отклонять"),
    ("join in", "qo'shilmoq / присоединяться"),
    ("drop by", "qisqa kirib o'tmoq / заглянуть"),
    ("be on time", "o'z vaqtida kelmoq / приходить вовремя"),
    ("be late", "kechikmoq / опаздывать"),
    ("host a party", "ziyofat uyushtirmoq / устраивать вечеринку"),
    ("RSVP", "javob berishingizni so'raymiz / просьба ответить"),
    ("occasion", "munosabat, sabab / повод"),
]

V5_AC = [
    ("apply for", "ariza bermoq / подавать заявление"),
    ("employ", "ishga olmoq / нанимать"),
    ("staff", "xodimlar / персонал"),
    ("shift", "smena / смена"),
    ("overtime", "qo'shimcha ish vaqti / сверхурочные"),
    ("deadline", "muddat / срок"),
    ("promotion", "lavozim ko'tarilishi / повышение"),
    ("colleague", "hamkasb / коллега"),
    ("interview", "suhbat / собеседование"),
    ("CV", "rezyume / резюме"),
    ("salary", "maosh / оклад"),
    ("wages", "ish haqi / заработок"),
    ("contract", "shartnoma / договор"),
    ("experience", "tajriba / опыт"),
    ("qualification", "malaka hujjati / квалификация"),
    ("training", "o'qitish / обучение"),
    ("workload", "ish hajmi / объём работы"),
    ("client", "mijoz / клиент"),
    ("responsible for", "javobgar / ответственный за"),
    ("resign", "ishdan bo'shamoq / увольняться"),
    ("sack", "ishdan bo'shatmoq / увольнять"),
    ("earn a living", "tirikchilik qilmoq / зарабатывать на жизнь"),
    ("self-employed", "o'ziga ishlaydigan / самозанятый"),
    ("in charge", "mas'ul / главный"),
    ("day off", "dam olish kuni / выходной"),
]

V5_BD = [
    ("accountant", "buxgalter / бухгалтер"),
    ("architect", "me'mor / архитектор"),
    ("chef", "oshpaz boshlig'i / шеф-повар"),
    ("electrician", "elektrchi / электрик"),
    ("journalist", "jurnalist / журналист"),
    ("lawyer", "advokat / юрист"),
    ("mechanic", "usta, mexanik / механик"),
    ("nurse", "hamshira / медсестра"),
    ("pharmacist", "farmatsevt / фармацевт"),
    ("programmer", "dasturchi / программист"),
    ("receptionist", "qabulxona xodimi / администратор"),
    ("scientist", "olim / учёный"),
    ("surgeon", "jarroh / хирург"),
    ("translator", "tarjimon / переводчик"),
    ("vet", "veterinar / ветеринар"),
    ("waiter", "ofitsiant / официант"),
    ("well-paid", "yaxshi maoshli / хорошо оплачиваемый"),
    ("part-time", "yarim stavka / неполная занятость"),
    ("full-time", "to'liq stavka / полная занятость"),
    ("permanent", "doimiy / постоянный"),
    ("temporary", "vaqtinchalik / временный"),
    ("freelance", "erkin ishlaydigan / фрилансер"),
    ("night shift", "tungi smena / ночная смена"),
    ("skilled", "malakali / квалифицированный"),
    ("demanding", "ko'p kuch talab qiladigan / требовательный"),
]

V6_AC = [
    ("device", "qurilma / устройство"),
    ("screen", "ekran / экран"),
    ("button", "tugma / кнопка"),
    ("switch on", "yoqmoq / включать"),
    ("switch off", "o'chirmoq / выключать"),
    ("plug in", "rozetkaga ulamoq / подключать"),
    ("charge", "quvvat olmoq / заряжать"),
    ("press", "bosmoq / нажимать"),
    ("hold down", "bosib turmoq / удерживать"),
    ("restart", "qayta ishga tushirmoq / перезапускать"),
    ("settings", "sozlamalar / настройки"),
    ("volume", "ovoz balandligi / громкость"),
    ("instructions", "ko'rsatmalar / инструкции"),
    ("manual", "qo'llanma / руководство"),
    ("wireless", "simsiz / беспроводной"),
    ("portable", "ko'chma / портативный"),
    ("rechargeable", "qayta quvvatlanadigan / перезаряжаемый"),
    ("broken", "buzilgan / сломанный"),
    ("repair", "ta'mirlamoq / чинить"),
    ("replace", "almashtirmoq / заменять"),
    ("warranty", "kafolat / гарантия"),
    ("out of order", "ishlamayapti / не работает"),
    ("touchscreen", "sensorli ekran / сенсорный экран"),
    ("remote control", "pult / пульт"),
    ("socket", "rozetka / розетка"),
]

V6_BD = [
    ("amazed", "hayratlangan / изумлённый"),
    ("amazing", "hayratlanarli / изумительный"),
    ("bored", "zerikkan / скучающий"),
    ("boring", "zerikarli / скучный"),
    ("confused", "chalkashib qolgan / сбитый с толку"),
    ("confusing", "chalkashtiradigan / запутывающий"),
    ("disappointed", "hafsalasi pir bo'lgan / разочарованный"),
    ("disappointing", "umidsizlantiradigan / разочаровывающий"),
    ("excited", "hayajonlangan / взволнованный"),
    ("exciting", "hayajonli / захватывающий"),
    ("frightened", "qo'rqqan / испуганный"),
    ("frightening", "qo'rqitadigan / пугающий"),
    ("interested", "qiziqqan / заинтересованный"),
    ("interesting", "qiziqarli / интересный"),
    ("relaxed", "xotirjam / расслабленный"),
    ("relaxing", "orom beruvchi / расслабляющий"),
    ("surprised", "ajablangan / удивлённый"),
    ("surprising", "ajablantiradigan / удивительный"),
    ("tired", "charchagan / уставший"),
    ("tiring", "charchatadigan / утомительный"),
    ("worried", "xavotirdagi / обеспокоенный"),
    ("worrying", "xavotirga soladigan / тревожный"),
    ("embarrassed", "uyalgan / смущённый"),
    ("embarrassing", "uyaltiradigan / неловкий"),
    ("shocked", "shokda qolgan / шокированный"),
]

LISTS = [
    ("Unit 1A&C · Vocabulary — describing things", "vocab", 1, V1_AC),
    ("Unit 1B&D · Vocabulary — keeping in touch", "vocab", 2, V1_BD),
    ("Unit 2A&C · Vocabulary — holidays", "vocab", 3, V2_AC),
    ("Unit 2B&D · Vocabulary — travel collocations", "vocab", 4, V2_BD),
    ("Unit 3A&C · Vocabulary — money", "vocab", 5, V3_AC),
    ("Unit 3B&D · Vocabulary — helping others", "vocab", 6, V3_BD),
    ("Unit 4A&C · Vocabulary — celebrations", "vocab", 7, V4_AC),
    ("Unit 4B&D · Vocabulary — invitations", "vocab", 8, V4_BD),
    ("Unit 5A&C · Vocabulary — work", "vocab", 9, V5_AC),
    ("Unit 5B&D · Vocabulary — jobs", "vocab", 10, V5_BD),
    ("Unit 6A&C · Vocabulary — devices", "vocab", 11, V6_AC),
    ("Unit 6B&D · Vocabulary — -ed and -ing adjectives", "vocab", 12, V6_BD),
]
