"""Empower Elementary Units 9-12, as Play steps, in the A&C / B&D pairing.

    9A  shopping; present continuous          9C in a clothes shop
    9B  present simple or continuous          9D presents and thanking
    10A IT collocations; comparatives         10C asking for help
    10B superlatives                          10D text messages, agreeing
    11A present perfect for experience        11C responding to opinions
    11B music; present perfect or past simple 11D film reviews
    12A geography; be going to                12C a hotel, showing surprise
    12B travel collocations; should           12D holiday plans
"""

U9_AC_V = [
    ("customer", "the person who buys something"),
    ("shop assistant", "the person who serves you in a shop"),
    ("cashier", "the person who takes your money"),
    ("till", "the machine the money goes into"),
    ("receipt", "the paper that proves you paid"),
    ("change", "the money you get back"),
    ("cash", "notes and coins"),
    ("card", "you pay with it instead of cash"),
    ("price", "how much something costs"),
    ("discount", "money taken off the usual price"),
    ("sale", "a time when a shop sells things more cheaply"),
    ("queue", "the line of people waiting"),
    ("basket", "you carry your shopping in it"),
    ("trolley", "you push it round a supermarket"),
    ("shelf", "goods are stood on it in a shop"),
    ("bargain", "something good for very little money"),
    ("refund", "your money given back to you"),
    ("exchange", "give something back and take another"),
    ("size", "how big or small clothes are"),
    ("changing room", "where you try clothes on"),
    ("bag", "you carry your shopping home in it"),
    ("market stall", "a small open shop at a market"),
    ("delivery", "when the shop brings it to your home"),
    ("order", "ask a shop to get something for you"),
    ("spend", "use your money to buy things"),
]

U9_AC_G = [
    ("I ___ for a new jacket.", "am looking", "look", "looking", "am look"),
    ("She ___ a coffee at the moment.", "is drinking", "drinks", "drink",
     "is drink"),
    ("They ___ in the queue.", "are waiting", "wait", "waiting", "are wait"),
    ("We ___ TV right now.", "aren't watching", "don't watching",
     "not watching", "aren't watch"),
    ("He ___ today. The shop is closed.", "isn't working", "doesn't working",
     "not working", "isn't work"),
    ("___ you looking for something?", "Are", "Do", "Is", "Have"),
    ("___ she trying the shoes on?", "Is", "Are", "Does", "Has"),
    ("'Are you waiting?' 'Yes, ___.'", "I am", "I do", "I'm", "am I"),
    ("Which is correct?", "He is buying a shirt.", "He buying a shirt.",
     "He is buy a shirt.", "He buy a shirt now."),
    ("Which is WRONG?", "They are go to the shops.",
     "They are going to the shops.", "They go to the shops every Saturday.",
     "Are they going to the shops?"),
    ("Look! It ___.", "is raining", "rains", "rain", "is rain"),
    ("The spelling of 'shop' with -ing is ___.", "shopping", "shoping",
     "shopping of", "shopped"),
    ("The spelling of 'take' with -ing is ___.", "taking", "takeing", "takking",
     "taked"),
    ("Which time phrase goes with the present continuous?", "at the moment",
     "every day", "usually", "on Mondays"),
    ("I can't talk. I ___ dinner.", "am cooking", "cook", "cooks", "am cook"),
    ("The children ___ in the park now.", "are playing", "play", "plays",
     "are play"),
    ("In a shop: 'Can I ___ this on?'", "try", "put on me", "test of", "wear to"),
    ("'What ___ are you?' 'Medium, I think.'", "size", "number of", "measure",
     "big"),
    ("'Have you got this ___ blue?'", "in", "on", "of", "at"),
    ("'How much ___ it cost?' 'Ninety thousand som.'", "does", "is", "do",
     "has"),
    ("'How would you like to ___?' 'By card, please.'", "pay", "give money of",
     "buy of", "cost"),
    ("'It doesn't ___ me. It's too small.'", "fit", "wear of", "size of",
     "put"),
    ("'Can I have a ___, please?' 'Here you are.'", "receipt", "paper of pay",
     "bill of shop", "ticket of money"),
    ("'Sorry, we haven't got that in ___.'", "stock", "shop of", "shelf of",
     "store of it"),
    ("'Would you like a ___?' 'No thanks, I've got one.'", "bag", "sack of",
     "case of", "box of paper"),
]

U9_BD_V = [
    ("clothes", "the things you wear"),
    ("jacket", "a short coat"),
    ("coat", "a long warm thing you wear outside"),
    ("shirt", "it has buttons down the front"),
    ("T-shirt", "a simple top with short sleeves"),
    ("jumper", "a warm top you pull over your head"),
    ("trousers", "you wear them on both legs"),
    ("jeans", "trousers made of strong blue cotton"),
    ("dress", "a woman wears it as one piece"),
    ("skirt", "a woman wears it from the waist down"),
    ("shoes", "you wear them on your feet outside"),
    ("boots", "shoes that come up your leg"),
    ("trainers", "soft shoes for sport"),
    ("socks", "you wear them inside your shoes"),
    ("scarf", "you wear it round your neck in winter"),
    ("hat", "you wear it on your head"),
    ("gloves", "you wear them on your hands"),
    ("belt", "it holds your trousers up"),
    ("suit", "a jacket and trousers that match"),
    ("uniform", "the clothes everybody at a school or job wears"),
    ("present", "something you give on a special day"),
    ("wrap", "cover a present in nice paper"),
    ("celebrate", "do something special because of a happy day"),
    ("guest", "somebody you invite to your home"),
    ("thank", "tell somebody you are grateful"),
]

U9_BD_G = [
    ("I usually ___ tea, but today I ___ coffee.", "drink / am drinking",
     "am drinking / drink", "drink / drink now", "am drinking / am drinking"),
    ("She ___ in a bank, but this week she ___ at home.",
     "works / is working", "is working / works", "work / working",
     "works / works"),
    ("Look! The bus ___.", "is coming", "comes", "come", "is come"),
    ("Water ___ at one hundred degrees.", "boils", "is boiling", "boil",
     "is boil"),
    ("My brother ___ football every Sunday.", "plays", "is playing", "play",
     "is play"),
    ("Be quiet, the baby ___.", "is sleeping", "sleeps", "sleep", "is sleep"),
    ("We ___ to Bukhara twice a year.", "go", "are going", "goes", "are go"),
    ("'What ___ you doing?' 'Nothing much.'", "are", "do", "is", "does"),
    ("'What ___ you do?' 'I'm a nurse.'", "do", "are", "is", "does"),
    ("Which sentence is about now?", "She's studying for an exam.",
     "She studies every evening.", "She studied yesterday.",
     "She usually studies here."),
    ("Which sentence is about a habit?", "He walks to work every day.",
     "He is walking to work now.", "He walked to work.",
     "He is walking at the moment."),
    ("Which is WRONG?", "I am knowing the answer.", "I know the answer.",
     "I am learning the answer.", "I don't know the answer."),
    ("These verbs are not usually used in the continuous form: ___.",
     "know, like, want", "run, eat, play", "watch, cook, write",
     "walk, read, sing"),
    ("It ___ a lot in Tashkent in winter, but it ___ today.",
     "snows / isn't snowing", "is snowing / doesn't snow",
     "snow / not snowing", "is snowing / isn't snow"),
    ("My parents ___ TV in the evenings, but tonight they ___ cards.",
     "watch / are playing", "are watching / play", "watch / play now",
     "are watching / are play"),
    ("'Where's Aziz?' 'He ___ a shower.'", "is having", "has", "have",
     "is have"),
    ("I always ___ my friends presents on their birthdays.", "give", "am giving",
     "gives", "am give"),
    ("She's ___ the present in gold paper.", "wrapping", "wraping", "wrapped",
     "wrap"),
    ("'Thank you so much!' 'You're ___.'", "welcome", "welcomed", "well come",
     "welcome of it"),
    ("'This is ___ you.' 'Oh, thank you!'", "for", "to", "of", "at"),
    ("'Happy birthday!' 'Thanks, that's very ___ of you.'", "kind", "kindly",
     "kindness", "kinder"),
    ("We ___ my mother's birthday every year with a big dinner.", "celebrate",
     "celebrating", "celebration", "celebrate of"),
    ("'I hope you ___ it.' 'I love it!'", "like", "will liking", "are liking",
     "liked of"),
    ("Which is a polite thank-you message?", "Thank you for the lovely scarf.",
     "Thanks, but small.", "Your present is OK.", "I thank of your present."),
    ("Which is correct?", "She's giving him a present.",
     "She giving him a present.", "She is give him a present.",
     "She gives him a present now here."),
]

U10_AC_V = [
    ("download an app", "put a program onto your phone"),
    ("send an email", "write to somebody online"),
    ("attach a file", "add a document to a message"),
    ("charge a phone", "put power back into it"),
    ("switch off", "make a machine stop"),
    ("log in", "enter your name and password to start"),
    ("log out", "leave your account safely"),
    ("save a file", "keep your work on the computer"),
    ("delete a file", "remove your work for good"),
    ("print a document", "put it on paper"),
    ("search online", "look for information on the internet"),
    ("click on a link", "press it to open a page"),
    ("take a photo", "make a picture with a camera"),
    ("share a post", "show it to other people online"),
    ("update software", "get the newest version"),
    ("back up", "make a second copy in case you lose it"),
    ("connect to wifi", "join the internet without a cable"),
    ("scan a document", "make a computer copy of a paper"),
    ("type a message", "write it with a keyboard"),
    ("install a program", "put a new program on a computer"),
    ("open a document", "make a file appear on the screen"),
    ("reply to an email", "write back"),
    ("forward an email", "send somebody else's message on"),
    ("turn up the volume", "make the sound louder"),
    ("plug in", "connect something to electricity"),
]

U10_AC_G = [
    ("My phone is ___ than yours.", "newer", "more new", "newest", "more newer"),
    ("This laptop is ___ than that one.", "more expensive", "expensiver",
     "most expensive", "more expensiver"),
    ("Tashkent is ___ than Bukhara.", "bigger", "more big", "biggest",
     "bigger than more"),
    ("Today is ___ than yesterday.", "hotter", "more hot", "hottest",
     "hotter more"),
    ("This exercise is ___ than the last one.", "easier", "more easy",
     "easyer", "easiest"),
    ("A bus is ___ than a taxi.", "cheaper", "more cheap", "cheapest",
     "more cheaper"),
    ("My new computer is ___ than my old one.", "better", "gooder", "more good",
     "best"),
    ("The traffic today is ___ than usual.", "worse", "badder", "more bad",
     "worst"),
    ("Which is correct?", "She is taller than her brother.",
     "She is more tall than her brother.", "She is tallest than her brother.",
     "She is taller then her brother."),
    ("Which is WRONG?", "This film is more better.", "This film is better.",
     "This film is worse.", "This film is more interesting."),
    ("A tablet is ___ to carry than a laptop.", "easier", "more easy", "easyer",
     "easiest"),
    ("My internet at home is ___ than at work.", "slower", "more slow",
     "slowest", "more slower"),
    ("Which word needs 'more' in front of it?", "comfortable", "big", "old",
     "fast"),
    ("Which word takes -er?", "young", "expensive", "difficult", "important"),
    ("This app is ___ popular than that one.", "more", "much", "many", "most"),
    ("My phone is not as fast ___ yours.", "as", "than", "that", "like of"),
    ("'Can you ___ me with this file?' 'Sure.'", "help", "aid of", "assist to",
     "do help"),
    ("'Could you show me ___ to do it?'", "how", "what", "which", "that"),
    ("'What's the ___?' 'It won't turn on.'", "problem", "wrong of",
     "trouble of it", "matter of it"),
    ("'Have you tried ___ it off and on again?'", "turning", "turn", "to turning",
     "turned"),
    ("'It still doesn't ___.'", "work", "works", "working", "worked"),
    ("'Thanks for your help.' 'No ___.'", "problem", "problems of", "worry of",
     "matter of"),
    ("'Can you ___ the file to me?' 'Yes, I'll send it now.'", "send", "sending",
     "sent", "sends of"),
    ("'I ___ my password.' 'Click on forgot password.'", "can't remember",
     "don't can remember", "am not remember", "no remember"),
    ("Which is the politest way to ask for help?",
     "Could you help me for a moment, please?", "Help me now.",
     "I need help right now.", "You must help me."),
]

U10_BD_V = [
    ("cheap", "the opposite of expensive"),
    ("modern", "the opposite of old-fashioned"),
    ("useful", "it helps you do something"),
    ("useless", "it does not help at all"),
    ("popular", "many people like it"),
    ("boring", "it does not interest you"),
    ("exciting", "it makes you feel full of energy"),
    ("difficult", "it is not easy"),
    ("simple", "it is very easy to use"),
    ("heavy", "it weighs a lot"),
    ("light", "it does not weigh much"),
    ("powerful", "it is strong and can do a lot"),
    ("slow", "it takes a long time"),
    ("quick", "it takes very little time"),
    ("safe", "there is no danger"),
    ("expensive", "it costs a lot of money"),
    ("beautiful", "it looks very good"),
    ("ugly", "it does not look good"),
    ("comfortable", "it feels nice to use or wear"),
    ("famous", "everybody knows it"),
    ("important", "it matters a lot"),
    ("friendly", "it is easy to get on with"),
    ("noisy", "it makes a lot of sound"),
    ("tiny", "it is extremely small"),
    ("enormous", "it is extremely big"),
]

U10_BD_G = [
    ("This is the ___ phone in the shop.", "cheapest", "cheaper", "most cheap",
     "more cheap"),
    ("She is the ___ student in the class.", "best", "goodest", "most good",
     "better"),
    ("That was the ___ day of my life.", "worst", "baddest", "most bad",
     "worse"),
    ("It's the ___ building in the city.", "tallest", "taller", "most tall",
     "more tall"),
    ("This is the ___ exercise in the book.", "most difficult",
     "difficultest", "more difficult", "most difficultest"),
    ("Samarkand is one of the ___ cities in the world.", "oldest", "older",
     "most old", "more old"),
    ("Which is correct?", "It's the most beautiful place I know.",
     "It's the beautifulest place I know.",
     "It's the more beautiful place I know.",
     "It's most beautiful place I know."),
    ("Which is WRONG?", "He is the most tallest.", "He is the tallest.",
     "He is taller than me.", "He is the most popular."),
    ("What is the superlative of 'happy'?", "the happiest", "the happyest",
     "the most happy", "the happier"),
    ("What is the superlative of 'expensive'?", "the most expensive",
     "the expensivest", "the more expensive", "the most expensivest"),
    ("Before a superlative we usually write ___.", "the", "a", "an", "more"),
    ("This is the ___ interesting book I have.", "most", "more", "much", "many"),
    ("It's the ___ app on my phone.", "most useful", "usefulest",
     "more useful", "most usefullest"),
    ("Which sentence compares three or more things?",
     "This is the best of the three.", "This is better than that.",
     "This is as good as that.", "This is good."),
    ("Which sentence compares two things?", "My phone is better than yours.",
     "My phone is the best.", "My phone is the newest.",
     "My phone is the most modern."),
    ("She's the ___ person in our family.", "funniest", "funnyest",
     "most funny", "more funny"),
    ("In a text message, 'thx' means ___.", "thanks", "this", "the next",
     "that is"),
    ("In a text message, 'c u l8r' means ___.", "see you later",
     "call your later", "come you last", "check you later"),
    ("Which is right for a message to a friend?", "See you at 6 :)",
     "Dear Sir, I shall arrive at six o'clock.",
     "To whom it may concern, six.", "Respected friend, at six I come."),
    ("Somebody says 'I think exams are useless.' You agree: '___.'",
     "So do I", "So I do", "Me too do", "I so do"),
    ("Somebody says 'I don't like horror films.' You agree: '___.'",
     "Neither do I", "Nor I do", "Me neither do", "Also I don't do"),
    ("Somebody says 'I love this song.' You disagree politely: '___.'",
     "Really? I'm not sure about it.", "No. You are wrong.",
     "That is bad idea.", "I disagree you."),
    ("'I think it's the best film of the year.' 'I ___ agree.'",
     "totally", "total", "totality", "very much of"),
    ("Which shows you agree?", "That's a good point.", "That's not point.",
     "You don't say right.", "I don't think so at all of it."),
    ("Which is the best short reply to a message?", "OK, see you then!",
     "I have received your message and I will attend.",
     "Yes yes yes yes.", "Affirmative, friend."),
]

U11_AC_V = [
    ("been", "the past participle of be"),
    ("gone", "the past participle of go"),
    ("seen", "the past participle of see"),
    ("done", "the past participle of do"),
    ("had", "the past participle of have"),
    ("made", "the past participle of make"),
    ("taken", "the past participle of take"),
    ("given", "the past participle of give"),
    ("eaten", "the past participle of eat"),
    ("drunk", "the past participle of drink"),
    ("written", "the past participle of write"),
    ("spoken", "the past participle of speak"),
    ("met", "the past participle of meet"),
    ("found", "the past participle of find"),
    ("bought", "the past participle of buy"),
    ("flown", "the past participle of fly"),
    ("swum", "the past participle of swim"),
    ("driven", "the past participle of drive"),
    ("forgotten", "the past participle of forget"),
    ("won", "the past participle of win"),
    ("lost", "the past participle of lose"),
    ("read", "the past participle of read"),
    ("known", "the past participle of know"),
    ("worn", "the past participle of wear"),
    ("broken", "the past participle of break"),
]

U11_AC_G = [
    ("I ___ never been to London.", "have", "has", "am", "did"),
    ("She ___ seen that film.", "has", "have", "is", "did"),
    ("They ___ been to Samarkand three times.", "have", "has", "are", "did"),
    ("___ you ever eaten sushi?", "Have", "Has", "Did", "Are"),
    ("___ he ever ridden a horse?", "Has", "Have", "Did", "Is"),
    ("'Have you been to Turkey?' 'Yes, ___.'", "I have", "I has", "I did",
     "have I"),
    ("'Has she met him?' 'No, ___.'", "she hasn't", "she haven't", "she didn't",
     "she isn't"),
    ("I've ___ been on a plane.", "never", "ever", "yet", "already"),
    ("Which is correct?", "We have taken a lot of photos.",
     "We have took a lot of photos.", "We has taken a lot of photos.",
     "We have take a lot of photos."),
    ("Which is WRONG?", "He has went to the shop.", "He has gone to the shop.",
     "He went to the shop.", "Has he gone to the shop?"),
    ("She's ___ to Paris. She's there now.", "gone", "been", "go", "went"),
    ("She's ___ to Paris twice. She's at home now.", "been", "gone", "go",
     "went"),
    ("The past participle of 'write' is ___.", "written", "wrote", "writed",
     "writing"),
    ("The past participle of 'break' is ___.", "broken", "broke", "breaked",
     "breaking"),
    ("Which sentence is about experience in your life?",
     "I've visited six countries.", "I visited Turkey in 2022.",
     "I was in Turkey last year.", "I am visiting Turkey now."),
    ("We ___ never tried Korean food.", "have", "has", "are", "did"),
    ("Somebody says 'I love this book.' A short reply that shows interest: '___'",
     "Do you? Why?", "Do I?", "You are?", "Am I?"),
    ("Somebody says 'I've been to Japan.' You reply: '___'", "Have you? Wow!",
     "Do you? Wow!", "Are you? Wow!", "Did you have? Wow!"),
    ("'I don't like this song.' '___ do I.'", "Neither", "So", "Too", "Also"),
    ("'I really enjoyed it.' '___ did I.'", "So", "Neither", "Too", "Also"),
    ("Which reply shows you are surprised?", "Really? That's amazing!",
     "Yes. Fine.", "OK, next.", "I know it already fine."),
    ("Which reply asks for more?", "Tell me more about it.",
     "Stop talking about it.", "I know everything.", "Not interesting to me."),
    ("'It's the best concert I've ever been to.' 'I ___ believe it!'",
     "can't", "don't can", "am not can", "no can"),
    ("Which is a polite way to disagree?", "I see what you mean, but...",
     "You are wrong.", "That's stupid.", "No, no, no."),
    ("'What ___ you think of it?' 'It was great.'", "did", "have", "are",
     "has"),
]

U11_BD_V = [
    ("song", "a short piece of music with words"),
    ("band", "a group of people who play music together"),
    ("singer", "the person who sings"),
    ("guitar", "an instrument with six strings"),
    ("piano", "a big instrument with black and white keys"),
    ("drums", "you hit them to keep the beat"),
    ("violin", "a small string instrument you hold under your chin"),
    ("concert", "a live musical performance"),
    ("audience", "the people who watch and listen"),
    ("stage", "the raised part the musicians stand on"),
    ("ticket", "you buy it to get into a concert"),
    ("album", "a collection of songs released together"),
    ("lyrics", "the words of a song"),
    ("melody", "the tune you can sing"),
    ("rhythm", "the regular beat of the music"),
    ("instrument", "any object you play music on"),
    ("composer", "the person who writes the music"),
    ("orchestra", "a large group of musicians with many instruments"),
    ("choir", "a group of people who sing together"),
    ("volume", "how loud or quiet the sound is"),
    ("live music", "music played in front of you, not recorded"),
    ("headphones", "you wear them to listen alone"),
    ("record", "put music onto a machine to keep it"),
    ("perform", "play or sing in front of people"),
    ("practise", "play again and again to improve"),
]

U11_BD_G = [
    ("I ___ that film last night.", "saw", "have seen", "seen", "did seen"),
    ("I ___ that film three times.", "have seen", "saw", "seen", "did see"),
    ("She ___ to Turkey in 2023.", "went", "has gone", "has been", "goes"),
    ("She ___ to Turkey twice.", "has been", "went", "was", "is going"),
    ("We ___ the concert last Friday.", "enjoyed", "have enjoyed", "enjoy",
     "has enjoyed"),
    ("___ you ever played the guitar?", "Have", "Did", "Do", "Are"),
    ("___ you play the guitar at the concert last week?", "Did", "Have",
     "Do", "Are"),
    ("Which sentence says when?", "I bought this album last year.",
     "I've bought this album.", "I've never bought an album.",
     "I have bought albums."),
    ("Which sentence does not say when?", "I've been to a live concert.",
     "I went to a concert in May.", "I saw them last year.",
     "I watched them yesterday."),
    ("Which is correct?", "He has lived here since 2020.",
     "He has lived here in 2020.", "He lived here since 2020.",
     "He is living here since 2020."),
    ("I've played the piano ___ five years.", "for", "since", "from", "during"),
    ("She's been in the band ___ last summer.", "since", "for", "from",
     "during"),
    ("Which is WRONG?", "I have seen him yesterday.", "I saw him yesterday.",
     "I have seen him before.", "I haven't seen him today."),
    ("'___ you finished your homework?' 'Yes, just now.'", "Have", "Did",
     "Are", "Do"),
    ("They ___ their new album last month.", "recorded", "have recorded",
     "record", "has recorded"),
    ("I ___ never heard this song before.", "have", "has", "did", "am"),
    ("A review often begins: 'I ___ this film last weekend.'", "watched",
     "have watched then", "watch then", "am watching last"),
    ("In a review, 'the acting was ___' praises the actors.", "excellent",
     "excellently", "excellence", "more excellent of"),
    ("Which sentence is a recommendation?", "You should definitely see it.",
     "You should not to see it.", "See you it must.", "It is see for you."),
    ("Which sentence is a criticism?", "The story was too slow.",
     "The story was more slow too.", "The story is slowest too.",
     "The story too slowly was."),
    ("'What did you think ___ the film?'", "of", "for", "to", "about of"),
    ("'It's ___ the best film of the year.' 'I agree.'", "probably",
     "probable", "probability", "probably of"),
    ("In a review you give the ___ first, then your opinion.", "story",
     "opinion again", "price of ticket", "cinema address"),
    ("Which is a good closing line for a review?",
     "I'd recommend it to anyone who likes comedies.",
     "The end of my review is here.", "I have written about this film.",
     "This was my review, thank you for the reading."),
    ("'Have you seen it ___?' 'Not yet.'", "yet", "already", "still", "ever yet"),
]

U12_AC_V = [
    ("mountain", "very high land with a peak"),
    ("hill", "high land, but not as high as a mountain"),
    ("river", "water that flows to the sea"),
    ("lake", "water with land all around it"),
    ("sea", "the salt water around the land"),
    ("island", "land with water all around it"),
    ("beach", "the sand at the edge of the sea"),
    ("desert", "a very dry place with sand"),
    ("forest", "a large area of trees"),
    ("valley", "the low land between two hills"),
    ("waterfall", "water falling from a high place"),
    ("coast", "where the land meets the sea"),
    ("field", "flat land where crops grow"),
    ("village", "a very small place where people live"),
    ("countryside", "the land away from towns"),
    ("border", "the line between two countries"),
    ("capital", "the main city of a country"),
    ("region", "one part of a country"),
    ("view", "what you can see from a place"),
    ("weather", "whether it is hot, cold, wet or dry"),
    ("climate", "the usual weather of a place"),
    ("landscape", "the way the land looks"),
    ("wildlife", "the wild animals of a place"),
    ("cave", "a large hole in a hill or under the ground"),
    ("bridge", "it crosses a river"),
]

U12_AC_G = [
    ("I ___ visit my cousin next week.", "am going to", "going to", "am go to",
     "will going to"),
    ("She ___ study medicine.", "is going to", "going to", "is go to",
     "are going to"),
    ("They ___ travel by train.", "are going to", "is going to", "going to",
     "are go to"),
    ("We ___ going to fly. We're taking the bus.", "aren't", "isn't", "not",
     "don't"),
    ("He ___ going to come. He's busy.", "isn't", "aren't", "not", "doesn't"),
    ("___ you going to book a hotel?", "Are", "Do", "Is", "Have"),
    ("___ she going to come with us?", "Is", "Are", "Does", "Has"),
    ("'Are you going to stay long?' 'Yes, ___.'", "I am", "I do", "I'm going",
     "am I"),
    ("Which is correct?", "We're going to see the mountains.",
     "We going to see the mountains.", "We're go to see the mountains.",
     "We're going see the mountains."),
    ("Which is WRONG?", "He is going to plays football.",
     "He is going to play football.", "He isn't going to play football.",
     "Is he going to play football?"),
    ("Look at those clouds! It ___ rain.", "is going to", "goes to", "going to",
     "will going"),
    ("What ___ you going to do at the weekend?", "are", "do", "is", "have"),
    ("Which sentence is about a plan?", "I'm going to learn to drive.",
     "I learn to drive.", "I learned to drive.", "I am learn to drive."),
    ("We ___ going to be late if we don't hurry.", "are", "is", "do", "have"),
    ("I'm going to ___ some photos of the lake.", "take", "do", "make", "put"),
    ("My family ___ going to spend a week by the sea.", "are", "is going",
     "be", "have"),
    ("At a hotel: 'I'd like to ___ in, please.'", "check", "sign of", "enter of",
     "register of me"),
    ("'Have you got a ___?' 'Yes, under Karimov.'", "reservation", "reserve of",
     "booking of place", "order of room"),
    ("'How many ___ are you staying?' 'Three.'", "nights", "sleeps", "days of",
     "times of night"),
    ("'Is breakfast ___?' 'Yes, from seven to ten.'", "included", "inside of",
     "with it of", "together"),
    ("'Could I have a ___ room, please?'", "double", "two", "couple of",
     "pair of"),
    ("Somebody says 'We climbed the mountain in two hours.' You show surprise: '___'",
     "Did you really?", "Do you really?", "Are you really?", "Have you really?"),
    ("Somebody says 'I'm going to swim in the lake.' Surprise: '___'",
     "Are you? It's freezing!", "Do you? It's freezing!",
     "Have you? It's freezing!", "Did you? It's freezing!"),
    ("'What time is ___?' 'Twelve o'clock.'", "check-out", "check out of time",
     "leaving of hotel", "the exit of"),
    ("'Could you tell me where the ___ office is?' 'Next to the station.'",
     "tourist", "tour of", "travel of tourists", "visit of"),
]

U12_BD_V = [
    ("book a flight", "arrange a plane seat in advance"),
    ("pack a suitcase", "put your clothes in your bag before a trip"),
    ("catch a flight", "get on your plane in time"),
    ("check in", "tell the hotel or airport you have arrived"),
    ("go sightseeing", "visit the interesting places of a city"),
    ("take a tour", "go round a place with a guide"),
    ("hire a car", "pay to use a car for a few days"),
    ("get lost", "not know where you are"),
    ("find your way", "work out how to get there"),
    ("stay in a hostel", "sleep somewhere cheap with shared rooms"),
    ("go camping", "sleep outdoors in a tent"),
    ("travel light", "take very little with you"),
    ("passport", "the document you show at the border"),
    ("visa", "the permission you need to enter some countries"),
    ("luggage", "all the bags you travel with"),
    ("guidebook", "a book that tells you about a place"),
    ("souvenir", "something you buy to remember a trip"),
    ("journey", "the travelling itself"),
    ("trip", "a short visit somewhere and back"),
    ("holiday", "the time you take off work to rest"),
    ("abroad", "in another country"),
    ("local", "belonging to the place you are visiting"),
    ("currency", "the money of a country"),
    ("exchange rate", "how much your money is worth there"),
    ("delayed", "later than the time it should be"),
]

U12_BD_G = [
    ("You ___ take warm clothes. It's cold there.", "should", "should to",
     "are should", "shoulds"),
    ("You ___ drink the tap water here.", "shouldn't", "should not to",
     "don't should", "aren't should"),
    ("___ I book the hotel now?", "Should", "Do should", "Am should",
     "Have should"),
    ("'Should I take a taxi?' 'Yes, ___.'", "you should", "you should to",
     "you shoulds", "should you"),
    ("Which is correct?", "You should visit the old city.",
     "You should to visit the old city.", "You should visiting the old city.",
     "You shoulds visit the old city."),
    ("Which is WRONG?", "He shoulds pack tonight.", "He should pack tonight.",
     "He shouldn't pack tonight.", "Should he pack tonight?"),
    ("You ___ leave your passport in the hotel room.", "shouldn't", "not should",
     "don't should", "aren't should"),
    ("We ___ book early. The flights get full.", "should", "should to",
     "are should", "should of"),
    ("What ___ we do in Samarkand?", "should", "shall to", "must to", "should to"),
    ("You ___ be at the airport two hours early.", "should", "should to",
     "are should to", "should being"),
    ("Which gives advice?", "You should try the local food.",
     "You are trying the local food.", "You tried the local food.",
     "You will trying the local food."),
    ("If you are lost, you ___ ask a local person.", "should", "should to",
     "are should", "shoulding"),
    ("I think you ___ take an umbrella.", "should", "shall of", "would to",
     "should to"),
    ("You ___ pack too much. Travel light.", "shouldn't", "not should",
     "don't should", "shouldn't to"),
    ("'Do I need a visa?' 'You ___ check online.'", "should", "should to",
     "are should", "should of"),
    ("Where ___ we stay, a hotel or a hostel?", "should", "shall to",
     "should to", "must to"),
    ("Before a flight you should ___ your suitcase the night before.", "pack",
     "package", "packing of", "put in of"),
    ("At the airport you ___ in two hours before the flight.", "check", "book",
     "pack", "sign of"),
    ("If you want to see the sights, you can ___ a guided tour.", "take",
     "make", "do", "have of"),
    ("We're going to ___ a car and drive to the mountains.", "hire", "borrow of",
     "take of it", "buy of hire"),
    ("Don't forget your ___. You can't cross the border without it.", "passport",
     "ticket of bus", "guidebook", "souvenir"),
    ("The flight is ___ by two hours because of the weather.", "delayed",
     "late of time", "slow of", "delay"),
    ("I always buy a small ___ to remember the trip.", "souvenir", "memory of",
     "remember of", "present of me"),
    ("We stayed in a ___ because the hotels were full.", "hostel", "host of",
     "hosting", "hotel of cheap"),
    ("Which sentence gives good travel advice?",
     "You should keep your money in different places.",
     "You should to keep money.", "Keep you money should.",
     "You are should keep money."),
]

LISTS = [
    ("Unit 9A&C · Vocabulary — shopping", "vocab", 17, U9_AC_V),
    ("Unit 9A&C · Grammar — what is happening now, and buying clothes", "grammar", 17, U9_AC_G),
    ("Unit 9B&D · Vocabulary — clothes and presents", "vocab", 18, U9_BD_V),
    ("Unit 9B&D · Grammar — usually or right now, and saying thank you", "grammar", 18, U9_BD_G),
    ("Unit 10A&C · Vocabulary — using a computer", "vocab", 19, U10_AC_V),
    ("Unit 10A&C · Grammar — comparing two things, and asking for help", "grammar", 19, U10_AC_G),
    ("Unit 10B&D · Vocabulary — describing things", "vocab", 20, U10_BD_V),
    ("Unit 10B&D · Grammar — the best and the worst, and messages", "grammar", 20, U10_BD_G),
    ("Unit 11A&C · Vocabulary — past participles", "vocab", 21, U11_AC_V),
    ("Unit 11A&C · Grammar — have you ever, and replying to opinions", "grammar", 21, U11_AC_G),
    ("Unit 11B&D · Vocabulary — music", "vocab", 22, U11_BD_V),
    ("Unit 11B&D · Grammar — present perfect or past simple, and reviews", "grammar", 22, U11_BD_G),
    ("Unit 12A&C · Vocabulary — land and water", "vocab", 23, U12_AC_V),
    ("Unit 12A&C · Grammar — going to, and at a hotel", "grammar", 23, U12_AC_G),
    ("Unit 12B&D · Vocabulary — travelling", "vocab", 24, U12_BD_V),
    ("Unit 12B&D · Grammar — should, and travel advice", "grammar", 24, U12_BD_G),
]
