"""Empower Beginner Units 1-3, as Play steps - A, B and C taught separately.

At Beginner Azamat teaches 1A, 1B and 1C as three separate lessons, so each
lesson gets its own step rather than being paired the way Elementary is.

Units 1-3 follow his own lesson scripts in ~/Documents/Beginner LMS:
    1A  I'm from Mexico     countries; be - I, you, we
    1B  He's Italian        nationalities; be - he, she, they
    1C  Everyday English    greetings and introducing yourself
    2A  Places and towns    city, town, village; it's / it isn't
    2B  Common objects      a / an; this / that; plurals
    2C  Everyday English    asking for things and prices
    3A  Food                food words; like / don't like
    3B  Meals and drinks    present simple - I, you, we
    3C  Everyday English    ordering in a cafe

Meanings are in Uzbek and Russian. A beginner cannot read an English
definition, so giving one as an option would test the wrong thing.
"""

LEVEL = "Beginner"
BOOK = "Empower Beginner"
PAST_FROM = 9        # the past simple is not met until late in this book


def lines_vocab(items):
    return items


# ---- 1A vocabulary: countries --------------------------------------------
U1A_V = [
    ("Uzbekistan", "O'zbekiston / Узбекистан"),
    ("Mexico", "Meksika / Мексика"),
    ("Spain", "Ispaniya / Испания"),
    ("Italy", "Italiya / Италия"),
    ("Turkey", "Turkiya / Турция"),
    ("Russia", "Rossiya / Россия"),
    ("France", "Fransiya / Франция"),
    ("Germany", "Germaniya / Германия"),
    ("China", "Xitoy / Китай"),
    ("Japan", "Yaponiya / Япония"),
    ("Korea", "Koreya / Корея"),
    ("Brazil", "Braziliya / Бразилия"),
    ("Egypt", "Misr / Египет"),
    ("India", "Hindiston / Индия"),
    ("Poland", "Polsha / Польша"),
    ("Greece", "Gretsiya / Греция"),
    ("the UK", "Buyuk Britaniya / Великобритания"),
    ("the USA", "Amerika Qo'shma Shtatlari / США"),
    ("Kazakhstan", "Qozog'iston / Казахстан"),
    ("Canada", "Kanada / Канада"),
    ("Australia", "Avstraliya / Австралия"),
    ("Portugal", "Portugaliya / Португалия"),
    ("Saudi Arabia", "Saudiya Arabistoni / Саудовская Аравия"),
    ("Afghanistan", "Afg'oniston / Афганистан"),
    ("Kyrgyzstan", "Qirg'iziston / Киргизия"),
]

# ---- 1A grammar: be, I / you / we ----------------------------------------
U1A_G = [
    ("Hi, ___ Azamat.", "I'm", "I is", "I are", "Am I"),
    ("___ from Uzbekistan.", "I'm", "I am not from", "Me is", "I be"),
    ("We ___ students.", "are", "is", "am", "be"),
    ("___ from Spain. (we, positive)", "We're", "We is", "We am", "Us are"),
    ("You ___ in my class.", "are", "is", "am", "be"),
    ("___ you from Turkey?", "Are", "Is", "Am", "Do"),
    ("I ___ a teacher. (negative)", "am not", "not am", "are not", "is not"),
    ("We ___ from Italy. (negative)", "aren't", "isn't", "amn't", "not are"),
    ("___ I in room 5?", "Am", "Are", "Is", "Do"),
    ("Where ___ you from?", "are", "is", "am", "be"),
    ("How ___ you?", "are", "is", "am", "be"),
    ("What ___ your name?", "is", "are", "am", "be"),
    ("Nice to ___ you.", "meet", "meeting", "met", "meets"),
    ("A: Are you from the UK? B: No, ___.", "I'm not", "I not", "I don't", "am not I"),
    ("A: Are you students? B: Yes, ___.", "we are", "we're", "we is", "us are"),
    ("___ name is Sophia.", "My", "I", "Me", "Mine"),
    ("'I'm' means ___.", "I am", "I are", "my", "me"),
    ("'We're' means ___.", "we are", "we is", "we am", "our"),
    ("'You're' means ___.", "you are", "you is", "your", "you am"),
    ("I'm ___ student.", "a", "an", "the", "-"),
    ("She and I ___ friends.", "are", "is", "am", "be"),
    ("___ your teacher.", "I'm", "I", "Me", "My"),
    ("Hello! ___ Camila.", "I'm", "Im", "I", "Me"),
    ("A: How are you? B: ___, thank you.", "I'm fine", "I fine", "Fine I am", "Me fine"),
    ("We ___ not from Mexico.", "are", "is", "am", "be"),
]

# ---- 1B vocabulary: nationalities ----------------------------------------
U1B_V = [
    ("Uzbek", "o'zbek / узбек"),
    ("Mexican", "meksikalik / мексиканец"),
    ("Spanish", "ispan / испанец"),
    ("Italian", "italyan / итальянец"),
    ("Turkish", "turk / турок"),
    ("Russian", "rus / русский"),
    ("French", "fransuz / француз"),
    ("German", "nemis / немец"),
    ("Chinese", "xitoylik / китаец"),
    ("Japanese", "yapon / японец"),
    ("Korean", "koreys / кореец"),
    ("Brazilian", "braziliyalik / бразилец"),
    ("Egyptian", "misrlik / египтянин"),
    ("Indian", "hind / индиец"),
    ("Polish", "polyak / поляк"),
    ("Greek", "yunon / грек"),
    ("British", "britaniyalik / британец"),
    ("American", "amerikalik / американец"),
    ("Kazakh", "qozoq / казах"),
    ("Canadian", "kanadalik / канадец"),
    ("Australian", "avstraliyalik / австралиец"),
    ("Portuguese", "portugal / португалец"),
    ("Arabic", "arab tili / арабский язык"),
    ("Afghan", "afg'on / афганец"),
    ("Kyrgyz", "qirg'iz / киргиз"),
]

# ---- 1B grammar: be, he / she / they -------------------------------------
U1B_G = [
    ("Marco is from Italy. ___ Italian.", "He's", "She's", "It's", "They're"),
    ("Sofia is from Spain. ___ Spanish.", "She's", "He's", "It's", "We're"),
    ("Ali and Bek are from Uzbekistan. ___ Uzbek.", "They're", "He's", "She's", "It's"),
    ("He ___ from Japan.", "is", "are", "am", "be"),
    ("They ___ my friends.", "are", "is", "am", "be"),
    ("She ___ a teacher. (negative)", "isn't", "aren't", "amn't", "not is"),
    ("They ___ from Turkey. (negative)", "aren't", "isn't", "amn't", "not are"),
    ("___ he from Brazil?", "Is", "Are", "Am", "Do"),
    ("___ they students?", "Are", "Is", "Am", "Do"),
    ("A: Is she German? B: Yes, ___.", "she is", "she's", "her is", "is she"),
    ("A: Are they Korean? B: No, ___.", "they aren't", "they not", "they don't", "aren't they"),
    ("What ___ his name?", "is", "are", "am", "be"),
    ("Where ___ they from?", "are", "is", "am", "be"),
    ("___ name is Harumi.", "Her", "She", "Hers", "She's"),
    ("___ name is Berkay.", "His", "He", "Him", "He's"),
    ("'He's' means ___.", "he is", "he are", "his", "him"),
    ("'They're' means ___.", "they are", "they is", "their", "them"),
    ("Anna is Polish. ___ from Warsaw.", "She's", "He's", "They're", "It's"),
    ("My parents ___ from Kazakhstan.", "are", "is", "am", "be"),
    ("This is my sister. ___ a doctor.", "She's", "He's", "It's", "They're"),
    ("Tom and I ___ in the same class.", "are", "is", "am", "be"),
    ("She's French. She's from ___.", "France", "French", "Frances", "the France"),
    ("He's from China. He's ___.", "Chinese", "China", "Chinaman", "Chinish"),
    ("They ___ Egyptian. They're Greek.", "aren't", "isn't", "amn't", "not"),
    ("___ is my teacher.", "He", "His", "Him", "He's"),
]

# ---- 1C everyday English: greetings --------------------------------------
U1C_V = [
    ("Good morning", "Xayrli tong / Доброе утро"),
    ("Good afternoon", "Xayrli kun / Добрый день"),
    ("Good evening", "Xayrli kech / Добрый вечер"),
    ("Good night", "Xayrli tun / Спокойной ночи"),
    ("Hello", "Salom / Здравствуйте"),
    ("Hi", "Salom (norasmiy) / Привет"),
    ("Goodbye", "Xayr / До свидания"),
    ("Bye", "Xayr (norasmiy) / Пока"),
    ("See you later", "Keyinroq ko'rishamiz / Увидимся позже"),
    ("See you tomorrow", "Ertaga ko'rishamiz / До завтра"),
    ("How are you?", "Qalaysiz? / Как дела?"),
    ("I'm fine, thanks", "Yaxshi, rahmat / Хорошо, спасибо"),
    ("Not bad", "Yomon emas / Неплохо"),
    ("And you?", "Sizchi? / А вы?"),
    ("What's your name?", "Ismingiz nima? / Как вас зовут?"),
    ("My name's Sophia", "Mening ismim Sofiya / Меня зовут София"),
    ("Nice to meet you", "Tanishganimdan xursandman / Приятно познакомиться"),
    ("This is my friend", "Bu mening do'stim / Это мой друг"),
    ("Please", "Iltimos / Пожалуйста"),
    ("Thank you", "Rahmat / Спасибо"),
    ("You're welcome", "Arzimaydi / Пожалуйста (в ответ)"),
    ("Sorry", "Kechirasiz / Извините"),
    ("Excuse me", "Uzr, ruxsat bering / Простите, позвольте"),
    ("Yes, of course", "Ha, albatta / Да, конечно"),
    ("I don't understand", "Tushunmadim / Я не понимаю"),
]

# ---- 2A vocabulary: places and towns -------------------------------------
U2A_V = [
    ("city", "katta shahar / город"),
    ("town", "kichik shahar / городок"),
    ("village", "qishloq / деревня"),
    ("street", "ko'cha / улица"),
    ("park", "bog' / парк"),
    ("shop", "do'kon / магазин"),
    ("market", "bozor / рынок"),
    ("school", "maktab / школа"),
    ("hospital", "kasalxona / больница"),
    ("bank", "bank / банк"),
    ("restaurant", "restoran / ресторан"),
    ("cafe", "kafe / кафе"),
    ("hotel", "mehmonxona / гостиница"),
    ("station", "bekat / вокзал"),
    ("airport", "aeroport / аэропорт"),
    ("museum", "muzey / музей"),
    ("library", "kutubxona / библиотека"),
    ("cinema", "kinoteatr / кинотеатр"),
    ("mosque", "masjid / мечеть"),
    ("bus stop", "avtobus bekati / автобусная остановка"),
    ("square", "maydon / площадь"),
    ("river", "daryo / река"),
    ("mountain", "tog' / гора"),
    ("beach", "plyaj / пляж"),
    ("capital", "poytaxt / столица"),
]

# ---- 2A grammar: it's / it isn't -----------------------------------------
U2A_G = [
    ("___ a big city.", "It's", "Its", "It", "He's"),
    ("___ a village. It's a town.", "It isn't", "It's not a", "Is not", "It aren't"),
    ("A city is ___ than a town.", "bigger", "big", "biggest", "more big"),
    ("A village is ___ small.", "very", "much", "many", "lot"),
    ("___ it a big town?", "Is", "Are", "Am", "Does"),
    ("A: Is it a city? B: Yes, ___.", "it is", "it's", "is it", "it are"),
    ("A: Is it beautiful? B: No, ___.", "it isn't", "it not", "it doesn't", "isn't it"),
    ("I'm from ___ village.", "a", "an", "the", "-"),
    ("Tashkent is ___ capital of Uzbekistan.", "the", "a", "an", "-"),
    ("It's ___ old city.", "an", "a", "the", "-"),
    ("___ is your town?", "Where", "What", "Who", "How"),
    ("The park is ___ the city.", "in", "on", "at", "to"),
    ("My house is ___ Navoi Street.", "on", "in", "at", "to"),
    ("It's a ___ town.", "small", "smalls", "smally", "more small"),
    ("What ___ it like?", "is", "are", "am", "does"),
    ("The shops ___ open.", "are", "is", "am", "be"),
    ("It's a nice place ___ live.", "to", "for", "of", "at"),
    ("There ___ a bank near my house.", "is", "are", "am", "be"),
    ("There ___ two schools in my village.", "are", "is", "am", "be"),
    ("___ there a hospital here?", "Is", "Are", "Am", "Does"),
    ("It's not big. It's ___.", "small", "big", "very", "a"),
    ("My city is ___ and beautiful.", "big", "bigger", "biggest", "more big"),
    ("The museum ___ old.", "is", "are", "am", "be"),
    ("A: What is it? B: ___ a market.", "It's", "Its", "It", "There"),
    ("Bukhara is ___ old city.", "an", "a", "the", "-"),
]

# ---- 2B vocabulary: common objects ---------------------------------------
U2B_V = [
    ("computer", "kompyuter / компьютер"),
    ("phone", "telefon / телефон"),
    ("newspaper", "gazeta / газета"),
    ("knife", "pichoq / нож"),
    ("key", "kalit / ключ"),
    ("watch", "qo'l soati / наручные часы"),
    ("umbrella", "soyabon / зонт"),
    ("ticket", "chipta / билет"),
    ("book", "kitob / книга"),
    ("bottle", "shisha / бутылка"),
    ("bag", "sumka / сумка"),
    ("pen", "ruchka / ручка"),
    ("pencil", "qalam / карандаш"),
    ("notebook", "daftar / тетрадь"),
    ("chair", "stul / стул"),
    ("table", "stol / стол"),
    ("window", "deraza / окно"),
    ("door", "eshik / дверь"),
    ("wallet", "hamyon / кошелёк"),
    ("camera", "fotoapparat / фотоаппарат"),
    ("glasses", "ko'zoynak / очки"),
    ("passport", "pasport / паспорт"),
    ("map", "xarita / карта"),
    ("clock", "devor soati / настенные часы"),
    ("box", "quti / коробка"),
]

# ---- 2B grammar: a / an, this / that, plurals ----------------------------
U2B_G = [
    ("It's ___ umbrella.", "an", "a", "the", "-"),
    ("It's ___ computer.", "a", "an", "the", "-"),
    ("It's ___ apple.", "an", "a", "the", "-"),
    ("It's ___ key.", "a", "an", "the", "-"),
    ("It's ___ egg.", "an", "a", "the", "-"),
    ("___ is my bag. (here)", "This", "That", "These", "Those"),
    ("___ is your bag. (over there)", "That", "This", "These", "Those"),
    ("___ are my books. (here)", "These", "This", "That", "Those"),
    ("___ are her keys. (over there)", "Those", "These", "This", "That"),
    ("one book, two ___", "books", "bookes", "book", "bookies"),
    ("one watch, two ___", "watches", "watchs", "watch", "watchies"),
    ("one knife, two ___", "knives", "knifes", "knife", "knifs"),
    ("one box, two ___", "boxes", "boxs", "box", "boxies"),
    ("one child, two ___", "children", "childs", "childrens", "child"),
    ("one man, two ___", "men", "mans", "mens", "man"),
    ("one woman, two ___", "women", "womans", "womens", "woman"),
    ("What ___ this?", "is", "are", "am", "does"),
    ("What ___ these?", "are", "is", "am", "does"),
    ("___ a pen, not a pencil.", "It's", "Its", "They're", "These"),
    ("They ___ my glasses.", "are", "is", "am", "be"),
    ("Is this ___ phone?", "your", "you", "yours", "you're"),
    ("It isn't my bag. It's ___.", "hers", "her", "she", "she's"),
    ("Whose book is this? It's ___.", "mine", "my", "me", "I"),
    ("The keys ___ on the table.", "are", "is", "am", "be"),
    ("There ___ some books here.", "are", "is", "am", "be"),
]

# ---- 2C everyday English: asking for things -------------------------------
U2C_V = [
    ("Can I have a coffee, please?", "Menga kofe bering, iltimos / Можно мне кофе, пожалуйста?"),
    ("How much is it?", "Bu qancha turadi? / Сколько это стоит?"),
    ("How much are they?", "Ular qancha turadi? / Сколько они стоят?"),
    ("It's five dollars", "Bu besh dollar / Это пять долларов"),
    ("Here you are", "Mana, oling / Вот, пожалуйста"),
    ("Anything else?", "Yana biror narsa kerakmi? / Что-нибудь ещё?"),
    ("No, thanks", "Yo'q, rahmat / Нет, спасибо"),
    ("That's all", "Hammasi shu / Это всё"),
    ("Do you have a bag?", "Sizda sumka bormi? / У вас есть пакет?"),
    ("I'd like this one", "Men shuni olaman / Я хотел бы вот этот"),
    ("Excuse me, how much?", "Kechirasiz, qancha? / Извините, сколько?"),
    ("Can I pay by card?", "Karta bilan to'lasam bo'ladimi? / Можно оплатить картой?"),
    ("Cash, please", "Naqd pul bilan / Наличными, пожалуйста"),
    ("Here's your change", "Mana qaytimingiz / Вот ваша сдача"),
    ("Sorry, we don't have it", "Kechirasiz, bizda yo'q / Извините, у нас этого нет"),
    ("What size?", "Qaysi o'lcham? / Какой размер?"),
    ("It's too expensive", "Bu juda qimmat / Это слишком дорого"),
    ("It's cheap", "Bu arzon / Это дёшево"),
    ("Is it open?", "U ochiqmi? / Он открыт?"),
    ("It's closed", "U yopiq / Он закрыт"),
    ("one thousand", "bir ming / одна тысяча"),
    ("a hundred", "yuz / сто"),
    ("twenty", "yigirma / двадцать"),
    ("fifty", "ellik / пятьдесят"),
    ("Thank you very much", "Katta rahmat / Большое спасибо"),
]

# ---- 3A vocabulary: food --------------------------------------------------
U3A_V = [
    ("meat", "go'sht / мясо"),
    ("fish", "baliq / рыба"),
    ("chicken", "tovuq / курица"),
    ("vegetables", "sabzavotlar / овощи"),
    ("fruit", "meva / фрукты"),
    ("rice", "guruch / рис"),
    ("bread", "non / хлеб"),
    ("eggs", "tuxum / яйца"),
    ("cheese", "pishloq / сыр"),
    ("butter", "sariyog' / сливочное масло"),
    ("milk", "sut / молоко"),
    ("potato", "kartoshka / картофель"),
    ("tomato", "pomidor / помидор"),
    ("onion", "piyoz / лук"),
    ("carrot", "sabzi / морковь"),
    ("apple", "olma / яблоко"),
    ("banana", "banan / банан"),
    ("grapes", "uzum / виноград"),
    ("sugar", "shakar / сахар"),
    ("salt", "tuz / соль"),
    ("soup", "sho'rva / суп"),
    ("salad", "salat / салат"),
    ("pasta", "makaron / макароны"),
    ("oil", "yog' / растительное масло"),
    ("yoghurt", "qatiq / йогурт"),
]

# ---- 3A grammar: like / don't like ----------------------------------------
U3A_G = [
    ("I ___ fish.", "like", "likes", "liking", "am like"),
    ("She ___ meat.", "likes", "like", "liking", "is like"),
    ("I ___ like onions.", "don't", "doesn't", "am not", "not"),
    ("He ___ like fish.", "doesn't", "don't", "isn't", "not"),
    ("___ you like rice?", "Do", "Does", "Are", "Is"),
    ("___ she like vegetables?", "Does", "Do", "Is", "Are"),
    ("A: Do you like cheese? B: Yes, ___.", "I do", "I like", "I am", "do I"),
    ("A: Does he like milk? B: No, ___.", "he doesn't", "he don't", "he isn't", "doesn't he"),
    ("We ___ fruit very much.", "like", "likes", "liking", "are like"),
    ("They ___ eat meat.", "don't", "doesn't", "aren't", "not"),
    ("I like ___.", "apples", "apple", "a apples", "the apple"),
    ("My mother ___ soup every day.", "makes", "make", "making", "is make"),
    ("I ___ tea in the morning.", "drink", "drinks", "drinking", "am drink"),
    ("He ___ bread for breakfast.", "eats", "eat", "eating", "is eat"),
    ("What ___ you like?", "do", "does", "are", "is"),
    ("I love ___.", "chocolate", "a chocolate", "the chocolates", "chocolates a"),
    ("She ___ like sugar in her tea.", "doesn't", "don't", "isn't", "not"),
    ("___ they like fish?", "Do", "Does", "Is", "Are"),
    ("I don't like tomatoes, ___ I like carrots.", "but", "and", "or", "so"),
    ("I like meat ___ rice.", "and", "but", "or", "so"),
    ("Do you want tea ___ coffee?", "or", "and", "but", "so"),
    ("My sister ___ vegetables.", "hates", "hate", "hating", "is hate"),
    ("I eat eggs ___ breakfast.", "for", "to", "in", "at"),
    ("She likes ___ very much.", "fruit", "a fruit", "the fruits", "fruits a"),
    ("We ___ like fast food.", "don't", "doesn't", "aren't", "not"),
]

# ---- 3B vocabulary: meals and drinks --------------------------------------
U3B_V = [
    ("breakfast", "nonushta / завтрак"),
    ("lunch", "tushlik / обед"),
    ("dinner", "kechki ovqat / ужин"),
    ("meal", "ovqatlanish / приём пищи"),
    ("water", "suv / вода"),
    ("tea", "choy / чай"),
    ("coffee", "kofe / кофе"),
    ("juice", "sharbat / сок"),
    ("cup", "piyola / чашка"),
    ("glass", "stakan / стакан"),
    ("plate", "tarelka / тарелка"),
    ("spoon", "qoshiq / ложка"),
    ("fork", "vilka / вилка"),
    ("menu", "menyu / меню"),
    ("hungry", "och / голодный"),
    ("thirsty", "chanqagan / испытывающий жажду"),
    ("delicious", "juda mazali / очень вкусный"),
    ("sweet", "shirin / сладкий"),
    ("hot", "issiq / горячий"),
    ("cold", "sovuq / холодный"),
    ("fresh", "yangi, ta'mi yo'qolmagan / свежий"),
    ("cook", "ovqat pishirmoq / готовить"),
    ("drink", "ichmoq / пить"),
    ("eat", "yemoq / есть"),
    ("order", "buyurtma bermoq / заказывать"),
]

# ---- 3B grammar: present simple, I / you / we -----------------------------
U3B_G = [
    ("I ___ breakfast at 7 o'clock.", "have", "has", "having", "am have"),
    ("We ___ dinner at home.", "eat", "eats", "eating", "are eat"),
    ("You ___ a lot of tea.", "drink", "drinks", "drinking", "are drink"),
    ("They ___ lunch at school.", "have", "has", "having", "are have"),
    ("I ___ coffee in the morning.", "don't drink", "doesn't drink", "not drink", "am not drink"),
    ("We ___ breakfast on Sunday.", "don't have", "doesn't have", "not have", "aren't have"),
    ("___ you have lunch at work?", "Do", "Does", "Are", "Is"),
    ("___ they cook at home?", "Do", "Does", "Are", "Is"),
    ("A: Do you drink tea? B: Yes, ___.", "I do", "I am", "I drink", "do I"),
    ("A: Do they eat meat? B: No, ___.", "they don't", "they aren't", "they not", "don't they"),
    ("What time ___ you have dinner?", "do", "does", "are", "is"),
    ("Where ___ you eat lunch?", "do", "does", "are", "is"),
    ("I ___ hungry.", "am", "is", "are", "be"),
    ("We ___ thirsty.", "are", "is", "am", "be"),
    ("I have lunch ___ 1 o'clock.", "at", "in", "on", "to"),
    ("I have breakfast ___ the morning.", "in", "at", "on", "to"),
    ("We don't work ___ Sunday.", "on", "in", "at", "to"),
    ("I ___ like coffee.", "don't", "doesn't", "am not", "not"),
    ("Would you like a cup ___ tea?", "of", "for", "with", "in"),
    ("I'd like a glass ___ water.", "of", "for", "with", "in"),
    ("She ___ dinner for her family.", "cooks", "cook", "cooking", "is cook"),
    ("He ___ juice every day.", "drinks", "drink", "drinking", "is drink"),
    ("They always ___ rice with meat.", "eat", "eats", "eating", "are eat"),
    ("I usually ___ at home.", "eat", "eats", "eating", "am eat"),
    ("We sometimes ___ in a restaurant.", "eat", "eats", "eating", "are eat"),
]

# ---- 3C everyday English: in a cafe ---------------------------------------
U3C_V = [
    ("Can I help you?", "Sizga yordam bera olamanmi? / Чем могу помочь?"),
    ("I'd like a coffee, please", "Menga kofe, iltimos / Я бы хотел кофе, пожалуйста"),
    ("Can I have the menu?", "Menyuni bera olasizmi? / Можно меню?"),
    ("What would you like?", "Nima buyurtma qilasiz? / Что будете заказывать?"),
    ("A tea, please", "Bitta choy, iltimos / Один чай, пожалуйста"),
    ("To eat in or take away?", "Shu yerdami yoki o'zingiz bilanmi? / Здесь или с собой?"),
    ("Take away, please", "O'zim bilan olaman / С собой, пожалуйста"),
    ("With milk, please", "Sut bilan, iltimos / С молоком, пожалуйста"),
    ("Without sugar", "Shakarsiz / Без сахара"),
    ("A table for two", "Ikki kishilik stol / Столик на двоих"),
    ("Is this seat free?", "Bu joy bo'shmi? / Это место свободно?"),
    ("The bill, please", "Hisob, iltimos / Счёт, пожалуйста"),
    ("Enjoy your meal", "Yoqimli ishtaha / Приятного аппетита"),
    ("It's very good", "Juda mazali / Очень вкусно"),
    ("I'm ready to order", "Buyurtma berishga tayyorman / Я готов заказать"),
    ("Just a moment, please", "Bir daqiqa, iltimos / Минутку, пожалуйста"),
    ("Small or large?", "Kichikmi yoki kattami? / Маленький или большой?"),
    ("Still or sparkling?", "Gazsizmi yoki gazlimi? / Без газа или с газом?"),
    ("Here's the menu", "Mana menyu / Вот меню"),
    ("I'm sorry, we're closed", "Kechirasiz, biz yopiqmiz / Извините, мы закрыты"),
    ("Could I have some water?", "Menga suv bering / Можно мне воды?"),
    ("How much is a coffee?", "Kofe qancha turadi? / Сколько стоит кофе?"),
    ("That comes to ten dollars", "Jami o'n dollar / Итого десять долларов"),
    ("Keep the change", "Qaytimi kerak emas / Сдачи не надо"),
    ("Thanks, that was lovely", "Rahmat, juda yoqdi / Спасибо, было очень вкусно"),
]

LISTS = [
    ("Unit 1A · Vocabulary — countries", "vocab", 1, U1A_V),
    ("Unit 1A · Grammar — be: I, you, we", "grammar", 2, U1A_G),
    ("Unit 1B · Vocabulary — nationalities", "vocab", 3, U1B_V),
    ("Unit 1B · Grammar — be: he, she, they", "grammar", 4, U1B_G),
    ("Unit 1C · Everyday English — hello and goodbye", "vocab", 5, U1C_V),
    ("Unit 2A · Vocabulary — places in a town", "vocab", 6, U2A_V),
    ("Unit 2A · Grammar — it's and it isn't", "grammar", 7, U2A_G),
    ("Unit 2B · Vocabulary — everyday things", "vocab", 8, U2B_V),
    ("Unit 2B · Grammar — a, an, this, that, plurals", "grammar", 9, U2B_G),
    ("Unit 2C · Everyday English — asking for things", "vocab", 10, U2C_V),
    ("Unit 3A · Vocabulary — food", "vocab", 11, U3A_V),
    ("Unit 3A · Grammar — like and don't like", "grammar", 12, U3A_G),
    ("Unit 3B · Vocabulary — meals and drinks", "vocab", 13, U3B_V),
    ("Unit 3B · Grammar — present simple: I, you, we", "grammar", 14, U3B_G),
    ("Unit 3C · Everyday English — in a cafe", "vocab", 15, U3C_V),
]
