"""Empower Intermediate Units 8-10, in the A&C / B&D pairing.

    8A sharing information; reported speech   8C sharing news
    8B reporting verbs; verb patterns         8D a news story
    9A the passive                            9C arranging to go out
    9B music; relative clauses                9D contrasting ideas
    10A sport; second conditional             10C talking about luck
    10B do, make and take; third conditional  10D volunteering
"""

LEVEL = "Intermediate"
BOOK = "Empower Intermediate"
PAST_FROM = 1

I8_AC_V = [
    ("announce", "e'lon qilmoq / объявлять"),
    ("reveal", "oshkor qilmoq / раскрывать"),
    ("keep a secret", "sirni saqlamoq / хранить секрет"),
    ("let slip", "og'zidan chiqib ketmoq / проговориться"),
    ("spread news", "xabarni tarqatmoq / распространять новость"),
    ("post online", "internetga joylamoq / публиковать онлайн"),
    ("share", "ulashmoq / делиться"),
    ("update somebody", "xabardor qilib turmoq / держать в курсе"),
    ("inform", "ma'lum qilmoq / информировать"),
    ("warn", "ogohlantirmoq / предупреждать"),
    ("confirm", "tasdiqlamoq / подтверждать"),
    ("deny", "inkor etmoq / отрицать"),
    ("exaggerate", "bo'rttirib yubormoq / преувеличивать"),
    ("rumour", "mish-mish / слух"),
    ("source", "manba / источник"),
    ("private", "shaxsiy / личный"),
    ("public", "ommaviy / публичный"),
    ("confidential", "maxfiy / конфиденциальный"),
    ("reliable", "ishonchli / надёжный"),
    ("misleading", "chalg'ituvchi / вводящий в заблуждение"),
    ("fake news", "soxta yangilik / фейковая новость"),
    ("headline", "sarlavha / заголовок"),
    ("forward a message", "xabarni uzatmoq / пересылать сообщение"),
    ("go viral", "keng tarqalib ketmoq / стать вирусным"),
    ("find out", "bilib olmoq / выяснять"),
]

I8_AC_G = [
    ("'I'm tired,' she said. She said she ___ tired.", "was", "is", "has been",
     "will be"),
    ("'We've finished,' they said. They said they ___ finished.", "had",
     "have", "has", "were"),
    ("'I'll call you,' he said. He said he ___ call me.", "would", "will",
     "shall", "is going"),
    ("'I live here,' she said. She said she ___ there.", "lived", "lives",
     "is living", "has lived"),
    ("She asked me where I ___ .", "worked", "work", "do work", "am working"),
    ("He asked if I ___ help.", "needed", "need", "do need", "am needing"),
    ("'Don't be late,' she said. She told me ___ late.", "not to be",
     "to not be of", "don't be of", "that not be"),
    ("'Please sit down.' He asked us ___ .", "to sit down", "sit down",
     "that sit down", "for sitting"),
    ("Which is WRONG?", "She asked me where did I live.",
     "She asked me where I lived.", "She asked where I lived.",
     "She asked if I lived there."),
    ("In reported speech, 'tomorrow' becomes ___ .", "the next day",
     "yesterday", "that day before", "the previous day"),
    ("In reported speech, 'now' becomes ___ .", "then", "now still",
     "at the moment", "today of"),
    ("'Can you help?' She asked me ___ help her.", "if I could",
     "can I", "could I to", "that I can"),
    ("He said he ___ never been there before.", "had", "has", "was", "did"),
    ("Which verb introduces a yes/no question?", "asked if", "said that",
     "told me that", "spoke that"),
    ("Which is correct?", "They told us they were leaving.",
     "They said us they were leaving.", "They told that they were leaving.",
     "They said to leave us."),
    ("'I saw it yesterday,' he said. He said he ___ it the day before.",
     "had seen", "has seen", "saw then", "was seeing"),
    ("Sharing news: 'Have you ___ about Aziz?'", "heard", "listened of",
     "known of it", "told of"),
    ("'Apparently, they ___ moving abroad.'", "are", "is", "be", "been"),
    ("'Who told ___ ?'", "you", "to you", "at you", "for you"),
    ("'Don't say anything, it's ___ a secret.'", "still", "yet of", "already of",
     "even of"),
    ("'I heard it ___ Nodira.'", "from", "of", "by of", "at"),
    ("'Is that ___ ?' 'Apparently so.'", "true", "truth of", "truly of",
     "trust of"),
    ("'I wouldn't ___ everything you read.'", "believe", "belief of",
     "believing of", "believed of"),
    ("'Keep it to ___ for now.'", "yourself", "you", "yours of",
     "your own of it"),
    ("Which reply is most careful about a rumour?",
     "I'd wait until we hear it from them directly.",
     "Tell everyone now.", "It must be true.", "I'll post it online."),
]

I8_BD_V = [
    ("admit", "tan olmoq / признавать"),
    ("agree", "rozi bo'lmoq / соглашаться"),
    ("announce", "e'lon qilmoq / объявлять"),
    ("apologise", "uzr so'ramoq / извиняться"),
    ("claim", "da'vo qilmoq / заявлять"),
    ("complain", "shikoyat qilmoq / жаловаться"),
    ("deny", "rad etmoq / отрицать"),
    ("explain", "tushuntirmoq / объяснять"),
    ("insist", "qat'iy turib olmoq / настаивать"),
    ("invite", "taklif qilmoq / приглашать"),
    ("mention", "tilga olmoq / упоминать"),
    ("offer", "taklif qilmoq / предлагать"),
    ("persuade", "ko'ndirmoq / убеждать"),
    ("promise", "va'da qilmoq / обещать"),
    ("recommend", "tavsiya etmoq / рекомендовать"),
    ("refuse", "rad qilmoq / отказываться"),
    ("remind", "eslatmoq / напоминать"),
    ("suggest", "taklif kiritmoq / предлагать"),
    ("threaten", "tahdid qilmoq / угрожать"),
    ("warn", "ogohlantirmoq / предупреждать"),
    ("advise", "maslahat bermoq / советовать"),
    ("encourage", "rag'batlantirmoq / поощрять"),
    ("accuse", "ayblamoq / обвинять"),
    ("blame", "aybdor qilmoq / винить"),
    ("congratulate", "tabriklamoq / поздравлять"),
]

I8_BD_G = [
    ("She refused ___ the document.", "to sign", "signing", "sign",
     "for signing"),
    ("He admitted ___ the mistake.", "making", "to make", "make",
     "for making"),
    ("They agreed ___ the price.", "to pay", "paying", "pay", "for paying"),
    ("She suggested ___ a taxi.", "taking", "to take", "take", "for take"),
    ("He apologised ___ late.", "for being", "to be", "being of",
     "for be of"),
    ("They persuaded me ___ .", "to stay", "staying", "stay", "for staying"),
    ("She reminded me ___ the door.", "to lock", "locking", "lock",
     "for locking"),
    ("He denied ___ anything.", "knowing", "to know", "know", "for know"),
    ("Which verb takes -ing?", "recommend", "promise", "offer", "refuse"),
    ("Which verb takes to + infinitive?", "promise", "suggest", "admit",
     "deny"),
    ("Which is WRONG?", "He suggested to go home.",
     "He suggested going home.", "He offered to go home.",
     "He wanted to go home."),
    ("She warned us ___ the ice.", "about", "for", "of to", "from of"),
    ("They congratulated her ___ passing.", "on", "for to", "about to",
     "with of"),
    ("He accused them ___ cheating.", "of", "for", "about", "with"),
    ("She insisted ___ paying.", "on", "to", "for", "about"),
    ("Which reports an order?", "He told me to wait.", "He said to wait me.",
     "He told that wait.", "He said me waiting."),
    ("A news story usually opens with ___ .", "what happened and to whom",
     "the writer's opinion", "the weather", "a joke"),
    ("'Police ___ that two people were arrested.'", "confirmed", "confirm of",
     "confirming of", "were confirm"),
    ("'The company ___ any responsibility.'", "denied", "denies of it",
     "was denied of", "denying of"),
    ("'A spokesperson ___ for the delay.'", "apologised", "apology of",
     "apologising of", "was apologise"),
    ("'Witnesses ___ hearing a loud bang.'", "reported", "reported of it that",
     "reporting of", "were report"),
    ("'The council has ___ to review the rules.'", "promised", "promise of",
     "promising of", "was promise"),
    ("'Residents ___ about the noise for months.'", "have complained",
     "complain since", "complained since", "are complaining since"),
    ("'The driver ___ to comment.'", "refused", "refuse of", "refusing of",
     "was refuse"),
    ("Which sentence is neutral, as news should be?",
     "The council said the work would finish in March.",
     "The council is useless as always.", "This is a disaster for everyone.",
     "Nobody believes the council anyway."),
]

I9_AC_V = [
    ("plot", "syujet / сюжет"),
    ("setting", "voqea joyi / место действия"),
    ("character", "personaj / персонаж"),
    ("lead role", "bosh rol / главная роль"),
    ("cast", "aktyorlar tarkibi / актёрский состав"),
    ("scene", "sahna / сцена"),
    ("episode", "qism / серия"),
    ("season", "mavsum / сезон"),
    ("sequel", "davomi / продолжение"),
    ("trailer", "anons / трейлер"),
    ("soundtrack", "film musiqasi / саундтрек"),
    ("special effects", "maxsus effektlar / спецэффекты"),
    ("subtitles", "subtitrlar / субтитры"),
    ("script", "ssenariy / сценарий"),
    ("director", "rejissyor / режиссёр"),
    ("producer", "prodyuser / продюсер"),
    ("review", "taqriz / рецензия"),
    ("thriller", "triller / триллер"),
    ("documentary", "hujjatli film / документальный фильм"),
    ("comedy", "komediya / комедия"),
    ("based on", "asosida / основанный на"),
    ("gripping", "diqqatni tortadigan / захватывающий"),
    ("predictable", "oldindan aytib bo'ladigan / предсказуемый"),
    ("moving", "ta'sirli / трогательный"),
    ("overrated", "haddan ortiq maqtalgan / переоценённый"),
]

I9_AC_G = [
    ("The film ___ in Uzbekistan.", "was shot", "shot", "is shooting",
     "was shooting"),
    ("These series ___ in many languages.", "are dubbed", "dub",
     "are dubbing", "is dubbed"),
    ("The book ___ into fifty languages.", "has been translated",
     "has translated", "is translating", "translated has"),
    ("The scene ___ three times yesterday.", "was filmed", "filmed",
     "is filming", "was filming"),
    ("Tickets ___ online only.", "are sold", "sell of", "are selling",
     "sold are"),
    ("Which is passive?", "The script was written by a Uzbek author.",
     "A Uzbek author wrote the script.", "The author writes scripts.",
     "Writing scripts is hard."),
    ("Which is WRONG?", "The film was direct by her.",
     "The film was directed by her.", "She directed the film.",
     "The film has been directed by her."),
    ("The awards ___ every February.", "are given", "give", "are giving",
     "is given"),
    ("The set ___ at the moment.", "is being built", "is building",
     "builds", "has building"),
    ("The ending ___ before the film came out.", "had been leaked",
     "has leaked then", "was leaking then", "leaked has"),
    ("Who ___ the music composed by?", "was", "did", "is", "were"),
    ("Nothing ___ about the sequel yet.", "has been announced",
     "has announced", "is announcing", "announced has"),
    ("Which keeps the doer unimportant?", "The film was postponed.",
     "They postponed the film, the studio people.",
     "Somebody postponed it, perhaps the studio.",
     "The studio, which postponed it, did so."),
    ("The trailer ___ millions of times.", "has been watched",
     "has watched", "is watching", "watched has"),
    ("The role ___ to a newcomer.", "was given", "gave", "is giving",
     "was giving"),
    ("Cinemas ___ during the pandemic.", "were closed", "closed by",
     "are closing", "was closed"),
    ("Arranging to go out: 'Are you ___ anything on Friday?'", "doing", "do",
     "done of", "make of"),
    ("'There's a film ___ at eight.'", "on", "in", "at of", "for"),
    ("'Shall we ___ for a coffee first?'", "meet", "meeting of", "met of",
     "to meet"),
    ("'I'll ___ the tickets.'", "book", "reserve of it", "take of", "make of"),
    ("'Is seven ___ for you?'", "OK", "okay of it", "fine of the", "good of"),
    ("'I'd rather ___ something lighter.'", "see", "seeing of", "to seeing",
     "saw of"),
    ("'What ___ do you fancy?'", "kind of film", "kind film of",
     "film of kind", "type film"),
    ("'Let's ___ on that, then.'", "settle", "decide of it", "agree of",
     "fix of"),
    ("Which is the easiest plan to agree to?",
     "How about the eight o'clock show, and food afterwards?",
     "Something tonight maybe.", "Films exist.", "We could do anything."),
]

I9_BD_V = [
    ("melody", "kuy / мелодия"),
    ("rhythm", "ritm / ритм"),
    ("beat", "zarb / бит"),
    ("lyrics", "qo'shiq matni / текст песни"),
    ("chorus", "naqorat / припев"),
    ("verse", "kuplet / куплет"),
    ("album", "albom / альбом"),
    ("single", "singl / сингл"),
    ("track", "trek / трек"),
    ("band", "guruh / группа"),
    ("solo artist", "yakkaxon ijrochi / сольный исполнитель"),
    ("composer", "bastakor / композитор"),
    ("conductor", "dirijyor / дирижёр"),
    ("orchestra", "orkestr / оркестр"),
    ("choir", "xor / хор"),
    ("instrument", "cholg'u asbobi / инструмент"),
    ("perform live", "jonli ijro etmoq / выступать вживую"),
    ("record", "yozib olmoq / записывать"),
    ("release", "chiqarmoq / выпускать"),
    ("gig", "konsert / концерт"),
    ("venue", "maskan / площадка"),
    ("catchy", "tez yodda qoladigan / запоминающийся"),
    ("upbeat", "quvnoq ohangdagi / бодрый"),
    ("soothing", "tinchlantiradigan / успокаивающий"),
    ("out of tune", "sozlanmagan / фальшивый"),
]

I9_BD_G = [
    ("The singer ___ wrote this is only twenty.", "who", "which", "whose",
     "what"),
    ("That's the album ___ I told you about.", "that", "who", "whose",
     "what"),
    ("This is the band ___ songs I love.", "whose", "who's", "which",
     "that's"),
    ("The hall ___ they played is enormous.", "where", "which", "who",
     "when"),
    ("2019 was the year ___ they split up.", "when", "which", "where", "who"),
    ("Which clause needs commas?", "a non-defining clause",
     "a defining clause", "both kinds", "neither kind"),
    ("Which is non-defining?",
     "My brother, who lives in Almaty, plays guitar.",
     "The man who lives next door plays guitar.",
     "The guitar that I bought is red.", "People who sing are happy."),
    ("In which can you use 'that'?", "a defining clause",
     "a non-defining clause", "both", "neither"),
    ("Which is WRONG?", "My sister, that sings, is here.",
     "My sister, who sings, is here.", "The girl that sings is here.",
     "The girl who sings is here."),
    ("The concert, ___ lasted three hours, was fantastic.", "which", "that",
     "who", "what"),
    ("She's the only person ___ can play it.", "who", "which", "whose",
     "whom of"),
    ("The song ___ we danced is on the radio.", "to which", "which", "that",
     "where"),
    ("You can leave out the relative pronoun when it is the ___ .",
     "object of the clause", "subject of the clause", "possessive",
     "first word of the sentence"),
    ("Which sentence can drop the pronoun?", "The album (that) I bought is great.",
     "The singer who wrote it is great.", "The band that plays here is great.",
     "The venue which holds 500 is great."),
    ("Their first album, ___ came out in 2015, was a hit.", "which", "that",
     "who", "what"),
    ("This is the studio ___ the album was recorded.", "where", "which",
     "that", "who"),
    ("Contrasting ideas: 'The tickets were expensive; ___ , it was worth it.'",
     "however", "although of", "despite of", "whereas of"),
    ("'___ the price, the hall was full.'", "Despite", "Although of",
     "However of", "Whereas of"),
    ("'___ the hall was full, we found seats.'", "Although", "Despite",
     "However", "In spite"),
    ("'The first half was slow, ___ the second was brilliant.'", "whereas",
     "despite", "although of it", "however of"),
    ("'In ___ of the rain, thousands came.'", "spite", "despite of",
     "although of", "however of"),
    ("'The band was late. ___ , nobody complained.'", "Even so",
     "Even though of", "Despite of", "Although of it"),
    ("'It was loud, ___ enjoyable.'", "but", "despite", "although of",
     "however of it"),
    ("Which links two contrasting sentences?", "On the other hand,",
     "For example,", "In addition,", "As a result,"),
    ("Which sentence contrasts correctly?",
     "Although the album is short, it is excellent.",
     "Although the album is short, but it is excellent.",
     "Despite the album is short, it is excellent.",
     "However the album is short, it is excellent."),
]

I10_AC_V = [
    ("take up a sport", "sport bilan shug'ullana boshlamoq / заняться спортом"),
    ("work out", "mashq qilmoq / тренироваться"),
    ("warm up", "qizdirish mashqlari qilmoq / разминаться"),
    ("get fit", "chiniqmoq / приходить в форму"),
    ("be out of shape", "formadan chiqqan bo'lmoq / быть не в форме"),
    ("beat an opponent", "raqibni yengmoq / победить соперника"),
    ("draw a match", "durang o'ynamoq / сыграть вничью"),
    ("score a goal", "gol urmoq / забить гол"),
    ("break a record", "rekord o'rnatmoq / побить рекорд"),
    ("win a title", "unvon yutmoq / выиграть титул"),
    ("train hard", "qattiq mashq qilmoq / усердно тренироваться"),
    ("get injured", "jarohat olmoq / получить травму"),
    ("give up", "tashlab qo'ymoq / бросить"),
    ("support a team", "jamoaga xayrixoh bo'lmoq / болеть за команду"),
    ("referee", "hakam / судья"),
    ("coach", "murabbiy / тренер"),
    ("league", "chempionat ligasi / лига"),
    ("tournament", "turnir / турнир"),
    ("opponent", "raqib / соперник"),
    ("spectator", "tomoshabin / зритель"),
    ("stadium", "stadion / стадион"),
    ("teammate", "jamoadosh / партнёр по команде"),
    ("fitness", "chiniqqanlik / физическая форма"),
    ("stamina", "chidamlilik / выносливость"),
    ("competitive", "raqobatbardosh / соревновательный"),
]

I10_AC_G = [
    ("If I had more time, I ___ take up tennis.", "would", "will", "would to",
     "did"),
    ("If I ___ you, I'd rest today.", "were", "am", "will be", "would be"),
    ("What would you do if you ___ the final?", "reached", "reach",
     "would reach", "will reach"),
    ("She would join the team if she ___ nearer.", "lived", "lives",
     "would live", "will live"),
    ("If we ___ harder, we'd win more.", "trained", "train", "would train",
     "will train"),
    ("Which is imaginary, not a real plan?",
     "If I had a coach, I'd improve faster.",
     "If I have a coach, I'll improve.", "When I have a coach, I improve.",
     "I have a coach and I improve."),
    ("Which is WRONG?", "If I would be fitter, I would run.",
     "If I were fitter, I would run.", "If I was fitter, I would run.",
     "I would run if I were fitter."),
    ("He ___ play if he weren't injured.", "would", "will", "would to",
     "does"),
    ("If the match ___ tomorrow, we'd go.", "were", "is", "will be",
     "would be"),
    ("Which half has 'would'?", "the result half", "the if half",
     "both halves", "neither half"),
    ("I'd train every day if I ___ a professional.", "were", "am",
     "would be", "will be"),
    ("Which gives advice?", "If I were you, I'd see a doctor.",
     "If I am you, I see a doctor.", "If I was you, I will see a doctor.",
     "If I would be you, I'd see a doctor."),
    ("They wouldn't lose so often if they ___ a better coach.", "had", "have",
     "would have", "will have"),
    ("If I could choose any sport, I ___ pick swimming.", "would", "will",
     "would to", "did"),
    ("Which sentence is a real future possibility?",
     "If we win tomorrow, we'll be top.",
     "If we won tomorrow, we would be top.",
     "If we had won, we would have been top.", "If we win, we would be top."),
    ("It would be easier if the stadium ___ nearer.", "were", "is",
     "would be", "will be"),
    ("Talking about luck: 'That was a ___ of luck.'", "stroke", "piece of",
     "hit of", "strike of"),
    ("'It was pure ___ that we met.'", "chance", "chancy of", "lucky of",
     "chanced of"),
    ("'Things ___ out well in the end.'", "worked", "came of", "went of it",
     "made of"),
    ("'You were ___ to get that ticket.'", "lucky", "luck of", "luckily of",
     "luckier of"),
    ("'It could have been ___ .'", "worse", "worst", "badder", "more bad"),
    ("'What are the ___ of that happening twice?'", "chances", "chance of",
     "lucky of", "possibles of"),
    ("'Just my ___ .' said after bad luck.", "luck", "lucky of", "luckily of",
     "fortune of me"),
    ("'Better luck next ___ .'", "time", "turn of it", "moment of",
     "round of it"),
    ("Which sentence describes good fortune best?",
     "If I hadn't missed that bus, I'd never have met her.",
     "Luck is a thing that exists.", "I am lucky always.",
     "Lucky people are lucky."),
]

I10_BD_V = [
    ("do your best", "bor kuchini sarflamoq / делать всё возможное"),
    ("do research", "tadqiqot qilmoq / проводить исследование"),
    ("do the washing-up", "idish yuvmoq / мыть посуду"),
    ("do an exam", "imtihon topshirmoq / сдавать экзамен"),
    ("do damage", "zarar yetkazmoq / наносить ущерб"),
    ("make a decision", "qaror qabul qilmoq / принимать решение"),
    ("make a mistake", "xato qilmoq / совершать ошибку"),
    ("make progress", "oldinga siljimoq / делать успехи"),
    ("make an effort", "harakat qilmoq / прилагать усилия"),
    ("make friends", "do'st orttirmoq / заводить друзей"),
    ("make a noise", "shovqin qilmoq / шуметь"),
    ("make sure", "ishonch hosil qilmoq / убедиться"),
    ("take a break", "tanaffus qilmoq / делать перерыв"),
    ("take part", "ishtirok etmoq / принимать участие"),
    ("take a risk", "tavakkal qilmoq / рисковать"),
    ("take place", "bo'lib o'tmoq / происходить"),
    ("take care of", "g'amxo'rlik qilmoq / заботиться"),
    ("take notes", "qayd qilib olmoq / делать заметки"),
    ("take your time", "shoshilmaslik / не торопиться"),
    ("take responsibility", "javobgarlikni olmoq / брать ответственность"),
    ("make up your mind", "qaror qilmoq / определиться"),
    ("do somebody a favour", "yaxshilik qilmoq / оказать услугу"),
    ("make an appointment", "uchrashuvga yozilmoq / записаться"),
    ("take an opportunity", "imkoniyatdan foydalanmoq / воспользоваться шансом"),
    ("do harm", "zarar keltirmoq / вредить"),
]

I10_BD_G = [
    ("If I had known, I ___ come.", "would have", "would", "will have",
     "had"),
    ("She ___ passed if she had studied.", "would have", "would", "will have",
     "had"),
    ("If they ___ left earlier, they wouldn't have missed it.", "had",
     "have", "would have", "did"),
    ("We wouldn't have got lost if we ___ a map.", "had had", "had",
     "have had", "would have"),
    ("If he hadn't been injured, he ___ played.", "would have",
     "would", "will have", "had"),
    ("Which talks about the past that cannot change?", "the third conditional",
     "the first conditional", "the second conditional", "the zero conditional"),
    ("Which is WRONG?", "If I would have known, I would have called.",
     "If I had known, I would have called.",
     "Had I known, I would have called.", "I would have called if I had known."),
    ("If she ___ the train, she would have been on time.", "had caught",
     "caught", "would have caught", "catches"),
    ("I ___ have helped if you had asked.", "would", "will", "would to",
     "had"),
    ("Which mixes past condition with present result?",
     "If I had saved money, I would be rich now.",
     "If I save money, I would be rich now.",
     "If I had saved money, I would have been rich now only.",
     "If I would save money, I am rich now."),
    ("If we hadn't moved, I ___ never have met you.", "would", "will",
     "would to", "had"),
    ("What ___ you have done in my place?", "would", "will", "did",
     "had"),
    ("If only I ___ listened!", "had", "have", "would have", "did"),
    ("They would have won if the referee ___ that goal.", "had allowed",
     "allowed", "would allow", "allows"),
    ("Which sentence expresses regret?",
     "I wish I had taken that job.", "I wish I take that job.",
     "I wish I would take that job then.", "I wished I take that job."),
    ("Had I known earlier, I ___ something.", "would have said", "would say",
     "will say", "had said"),
    ("A volunteer advert asks for people who ___ help.", "are willing to",
     "are willing for", "will willing", "want for"),
    ("'No ___ is necessary.'", "experience", "experiences of",
     "experienced of", "experiencing of"),
    ("'Volunteers ___ full training.'", "receive", "receiving of",
     "are receive", "received of"),
    ("'We're looking ___ people with a few free hours.'", "for", "to", "of",
     "at"),
    ("'It's a chance to ___ something back.'", "give", "make", "take",
     "do of"),
    ("'Hours are ___ .'", "flexible", "flexibly", "flexibility of",
     "flexed of"),
    ("'Please ___ in the form below.'", "fill", "make", "do", "put of"),
    ("'The work is ___ but rewarding.'", "demanding", "demand of",
     "demanded of", "demandingly of"),
    ("Which advert line would attract volunteers best?",
     "Two hours a week could change a child's year.",
     "We need volunteers.", "Volunteering is a thing you can do.",
     "Apply if you want to apply."),
]

LISTS = [
    ("Unit 8A&C · Vocabulary — sharing information", "vocab", 15, I8_AC_V),
    ("Unit 8A&C · Grammar — reported speech, and passing on news", "grammar", 15, I8_AC_G),
    ("Unit 8B&D · Vocabulary — reporting verbs", "vocab", 16, I8_BD_V),
    ("Unit 8B&D · Grammar — verb patterns, and a news story", "grammar", 16, I8_BD_G),
    ("Unit 9A&C · Vocabulary — films and series", "vocab", 17, I9_AC_V),
    ("Unit 9A&C · Grammar — the passive, and going out", "grammar", 17, I9_AC_G),
    ("Unit 9B&D · Vocabulary — music", "vocab", 18, I9_BD_V),
    ("Unit 9B&D · Grammar — relative clauses, and contrasting ideas", "grammar", 18, I9_BD_G),
    ("Unit 10A&C · Vocabulary — sport", "vocab", 19, I10_AC_V),
    ("Unit 10A&C · Grammar — the second conditional, and luck", "grammar", 19, I10_AC_G),
    ("Unit 10B&D · Vocabulary — do, make and take", "vocab", 20, I10_BD_V),
    ("Unit 10B&D · Grammar — the third conditional, and volunteering", "grammar", 20, I10_BD_G),
]
