"""Empower Elementary Units 5-8, as Play steps, in the A&C / B&D pairing.

    5A places in a city; there is / there are   5C directions and checking
    5B furniture; possessive 's and pronouns    5D describing where you live
    6A family; past simple of be                6C voicemail messages
    6B past simple of regular and irregular verbs  6D life events
    7A transport; past simple negatives and questions   7C excuse me / sorry
    7B transport adjectives; like, love, don't mind + -ing   7D an email
    8A sport; can, can't, could, couldn't       8C health and how you feel
    8B parts of the body; have to / don't have to   8D free time
"""

U5_AC_V = [
    ("bank", "you go there to take out money"),
    ("post office", "you go there to send a parcel"),
    ("chemist", "you go there to buy medicine"),
    ("library", "you borrow books there"),
    ("museum", "you go there to look at old or famous things"),
    ("bus station", "buses leave from there"),
    ("railway station", "trains leave from there"),
    ("airport", "planes take off from there"),
    ("market", "many small sellers sell food there"),
    ("shopping centre", "a big building full of shops"),
    ("cafe", "you go there for coffee and a small meal"),
    ("restaurant", "you sit down there for a full meal"),
    ("hotel", "visitors sleep there and pay by the night"),
    ("hospital", "ill people stay there"),
    ("school", "children go there to learn"),
    ("park", "a green open place in a city"),
    ("bridge", "it takes a road over a river"),
    ("square", "an open place in the middle of a town"),
    ("cinema", "you watch films there"),
    ("stadium", "big matches are played there"),
    ("mosque", "people pray there"),
    ("car park", "you leave your car there"),
    ("bus stop", "you wait there for the bus"),
    ("street", "a road with buildings on both sides"),
    ("crossing", "the place where you walk over the road"),
]

U5_AC_G = [
    ("___ a bank near here?", "Is there", "Are there", "There is", "Have there"),
    ("___ two cafes in my street.", "There are", "There is", "Are there",
     "It has"),
    ("There ___ a post office on the corner.", "is", "are", "have", "has"),
    ("There ___ any shops in this street.", "aren't", "isn't", "not are",
     "don't"),
    ("There ___ a car park behind the hotel.", "isn't", "aren't", "not is",
     "doesn't"),
    ("'Is there a market near the square?' 'Yes, ___.'", "there is", "it is",
     "there has", "is there"),
    ("'Are there any hotels here?' 'No, ___.'", "there aren't", "there isn't",
     "they aren't", "no there"),
    ("How many bridges ___ in your city?", "are there", "there are", "is there",
     "have there"),
    ("Which is correct?", "There are a lot of parks in Tashkent.",
     "There is a lot of parks in Tashkent.", "It has a lot of parks in Tashkent.",
     "There have a lot of parks in Tashkent."),
    ("Which is WRONG?", "There is three cinemas here.",
     "There are three cinemas here.", "There is a cinema here.",
     "Are there three cinemas here?"),
    ("There's ___ old museum in the centre.", "an", "a", "some", "any"),
    ("___ there a stadium in your town?", "Is", "Are", "Has", "Does"),
    ("The bank is ___ the post office and the cafe.", "between", "among",
     "middle", "next"),
    ("The car park is ___ the hotel.", "behind", "back", "after", "under of"),
    ("The bus stop is ___ from the school.", "opposite", "in front",
     "face to", "across of"),
    ("Go ___ ahead and then turn left.", "straight", "direct", "right ahead",
     "forward of"),
    ("Take the ___ turning on the right.", "second", "two", "twice", "second of"),
    ("'Excuse me, how do I ___ to the station?'", "get", "go to arrive",
     "reach to", "come"),
    ("'Is it far?' 'No, it's about five minutes ___ foot.'", "on", "by", "with",
     "at"),
    ("'Sorry, could you ___ that again?'", "say", "speak", "tell", "repeat to"),
    ("'Do you mean the third street?' 'That's ___.'", "right", "true of",
     "correctly", "good right"),
    ("'Sorry, could you speak more ___?' 'Of course.'", "slowly", "slow",
     "slower of", "slowly of"),
    ("'The museum? It's ___ the river.'", "over", "up of", "through of", "at on"),
    ("The cinema is ___ the shopping centre.", "inside", "in of", "on in",
     "within of"),
    ("'Thanks for your help.' '___.'", "You're welcome", "Welcome you",
     "No thanks", "It is nothing of"),
]

U5_BD_V = [
    ("sofa", "a long soft seat for two or three people"),
    ("armchair", "a soft chair with sides for one person"),
    ("cupboard", "you keep plates and cups in it"),
    ("wardrobe", "you hang your clothes in it"),
    ("bookshelf", "you stand your books on it"),
    ("desk", "a table you work or study at"),
    ("mirror", "you look at yourself in it"),
    ("curtains", "you close them over the window at night"),
    ("carpet", "it covers the whole floor"),
    ("lamp", "a small light you put on a table"),
    ("fridge", "it keeps your food cold"),
    ("cooker", "you cook your food on it"),
    ("sink", "you wash the plates in it"),
    ("washing machine", "it washes your clothes"),
    ("cushion", "a small soft bag you put behind your back"),
    ("blanket", "you put it over you in bed when it is cold"),
    ("pillow", "you put your head on it in bed"),
    ("shelf", "a flat board on a wall for putting things on"),
    ("drawer", "you pull it out of a desk to get things"),
    ("bin", "you put rubbish in it"),
    ("clock", "it tells you the time on the wall"),
    ("plant", "something green you grow indoors"),
    ("kettle", "you boil water in it"),
    ("oven", "you bake in it"),
    ("balcony", "a small outdoor space on an upper floor"),
]

U5_BD_G = [
    ("This is ___ book.", "Dilnoza's", "Dilnoza", "Dilnozas", "of Dilnoza"),
    ("That is my ___ car.", "brother's", "brothers", "brother", "brother of"),
    ("Those are my ___ shoes.", "parents'", "parent's", "parents", "of parents"),
    ("Whose bag is this? It's ___.", "mine", "my", "me", "my one"),
    ("This phone isn't ___. It's Sardor's.", "yours", "your", "you", "your one"),
    ("The blue coat is ___.", "hers", "her", "she", "her's"),
    ("That flat is ___. We live there.", "ours", "our", "us", "our one"),
    ("These books are ___. They study here.", "theirs", "their", "them",
     "their's"),
    ("Which is correct?", "It's my sister's room.", "It's my sisters room.",
     "It's my sister room.", "It's the room of my sister's."),
    ("Which is WRONG?", "This pen is my.", "This pen is mine.",
     "This is my pen.", "Is this pen yours?"),
    ("'___ is that?' 'It's Aziz's.'", "Whose", "Who's", "Who", "Whom"),
    ("The ___ toys are in the box.", "children's", "childrens", "childrens'",
     "children"),
    ("This is the ___ office.", "manager's", "managers", "manager",
     "manager of"),
    ("Is this umbrella ___?", "yours", "your", "you", "your's"),
    ("The white house on the corner is ___.", "theirs", "their", "them",
     "they're"),
    ("Which shows one boy?", "the boy's room", "the boys' room",
     "the boys room", "the room boys"),
    ("Which shows more than one girl?", "the girls' school",
     "the girl's school", "the girls school", "the school girl's"),
    ("In my flat there ___ two bedrooms.", "are", "is", "have", "has"),
    ("My room is small ___ comfortable.", "but", "so", "because", "although of"),
    ("The kitchen is ___ the living room.", "next to", "next of", "near to of",
     "beside of the"),
    ("I live in a flat ___ the fourth floor.", "on", "in", "at", "to"),
    ("There's a nice view ___ my balcony.", "from", "of out", "since", "off"),
    ("My neighbourhood is quiet ___ friendly.", "and", "but", "so", "or"),
    ("It's a good place to live ___ everything is near.", "because", "so",
     "but", "although of"),
    ("Which sentence describes a place well?",
     "My street is quiet, with a park at the end.",
     "My street is street.", "My street is have park.",
     "My street there is a park at the end of it is."),
]

U6_AC_V = [
    ("mother", "your female parent"),
    ("father", "your male parent"),
    ("sister", "a girl with the same parents as you"),
    ("brother", "a boy with the same parents as you"),
    ("grandmother", "your parent's mother"),
    ("grandfather", "your parent's father"),
    ("aunt", "your parent's sister"),
    ("uncle", "your parent's brother"),
    ("cousin", "your aunt's or uncle's child"),
    ("nephew", "your brother's or sister's son"),
    ("niece", "your brother's or sister's daughter"),
    ("wife", "the woman a man is married to"),
    ("husband", "the man a woman is married to"),
    ("son", "somebody's male child"),
    ("daughter", "somebody's female child"),
    ("parents", "your mother and father together"),
    ("grandparents", "your parents' parents"),
    ("twins", "two children born on the same day to one mother"),
    ("only child", "a child with no brothers or sisters"),
    ("relatives", "all the people in your wider family"),
    ("neighbour", "the person who lives next to you"),
    ("friend", "somebody you like and spend time with"),
    ("married", "having a husband or a wife"),
    ("single", "not married"),
    ("retired", "not working any more because of your age"),
]

U6_AC_G = [
    ("I ___ at home yesterday.", "was", "were", "am", "is"),
    ("They ___ at school on Monday.", "were", "was", "are", "is"),
    ("She ___ born in Bukhara.", "was", "were", "is", "did"),
    ("We ___ very tired after the trip.", "were", "was", "are", "did"),
    ("It ___ cold last night.", "was", "were", "is", "did"),
    ("My grandparents ___ farmers.", "were", "was", "are", "did"),
    ("I ___ at the party. I was ill.", "wasn't", "weren't", "am not", "didn't"),
    ("They ___ at home. The house was empty.", "weren't", "wasn't", "aren't",
     "didn't"),
    ("___ you at the wedding?", "Were", "Was", "Are", "Did"),
    ("___ your sister at university last year?", "Was", "Were", "Is", "Did"),
    ("'Were you late?' 'No, ___.'", "I wasn't", "I weren't", "I didn't",
     "I am not"),
    ("'Was the film good?' 'Yes, ___.'", "it was", "it were", "it did",
     "it is"),
    ("Which is correct?", "My parents were teachers.",
     "My parents was teachers.", "My parents are was teachers.",
     "My parents did teachers."),
    ("Which is WRONG?", "She were my neighbour.", "She was my neighbour.",
     "She wasn't my neighbour.", "Was she your neighbour?"),
    ("Where ___ you last weekend?", "were", "was", "did", "are"),
    ("My cousin ___ at the same school as me.", "was", "were", "did", "is was"),
    ("A voicemail starts: 'Hi, ___ Aziz.'", "it's", "I am it", "here is me",
     "this here"),
    ("'Sorry, I ___ answer the phone. I was in a lesson.'", "couldn't",
     "can't", "didn't could", "not could"),
    ("'Can I ___ a message?' 'Yes, of course.'", "leave", "let", "put", "give in"),
    ("'Could you ask her to ___ me back?'", "call", "ring to", "phone to",
     "return"),
    ("'I'll ___ you later.' 'OK, bye.'", "call", "calling", "called", "to call"),
    ("'Is Nodira ___?' 'No, sorry, she's out.'", "there", "here to", "at",
     "inside of"),
    ("'Who's ___, please?' 'It's her brother.'", "calling", "call", "called",
     "to call"),
    ("'Sorry, the line is ___. I'll try again.'", "busy", "full", "taken of",
     "closed"),
    ("'Thanks for your message. I'll get ___ to you tomorrow.'", "back",
     "again", "return", "back again to"),
]

U6_BD_V = [
    ("go", "its past form is went"),
    ("have", "its past form is had"),
    ("see", "its past form is saw"),
    ("do", "its past form is did"),
    ("make", "its past form is made"),
    ("take", "its past form is took"),
    ("get", "its past form is got"),
    ("come", "its past form is came"),
    ("give", "its past form is gave"),
    ("buy", "its past form is bought"),
    ("eat", "its past form is ate"),
    ("drink", "its past form is drank"),
    ("write", "its past form is wrote"),
    ("read", "its past form sounds like red"),
    ("meet", "its past form is met"),
    ("leave", "its past form is left"),
    ("find", "its past form is found"),
    ("think", "its past form is thought"),
    ("say", "its past form is said"),
    ("tell", "its past form is told"),
    ("begin", "its past form is began"),
    ("feel", "its past form is felt"),
    ("win", "its past form is won"),
    ("lose", "its past form is lost"),
    ("wear", "its past form is wore"),
]

U6_BD_G = [
    ("I ___ football yesterday.", "played", "play", "playd", "was play"),
    ("She ___ in Nukus in 2019.", "lived", "lives", "livd", "was live"),
    ("We ___ TV all evening.", "watched", "watch", "watchd", "were watch"),
    ("He ___ to the bazaar on Saturday.", "went", "goed", "gone", "did go"),
    ("They ___ a new car last month.", "bought", "buyed", "buy", "did bought"),
    ("I ___ my homework before dinner.", "did", "done", "doed", "was do"),
    ("She ___ a message to her cousin.", "wrote", "writed", "written",
     "was write"),
    ("The lesson ___ at nine.", "began", "beginned", "begun", "did begin"),
    ("Which is the past of 'study'?", "studied", "studyed", "studed",
     "did study"),
    ("Which is the past of 'stop'?", "stopped", "stoped", "stopt", "did stop"),
    ("Which verb is irregular?", "take", "work", "play", "listen"),
    ("Which verb is regular?", "cook", "come", "give", "win"),
    ("We ___ our grandparents last summer.", "visited", "visit", "visitted",
     "was visit"),
    ("He ___ his keys on the bus.", "lost", "losed", "lose", "was lose"),
    ("Which is correct?", "She met her friend at the cafe.",
     "She meeted her friend at the cafe.", "She did met her friend at the cafe.",
     "She was meet her friend at the cafe."),
    ("Which is WRONG?", "They goed home early.", "They went home early.",
     "They came home early.", "They left home early."),
    ("I ___ my first job when I was eighteen.", "got", "getted", "geted",
     "was get"),
    ("The film ___ two hours.", "lasted", "last", "lastd", "was last"),
    ("Put these in order: born, started school, left school, got a job.",
     "born, started school, left school, got a job",
     "started school, born, got a job, left school",
     "got a job, born, started school, left school",
     "left school, born, started school, got a job"),
    ("He ___ university in 2020 and became a teacher.", "finished", "finish",
     "finishd", "was finish"),
    ("She ___ married two years ago.", "got", "getted", "goted", "was get"),
    ("They ___ to Tashkent when he was a child.", "moved", "move", "movd",
     "was move"),
    ("Which word talks about the past?", "yesterday", "tomorrow", "next week",
     "now"),
    ("Which phrase goes with the past simple?", "two years ago", "at the moment",
     "next month", "every day now"),
    ("In 2015 my family ___ in a small village.", "lived", "live", "was live",
     "living"),
]

U7_AC_V = [
    ("catch a bus", "get on a bus at the right time"),
    ("miss a train", "arrive too late and not get on"),
    ("drive a car", "control a car on the road"),
    ("ride a bike", "travel on a bicycle"),
    ("take a taxi", "travel by car and pay the driver"),
    ("get on", "climb into a bus or train"),
    ("get off", "leave a bus or train"),
    ("ticket", "the paper or card that lets you travel"),
    ("platform", "the place at a station where you wait for a train"),
    ("timetable", "the list of times that buses or trains go"),
    ("journey", "the whole trip from one place to another"),
    ("traffic", "all the cars on the road together"),
    ("traffic jam", "the cars are not moving"),
    ("underground", "the train system below a city"),
    ("tram", "a vehicle that runs on rails in the street"),
    ("flight", "a journey by plane"),
    ("passenger", "somebody travelling who is not the driver"),
    ("fare", "the money you pay to travel"),
    ("petrol", "what you put in a car to make it go"),
    ("seatbelt", "you fasten it to stay safe in a car"),
    ("motorway", "a big fast road between cities"),
    ("driving licence", "the card that says you can drive"),
    ("delay", "when something leaves later than it should"),
    ("on foot", "walking, not using a vehicle"),
    ("return ticket", "a ticket for going and coming back"),
]

U7_AC_G = [
    ("I ___ go to work yesterday.", "didn't", "don't", "wasn't", "not did"),
    ("She ___ catch the early bus.", "didn't", "doesn't", "wasn't", "not"),
    ("They ___ enjoy the journey.", "didn't", "don't", "weren't", "no"),
    ("___ you take a taxi?", "Did", "Do", "Were", "Was"),
    ("___ he drive to Samarkand?", "Did", "Does", "Was", "Do"),
    ("Where ___ you go last weekend?", "did", "do", "were", "was"),
    ("What time ___ the train leave?", "did", "does", "was", "were"),
    ("'Did you miss the bus?' 'Yes, ___.'", "I did", "I was", "I do",
     "did I"),
    ("'Did she buy a ticket?' 'No, ___.'", "she didn't", "she wasn't",
     "she doesn't", "didn't she"),
    ("Which is correct?", "He didn't come to the station.",
     "He didn't came to the station.", "He not came to the station.",
     "He wasn't come to the station."),
    ("Which is WRONG?", "Did you went by train?", "Did you go by train?",
     "You went by train.", "You didn't go by train."),
    ("Why ___ the flight late?", "was", "did", "does", "were"),
    ("How ___ you get there?", "did", "was", "were", "do"),
    ("We ___ find a taxi, so we walked.", "couldn't", "didn't could",
     "can't", "not could"),
    ("I ___ to the airport by bus, not by taxi.", "went", "did go", "goed",
     "was go"),
    ("She ___ her ticket at the machine.", "bought", "did buy it", "buyed",
     "was buy"),
    ("If you step on somebody's foot, you say ___.", "I'm sorry", "Excuse me to",
     "Pardon me for it", "Sorry me"),
    ("To get past somebody on a bus you say ___.", "Excuse me", "Sorry me",
     "Pardon to you", "Let me to pass"),
    ("'I'm sorry I'm late.' '___.'", "Never mind", "No mind", "Not mind",
     "Mind not"),
    ("'Excuse me, is this seat ___?' 'No, it's free.'", "taken", "took",
     "busy of", "full of"),
    ("'Sorry, that's my ___.' 'Oh, I'm sorry.'", "seat", "chair of", "place of me",
     "sit"),
    ("'Excuse me, ___ I get past?'", "could", "should", "would to", "may to"),
    ("'I'm really sorry about that.' 'It's ___.'", "all right", "all good of",
     "right all", "nothing at all of"),
    ("'___ me, does this bus go to the centre?'", "Excuse", "Sorry for",
     "Pardon for", "Forgive of"),
    ("Which is the most polite?", "Excuse me, could you move your bag?",
     "Move your bag.", "Your bag is on my seat, move.", "Bag off, please."),
]

U7_BD_V = [
    ("crowded", "full of people with little space"),
    ("comfortable", "nice to sit in for a long time"),
    ("uncomfortable", "not nice to sit in"),
    ("cheap", "it does not cost much"),
    ("expensive", "it costs a lot"),
    ("fast", "it moves quickly"),
    ("slow", "it moves without speed"),
    ("safe", "there is little danger"),
    ("dangerous", "you could be hurt"),
    ("noisy", "there is a lot of sound"),
    ("quiet", "there is almost no sound"),
    ("clean", "there is no dirt"),
    ("dirty", "it needs washing"),
    ("convenient", "easy to use and near what you need"),
    ("reliable", "it comes when it says it will"),
    ("late", "after the time it should be"),
    ("early", "before the time it should be"),
    ("direct", "it goes there without stopping to change"),
    ("busy", "with many people or cars at that time"),
    ("empty", "with nobody in it"),
    ("modern", "new in style"),
    ("old-fashioned", "in a style from many years ago"),
    ("relaxing", "it makes you feel calm"),
    ("tiring", "it makes you feel you need a rest"),
    ("popular", "many people choose it"),
]

U7_BD_G = [
    ("I love ___ by train.", "travelling", "travel", "to travelling", "travelled"),
    ("She doesn't like ___ in traffic jams.", "sitting", "sit", "to sitting",
     "sat"),
    ("They hate ___ early.", "getting up", "get up", "to getting up", "got up"),
    ("We don't mind ___ to school.", "walking", "walk", "to walking", "walked"),
    ("He enjoys ___ his bike at the weekend.", "riding", "ride", "to riding",
     "rode"),
    ("Which is correct?", "I like driving.", "I like drive.", "I like to driving.",
     "I like drived."),
    ("Which is WRONG?", "She loves to cooking.", "She loves cooking.",
     "She loves to cook.", "She likes cooking."),
    ("I ___ flying. It makes me nervous.", "don't like", "not like",
     "am not like", "no like"),
    ("'Do you like taking the bus?' 'It's OK, I ___.'", "don't mind",
     "don't mind it of", "not mind", "am not minding of"),
    ("My father hates ___ in the city centre.", "parking", "park", "to parking",
     "parked"),
    ("Put in order: like / I / to / walking / work", "I like walking to work.",
     "I like to walking work.", "I walking like to work.",
     "Like I walking to work."),
    ("She's good ___ driving.", "at", "in", "on", "for"),
    ("The underground is ___ than the bus.", "faster", "more fast", "fastest",
     "more faster"),
    ("Taxis are ___ than buses.", "more expensive", "expensiver",
     "most expensive", "more expensiver"),
    ("This train is very ___ in the morning.", "crowded", "crowd", "crowding",
     "crowds"),
    ("I prefer ___ to work because it's relaxing.", "cycling", "cycle",
     "to cycling", "cycled"),
    ("An email to a host family often starts ___.", "Dear Mr and Mrs Brown,",
     "Hey you,", "Hello family,", "To the family of house,"),
    ("In an email you write: 'I'm ___ to meet you.'", "looking forward",
     "look forward", "looking forwards to be", "forward looking of"),
    ("'I'm eighteen and I ___ in Tashkent.'", "live", "living", "am live",
     "lives"),
    ("'My hobbies ___ reading and swimming.'", "are", "is", "have", "does"),
    ("'Please ___ me know if you have any questions.'", "let", "make", "give",
     "allow to"),
    ("An email to a family you don't know ends ___.", "Best wishes,",
     "See ya,", "Love and kisses,", "Bye bye bye,"),
    ("'I don't eat ___, but I eat everything else.'", "meat", "a meat",
     "the meats", "some meats"),
    ("Which sentence is most polite in an email?",
     "Could you tell me what time dinner is?", "Tell me dinner time.",
     "I want to know dinner time.", "Dinner time?"),
    ("'Thank you ___ your email.'", "for", "of", "by", "to"),
]

U8_AC_V = [
    ("football", "eleven players and one ball, with goals"),
    ("basketball", "you throw the ball into a high net"),
    ("volleyball", "you hit the ball over a high net with your hands"),
    ("tennis", "you hit a small ball with a racket"),
    ("swimming", "moving through water"),
    ("running", "going fast on your feet for exercise"),
    ("cycling", "going out on a bike for exercise"),
    ("boxing", "a sport where two people fight with gloves"),
    ("wrestling", "a sport where you try to hold your opponent down"),
    ("gym", "the place with machines for exercise"),
    ("team", "the group of players on your side"),
    ("coach", "the person who trains the players"),
    ("match", "one game between two teams"),
    ("score", "the number of goals or points"),
    ("win", "finish first or with more points"),
    ("lose", "finish with fewer points"),
    ("train", "practise a sport regularly"),
    ("fit", "in good condition from exercise"),
    ("warm up", "move gently before you start exercising"),
    ("stretch", "make your arms or legs long and straight"),
    ("champion", "the best player or team of all"),
    ("referee", "the person who makes sure the rules are followed"),
    ("pitch", "the ground a football match is played on"),
    ("court", "the ground a tennis match is played on"),
    ("exercise", "activity you do to stay healthy"),
]

U8_AC_G = [
    ("I ___ swim very well.", "can", "can to", "am can", "do can"),
    ("She ___ play the guitar.", "can't", "can not to", "doesn't can",
     "isn't can"),
    ("___ you ride a bike?", "Can", "Do can", "Are", "Does"),
    ("'Can he speak English?' 'Yes, ___.'", "he can", "he cans", "he does",
     "can he"),
    ("When I was five I ___ swim.", "couldn't", "can't", "didn't could",
     "not could"),
    ("My grandfather ___ run very fast when he was young.", "could", "can",
     "could to", "was could"),
    ("___ you swim when you were seven?", "Could", "Can", "Did could",
     "Were could"),
    ("Which is correct?", "She can play tennis well.",
     "She can plays tennis well.", "She can to play tennis well.",
     "She cans play tennis well."),
    ("Which is WRONG?", "I couldn't to drive then.", "I couldn't drive then.",
     "I could drive then.", "Could you drive then?"),
    ("'I can't come to training today.' 'Why ___?'", "not", "no", "don't",
     "can't"),
    ("He ___ play football because of his leg.", "can't", "doesn't can",
     "not can", "isn't can"),
    ("We ___ see the match last night. The TV was broken.", "couldn't",
     "can't", "weren't could", "didn't can"),
    ("Which sentence is about ability now?", "I can swim.", "I could swim then.",
     "I swam.", "I was swimming."),
    ("Which sentence is about ability in the past?", "She could read at four.",
     "She can read.", "She reads.", "She is reading."),
    ("'Can you help me with this exercise?' 'Of ___.'", "course", "sure of",
     "yes of", "certain of"),
    ("At the doctor's you say: 'I've got a ___.'", "headache", "head pain of",
     "hurt head of", "pain of head"),
    ("'How do you ___?' 'Much better, thanks.'", "feel", "feel you of",
     "are feel", "feeling"),
    ("'I've got a ___ throat. It hurts when I speak.'", "sore", "hurt", "sick",
     "painful of"),
    ("'You should ___ a rest.'", "have", "do", "make", "take of it"),
    ("'I hope you ___ better soon.'", "get", "become to", "go", "make"),
    ("'What's the ___?' 'I've got a temperature.'", "matter", "problem of you",
     "wrong", "illness of"),
    ("'You don't look very ___.' 'No, I feel ill.'", "well", "good of health",
     "healthy of", "fine of"),
    ("'I've got a ___ stomach after lunch.'", "bad", "ill", "sick of",
     "painful of"),
    ("'Take this medicine ___ a day.'", "twice", "two time", "second time",
     "two times of"),
    ("'Shall I call a doctor?' 'No, I'll be ___.'", "fine", "finely",
     "good of", "well of it"),
]

U8_BD_V = [
    ("head", "the top part of your body, with your face"),
    ("hair", "it grows on your head"),
    ("eye", "you see with it"),
    ("ear", "you hear with it"),
    ("nose", "you smell with it"),
    ("mouth", "you speak and eat with it"),
    ("tooth", "you bite with it"),
    ("tongue", "you taste with it"),
    ("neck", "it joins your head to your body"),
    ("shoulder", "the top of your arm where it meets your body"),
    ("arm", "it goes from your shoulder to your hand"),
    ("elbow", "the middle of your arm, where it bends"),
    ("hand", "it has five fingers"),
    ("finger", "one of the five on your hand"),
    ("thumb", "the short strong one on your hand"),
    ("chest", "the front of your body above your stomach"),
    ("stomach", "it hurts when you eat too much"),
    ("back", "the part of you behind your chest"),
    ("leg", "you walk on two of them"),
    ("knee", "the middle of your leg, where it bends"),
    ("foot", "the part at the bottom of your leg"),
    ("toe", "one of the five at the end of your foot"),
    ("skin", "it covers your whole body"),
    ("heart", "it sends blood round your body"),
    ("brain", "you think with it"),
]

U8_BD_G = [
    ("I ___ wear a uniform at work.", "have to", "have", "must to", "am have to"),
    ("She ___ get up early on Mondays.", "has to", "have to", "must to",
     "is have to"),
    ("We ___ pay. It's free.", "don't have to", "haven't to", "don't must",
     "not have to"),
    ("He ___ work at the weekend. He's free.", "doesn't have to", "don't have to",
     "hasn't to", "doesn't must"),
    ("___ you have to wear a suit?", "Do", "Are", "Have", "Does"),
    ("___ she have to study tonight?", "Does", "Do", "Is", "Has"),
    ("'Do you have to work on Sunday?' 'No, ___.'", "I don't", "I haven't",
     "I don't must", "I amn't"),
    ("Which is correct?", "He has to leave early.", "He have to leave early.",
     "He has to leaves early.", "He has leave early."),
    ("Which is WRONG?", "They must to train every day.",
     "They have to train every day.", "They must train every day.",
     "They don't have to train every day."),
    ("Patients ___ wait in this room.", "have to", "has to", "must to",
     "are have to"),
    ("You ___ take this medicine with food.", "have to", "have", "must to",
     "are having to"),
    ("'Do I have to come tomorrow?' 'No, you ___.'", "don't have to",
     "mustn't have", "haven't", "don't must"),
    ("Which sentence means it is not necessary?", "You don't have to come.",
     "You mustn't come.", "You have to come.", "You must come."),
    ("Which sentence means it is necessary?", "I have to finish this today.",
     "I don't have to finish this today.", "I can finish this today.",
     "I could finish this today."),
    ("My brother ___ wear glasses to drive.", "has to", "have to", "must to",
     "is have to"),
    ("When I was at school we ___ wear a uniform.", "had to", "have to",
     "must to", "was have to"),
    ("Which part of the body do you use to think?", "brain", "heart", "stomach",
     "knee"),
    ("If you run a lot, your ___ may hurt.", "knees", "ears", "fingers",
     "teeth"),
    ("You go to the dentist when you have a problem with your ___.", "teeth",
     "elbows", "shoulders", "toes"),
    ("He broke his ___ playing football and can't walk.", "leg", "hair",
     "skin of", "tongue"),
    ("I've got a pain in my ___ after carrying that box.", "back", "nose",
     "tongue", "toe"),
    ("She cut her ___ while she was chopping onions.", "finger", "knee",
     "chest", "ear"),
    ("In my free time I ___ basketball with my friends.", "play", "do", "make",
     "go"),
    ("At the weekend I ___ swimming.", "go", "play", "do", "make"),
    ("Three times a week I ___ exercise at home.", "do", "go", "play", "make"),
]

LISTS = [
    ("Unit 5A&C · Vocabulary — places in a city", "vocab", 9, U5_AC_V),
    ("Unit 5A&C · Grammar — there is, there are, and directions", "grammar", 9, U5_AC_G),
    ("Unit 5B&D · Vocabulary — things in a home", "vocab", 10, U5_BD_V),
    ("Unit 5B&D · Grammar — whose it is, and describing where you live", "grammar", 10, U5_BD_G),
    ("Unit 6A&C · Vocabulary — family", "vocab", 11, U6_AC_V),
    ("Unit 6A&C · Grammar — was and were, and phone messages", "grammar", 11, U6_AC_G),
    ("Unit 6B&D · Vocabulary — past forms of common verbs", "vocab", 12, U6_BD_V),
    ("Unit 6B&D · Grammar — the past simple, and telling a life story", "grammar", 12, U6_BD_G),
    ("Unit 7A&C · Vocabulary — getting around", "vocab", 13, U7_AC_V),
    ("Unit 7A&C · Grammar — past questions, and being polite", "grammar", 13, U7_AC_G),
    ("Unit 7B&D · Vocabulary — what a journey is like", "vocab", 14, U7_BD_V),
    ("Unit 7B&D · Grammar — like and hate with -ing, and an email", "grammar", 14, U7_BD_G),
    ("Unit 8A&C · Vocabulary — sport and exercise", "vocab", 15, U8_AC_V),
    ("Unit 8A&C · Grammar — can and could, and how you feel", "grammar", 15, U8_AC_G),
    ("Unit 8B&D · Vocabulary — the body", "vocab", 16, U8_BD_V),
    ("Unit 8B&D · Grammar — have to, and free time", "grammar", 16, U8_BD_G),
]
