"""Empower Pre-Intermediate Units 1-4, in the A&C / B&D pairing.

From the Teacher's Book:
    1A common adjectives; question forms        1C meeting people again
    1B communication; present simple/continuous 1D keeping in touch
    2A holidays; past simple                    2C asking for information
    2B travel collocations; past continuous     2D a travel blog
    3A money and shopping; present perfect or past simple   3C in a shop
    3B generosity; present perfect with already and yet     3D charities
    4A celebrations; present continuous and going to        4C arrangements
    4B will, won't and shall                    4D invitations
"""

LEVEL = "Pre-Intermediate"
BOOK = "Empower Pre-Intermediate"
PAST_FROM = 1      # Pre-Intermediate students already have the past simple:
                   # Unit 2 revises it, so it is not too early anywhere here

P1_AC_V = [
    ("annoying", "it makes you slightly angry"),
    ("boring", "it does not interest you at all"),
    ("confusing", "it is hard to understand"),
    ("disappointing", "it is worse than you hoped"),
    ("embarrassing", "it makes you feel ashamed in front of others"),
    ("exhausting", "it makes you extremely tired"),
    ("fascinating", "it is extremely interesting"),
    ("frightening", "it makes you afraid"),
    ("impressive", "it makes people admire it"),
    ("relaxing", "it makes you feel calm"),
    ("stressful", "it makes you worried and tense"),
    ("surprising", "you did not expect it"),
    ("challenging", "it is difficult in an interesting way"),
    ("enjoyable", "it gives you pleasure"),
    ("essential", "you absolutely need it"),
    ("brilliant", "extremely good or extremely clever"),
    ("awkward", "it makes a situation uncomfortable"),
    ("unusual", "it does not happen often"),
    ("worrying", "it makes you anxious"),
    ("rewarding", "it gives you a good feeling of achievement"),
    ("complicated", "it has many parts and is hard to follow"),
    ("practical", "it works well in real life"),
    ("reliable", "you can depend on it"),
    ("popular", "a lot of people like it"),
    ("weird", "strange in an odd way"),
]

P1_AC_G = [
    ("___ do you live?", "Where", "What", "Which", "Who"),
    ("___ many brothers have you got?", "How", "What", "Which", "How much"),
    ("___ you speak French?", "Do", "Are", "Is", "Does"),
    ("___ your sister work in Tashkent?", "Does", "Do", "Is", "Are"),
    ("Who ___ you this book?", "gave", "did give", "gived", "was give"),
    ("What ___ you doing at eight o'clock?", "were", "was", "did", "are was"),
    ("Which is correct?", "What time does the film start?",
     "What time the film starts?", "What time start the film?",
     "What time do the film start?"),
    ("Which question has no auxiliary because who is the subject?",
     "Who called you?", "Who did call you?", "Who does call you?",
     "Who is call you?"),
    ("___ is this bag?", "Whose", "Who's", "Which of", "Whom"),
    ("What ___ your brother like?", "is", "does", "has", "do"),
    ("How ___ does the ticket cost?", "much", "many", "long", "far"),
    ("How ___ have you lived here?", "long", "much", "many", "far"),
    ("Which is WRONG?", "Where you are from?", "Where are you from?",
     "Where do you come from?", "Where were you born?"),
    ("___ you ever been to Turkey?", "Have", "Did", "Do", "Are"),
    ("What ___ happened?", "(nothing needed)", "did", "does", "has been"),
    ("Put in order: you / what / studying / are / ?", "What are you studying?",
     "What you are studying?", "What studying are you?",
     "Are what you studying?"),
    ("'Nice to see you again! How ___ things?'", "are", "is", "do", "does"),
    ("'How's it ___?' 'Not bad, thanks.'", "going", "go", "gone", "goes"),
    ("'Long time no ___!'", "see", "seen", "seeing", "sees"),
    ("'What have you been ___ to?' 'Working mostly.'", "up", "on", "in", "at"),
    ("'This is my colleague, Aziz.' 'Pleased to ___ you.'", "meet", "meeting",
     "met", "meet with"),
    ("'How do you two know ___?'", "each other", "themselves", "one to one",
     "together"),
    ("'Sorry, I didn't ___ your name.'", "catch", "hear of", "take", "get of"),
    ("'Do you two ___?' 'Yes, we were at school together.'",
     "know each other", "know themselves", "know together", "know ourselves"),
    ("'I must be off. It was ___ to see you.'", "great", "greatly", "greater",
     "the great"),
]

P1_BD_V = [
    ("get in touch", "start communicating with somebody"),
    ("keep in touch", "continue communicating over time"),
    ("lose touch", "stop communicating with somebody"),
    ("catch up", "find out somebody's news after a while"),
    ("chat", "talk in a friendly, informal way"),
    ("text", "send a short written message by phone"),
    ("call back", "return somebody's phone call"),
    ("post", "put a message or photo online"),
    ("reply", "answer a message"),
    ("forward", "send on a message you received"),
    ("share", "let others see something online"),
    ("follow", "choose to see somebody's posts"),
    ("block", "stop somebody contacting you"),
    ("comment", "write your opinion under a post"),
    ("video call", "speak to somebody and see them on screen"),
    ("voice message", "a recording of your voice sent to somebody"),
    ("notification", "the alert your phone shows you"),
    ("group chat", "a conversation with several people at once"),
    ("emoji", "a small picture used instead of words"),
    ("attachment", "a file sent with a message"),
    ("face to face", "in person, not online"),
    ("get on well", "have a good relationship with somebody"),
    ("hang out", "spend free time together"),
    ("drop somebody a line", "send a short friendly message"),
    ("stay in contact", "not lose touch with somebody"),
]

P1_BD_G = [
    ("I ___ to my cousin every Sunday.", "speak", "am speaking", "speaks",
     "am speak"),
    ("Look, she ___ on the phone right now.", "is talking", "talks", "talk",
     "is talk"),
    ("We ___ usually text after midnight.", "don't", "aren't", "not", "doesn't"),
    ("He ___ working from home this week.", "is", "does", "has", "do"),
    ("Water ___ at 100 degrees.", "boils", "is boiling", "boil", "is boil"),
    ("Which is correct?", "I'm staying with my aunt this month.",
     "I stay with my aunt this month.", "I am stay with my aunt this month.",
     "I staying with my aunt this month."),
    ("Which verb is not normally used in the continuous?", "know", "work",
     "study", "travel"),
    ("She ___ checks her messages in class.", "hardly ever", "hardly never",
     "ever hardly", "never hardly"),
    ("Where does the adverb go? He ___ replies ___ quickly.",
     "usually / (nothing)", "(nothing) / usually", "usually is / (nothing)",
     "(nothing) / usually is"),
    ("I am ___ late for video calls.", "never", "never am", "not never",
     "ever not"),
    ("How ___ do you call your family?", "often", "much", "many", "long"),
    ("They ___ post anything on social media.", "rarely", "rare", "rarely are",
     "are rarely post"),
    ("Which is WRONG?", "I am knowing her since 2019.", "I have known her since 2019.",
     "I know her well.", "I am getting to know her."),
    ("'What ___ you doing?' 'Writing an email.'", "are", "do", "is", "does"),
    ("'What ___ you do?' 'I'm a student.'", "do", "are", "is", "does"),
    ("These days more people ___ voice messages than before.", "are sending",
     "send is", "sends", "is sending"),
    ("An email to a friend often begins ___.", "Hi Nodira,",
     "Dear Sir or Madam,", "To whom it may concern,", "Respected Nodira,"),
    ("'Sorry for the ___ reply.'", "late", "lately", "later of", "latest of"),
    ("'It was great to ___ from you.'", "hear", "listen", "know of", "get"),
    ("'Let's ___ up soon.'", "catch", "take", "make", "hold"),
    ("'___ my love to your family.'", "Give", "Do", "Make", "Take"),
    ("Which closing suits a friend?", "Take care,", "Yours faithfully,",
     "I remain respectfully yours,", "With highest regards of mine,"),
    ("'I'm attaching the photos ___ this email.'", "to", "on", "in", "at"),
    ("'Say hello to Aziz ___ me.'", "for", "to", "of", "by"),
    ("Which is the most natural in a message to a friend?",
     "Anyway, how are things with you?",
     "Anyway, how is the situation of your life?",
     "Anyway, inform me of your news.", "Anyway, what is your condition?"),
]

P2_AC_V = [
    ("abroad", "in or to another country"),
    ("accommodation", "the place where you stay"),
    ("book", "arrange a place in advance"),
    ("check in", "register when you arrive"),
    ("check out", "pay and leave at the end"),
    ("delayed", "later than the planned time"),
    ("destination", "the place you are travelling to"),
    ("guest house", "a small private hotel"),
    ("hostel", "cheap accommodation with shared rooms"),
    ("journey", "the act of travelling from one place to another"),
    ("luggage", "the bags you take with you"),
    ("passenger", "somebody who travels but does not drive"),
    ("resort", "a place built for holidays"),
    ("sightseeing", "visiting the famous places of a city"),
    ("souvenir", "an object you buy to remember a trip"),
    ("tour guide", "the person who shows visitors around"),
    ("trip", "a short journey there and back"),
    ("visa", "official permission to enter a country"),
    ("flight", "a journey by plane"),
    ("crowded", "with too many people"),
    ("local", "belonging to the place you are visiting"),
    ("scenery", "the natural things you can see around you"),
    ("coast", "the land next to the sea"),
    ("adventure", "an exciting and slightly risky experience"),
    ("backpacking", "travelling cheaply with a rucksack"),
]

P2_AC_G = [
    ("We ___ to Bukhara last summer.", "went", "have gone", "was going", "go"),
    ("She ___ her passport at home.", "left", "leaved", "has left then",
     "was leave"),
    ("They ___ the hotel online.", "booked", "have booked yesterday", "book",
     "was booked"),
    ("___ you enjoy the trip?", "Did", "Have", "Do", "Were"),
    ("Where ___ you stay?", "did", "have", "were", "was"),
    ("We ___ take a taxi. We walked.", "didn't", "don't", "weren't", "hadn't"),
    ("How long ___ the flight take?", "did", "does", "was", "has"),
    ("The tour ___ three hours.", "lasted", "was last", "did last",
     "has lasted then"),
    ("Which is correct?", "I didn't see the museum.", "I didn't saw the museum.",
     "I not saw the museum.", "I wasn't see the museum."),
    ("Which is WRONG?", "Did you went alone?", "Did you go alone?",
     "You went alone.", "You didn't go alone."),
    ("The past of 'fly' is ___.", "flew", "flied", "flown then", "flyed"),
    ("The past of 'spend' is ___.", "spent", "spended", "spend then",
     "did spent"),
    ("We ___ in a guest house for three nights.", "stayed", "was staying then",
     "stay", "have stayed then"),
    ("What time ___ you arrive?", "did", "have", "were", "was"),
    ("It ___ a long journey, but it was worth it.", "was", "were", "did",
     "has been then"),
    ("They ___ any souvenirs.", "didn't buy", "didn't bought", "not bought",
     "weren't buy"),
    ("At the station: 'Excuse me, could you tell me ___ the train leaves?'",
     "what time", "what time does", "when does it", "which time does"),
    ("'Do you know ___ the tickets?' 'At that machine.'", "where to buy",
     "where buy", "where to buying", "where I buy it"),
    ("'Is there a bus ___ the airport?'", "to", "at", "for to", "in"),
    ("'How ___ is the hotel from here?'", "far", "long", "much", "many"),
    ("'Sorry, could you ___ that, please?' 'Of course.'", "repeat", "again",
     "say twice", "tell again of"),
    ("'Which platform ___ the train leave from?'", "does", "is", "do", "has"),
    ("'Excuse me, I'm ___ for the tourist office.'", "looking", "searching of",
     "finding of", "watching"),
    ("'Is this seat ___?' 'No, go ahead.'", "taken", "took", "occupy",
     "busy of"),
    ("Which is the most polite?", "Could you tell me where the exit is?",
     "Tell me the exit.", "Where exit?", "I want the exit now."),
]

P2_BD_V = [
    ("catch a flight", "get on your plane in time"),
    ("miss a train", "arrive too late to get on"),
    ("get on", "board a bus, train or plane"),
    ("get off", "leave a bus, train or plane"),
    ("set off", "start a journey"),
    ("pick somebody up", "collect somebody in a vehicle"),
    ("drop somebody off", "leave somebody somewhere by car"),
    ("hire a car", "pay to use a car for a short time"),
    ("get lost", "not know where you are"),
    ("run out of", "have none left"),
    ("take off", "leave the ground, for a plane"),
    ("land", "come down to the ground, for a plane"),
    ("change trains", "get off one train and onto another"),
    ("go through customs", "pass the border check for goods"),
    ("check in luggage", "hand your bags over before a flight"),
    ("board", "get onto a plane or ship"),
    ("depart", "leave, for a train or plane"),
    ("arrive", "reach the place you were going to"),
    ("queue", "wait in a line"),
    ("stop over", "break a journey for a short stay"),
    ("travel light", "take very little luggage"),
    ("book in advance", "arrange it a long time before"),
    ("go camping", "sleep outdoors in a tent"),
    ("see the sights", "visit the famous places"),
    ("cross the border", "go from one country into another"),
]

P2_BD_G = [
    ("While I ___ , my phone rang.", "was driving", "drove", "am driving",
     "were driving"),
    ("They ___ dinner when we arrived.", "were having", "had", "have",
     "was having"),
    ("It ___ when we left the hotel.", "was raining", "rained then",
     "is raining", "were raining"),
    ("I ___ my ticket while I was running for the train.", "dropped",
     "was dropping", "drop", "were dropping"),
    ("What ___ you doing at ten last night?", "were", "was", "did", "are"),
    ("She ___ TV when the lights went out.", "was watching", "watched then",
     "watches", "were watching"),
    ("Which sentence shows a longer action interrupted by a shorter one?",
     "I was reading when he called.", "I read when he called.",
     "I have read when he called.", "I read and he called."),
    ("Which is correct?", "While we were waiting, we had a coffee.",
     "While we waited, we were having a coffee then.",
     "While we are waiting, we had a coffee.",
     "While we was waiting, we had a coffee."),
    ("We ___ for an hour when the bus finally came.", "had been waiting",
     "were waiting since", "waited since", "have waited"),
    ("Which is WRONG?", "I was knowing him then.", "I knew him then.",
     "I was meeting him then.", "I met him then."),
    ("The children ___ while their parents were checking in.", "were playing",
     "played then", "are playing", "was playing"),
    ("He broke his leg while he ___ .", "was skiing", "skied then", "skis",
     "were skiing"),
    ("___ it snowing when you arrived?", "Was", "Were", "Did", "Is"),
    ("We ___ not travelling at that time.", "were", "was", "did", "are"),
    ("At six o'clock yesterday I ___ home.", "was driving", "drove then",
     "drive", "were driving"),
    ("They ___ their luggage when the announcement came.", "were collecting",
     "collected then", "collect", "was collecting"),
    ("A travel blog often starts with ___.", "where you went and when",
     "your full address", "a list of prices only", "the weather forecast"),
    ("'The best ___ of the trip was the mountains.'", "part", "piece of",
     "side of", "half of it"),
    ("'I'd definitely ___ this place to anybody.'", "recommend",
     "advise to", "suggest to go of", "propose of"),
    ("'The food was amazing, ___ the bread.'", "especially", "specially of",
     "special of", "specific of"),
    ("Which sentence gives useful advice to a reader?",
     "Book your tickets early, because the train fills up.",
     "The train was there.", "We took a train and it was a train.",
     "Trains exist in this city."),
    ("'We stayed ___ a small guest house near the river.'", "in", "on", "at of",
     "by of"),
    ("'It took us three hours to ___ there.'", "get", "arrive", "reach to",
     "come of"),
    ("'___ , we had a wonderful time.'", "Overall", "In all of it",
     "On the whole of", "By all"),
    ("Which is the best blog title?", "Three days in the mountains",
     "My trip", "Text about travel", "Blog number four"),
]

P3_AC_V = [
    ("afford", "have enough money for something"),
    ("bargain", "something bought for much less than usual"),
    ("bill", "the paper saying how much you owe"),
    ("borrow", "take money and give it back later"),
    ("lend", "give money to be returned later"),
    ("cash", "notes and coins"),
    ("charge", "ask somebody to pay an amount"),
    ("cost", "the amount of money needed"),
    ("discount", "money off the usual price"),
    ("earn", "get money by working"),
    ("owe", "have to pay somebody back"),
    ("refund", "money returned to you"),
    ("save", "keep money instead of spending it"),
    ("spend", "use money to buy things"),
    ("receipt", "proof of what you paid"),
    ("salary", "the money you get for your job each month"),
    ("value", "how much something is worth"),
    ("waste", "use money or time badly"),
    ("expensive", "costing a lot"),
    ("reasonable", "not too expensive for what it is"),
    ("worth it", "good enough for the money you paid"),
    ("in advance", "paid before you get the thing"),
    ("second-hand", "not new, used by somebody before"),
    ("customer", "somebody who buys"),
    ("pay back", "return money you borrowed"),
]

P3_AC_G = [
    ("I ___ my new phone last week.", "bought", "have bought", "buy",
     "was buying"),
    ("I ___ this phone for two weeks.", "have had", "had", "have has",
     "am having"),
    ("She ___ to the new shopping centre yet.", "hasn't been", "wasn't",
     "didn't be", "hasn't gone yesterday"),
    ("We ___ our tickets yesterday.", "got", "have got", "have gotten then",
     "were getting"),
    ("___ you ever borrowed money from a friend?", "Have", "Did", "Do", "Are"),
    ("___ you borrow money last month?", "Did", "Have", "Do", "Were"),
    ("Which sentence says when?", "I paid the bill on Monday.",
     "I have paid the bill.", "I've just paid the bill.",
     "I have already paid it."),
    ("Which is correct?", "He has worked here since May.",
     "He has worked here in May.", "He worked here since May.",
     "He is working here since May."),
    ("They ___ in this shop for ten years.", "have worked", "worked since",
     "are working since", "work since"),
    ("Which is WRONG?", "I have bought it yesterday.", "I bought it yesterday.",
     "I have bought it already.", "I haven't bought it yet."),
    ("The shop ___ last year and is doing well.", "opened", "has opened then",
     "opens", "was opened then"),
    ("'___ you finished shopping?' 'Not yet.'", "Have", "Did", "Do", "Are"),
    ("Prices ___ a lot since last year.", "have risen", "rose since",
     "are rising since", "rise since"),
    ("I ___ my wallet. I can't find it anywhere.", "have lost", "lost then",
     "am losing", "was losing"),
    ("She ___ that dress twice this month.", "has worn", "wore this month",
     "wears", "is wearing then"),
    ("How long ___ you had that bag?", "have", "did", "are", "do"),
    ("In a shop: 'Can I ___ this, please?' 'Of course, the till is here.'",
     "pay for", "pay to", "buy of", "cost of"),
    ("'Are you paying by card or in ___?'", "cash", "money", "coins of",
     "notes only of"),
    ("'Can I have a ___, please?' 'Here you are.'", "receipt", "bill of paper",
     "ticket of money", "paper of pay"),
    ("'I'd like to ___ this jacket. It doesn't fit.'", "return", "give back to",
     "bring of", "change of it"),
    ("'Have you got the ___?' 'Yes, I kept it.'", "receipt", "money back",
     "refund of", "bill to pay"),
    ("'It's ___ than I expected.'", "cheaper", "more cheap", "cheapest",
     "more cheaper"),
    ("'Sorry, we don't ___ cards under ten thousand som.'", "accept",
     "receive of", "take of it", "allow of"),
    ("'Would you like a ___?' 'No thanks, I have a bag.'", "bag", "sack",
     "package of", "box of"),
    ("Which is polite at a till?", "Could I pay by card, please?",
     "Card. Now.", "I pay card.", "Take my card quickly."),
]

P3_BD_V = [
    ("charity", "an organisation that helps people for free"),
    ("donate", "give money or things to help"),
    ("raise money", "collect money for a cause"),
    ("volunteer", "somebody who works without pay to help"),
    ("generous", "happy to give a lot"),
    ("mean", "not willing to give or spend"),
    ("support", "help a person or cause"),
    ("fundraiser", "an event to collect money"),
    ("sponsor", "pay to support somebody's effort"),
    ("collection", "money gathered from many people"),
    ("homeless", "having nowhere to live"),
    ("poverty", "the state of being very poor"),
    ("aid", "help given to people in need"),
    ("give away", "hand over without payment"),
    ("look after", "take care of somebody"),
    ("take part", "join in an activity"),
    ("set up", "start an organisation"),
    ("get involved", "start taking part in something"),
    ("make a difference", "change things for the better"),
    ("needy", "not having enough of what is necessary"),
    ("grateful", "feeling thankful"),
    ("kindness", "friendly, helpful behaviour"),
    ("community", "the people living in one area"),
    ("campaign", "an organised effort to achieve something"),
    ("cause", "the aim an organisation works for"),
]

P3_BD_G = [
    ("I've ___ finished the report.", "already", "yet", "still not", "ever"),
    ("Have you called them ___?", "yet", "already", "just now of", "ever yet"),
    ("She's ___ arrived. She's in the kitchen.", "just", "yet", "still of",
     "since"),
    ("We haven't decided ___.", "yet", "already", "just", "ever"),
    ("Which is correct?", "I've already seen that film.",
     "I've seen already that film.", "I already have seen that film yet.",
     "I've seen that film already yet."),
    ("Where does 'yet' usually go?", "at the end of a question or negative",
     "before the verb", "after the subject", "at the start of the sentence"),
    ("'Has the post arrived ___?' 'Yes, it came an hour ago.'", "yet",
     "already", "just", "still"),
    ("They've ___ raised half the money.", "already", "yet", "still",
     "ever since"),
    ("Which is WRONG?", "I have finished yet.", "I have already finished.",
     "I haven't finished yet.", "Have you finished yet?"),
    ("He's ___ donated to three charities this year.", "already", "yet",
     "since", "ever"),
    ("'___ you decided which charity to support?'", "Have", "Did", "Do",
     "Are"),
    ("We've ___ collected enough for the school.", "just", "yet", "since",
     "ever"),
    ("She has ___ volunteered there for two years.", "already", "yet", "just of",
     "since of"),
    ("Which sentence means it happened a moment ago?", "They've just left.",
     "They've already left.", "They haven't left yet.", "They left yet."),
    ("Which sentence means it is still expected?", "He hasn't replied yet.",
     "He has already replied.", "He has just replied.", "He replied already."),
    ("I've ___ been to that charity shop. It's great.", "already", "yet",
     "still of", "ever of"),
    ("An email asking for help might begin: 'I'm writing to ___ for support.'",
     "ask", "request of you", "demand", "order"),
    ("'Would you be ___ to help us on Saturday?'", "able", "can", "possible of",
     "capable to"),
    ("'Any amount, however small, ___ a difference.'", "makes", "does", "takes",
     "gives of"),
    ("'Thank you ___ your generous donation.'", "for", "of", "by", "to"),
    ("'We're ___ money for the children's hospital.'", "raising", "rising",
     "lifting of", "growing of"),
    ("'All the money ___ to the families directly.'", "goes", "gives", "takes",
     "brings of"),
    ("Which is the strongest reason to give?",
     "Every donation pays for a week of medicine.",
     "We need money.", "Please give us something.", "Donations are good."),
    ("'Please ___ this message with your friends.'", "share", "divide",
     "separate of", "part of"),
    ("Which closing suits a charity email?", "Thank you for your support,",
     "Give now or else,", "Whatever,", "Money please,"),
]

P4_AC_V = [
    ("celebration", "an occasion when people enjoy something special"),
    ("anniversary", "the date something important happened in an earlier year"),
    ("ceremony", "a formal public event"),
    ("decorate", "make a place look nice for an event"),
    ("fireworks", "explosions of colour in the night sky"),
    ("guest", "somebody invited to an event"),
    ("host", "the person who invites and looks after guests"),
    ("invitation", "the message asking somebody to come"),
    ("occasion", "a special event or time"),
    ("parade", "a public procession through the streets"),
    ("present", "something you give on a special day"),
    ("tradition", "something people have done for many years"),
    ("wedding", "the ceremony when two people marry"),
    ("birthday", "the yearly date of your birth"),
    ("graduation", "the ceremony when you finish studying"),
    ("festival", "days of public celebration"),
    ("candle", "wax with a wick that you light"),
    ("cake", "the sweet food cut at a celebration"),
    ("speech", "a formal talk given to guests"),
    ("toast", "raising your glass to wish somebody well"),
    ("costume", "special clothes worn for an event"),
    ("gathering", "a meeting of people together"),
    ("celebrate", "do something enjoyable for a special reason"),
    ("congratulate", "tell somebody you are pleased for them"),
    ("religious holiday", "a day off for religious reasons"),
]

P4_AC_G = [
    ("I ___ my grandmother on Sunday. It's arranged.", "am visiting",
     "will visit maybe", "visit", "am visit"),
    ("We ___ to have a big party next month.", "are going", "will going",
     "go", "are go"),
    ("Look at the clouds! It ___ rain.", "is going to", "will", "goes to",
     "going to"),
    ("The train ___ at 7.15 tomorrow.", "leaves", "is leaving then", "will leave",
     "leave"),
    ("She ___ study medicine. She's decided.", "is going to", "will",
     "is go to", "going to"),
    ("Which sentence is an arrangement with another person?",
     "I'm meeting Sara at six.", "I'll meet Sara at six.",
     "I meet Sara at six.", "I am meet Sara at six."),
    ("Which sentence is a prediction from what you can see?",
     "She's going to fall!", "She falls!", "She will fall always.",
     "She is fall!"),
    ("___ you doing anything on Friday?", "Are", "Do", "Will", "Is"),
    ("What ___ you going to wear?", "are", "do", "will", "is"),
    ("We aren't ___ to invite many people.", "going", "go", "will", "gone"),
    ("Which is WRONG?", "I'm going to meeting him tomorrow.",
     "I'm going to meet him tomorrow.", "I'm meeting him tomorrow.",
     "I'll meet him tomorrow."),
    ("The ceremony ___ at nine o'clock, according to the programme.",
     "starts", "is starting maybe", "will start maybe", "start"),
    ("'What are your ___ for the weekend?'", "plans", "plan of", "planning of",
     "planned of"),
    ("They ___ get married in autumn.", "are going to", "will going to",
     "go to", "are going"),
    ("I ___ see my cousin at the wedding.", "am going to", "am go to",
     "will going", "go to"),
    ("Which is a fixed timetable?", "The film starts at eight.",
     "I'm starting the film at eight.", "I will start the film at eight.",
     "I am going to start the film at eight."),
    ("'Are you free on Saturday?' 'Sorry, I ___ my aunt.'", "am visiting",
     "visit", "will visit then", "am visit"),
    ("'___ we meet at seven?' 'Perfect.'", "Shall", "Will", "Do", "Are"),
    ("'How ___ meeting outside the cinema?'", "about", "for", "to", "of"),
    ("'I'll ___ you outside at six.'", "see", "seeing", "saw", "to see"),
    ("'Let's ___ it half past seven.'", "make", "do", "take", "put"),
    ("'Sorry, I can't ___ it on Friday.'", "make", "do", "take", "have"),
    ("'Is Tuesday ___ for you?'", "OK", "okey of", "fine of it", "good of"),
    ("'I'm afraid something has come ___.'", "up", "on", "in", "over"),
    ("Which is the politest way to change a plan?",
     "Would it be possible to meet on Thursday instead?",
     "Change it to Thursday.", "I want Thursday.", "Not Friday. Thursday."),
]

P4_BD_V = [
    ("accept", "say yes to an offer or invitation"),
    ("refuse", "say no to something offered"),
    ("reply", "answer a message or invitation"),
    ("attend", "go to an event"),
    ("apologise", "say you are sorry"),
    ("arrange", "organise something in advance"),
    ("cancel", "say an event will not happen"),
    ("postpone", "move an event to a later date"),
    ("confirm", "say definitely that something is true"),
    ("remind", "help somebody remember"),
    ("look forward to", "feel happy about something coming"),
    ("free", "not busy at that time"),
    ("busy", "having a lot to do"),
    ("available", "able to be used or seen at that time"),
    ("suit", "be convenient for somebody"),
    ("meet up", "come together with somebody"),
    ("put off", "delay to a later time"),
    ("turn down", "say no to an offer"),
    ("join in", "take part with others"),
    ("drop by", "visit somebody for a short time"),
    ("be on time", "arrive at the right moment"),
    ("be late", "arrive after the right moment"),
    ("host a party", "hold a party at your place"),
    ("RSVP", "please reply to this invitation"),
    ("occasion", "a particular event or time"),
]

P4_BD_G = [
    ("I think it ___ rain tomorrow.", "will", "is going", "shall", "would"),
    ("I ___ help you with that bag.", "'ll", "am", "do", "would of"),
    ("They ___ come. They're too busy.", "won't", "willn't", "don't will",
     "aren't will"),
    ("___ I open the window?", "Shall", "Will", "Do", "Am"),
    ("___ we take a taxi?", "Shall", "Will", "Do", "Are"),
    ("Which sentence is a decision made now?", "OK, I'll call her.",
     "OK, I'm going to call her already.", "OK, I call her.",
     "OK, I am call her."),
    ("Which sentence is a plan made before?", "I'm going to call her tonight.",
     "I'll call her tonight, I've just decided.", "I call her tonight.",
     "Shall I call her tonight?"),
    ("She ___ be at home. Her car isn't there.", "won't", "willn't",
     "don't will", "isn't will"),
    ("Which is a promise?", "I'll pay you back on Friday.",
     "I'm paying you back on Friday.", "I pay you back on Friday.",
     "Shall I pay you back?"),
    ("Which is an offer?", "I'll carry that for you.",
     "I'm carrying that for you now.", "I carry that for you.",
     "I am carry that for you."),
    ("Which is WRONG?", "I will to help you.", "I will help you.",
     "I'll help you.", "Will you help me?"),
    ("Perhaps we ___ see them at the party.", "will", "shall of", "are will",
     "do will"),
    ("'Will she come?' 'I don't think ___.'", "so", "it", "that of", "yes of"),
    ("The party ___ be on Saturday, not Friday.", "will", "shall of",
     "is will", "does will"),
    ("Which shows a strong prediction?", "It will definitely rain.",
     "It will rain maybe not.", "It shall rain of.", "It wills rain."),
    ("'Shall I bring something?' 'That ___ be lovely.'", "would", "will of be",
     "shall", "is will"),
    ("An invitation often ends with ___.", "Please let me know if you can come.",
     "Come or don't.", "Reply immediately or lose.", "This is compulsory."),
    ("Accepting: '___ love to come.'", "I'd", "I will of", "I am of", "I do"),
    ("Refusing politely: 'I'm afraid I ___ make it.'", "won't be able to",
     "will not can", "don't can", "am not able of"),
    ("'Thanks for the ___. I'll be there.'", "invitation", "invite of me",
     "inviting of", "invited"),
    ("'Sorry, I've already ___ something that evening.'", "arranged",
     "arrange", "arranging of", "arrangement of"),
    ("'Can I bring a ___?' 'Of course.'", "friend", "friendly of",
     "friendship", "friends of mine to be"),
    ("'What time should I ___?'", "arrive", "arriving", "arrival of", "arrived"),
    ("'Looking forward ___ seeing you.'", "to", "for", "of", "at"),
    ("Which is a good short reply to an invitation?",
     "Thanks! Count me in.", "Yes.", "Maybe I will come or not.",
     "I have received your invitation and will consider it."),
]

LISTS = [
    ("Unit 1A&C · Vocabulary — describing things", "vocab", 1, P1_AC_V),
    ("Unit 1A&C · Grammar — question forms, and meeting people", "grammar", 1, P1_AC_G),
    ("Unit 1B&D · Vocabulary — keeping in touch", "vocab", 2, P1_BD_V),
    ("Unit 1B&D · Grammar — simple or continuous, and emails", "grammar", 2, P1_BD_G),
    ("Unit 2A&C · Vocabulary — holidays", "vocab", 3, P2_AC_V),
    ("Unit 2A&C · Grammar — the past simple, and asking in public", "grammar", 3, P2_AC_G),
    ("Unit 2B&D · Vocabulary — travel collocations", "vocab", 4, P2_BD_V),
    ("Unit 2B&D · Grammar — the past continuous, and a travel blog", "grammar", 4, P2_BD_G),
    ("Unit 3A&C · Vocabulary — money", "vocab", 5, P3_AC_V),
    ("Unit 3A&C · Grammar — perfect or past, and paying", "grammar", 5, P3_AC_G),
    ("Unit 3B&D · Vocabulary — helping others", "vocab", 6, P3_BD_V),
    ("Unit 3B&D · Grammar — already and yet, and asking for help", "grammar", 6, P3_BD_G),
    ("Unit 4A&C · Vocabulary — celebrations", "vocab", 7, P4_AC_V),
    ("Unit 4A&C · Grammar — talking about plans, and arrangements", "grammar", 7, P4_AC_G),
    ("Unit 4B&D · Vocabulary — invitations", "vocab", 8, P4_BD_V),
    ("Unit 4B&D · Grammar — will and shall, and replying", "grammar", 8, P4_BD_G),
]
