"""Empower Intermediate (B1+) Units 1-4, in the A&C / B&D pairing.

    1A friendship; subject and object questions   1C giving news
    1B gradable and extreme adjectives; simple or continuous   1D how you learn
    2A work; present perfect and past simple      2C talking about changes
    2B technology; perfect simple or continuous   2D life changes
    3A relationships; narrative tenses            3C telling a story
    3B multi-word verbs; used to and usually      3D a story
    4A ability; modals of ability                 4C question tags
    4B personality; articles                      4D websites
"""

LEVEL = "Intermediate"
BOOK = "Empower Intermediate"
PAST_FROM = 1

I1_AC_V = [
    ("acquaintance", "tanish / знакомый"),
    ("close friend", "yaqin do'st / близкий друг"),
    ("colleague", "hamkasb / коллега"),
    ("get on with", "chiqishib ketmoq / ладить"),
    ("fall out with", "urishib qolmoq / поссориться"),
    ("make up with", "yarashmoq / помириться"),
    ("keep in touch", "aloqani saqlamoq / поддерживать связь"),
    ("lose touch", "aloqani uzmoq / терять связь"),
    ("have a lot in common", "umumiyligi ko'p / иметь много общего"),
    ("get to know", "tanishib olmoq / узнавать ближе"),
    ("trust", "ishonmoq / доверять"),
    ("support", "qo'llab-quvvatlamoq / поддерживать"),
    ("argue", "janjallashmoq / спорить"),
    ("apologise", "kechirim so'ramoq / извиняться"),
    ("gossip", "g'iybat qilmoq / сплетничать"),
    ("misunderstand", "noto'g'ri tushunmoq / неправильно понять"),
    ("interrupt", "so'zini bo'lmoq / перебивать"),
    ("whisper", "shivirlamoq / шептать"),
    ("mention", "eslatib o'tmoq / упоминать"),
    ("discuss", "muhokama qilmoq / обсуждать"),
    ("persuade", "ko'ndirmoq / уговаривать"),
    ("admit", "tan olmoq / признавать"),
    ("promise", "va'da bermoq / обещать"),
    ("reply", "javob qaytarmoq / отвечать"),
    ("catch up", "yangiliklarni bilib olmoq / наверстать новости"),
]

I1_AC_G = [
    ("Who ___ you this news?", "told", "did tell", "has told you of",
     "was telling to"),
    ("Who ___ the window?", "broke", "did break", "was break", "did broke"),
    ("What ___ ?", "happened", "did happen", "was happen", "has happen"),
    ("Which question asks about the subject?", "Who called you?",
     "Who did you call?", "Whom did you call?", "Who did call you?"),
    ("Which question asks about the object?", "Who did you invite?",
     "Who invited you?", "Who came?", "What happened?"),
    ("___ told you about the party?", "Who", "Whom", "Who did", "What did"),
    ("Who did she ___ at the conference?", "meet", "met", "meets",
     "meeting"),
    ("What ___ you say to him?", "did", "were", "have", "was"),
    ("Which is correct?", "Who wants tea?", "Who does want tea?",
     "Who do want tea?", "Who is want tea?"),
    ("Which is WRONG?", "Who did write this?", "Who wrote this?",
     "Who did you write to?", "What did you write?"),
    ("How many people ___ to the meeting?", "came", "did come", "was coming",
     "did came"),
    ("___ happened to your phone?", "What", "What did", "Which did",
     "How did"),
    ("Which needs the auxiliary 'did'?", "Where did they go?",
     "Who went there?", "What happened next?", "Who called?"),
    ("Who ___ she invite to dinner?", "did", "was", "has", "does"),
    ("Which sounds natural?", "Who told you?", "Who has told you it?",
     "Who did told you?", "By whom told you?"),
    ("Giving news: 'You'll never ___ what happened.'", "guess", "know of",
     "think of it", "believe of"),
    ("'Guess ___ !' 'What?'", "what", "which", "how", "that"),
    ("Responding: 'You're ___ !'", "kidding", "kidder", "kidded of",
     "kid of it"),
    ("'That's ___ news.'", "great", "greatly", "greater of", "the great"),
    ("'I'm so ___ for you.'", "happy", "happily", "happiness of", "happier of"),
    ("'Oh no, that's ___ .'", "terrible", "terribly", "terror of",
     "the terrible"),
    ("'What a ___ !' 'I know, I didn't expect it either.'", "surprise",
     "surprised", "surprising of it", "surprisingly"),
    ("'How did it ___ out?' 'Really well.'", "turn", "come of", "go of it",
     "finish of"),
    ("'Tell me all about ___ .'", "it", "them of", "that of it", "this of"),
    ("Which reply shows interest best?", "Really? What happened next?",
     "OK.", "Fine.", "Anyway."),
]

I1_BD_V = [
    ("exhausted", "holdan toygan / измотанный"),
    ("freezing", "muzlagan darajada sovuq / очень холодный"),
    ("boiling", "qaynoq issiq / очень жаркий"),
    ("starving", "och qolgan / очень голодный"),
    ("delighted", "juda xursand / в восторге"),
    ("furious", "g'azabda / в ярости"),
    ("terrified", "dahshatga tushgan / в ужасе"),
    ("fascinating", "o'ta qiziqarli / захватывающий"),
    ("enormous", "juda katta / огромный"),
    ("tiny", "juda kichkina / крошечный"),
    ("awful", "dahshatli yomon / ужасный"),
    ("brilliant", "juda zo'r / великолепный"),
    ("filthy", "juda iflos / очень грязный"),
    ("ancient", "juda qadimiy / древний"),
    ("gorgeous", "juda go'zal / великолепный"),
    ("hilarious", "juda kulgili / уморительный"),
    ("impossible", "mutlaqo mumkin emas / невозможный"),
    ("packed", "liq to'la / битком набитый"),
    ("spotless", "ozoda / безупречно чистый"),
    ("tiring", "charchatadigan / утомительный"),
    ("annoying", "asabga tegadigan / раздражающий"),
    ("crowded", "gavjum / переполненный"),
    ("pleased", "mamnun / довольный"),
    ("upset", "xafa / расстроенный"),
    ("scared", "qo'rqqan / напуганный"),
]

I1_BD_G = [
    ("I ___ to work by bus every day.", "go", "am going", "goes", "am go"),
    ("This week I ___ from home.", "am working", "work", "works",
     "am work"),
    ("She ___ three languages.", "speaks", "is speaking", "speak",
     "is speak"),
    ("Listen! Somebody ___ at the door.", "is knocking", "knocks", "knock",
     "is knock"),
    ("Which verb is not used in the continuous?", "believe", "study", "watch",
     "travel"),
    ("I ___ what you mean.", "see", "am seeing", "sees", "am see"),
    ("He ___ his brother this week.", "is seeing", "sees", "see", "is see"),
    ("These days more people ___ from home.", "are working", "work every",
     "works", "is working"),
    ("Water ___ at 100 degrees.", "boils", "is boiling", "boil", "is boil"),
    ("Which is correct?", "I'm thinking of changing jobs.",
     "I think of changing jobs now.", "I am think of changing jobs.",
     "I thinking of changing jobs."),
    ("Which is WRONG?", "I am knowing the answer.", "I know the answer.",
     "I'm learning the answer.", "I don't know the answer."),
    ("The film ___ at eight tonight.", "starts", "is starting always",
     "start", "is start"),
    ("Why ___ you looking at me like that?", "are", "do", "is", "does"),
    ("My phone ___ working properly these days.", "isn't", "doesn't",
     "not is", "aren't"),
    ("She ___ always late! It drives me mad.", "is", "has", "does", "was"),
    ("Which describes a temporary situation?", "I'm staying with my aunt.",
     "I stay with my aunt.", "I stayed with my aunt.",
     "I have stayed with my aunt."),
    ("Learning styles: 'I learn best by ___ things.'", "doing", "do",
     "to do", "done of"),
    ("'I find it easier ___ information with pictures.'", "to remember",
     "remembering of", "remember", "for remember"),
    ("'Highlighting helps me ___ the main points.'", "notice", "noticing of",
     "to noticing", "noticed of"),
    ("'I ___ better in the morning.'", "concentrate", "concentration of",
     "am concentrate", "concentrating of"),
    ("'Repeating something aloud ___ me remember it.'", "helps", "help",
     "helping of", "is help"),
    ("'What ___ for you?' 'Flashcards.'", "works", "work", "working of",
     "is work"),
    ("'I'm ___ at learning from videos.'", "good", "well", "goodly of",
     "better of it"),
    ("'Everyone learns ___ .'", "differently", "different", "difference of",
     "differ of"),
    ("Which is the most useful learning tip?",
     "Test yourself instead of rereading your notes.",
     "Read your notes again and again.", "Learn everything at once.",
     "Study only the night before."),
]

I2_AC_V = [
    ("apply for", "ish uchun ariza bermoq / подавать заявление"),
    ("be promoted", "lavozimi ko'tarilmoq / получить повышение"),
    ("be made redundant", "ishdan qisqartirilmoq / попасть под сокращение"),
    ("resign", "ishdan bo'shamoq / увольняться"),
    ("take on", "ishga olmoq / нанимать"),
    ("deal with", "hal qilmoq / заниматься"),
    ("run a business", "biznes yuritmoq / вести бизнес"),
    ("work shifts", "smenada ishlamoq / работать посменно"),
    ("do overtime", "qo'shimcha ishlamoq / работать сверхурочно"),
    ("meet a deadline", "muddatga ulgurmoq / уложиться в срок"),
    ("attend a meeting", "yig'ilishda qatnashmoq / присутствовать на собрании"),
    ("give a presentation", "taqdimot qilmoq / делать презентацию"),
    ("earn a salary", "maosh olmoq / получать зарплату"),
    ("get a bonus", "mukofot olmoq / получать премию"),
    ("be self-employed", "o'ziga ishlamoq / быть самозанятым"),
    ("work freelance", "erkin ishlamoq / работать фрилансером"),
    ("employer", "ish beruvchi / работодатель"),
    ("employee", "xodim / сотрудник"),
    ("workload", "ish yuki / нагрузка"),
    ("colleague", "hamkasb / коллега"),
    ("qualification", "malaka / квалификация"),
    ("experience", "tajriba / опыт"),
    ("career break", "ishdan tanaffus / перерыв в карьере"),
    ("work-life balance", "ish va hayot muvozanati / баланс работы и жизни"),
    ("staff turnover", "xodimlar almashinuvi / текучесть кадров"),
]

I2_AC_G = [
    ("I ___ in this company since 2020.", "have worked", "worked since",
     "am working since", "work since"),
    ("She ___ her job last month.", "left", "has left last month",
     "leaves", "is leaving then"),
    ("___ you ever worked abroad?", "Have", "Did", "Do", "Are"),
    ("___ you work abroad in 2019?", "Did", "Have", "Do", "Were"),
    ("He ___ three jobs so far this year.", "has had", "had this year",
     "has have", "is having"),
    ("We ___ the contract yesterday.", "signed", "have signed yesterday",
     "sign", "were signing then"),
    ("Which sentence says when it happened?", "I applied in March.",
     "I have applied.", "I've just applied.", "I have already applied."),
    ("Which is correct?", "She has been a manager since May.",
     "She has been a manager in May.", "She is a manager since May.",
     "She was a manager since May."),
    ("How long ___ you known your boss?", "have", "did", "are", "do"),
    ("Which is WRONG?", "I have started this job last week.",
     "I started this job last week.", "I have started a new job.",
     "I haven't started yet."),
    ("They ___ never worked shifts before.", "have", "has", "did", "are"),
    ("The company ___ in 1998.", "was founded", "has been founded in 1998",
     "founds", "is founding"),
    ("I ___ my CV three times this week.", "have updated", "updated this week",
     "update", "am updating then"),
    ("'___ you finished the report?' 'Not yet.'", "Have", "Did", "Do", "Are"),
    ("She ___ for that firm for two years, then she moved.", "worked",
     "has worked", "works", "is working"),
    ("Which time phrase goes with the present perfect?", "so far",
     "yesterday", "in 2019", "last week"),
    ("Talking about change: 'I've decided to ___ a career break.'", "take",
     "make", "do", "have of"),
    ("'I'm thinking of ___ something completely different.'", "doing", "do",
     "to do", "done of"),
    ("'What made you ___ your mind?'", "change", "changing of", "to changing",
     "changed of"),
    ("'It was a difficult ___ to make.'", "decision", "decide of",
     "deciding of", "decided of"),
    ("'In the ___ , it was the right move.'", "end", "final of", "last of it",
     "ending of"),
    ("'I don't ___ leaving at all.'", "regret", "regretting of", "regrets of",
     "regretted of it"),
    ("'It's ___ out well so far.'", "turned", "turn", "turning of",
     "turns of"),
    ("'I'd never ___ back.'", "go", "gone", "went", "going of"),
    ("Which sentence reflects on a change well?",
     "Looking back, leaving was the best thing I did.",
     "I left my job and that is all.", "My job was left by me.",
     "Leaving happened to me then."),
]

I2_BD_V = [
    ("device", "qurilma / устройство"),
    ("gadget", "kichik qurilma / гаджет"),
    ("app", "ilova / приложение"),
    ("software", "dastur ta'minoti / программное обеспечение"),
    ("hardware", "texnik jihoz / аппаратное обеспечение"),
    ("data", "ma'lumotlar / данные"),
    ("download", "yuklab olmoq / скачивать"),
    ("upload", "yuklamoq / загружать"),
    ("update", "yangilamoq / обновлять"),
    ("install", "o'rnatmoq / устанавливать"),
    ("back up", "zaxira nusxa qilmoq / делать резервную копию"),
    ("log in", "kirmoq / входить"),
    ("password", "parol / пароль"),
    ("screen time", "ekran oldida o'tgan vaqt / экранное время"),
    ("charger", "quvvatlagich / зарядка"),
    ("battery life", "batareya quvvati / время работы батареи"),
    ("wireless", "simsiz / беспроводной"),
    ("network", "tarmoq / сеть"),
    ("storage", "xotira joyi / хранилище"),
    ("stream", "onlayn ko'rmoq / смотреть онлайн"),
    ("addictive", "o'ziga bog'lab qo'yadigan / вызывающий зависимость"),
    ("notification", "bildirishnoma / уведомление"),
    ("crash", "ishdan chiqmoq / зависать"),
    ("user-friendly", "foydalanish oson / удобный в использовании"),
    ("out of date", "eskirgan / устаревший"),
]

I2_BD_G = [
    ("I ___ this app for two months.", "have been using", "use since",
     "am using since", "used since"),
    ("She ___ three emails today.", "has written", "has been writing three",
     "writes", "is writing then"),
    ("They ___ all morning and they're still not finished.",
     "have been working", "have worked all morning and still",
     "are working since", "work since"),
    ("How long ___ you been waiting?", "have", "did", "are", "do"),
    ("I'm tired because I ___ .", "have been running", "have run three times",
     "run", "am run"),
    ("Which stresses the result?", "I've written ten emails.",
     "I've been writing emails.", "I write emails.", "I am writing emails."),
    ("Which stresses how long?", "I've been reading all day.",
     "I've read the book.", "I read the book.", "I have read it twice."),
    ("He ___ his phone three times this year.", "has changed",
     "has been changing three times", "changes", "is changing"),
    ("Which is WRONG?", "I have been knowing him for years.",
     "I have known him for years.", "I've been learning English for years.",
     "I've learnt a lot."),
    ("My laptop ___ strangely since the update.", "has been behaving",
     "behaves since", "is behaving since", "behaved since"),
    ("She ___ that series since Monday.", "has been watching", "watches since",
     "watched since", "is watching since"),
    ("'You look hot.' 'Yes, I ___ .'", "have been running",
     "have run every day", "run", "am run"),
    ("We ___ each other since university.", "have known", "have been knowing",
     "know since", "are knowing since"),
    ("The battery ___ much faster lately.", "has been dying", "dies since",
     "died since", "is died"),
    ("Which is correct?", "I've been trying to call you all day.",
     "I've tried to call you all day long continuously.",
     "I try to call you all day.", "I am try to call you."),
    ("They've ___ over 200 photos on that trip.", "taken", "been taking 200",
     "take", "taking"),
    ("Talking about a change in life: 'I've ___ up running.'", "taken",
     "made", "done", "got of"),
    ("'I've ___ down on coffee.'", "cut", "made", "put", "taken of"),
    ("'She's ___ on a lot of new responsibilities.'", "taken", "made", "put",
     "got of"),
    ("'He's ___ out of the habit of checking his phone.'", "got", "taken",
     "made", "come of"),
    ("'I'm trying to ___ more time outdoors.'", "spend", "pass of", "make of",
     "do of"),
    ("'It's ___ a big difference.'", "made", "done", "taken", "got of"),
    ("'I don't ___ as much time online as I used to.'", "spend", "pass",
     "make", "do"),
    ("'Life has ___ a lot since then.'", "changed", "changing of",
     "change of", "been change"),
    ("Which sentence describes a recent habit best?",
     "I've been going to the gym before work lately.",
     "I go to the gym once in my life.", "I went to the gym yesterday only.",
     "I will go to the gym."),
]

I3_AC_V = [
    ("get married", "turmush qurmoq / жениться"),
    ("get engaged", "unashtirilmoq / обручиться"),
    ("get divorced", "ajrashmoq / разводиться"),
    ("split up", "ajralishmoq / расставаться"),
    ("go out with", "uchrashib yurmoq / встречаться с"),
    ("fall in love", "sevib qolmoq / влюбиться"),
    ("propose", "turmushga taklif qilmoq / делать предложение"),
    ("settle down", "oila qurib joylashmoq / остепениться"),
    ("bring up", "tarbiyalamoq / воспитывать"),
    ("look after", "qaramoq / ухаживать"),
    ("take after", "o'xshamoq / быть похожим на"),
    ("grow apart", "bir-biridan uzoqlashmoq / отдаляться"),
    ("make up", "yarashmoq / мириться"),
    ("get on well", "yaxshi chiqishmoq / хорошо ладить"),
    ("stay in touch", "aloqada bo'lmoq / оставаться на связи"),
    ("relative", "qarindosh / родственник"),
    ("partner", "hayot yo'ldoshi / партнёр"),
    ("neighbour", "qo'shni / сосед"),
    ("ex", "sobiq / бывший"),
    ("in-laws", "qaynonalar tomon / родня супруга"),
    ("retired", "nafaqadagi / на пенсии"),
    ("single", "yolg'iz, turmush qurmagan / холостой"),
    ("couple", "juftlik / пара"),
    ("anniversary", "yilligi / годовщина"),
    ("reunion", "uchrashuv / воссоединение"),
]

I3_AC_G = [
    ("I ___ dinner when the phone rang.", "was cooking", "cooked then",
     "have cooked", "am cooking"),
    ("By the time we arrived, they ___ .", "had left", "left already then",
     "have left", "were leaving then"),
    ("She ___ for an hour before he called.", "had been waiting",
     "was waiting since", "waited since", "has waited"),
    ("While I ___ , I met an old friend.", "was walking", "walked then",
     "have walked", "had walked then"),
    ("He told me he ___ her before.", "had met", "met then", "has met",
     "was meeting"),
    ("Which tense sets the scene of a story?", "the past continuous",
     "the present perfect", "the past perfect continuous only",
     "the present simple"),
    ("Which tense shows the earlier event?", "the past perfect",
     "the past continuous", "the past simple", "the present perfect"),
    ("The sun ___ when we left the house.", "was shining", "shone then",
     "has shone", "had shone then"),
    ("They ___ married for ten years when they split up.", "had been",
     "were being", "have been", "was"),
    ("Which is correct?", "I had finished when she arrived.",
     "I have finished when she arrived.", "I was finish when she arrived.",
     "I finish when she arrived."),
    ("Which is WRONG?", "While I was going, I had seen him.",
     "While I was going, I saw him.", "I had seen him before I went.",
     "I saw him while I was going."),
    ("She was tired because she ___ all night.", "had been studying",
     "was studying since", "studied since", "has studied"),
    ("We ___ the film when the power went off.", "were watching",
     "watched then", "have watched", "had watched then"),
    ("I didn't recognise him because he ___ a beard.", "had grown",
     "grew then", "has grown", "was growing then"),
    ("What ___ you doing at ten last night?", "were", "was", "did", "are"),
    ("The story began: 'It ___ a cold winter evening.'", "was", "were", "had",
     "has been"),
    ("Telling a story: '___ , I was walking home.'", "Anyway", "By the way of",
     "Although of", "However of it"),
    ("'Suddenly, I ___ a loud noise.'", "heard", "was hearing", "have heard",
     "had hear"),
    ("'You'll never guess what ___ next.'", "happened", "did happen",
     "was happen", "has happen"),
    ("'___ that, everything went quiet.'", "After", "Afterwards of",
     "Later of that", "Then of"),
    ("'It ___ out that it was just the cat.'", "turned", "came of", "went of",
     "got of"),
    ("'To cut a long story ___ , we got home safely.'", "short", "shorter",
     "shortly of", "small of"),
    ("'In the ___ , nothing serious happened.'", "end", "final of",
     "last of it", "ending of"),
    ("'I couldn't ___ believe it.'", "quite", "quiet", "quietly of",
     "quit of"),
    ("Which sentence keeps a story moving?", "Then, out of nowhere, it started to rain.",
     "It was a story about rain.", "Rain is water from the sky.",
     "The rain existed at that time."),
]

I3_BD_V = [
    ("come across", "duch kelmoq / натыкаться"),
    ("get over", "o'zini o'nglamoq / приходить в себя"),
    ("put up with", "chidamoq / мириться с"),
    ("look up to", "hurmat qilmoq / уважать"),
    ("look down on", "mensimaslik / смотреть свысока"),
    ("run into", "tasodifan uchratmoq / случайно встретить"),
    ("turn up", "kelib qolmoq / появляться"),
    ("call off", "bekor qilmoq / отменять"),
    ("bring about", "keltirib chiqarmoq / вызывать"),
    ("carry out", "amalga oshirmoq / выполнять"),
    ("give away", "bermoq, oshkor qilmoq / отдавать, выдавать"),
    ("hold on", "kutib turmoq / подождать"),
    ("let down", "umidini puchga chiqarmoq / подводить"),
    ("make out", "ilg'amoq / разобрать"),
    ("pick up", "o'rganib olmoq / подхватывать"),
    ("point out", "e'tiborni qaratmoq / указывать"),
    ("put off", "kechiktirmoq / откладывать"),
    ("set up", "tashkil etmoq / основывать"),
    ("take over", "boshqaruvni olmoq / принимать управление"),
    ("work out", "hal bo'lmoq / решаться, получаться"),
    ("come up with", "o'ylab topmoq / придумывать"),
    ("get away with", "jazosiz qolmoq / сходить с рук"),
    ("look forward to", "intiq kutmoq / с нетерпением ждать"),
    ("run out of", "tugab qolmoq / заканчиваться"),
    ("go through", "boshdan kechirmoq / переживать"),
]

I3_BD_G = [
    ("I ___ play the piano when I was a child.", "used to", "use to",
     "am used to", "was used"),
    ("She ___ get up at five, but now she doesn't.", "used to", "use to",
     "is used to", "was use"),
    ("We ___ go to the same school.", "used to", "use to", "are used to",
     "were use"),
    ("He ___ smoke, but he gave up.", "used to", "use to", "is used to",
     "was used"),
    ("They ___ visit us every summer.", "usually", "used", "use to usually",
     "usual"),
    ("Which talks about a past habit that stopped?", "I used to cycle to work.",
     "I usually cycle to work.", "I'm used to cycling to work.",
     "I cycle to work."),
    ("Which talks about what normally happens now?",
     "She usually works late on Fridays.", "She used to work late.",
     "She is used to working late then.", "She was used to work late."),
    ("Which means you are familiar with something?",
     "I'm used to the noise now.", "I used to the noise.",
     "I use to the noise.", "I used to be the noise."),
    ("___ you use to live here?", "Did", "Do", "Have", "Were"),
    ("Which is WRONG?", "I didn't used to like it.", "I didn't use to like it.",
     "I used to like it.", "I never used to like it."),
    ("My grandmother ___ tell us stories.", "used to", "use to", "is used to",
     "was use to"),
    ("There ___ be a cinema on this corner.", "used to", "use to",
     "is used to", "was used"),
    ("We ___ spend our holidays by the sea.", "used to", "use to",
     "are used to", "were use"),
    ("He's ___ working nights now.", "used to", "use to", "used", "using to"),
    ("Which sentence is about a repeated past action?",
     "Every summer we used to camp by the river.",
     "We are used to camping.", "We camp every summer now.",
     "We will camp next summer."),
    ("I ___ think exams were pointless, but I've changed my mind.",
     "used to", "use to", "am used to", "was use to"),
    ("A story often begins: 'When I ___ younger...'", "was", "were", "had been",
     "have been"),
    ("'It all ___ when I was eighteen.'", "started", "was starting then",
     "has started", "had start"),
    ("'Looking ___ , it was a turning point.'", "back", "behind of",
     "backwards of it", "past of"),
    ("'I'll never ___ that day.'", "forget", "forgetting of", "forgot of",
     "be forget"),
    ("'At the ___ , I didn't realise how important it was.'", "time",
     "moment of then", "hour of", "period of"),
    ("'Since then, I ___ lived in three countries.'", "have", "had", "am",
     "was"),
    ("'It ___ me a lot about myself.'", "taught", "learned me",
     "teached", "was teach"),
    ("'If I ___ the chance again, I'd do the same.'", "had", "have", "would have",
     "will have"),
    ("Which is a strong story ending?",
     "I still think about that summer every year.",
     "That is the end of my story.", "The story has finished now.",
     "Thank you for reading my story."),
]

I4_AC_V = [
    ("be good at", "yaxshi eplamoq / хорошо уметь"),
    ("be capable of", "qodir bo'lmoq / быть способным"),
    ("have a talent for", "iqtidori bo'lmoq / иметь талант"),
    ("be useless at", "umuman eplay olmaslik / совершенно не уметь"),
    ("manage to", "uddalamoq / суметь"),
    ("succeed in", "erishmoq / преуспеть в"),
    ("have no idea how", "qanday qilishni bilmaslik / не иметь понятия как"),
    ("pick up quickly", "tez o'zlashtirmoq / быстро схватывать"),
    ("practise", "mashq qilmoq / практиковаться"),
    ("improve", "yaxshilamoq / улучшать"),
    ("skill", "ko'nikma / навык"),
    ("ability", "qobiliyat / способность"),
    ("strength", "kuchli tomon / сильная сторона"),
    ("weakness", "zaif tomon / слабая сторона"),
    ("confident", "ishonchli / уверенный"),
    ("hopeless", "umidsiz yomon / безнадёжный"),
    ("expert", "mutaxassis / эксперт"),
    ("beginner", "yangi boshlovchi / новичок"),
    ("training", "tayyorgarlik / подготовка"),
    ("experience", "tajriba / опыт"),
    ("effort", "harakat / усилие"),
    ("progress", "taraqqiyot / прогресс"),
    ("achievement", "yutuq / достижение"),
    ("challenge", "sinov / вызов"),
    ("determined", "qat'iyatli / решительный"),
]

I4_AC_G = [
    ("I ___ swim when I was five.", "could", "can", "could to", "was can"),
    ("She ___ to finish the race despite the pain.", "managed", "could",
     "was able of", "succeeded to"),
    ("He ___ in passing the exam.", "succeeded", "managed", "could of",
     "was able of"),
    ("They ___ speak three languages each.", "can", "could to", "cans",
     "are can"),
    ("I've never ___ able to whistle.", "been", "be", "being", "was"),
    ("Which describes a single past success?", "I managed to fix it.",
     "I could fix things.", "I can fix it.", "I am able of fixing."),
    ("Which describes a general past ability?", "She could play chess at six.",
     "She managed to play chess once.", "She was able to play once.",
     "She succeeded in playing once."),
    ("We won't ___ to come tomorrow.", "be able", "can", "could", "be can"),
    ("Which is WRONG?", "I can to drive.", "I can drive.", "I'm able to drive.",
     "I could drive then."),
    ("He's very good ___ fixing things.", "at", "in", "on", "for"),
    ("She has a talent ___ music.", "for", "of", "in", "at"),
    ("I'm hopeless ___ maths.", "at", "in", "with", "for"),
    ("Do you think you'll ___ to finish today?", "manage", "can", "could",
     "be can"),
    ("After months of practice he ___ to play the piece.", "was able",
     "could all the time", "can", "is able of"),
    ("Which is the most natural?", "I couldn't understand a word.",
     "I didn't could understand.", "I wasn't can understand.",
     "I not could understand."),
    ("Nobody ___ answer the question.", "could", "can then", "could to",
     "was can"),
    ("Question tag: 'You're coming, ___ ?'", "aren't you", "are you",
     "isn't it", "don't you"),
    ("'She doesn't drive, ___ ?'", "does she", "doesn't she", "is she",
     "do she"),
    ("'They've finished, ___ ?'", "haven't they", "have they", "didn't they",
     "aren't they"),
    ("'Let's start, ___ ?'", "shall we", "will we", "don't we", "shan't we"),
    ("'You can swim, ___ ?'", "can't you", "can you", "don't you",
     "aren't you"),
    ("'It wasn't easy, ___ ?'", "was it", "wasn't it", "did it", "is it"),
    ("'Nobody called, ___ ?'", "did they", "didn't they", "do they",
     "were they"),
    ("A tag with falling intonation means you are ___ .",
     "fairly sure and just checking", "asking a real question",
     "disagreeing", "changing the subject"),
    ("Which tag is correct?", "I'm late, aren't I?", "I'm late, amn't I?",
     "I'm late, am not I?", "I'm late, isn't it?"),
]

I4_BD_V = [
    ("outgoing", "ochiq ko'ngilli / общительный"),
    ("reserved", "o'zini tutadigan / сдержанный"),
    ("introvert", "introvert / интроверт"),
    ("extrovert", "ekstrovert / экстраверт"),
    ("sociable", "odamovi emas, xushmuomala / компанейский"),
    ("thoughtful", "o'ylab ish qiladigan / вдумчивый"),
    ("considerate", "boshqalarni o'ylaydigan / внимательный к другим"),
    ("sensitive", "ta'sirchan / чувствительный"),
    ("sensible", "aqlli, mulohazali / здравомыслящий"),
    ("ambitious", "intiluvchan / честолюбивый"),
    ("competitive", "raqobatchi / соперничающий"),
    ("hard-working", "mehnatkash / трудолюбивый"),
    ("laid-back", "beg'am, xotirjam / расслабленный"),
    ("impatient", "sabrsiz / нетерпеливый"),
    ("moody", "kayfiyati tez o'zgaruvchan / переменчивый"),
    ("stubborn", "qaysar / упрямый"),
    ("generous", "saxiy / щедрый"),
    ("selfish", "xudbin / эгоистичный"),
    ("reliable", "ishonchli / надёжный"),
    ("honest", "halol / честный"),
    ("modest", "kamtarin / скромный"),
    ("arrogant", "manman / высокомерный"),
    ("cheerful", "quvnoq / жизнерадостный"),
    ("anxious", "tashvishlanadigan / тревожный"),
    ("curious", "qiziquvchan / любознательный"),
]

I4_BD_G = [
    ("She's ___ engineer.", "an", "a", "the", "one of"),
    ("I saw ___ film you recommended.", "the", "a", "an", "(no article)"),
    ("___ water in this bottle is warm.", "The", "A", "An", "(no article)"),
    ("Do you like ___ classical music?", "(no article)", "the", "a", "an"),
    ("He plays ___ violin beautifully.", "the", "a", "an", "(no article)"),
    ("We had ___ lunch at two.", "(no article)", "the", "a", "an"),
    ("___ Uzbekistan is in Central Asia.", "(no article)", "The", "A", "An"),
    ("She's ___ most talented person I know.", "the", "a", "an",
     "(no article)"),
    ("Which is correct?", "I go to university by bus.",
     "I go to the university by the bus always.",
     "I go to a university by a bus.", "I go university by bus."),
    ("Which is WRONG?", "He is the doctor by profession.",
     "He is a doctor.", "He is the doctor who treated me.",
     "He works as a doctor."),
    ("It's ___ interesting idea.", "an", "a", "the", "(no article)"),
    ("___ sun sets early in winter.", "The", "A", "An", "(no article)"),
    ("I need ___ advice.", "some", "an", "a", "the a"),
    ("She's got ___ great sense of humour.", "a", "an", "the", "(no article)"),
    ("Which noun is uncountable and takes no 'a'?", "information", "idea",
     "suggestion", "opinion"),
    ("We stayed at ___ hotel. ___ hotel was lovely.", "a / The", "the / A",
     "an / A", "the / The"),
    ("A profile of a website says what it is ___ .", "for", "to", "of it",
     "about of"),
    ("'The site is easy ___ .'", "to use", "using of", "for use of",
     "to using"),
    ("'It ___ you to compare prices.'", "lets", "allows of", "makes of",
     "permits of it"),
    ("'You can ___ an account in seconds.'", "set up", "set of", "put up of",
     "make up of"),
    ("'What I ___ about it is the design.'", "like", "liking of", "am like",
     "liked of it"),
    ("'The only ___ is the price.'", "drawback", "draw of back",
     "pull back of", "minus of it"),
    ("'I'd ___ it to anyone who travels.'", "recommend", "advise of",
     "propose of", "suggest of it"),
    ("'Overall, it's ___ trying.'", "worth", "worthy of to", "value of",
     "worthwhile of it"),
    ("Which is the clearest recommendation?",
     "If you book a lot of trips, this site will save you time.",
     "This site is a site.", "The site is on the internet.",
     "Sites like this one exist now."),
]

LISTS = [
    ("Unit 1A&C · Vocabulary — friendship", "vocab", 1, I1_AC_V),
    ("Unit 1A&C · Grammar — subject and object questions, and news", "grammar", 1, I1_AC_G),
    ("Unit 1B&D · Vocabulary — strong adjectives", "vocab", 2, I1_BD_V),
    ("Unit 1B&D · Grammar — simple or continuous, and how you learn", "grammar", 2, I1_BD_G),
    ("Unit 2A&C · Vocabulary — work", "vocab", 3, I2_AC_V),
    ("Unit 2A&C · Grammar — perfect or past, and talking about change", "grammar", 3, I2_AC_G),
    ("Unit 2B&D · Vocabulary — technology", "vocab", 4, I2_BD_V),
    ("Unit 2B&D · Grammar — perfect simple or continuous", "grammar", 4, I2_BD_G),
    ("Unit 3A&C · Vocabulary — relationships", "vocab", 5, I3_AC_V),
    ("Unit 3A&C · Grammar — narrative tenses, and telling a story", "grammar", 5, I3_AC_G),
    ("Unit 3B&D · Vocabulary — multi-word verbs", "vocab", 6, I3_BD_V),
    ("Unit 3B&D · Grammar — used to and usually, and a life story", "grammar", 6, I3_BD_G),
    ("Unit 4A&C · Vocabulary — ability", "vocab", 7, I4_AC_V),
    ("Unit 4A&C · Grammar — ability, and question tags", "grammar", 7, I4_AC_G),
    ("Unit 4B&D · Vocabulary — personality", "vocab", 8, I4_BD_V),
    ("Unit 4B&D · Grammar — a, an and the, and reviewing a website", "grammar", 8, I4_BD_G),
]
