"""Empower Beginner Units 7-9, as Play steps, A / B / C taught separately.

    7A  clothes; present continuous             7C in a clothes shop
    7B  colours and shopping; simple or continuous
    8A  the body; feel and have got             8C at the doctor's
    8B  illness; should and imperatives
    9A  was and were                            9C talking about the weekend
    9B  past simple - regular verbs

The past simple appears for the first time in Unit 9, which is where this
book teaches it. Nothing before Unit 9 uses it.

Topics from Unit 4 on follow the standard A1 progression rather than
Azamat's own scripts, which stop at 3A. Meanings in Uzbek and Russian.
"""

LEVEL = "Beginner"
BOOK = "Empower Beginner"
PAST_FROM = 9

U7A_V = [
    ("clothes", "kiyim / одежда"),
    ("shirt", "ko'ylak (erkaklar) / рубашка"),
    ("T-shirt", "futbolka / футболка"),
    ("dress", "ko'ylak (ayollar) / платье"),
    ("skirt", "yubka / юбка"),
    ("trousers", "shim / брюки"),
    ("jeans", "jinsi shim / джинсы"),
    ("jacket", "kurtka / куртка"),
    ("coat", "palto / пальто"),
    ("jumper", "sviter / свитер"),
    ("suit", "kostyum / костюм"),
    ("shoes", "poyabzal / обувь"),
    ("boots", "etik / сапоги"),
    ("trainers", "krossovka / кроссовки"),
    ("socks", "paypoq / носки"),
    ("hat", "shlyapa / шляпа"),
    ("cap", "kepka / кепка"),
    ("scarf", "sharf / шарф"),
    ("gloves", "qo'lqop / перчатки"),
    ("belt", "kamar / ремень"),
    ("tie", "galstuk / галстук"),
    ("bag", "sumka / сумка"),
    ("wear", "kiyib yurmoq / носить"),
    ("put on", "kiymoq / надевать"),
    ("take off", "yechmoq / снимать"),
]

U7A_G = [
    ("I ___ a blue shirt today.", "am wearing", "wear", "wears", "am wear"),
    ("She ___ a red dress.", "is wearing", "wear", "wears", "are wearing"),
    ("They ___ jeans.", "are wearing", "is wearing", "wear is", "wearing"),
    ("He ___ a hat today.", "isn't wearing", "aren't wearing", "not wearing", "don't wear"),
    ("___ you wearing a coat?", "Are", "Do", "Is", "Does"),
    ("___ she wearing boots?", "Is", "Are", "Does", "Do"),
    ("A: Are you working now? B: Yes, ___.", "I am", "I do", "I'm", "am I"),
    ("A: Is he sleeping? B: No, ___.", "he isn't", "he doesn't", "he not", "isn't he"),
    ("What ___ you doing?", "are", "do", "is", "does"),
    ("Where ___ she going?", "is", "does", "are", "do"),
    ("Look! It ___.", "is raining", "rains", "rain", "are raining"),
    ("Listen! They ___.", "are singing", "sing", "sings", "is singing"),
    ("I ___ my homework at the moment.", "am doing", "do", "does", "am do"),
    ("We ___ TV now.", "are watching", "watch", "watches", "is watching"),
    ("He ___ lunch right now.", "is having", "has", "have", "are having"),
    ("The children ___ in the garden.", "are playing", "is playing", "play is", "playing"),
    ("She ___ to music now.", "is listening", "listens", "listen", "are listening"),
    ("I'm ___ a cup of tea.", "drinking", "drink", "drinks", "to drink"),
    ("They ___ at the moment.", "aren't working", "don't working", "not working", "isn't working"),
    ("My sister ___ a new jacket today.", "is wearing", "wear", "wears", "are wearing"),
    ("Why ___ you laughing?", "are", "do", "is", "does"),
    ("The baby ___ now.", "is sleeping", "sleeps", "sleep", "are sleeping"),
    ("We ___ for the bus.", "are waiting", "wait", "waits", "is waiting"),
    ("He ___ a black suit to work.", "is wearing", "wear", "wearing", "are wearing"),
    ("I ___ new shoes today.", "am wearing", "wear", "wears", "is wearing"),
]

U7B_V = [
    ("red", "qizil / красный"),
    ("blue", "ko'k / синий"),
    ("green", "yashil / зелёный"),
    ("yellow", "sariq / жёлтый"),
    ("black", "qora / чёрный"),
    ("white", "oq / белый"),
    ("brown", "jigarrang / коричневый"),
    ("grey", "kulrang / серый"),
    ("pink", "pushti / розовый"),
    ("orange", "to'q sariq / оранжевый"),
    ("size", "o'lcham / размер"),
    ("small", "kichik / маленький"),
    ("medium", "o'rtacha / средний"),
    ("large", "katta / большой"),
    ("expensive", "qimmat / дорогой"),
    ("cheap", "arzon / дешёвый"),
    ("new", "yangi / новый"),
    ("nice", "chiroyli / красивый"),
    ("try on", "kiyib ko'rmoq / примерить"),
    ("buy", "sotib olmoq / покупать"),
    ("sell", "sotmoq / продавать"),
    ("pay", "to'lamoq / платить"),
    ("cost", "turmoq (narx) / стоить"),
    ("shop", "do'kon / магазин"),
    ("money", "pul / деньги"),
]

U7B_G = [
    ("I usually ___ jeans, but today I'm wearing a suit.", "wear", "am wearing", "wears", "wearing"),
    ("She ___ to work by bus every day.", "goes", "is going", "go", "going"),
    ("Right now he ___ a book.", "is reading", "reads", "read", "are reading"),
    ("We ___ football every Sunday.", "play", "are playing", "plays", "playing"),
    ("Be quiet! The baby ___.", "is sleeping", "sleeps", "sleep", "are sleeping"),
    ("My father ___ in a bank.", "works", "is working", "work", "working"),
    ("Look at her! She ___.", "is dancing", "dances", "dance", "are dancing"),
    ("I ___ coffee every morning.", "drink", "am drinking", "drinks", "drinking"),
    ("___ you usually walk to school?", "Do", "Are", "Is", "Does"),
    ("___ you walking to school now?", "Are", "Do", "Is", "Does"),
    ("He ___ TV at the moment.", "is watching", "watches", "watch", "are watching"),
    ("They ___ to the cinema on Fridays.", "go", "are going", "goes", "going"),
    ("How much ___ this shirt cost?", "does", "do", "is", "are"),
    ("How much ___ these shoes?", "are", "is", "does", "do"),
    ("I'd like ___ this jacket on.", "to try", "try", "trying", "tries"),
    ("This is ___ than that one.", "cheaper", "cheap", "cheapest", "more cheap"),
    ("It's the ___ shirt in the shop.", "most expensive", "expensiver", "more expensive", "expensivest"),
    ("Have you got this ___ a larger size?", "in", "on", "at", "of"),
    ("I'm looking ___ a black coat.", "for", "at", "to", "on"),
    ("These trousers ___ too small.", "are", "is", "am", "does"),
    ("That dress ___ very nice.", "looks", "look", "looking", "are look"),
    ("I want ___ a new bag.", "to buy", "buy", "buying", "buys"),
    ("She ___ a lot of clothes.", "has", "have", "having", "is have"),
    ("What colour ___ your new shoes?", "are", "is", "does", "do"),
    ("I ___ like the colour.", "don't", "doesn't", "am not", "not"),
]

U7C_V = [
    ("Can I help you?", "Sizga yordam bera olamanmi? / Вам помочь?"),
    ("I'm just looking", "Shunchaki ko'ryapman / Я просто смотрю"),
    ("I'm looking for a jacket", "Kurtka qidiryapman / Я ищу куртку"),
    ("What size are you?", "Qaysi o'lchamdasiz? / Какой у вас размер?"),
    ("Can I try it on?", "Kiyib ko'rsam bo'ladimi? / Можно примерить?"),
    ("The changing room is there", "Kiyinish xonasi u yerda / Примерочная там"),
    ("It fits well", "Menga to'g'ri keldi / Хорошо сидит"),
    ("It's too big", "Bu juda katta / Слишком велико"),
    ("It's too small", "Bu juda kichik / Слишком мало"),
    ("Have you got a bigger one?", "Kattarog'i bormi? / Есть побольше?"),
    ("Have you got it in blue?", "Ko'k rangi bormi? / Есть в синем цвете?"),
    ("How much is this?", "Bu qancha turadi? / Сколько это стоит?"),
    ("It's on sale", "Bu chegirmada / Это со скидкой"),
    ("I'll take it", "Men shuni olaman / Я возьму это"),
    ("I'll think about it", "O'ylab ko'raman / Я подумаю"),
    ("Where do I pay?", "Qayerda to'layman? / Где оплатить?"),
    ("At the till, please", "Kassada, iltimos / На кассе, пожалуйста"),
    ("Card or cash?", "Karta bilanmi yoki naqdmi? / Картой или наличными?"),
    ("Can I have a receipt?", "Chek bera olasizmi? / Можно чек?"),
    ("Can I change it?", "Almashtirsam bo'ladimi? / Можно обменять?"),
    ("Keep the receipt", "Chekni saqlang / Сохраните чек"),
    ("It suits you", "Bu sizga yarashadi / Вам идёт"),
    ("What do you think?", "Nima deb o'ylaysiz? / Как вам?"),
    ("It's a good price", "Narxi yaxshi / Хорошая цена"),
    ("Thanks for your help", "Yordamingiz uchun rahmat / Спасибо за помощь"),
]

U8A_V = [
    ("body", "tana / тело"),
    ("head", "bosh / голова"),
    ("face", "yuz / лицо"),
    ("eye", "ko'z / глаз"),
    ("ear", "quloq / ухо"),
    ("nose", "burun / нос"),
    ("mouth", "og'iz / рот"),
    ("tooth", "tish / зуб"),
    ("hair", "soch / волосы"),
    ("neck", "bo'yin / шея"),
    ("arm", "qo'l (yelkadan) / рука"),
    ("hand", "kaft / кисть руки"),
    ("finger", "barmoq / палец"),
    ("leg", "oyoq / нога"),
    ("foot", "oyoq panjasi / ступня"),
    ("back", "orqa / спина"),
    ("stomach", "qorin / живот"),
    ("heart", "yurak / сердце"),
    ("tall", "baland bo'yli / высокий"),
    ("short", "past bo'yli / невысокий"),
    ("thin", "ozg'in / худой"),
    ("strong", "kuchli / сильный"),
    ("tired", "charchagan / уставший"),
    ("healthy", "sog'lom / здоровый"),
    ("ill", "kasal / больной"),
]

U8A_G = [
    ("I ___ tired today.", "feel", "feels", "am feel", "feeling"),
    ("She ___ well.", "doesn't feel", "don't feel", "isn't feel", "not feels"),
    ("He ___ long hair.", "has got", "have got", "is got", "has get"),
    ("They ___ blue eyes.", "have got", "has got", "are got", "have get"),
    ("___ you got a headache?", "Have", "Has", "Do", "Are"),
    ("My head ___.", "hurts", "hurt", "hurting", "is hurt"),
    ("My legs ___.", "hurt", "hurts", "hurting", "is hurt"),
    ("I've got ___ headache.", "a", "an", "the", "-"),
    ("She's got ___ earache.", "an", "a", "the", "-"),
    ("He is ___ tall.", "very", "much", "many", "a lot"),
    ("She's got ___ hair.", "long black", "black long", "long and black very", "the long black"),
    ("I'm not feeling ___ today.", "well", "good well", "goodly", "the well"),
    ("What's the ___?", "matter", "problem is", "wrong", "hurt"),
    ("How ___ you feeling?", "are", "do", "is", "does"),
    ("My brother is ___ than me.", "taller", "tall", "tallest", "more tall"),
    ("She is the ___ in the class.", "tallest", "taller", "tall", "most tall"),
    ("I ___ got a cold.", "have", "has", "am", "do"),
    ("He ___ got a temperature.", "hasn't", "haven't", "doesn't", "isn't"),
    ("My eyes ___ tired.", "are", "is", "am", "does"),
    ("Her hair ___ very long.", "is", "are", "am", "does"),
    ("I want ___ healthy.", "to be", "be", "being", "am"),
    ("You look ___ today.", "well", "good well", "the well", "goodly"),
    ("He's got two ___.", "feet", "foots", "footes", "foot"),
    ("I've got white ___.", "teeth", "tooths", "toothes", "tooth"),
    ("She ___ got short hair.", "has", "have", "is", "does"),
]

U8B_V = [
    ("headache", "bosh og'rig'i / головная боль"),
    ("toothache", "tish og'rig'i / зубная боль"),
    ("stomachache", "qorin og'rig'i / боль в животе"),
    ("backache", "bel og'rig'i / боль в спине"),
    ("sore throat", "tomoq og'rig'i / больное горло"),
    ("cold", "shamollash / простуда"),
    ("flu", "gripp / грипп"),
    ("cough", "yo'tal / кашель"),
    ("temperature", "harorat / температура"),
    ("pain", "og'riq / боль"),
    ("medicine", "dori / лекарство"),
    ("tablet", "tabletka / таблетка"),
    ("doctor", "shifokor / врач"),
    ("hospital", "kasalxona / больница"),
    ("pharmacy", "dorixona / аптека"),
    ("appointment", "qabulga yozilish / приём у врача"),
    ("rest", "dam olmoq / отдыхать"),
    ("better", "yaxshiroq / лучше"),
    ("worse", "yomonroq / хуже"),
    ("exercise", "mashq qilish / физические упражнения"),
    ("sleep well", "yaxshi uxlamoq / хорошо спать"),
    ("smoke", "chekmoq / курить"),
    ("dangerous", "xavfli / опасный"),
    ("careful", "ehtiyotkor / осторожный"),
    ("get well", "tuzalmoq / выздоравливать"),
]

U8B_G = [
    ("You ___ see a doctor.", "should", "shoulds", "should to", "are should"),
    ("He ___ smoke.", "shouldn't", "shouldn't to", "don't should", "not should"),
    ("___ I take this medicine?", "Should", "Do should", "Am should", "Shoulds"),
    ("You should ___ in bed.", "stay", "to stay", "staying", "stays"),
    ("You shouldn't ___ so much coffee.", "drink", "to drink", "drinking", "drinks"),
    ("___ down, please. (an instruction)", "Sit", "You sit", "To sit", "Sitting"),
    ("___ worry. (a negative instruction)", "Don't", "No", "Not", "Doesn't"),
    ("___ late! (a negative instruction)", "Don't be", "Don't", "No be", "Not be"),
    ("Open the window, ___.", "please", "pleased", "to please", "pleasing"),
    ("You ___ eat more vegetables.", "should", "shoulds", "should to", "are should"),
    ("I've got a headache. What ___ I do?", "should", "shall should", "do should", "am"),
    ("You look ill. You ___ go home.", "should", "shoulds", "should to", "are should"),
    ("She ___ work today. She's ill.", "shouldn't", "don't should", "not should", "shouldn't to"),
    ("Take this medicine ___ a day.", "twice", "two", "two time", "second"),
    ("Drink a lot ___ water.", "of", "from", "with", "for"),
    ("You should ___ more exercise.", "do", "to do", "doing", "does"),
    ("Do you feel ___ today?", "better", "gooder", "more good", "the better"),
    ("I feel ___ than yesterday.", "worse", "bad", "worst", "more bad"),
    ("___ me if you need help.", "Call", "You call", "To call", "Calling"),
    ("He should ___ a doctor.", "see", "to see", "seeing", "sees"),
    ("You ___ drive when you are tired.", "shouldn't", "don't should", "not should", "shouldn't to"),
    ("Let's ___ home early.", "go", "to go", "going", "goes"),
    ("I hope you ___ better soon.", "get", "gets", "getting", "to get"),
    ("Be ___ with the knife.", "careful", "carefully", "care", "carefuly"),
    ("You should go to ___ pharmacy.", "the", "a an", "-", "an"),
]

U8C_V = [
    ("I'd like an appointment", "Qabulga yozilmoqchiman / Я бы хотел записаться на приём"),
    ("What's the matter?", "Nima bo'ldi? / Что случилось?"),
    ("I don't feel well", "O'zimni yomon his qilyapman / Мне нехорошо"),
    ("I've got a headache", "Boshim og'riyapti / У меня болит голова"),
    ("My throat hurts", "Tomog'im og'riyapti / У меня болит горло"),
    ("How long have you had it?", "Qachondan beri shunday? / Как давно это у вас?"),
    ("Since yesterday", "Kechadan beri / Со вчерашнего дня"),
    ("Take one tablet a day", "Kuniga bitta tabletka iching / Принимайте по одной таблетке в день"),
    ("Take this to the pharmacy", "Buni dorixonaga olib boring / Отнесите это в аптеку"),
    ("Stay in bed", "To'shakda yoting / Оставайтесь в постели"),
    ("Drink a lot of water", "Ko'p suv iching / Пейте много воды"),
    ("You need a rest", "Sizga dam kerak / Вам нужен отдых"),
    ("It's nothing serious", "Jiddiy hech narsa yo'q / Ничего серьёзного"),
    ("Come back in a week", "Bir haftadan keyin keling / Приходите через неделю"),
    ("Get well soon", "Tezroq tuzalib keting / Поправляйтесь скорее"),
    ("Where does it hurt?", "Qayeringiz og'riyapti? / Где болит?"),
    ("Open your mouth", "Og'zingizni oching / Откройте рот"),
    ("I feel sick", "Ko'nglim aynayapti / Меня тошнит"),
    ("I'm allergic to it", "Menda unga allergiya bor / У меня на это аллергия"),
    ("Have you got a temperature?", "Haroratingiz bormi? / У вас есть температура?"),
    ("Is it serious?", "Bu jiddiymi? / Это серьёзно?"),
    ("Thank you, doctor", "Rahmat, doktor / Спасибо, доктор"),
    ("Call an ambulance", "Tez yordam chaqiring / Вызовите скорую"),
    ("I feel better now", "Hozir o'zimni yaxshi his qilyapman / Сейчас мне лучше"),
    ("Take care", "O'zingizni ehtiyot qiling / Берегите себя"),
]

U9A_V = [
    ("yesterday", "kecha / вчера"),
    ("last night", "kecha kechqurun / вчера вечером"),
    ("last week", "o'tgan hafta / на прошлой неделе"),
    ("last year", "o'tgan yili / в прошлом году"),
    ("ago", "oldin / тому назад"),
    ("born", "tug'ilgan / рождённый"),
    ("childhood", "bolalik / детство"),
    ("at home", "uyda / дома"),
    ("at school", "maktabda / в школе"),
    ("at work", "ishda / на работе"),
    ("on holiday", "ta'tilda / в отпуске"),
    ("abroad", "chet elda / за границей"),
    ("birthday", "tug'ilgan kun / день рождения"),
    ("party", "bazm / вечеринка"),
    ("happy", "baxtli / счастливый"),
    ("sad", "xafa / грустный"),
    ("angry", "jahli chiqqan / сердитый"),
    ("afraid", "qo'rqqan / испуганный"),
    ("boring", "zerikarli / скучный"),
    ("interesting", "qiziqarli / интересный"),
    ("difficult", "qiyin / трудный"),
    ("easy", "oson / лёгкий"),
    ("busy", "band / занятый"),
    ("free", "bo'sh / свободный"),
    ("famous", "mashhur / известный"),
]

U9A_G = [
    ("I ___ at home yesterday.", "was", "were", "am", "is"),
    ("She ___ at school last week.", "was", "were", "is", "are"),
    ("We ___ very happy.", "were", "was", "are", "is"),
    ("They ___ at the party.", "were", "was", "are", "is"),
    ("You ___ late yesterday.", "were", "was", "are", "is"),
    ("It ___ very cold last night.", "was", "were", "is", "are"),
    ("I ___ at work yesterday.", "wasn't", "weren't", "am not", "not was"),
    ("They ___ at home.", "weren't", "wasn't", "aren't", "not were"),
    ("___ you at the cinema?", "Were", "Was", "Are", "Did"),
    ("___ she at the party?", "Was", "Were", "Is", "Did"),
    ("A: Were you tired? B: Yes, ___.", "I was", "I were", "I am", "was I"),
    ("A: Was he there? B: No, ___.", "he wasn't", "he weren't", "he isn't", "wasn't he"),
    ("Where ___ you last night?", "were", "was", "are", "did"),
    ("Why ___ she angry?", "was", "were", "is", "did"),
    ("I was born ___ 2005.", "in", "on", "at", "to"),
    ("She was born ___ 3 May.", "on", "in", "at", "to"),
    ("We were there two years ___.", "ago", "before", "past", "last"),
    ("The film ___ very boring.", "was", "were", "is", "did"),
    ("My parents ___ young then.", "were", "was", "are", "did"),
    ("It ___ an easy exam.", "wasn't", "weren't", "isn't", "not was"),
    ("How ___ your holiday?", "was", "were", "is", "did"),
    ("The shops ___ closed yesterday.", "were", "was", "are", "did"),
    ("I ___ born in Samarkand.", "was", "were", "am", "did"),
    ("They ___ at home last weekend.", "were", "was", "are", "did"),
    ("___ it cold yesterday?", "Was", "Were", "Is", "Did"),
]

U9B_V = [
    ("watched", "ko'rdi / смотрел"),
    ("played", "o'ynadi / играл"),
    ("worked", "ishladi / работал"),
    ("studied", "o'qidi / учился"),
    ("started", "boshladi / начал"),
    ("finished", "tugatdi / закончил"),
    ("visited", "tashrif buyurdi / посетил"),
    ("travelled", "sayohat qildi / путешествовал"),
    ("stayed", "qoldi / остался"),
    ("arrived", "yetib keldi / приехал"),
    ("walked", "piyoda yurdi / шёл пешком"),
    ("cooked", "ovqat pishirdi / готовил"),
    ("helped", "yordam berdi / помог"),
    ("called", "qo'ng'iroq qildi / позвонил"),
    ("asked", "so'radi / спросил"),
    ("answered", "javob berdi / ответил"),
    ("listened", "tingladi / слушал"),
    ("wanted", "xohladi / хотел"),
    ("needed", "kerak bo'ldi / нуждался"),
    ("liked", "yoqdi / понравилось"),
    ("lived", "yashadi / жил"),
    ("moved", "ko'chdi / переехал"),
    ("opened", "ochdi / открыл"),
    ("closed", "yopdi / закрыл"),
    ("cleaned", "tozaladi / убрал"),
]

U9B_G = [
    ("I ___ TV last night.", "watched", "watch", "watching", "was watch"),
    ("She ___ football yesterday.", "played", "play", "playing", "was play"),
    ("We ___ in a hotel.", "stayed", "stay", "staying", "were stay"),
    ("They ___ at eight o'clock.", "arrived", "arrive", "arriving", "were arrive"),
    ("He ___ very hard last year.", "studied", "studyed", "studing", "study"),
    ("I ___ dinner for my family.", "cooked", "cook", "cooking", "was cook"),
    ("I ___ watch TV last night.", "didn't", "don't", "wasn't", "not did"),
    ("She ___ go to school yesterday.", "didn't", "doesn't", "wasn't", "not did"),
    ("___ you work yesterday?", "Did", "Do", "Were", "Was"),
    ("___ he call you?", "Did", "Do", "Was", "Were"),
    ("A: Did you like it? B: Yes, ___.", "I did", "I liked", "I was", "did I"),
    ("A: Did she come? B: No, ___.", "she didn't", "she don't", "she wasn't", "didn't she"),
    ("What ___ you do yesterday?", "did", "do", "were", "was"),
    ("Where ___ they go?", "did", "do", "were", "was"),
    ("I visited my friend ___ week.", "last", "ago", "before", "past"),
    ("We arrived two hours ___.", "ago", "last", "before", "past"),
    ("He didn't ___ the film.", "like", "liked", "liking", "likes"),
    ("Did she ___ you?", "help", "helped", "helping", "helps"),
    ("They ___ to Bukhara last summer.", "travelled", "travel", "travelling", "were travel"),
    ("I ___ the door.", "opened", "open", "opening", "was open"),
    ("We ___ our homework.", "finished", "finish", "finishing", "were finish"),
    ("She ___ in London for two years.", "lived", "live", "living", "was live"),
    ("___ they enjoy the party?", "Did", "Do", "Were", "Was"),
    ("He ___ me yesterday evening.", "called", "call", "calling", "was call"),
    ("I ___ my room this morning.", "cleaned", "clean", "cleaning", "was clean"),
]

U9C_V = [
    ("How was your weekend?", "Dam olish kuningiz qanday o'tdi? / Как прошли выходные?"),
    ("It was great", "Ajoyib bo'ldi / Было отлично"),
    ("It was OK", "Yomon emas edi / Нормально"),
    ("Nothing special", "Alohida hech narsa / Ничего особенного"),
    ("I stayed at home", "Uyda qoldim / Я остался дома"),
    ("I visited my family", "Oilamnikiga bordim / Я навестил семью"),
    ("We went to the park", "Bog'ga bordik / Мы ходили в парк"),
    ("What did you do?", "Nima qildingiz? / Что вы делали?"),
    ("Did you have a good time?", "Yaxshi vaqt o'tkazdingizmi? / Хорошо провели время?"),
    ("Yes, it was fun", "Ha, qiziqarli bo'ldi / Да, было весело"),
    ("I was very busy", "Juda band edim / Я был очень занят"),
    ("I was tired", "Charchagan edim / Я устал"),
    ("The weather was nice", "Ob-havo yaxshi edi / Погода была хорошая"),
    ("It rained all day", "Kun bo'yi yomg'ir yog'di / Весь день шёл дождь"),
    ("I slept a lot", "Ko'p uxladim / Я много спал"),
    ("We had a party", "Bazm qildik / У нас была вечеринка"),
    ("Sounds nice", "Yaxshi ekan / Звучит здорово"),
    ("Lucky you!", "Omadingiz bor ekan! / Везёт тебе!"),
    ("Me too", "Men ham / Я тоже"),
    ("Really?", "Rostdanmi? / Правда?"),
    ("That's a pity", "Afsus / Жаль"),
    ("Tell me about it", "Menga gapirib bering / Расскажи мне"),
    ("What about you?", "Sizchi? / А ты?"),
    ("See you on Monday", "Dushanbada ko'rishamiz / Увидимся в понедельник"),
    ("Have a good weekend", "Dam olish kuningiz yaxshi o'tsin / Хороших выходных"),
]

LISTS = [
    ("Unit 7A · Vocabulary — clothes", "vocab", 31, U7A_V),
    ("Unit 7A · Grammar — present continuous", "grammar", 32, U7A_G),
    ("Unit 7B · Vocabulary — colours and shopping", "vocab", 33, U7B_V),
    ("Unit 7B · Grammar — simple or continuous", "grammar", 34, U7B_G),
    ("Unit 7C · Everyday English — in a clothes shop", "vocab", 35, U7C_V),
    ("Unit 8A · Vocabulary — the body", "vocab", 36, U8A_V),
    ("Unit 8A · Grammar — feel and have got", "grammar", 37, U8A_G),
    ("Unit 8B · Vocabulary — illness", "vocab", 38, U8B_V),
    ("Unit 8B · Grammar — should and instructions", "grammar", 39, U8B_G),
    ("Unit 8C · Everyday English — at the doctor's", "vocab", 40, U8C_V),
    ("Unit 9A · Vocabulary — yesterday and feelings", "vocab", 41, U9A_V),
    ("Unit 9A · Grammar — was and were", "grammar", 42, U9A_G),
    ("Unit 9B · Vocabulary — past simple verbs", "vocab", 43, U9B_V),
    ("Unit 9B · Grammar — past simple: regular verbs", "grammar", 44, U9B_G),
    ("Unit 9C · Everyday English — your weekend", "vocab", 45, U9C_V),
]
