"""Empower Pre-Intermediate Units 9-12, in the A&C / B&D pairing.

    9A  first conditional                   9C  phone calls
    9B  verb patterns; celebrities          9D  ways of learning
    10A multi-word verbs; second conditional 10C returning goods, complaints
    10B quantifiers, too and not enough      10D apology emails
    11A compound nouns; defining relative clauses  11C directions, checking
    11B articles; luck and chance            11D an opinion post
    12A the past perfect                     12C agreeing and disagreeing
    12B reported speech                      12D news reports
"""

LEVEL = "Pre-Intermediate"
BOOK = "Empower Pre-Intermediate"
PAST_FROM = 1

P9_AC_V = [
    ("ingredient", "one of the things a dish is made from"),
    ("recipe", "the instructions for making a dish"),
    ("bake", "cook in an oven"),
    ("roast", "cook meat in an oven with fat"),
    ("grill", "cook with direct heat from above"),
    ("boil", "cook in bubbling water"),
    ("fry", "cook in hot oil"),
    ("steam", "cook over boiling water"),
    ("chop", "cut into small pieces"),
    ("slice", "cut into thin flat pieces"),
    ("peel", "remove the skin"),
    ("stir", "move a liquid round with a spoon"),
    ("mix", "combine things together"),
    ("season", "add salt, pepper or spices"),
    ("serve", "put food in front of people"),
    ("dish", "a prepared food, or a plate"),
    ("starter", "the first course of a meal"),
    ("main course", "the biggest course of a meal"),
    ("side dish", "food served with the main course"),
    ("leftovers", "food not eaten at a meal"),
    ("tasty", "having a good flavour"),
    ("bland", "having almost no flavour"),
    ("homemade", "made at home, not bought"),
    ("takeaway", "food bought to eat elsewhere"),
    ("vegetarian", "eating no meat"),
]

P9_AC_G = [
    ("If it ___ tomorrow, we'll stay at home.", "rains", "will rain", "rain",
     "is raining then"),
    ("If you ___ hard, you'll pass.", "study", "will study", "studied",
     "are study"),
    ("We ___ late if we don't leave now.", "will be", "are", "would be",
     "will to be"),
    ("If she ___ the bus, she'll be here by six.", "catches", "will catch",
     "catch", "catched"),
    ("I'll call you if I ___ any news.", "get", "will get", "got", "am get"),
    ("Which is correct?", "If I see him, I'll tell him.",
     "If I will see him, I'll tell him.", "If I see him, I tell him will.",
     "If I saw him, I'll tell him."),
    ("Which half has the present tense?", "the if half",
     "the will half", "both halves", "neither half"),
    ("If you don't hurry, you ___ the train.", "'ll miss", "miss will",
     "missed", "are missing then"),
    ("Which is WRONG?", "If it will snow, we'll stay in.",
     "If it snows, we'll stay in.", "We'll stay in if it snows.",
     "If it snows, we will stay in."),
    ("She won't come ___ you invite her.", "unless", "if not to", "except",
     "without that"),
    ("___ you finish early, call me.", "If", "Will", "Would", "Unless not"),
    ("I'll help you ___ I have time.", "if", "will", "unless not", "that"),
    ("What ___ you do if they say no?", "will", "do", "would of", "are"),
    ("If the food ___ too salty, add water.", "is", "will be", "was",
     "would be"),
    ("Which sentence is about a real future possibility?",
     "If I have time, I'll cook.", "If I had time, I would cook.",
     "If I had had time, I would have cooked.", "If I have time, I cooked."),
    ("We'll eat outside ___ it's warm enough.", "if", "will", "would of",
     "unless of"),
    ("On the phone: '___ I speak to Nodira, please?'", "Could", "Do", "Am",
     "Will"),
    ("'___ is calling, please?'", "Who", "Whose", "Whom of", "Which"),
    ("'Can I take a ___ ?' 'Yes, please.'", "message", "note of say",
     "word of", "writing of"),
    ("'Hold ___ a moment, please.'", "on", "in", "at", "up of"),
    ("'Sorry, the line is ___ .'", "engaged", "busy of line", "taken of",
     "occupied of"),
    ("'I'm afraid she's not ___ at the moment.'", "available", "able of",
     "possible of", "free of it"),
    ("'Could you ask her to ___ me back?'", "call", "ring of", "phone of",
     "return of"),
    ("'Sorry, I think you've got the wrong ___ .'", "number", "line of",
     "call of", "phone of it"),
    ("Which is the most polite on the phone?",
     "Could you tell her I called, please?", "Tell her I called.",
     "Say to her about my call.", "She must know I called."),
]

P9_BD_V = [
    ("fame", "the state of being known by many"),
    ("privacy", "being free from public attention"),
    ("pressure", "the feeling of being forced to do well"),
    ("paparazzi", "photographers who follow famous people"),
    ("rumour", "a story people repeat that may not be true"),
    ("scandal", "an event that shocks the public"),
    ("interview", "a meeting where somebody is asked questions"),
    ("fan", "somebody who admires a person or team"),
    ("talent", "a natural ability"),
    ("career", "your working life over time"),
    ("success", "achieving what you aimed for"),
    ("failure", "not achieving what you aimed for"),
    ("achievement", "something good you managed to do"),
    ("opportunity", "a chance to do something"),
    ("motivation", "the reason that makes you act"),
    ("confidence", "belief in your own ability"),
    ("criticism", "statements about what is wrong"),
    ("praise", "words saying somebody did well"),
    ("role model", "somebody others want to copy"),
    ("lifestyle", "the way a person lives"),
    ("earn", "get money by working"),
    ("deserve", "have earned the right to something"),
    ("cope with", "deal with something difficult"),
    ("give up", "stop trying"),
    ("take up", "start an activity"),
]

P9_BD_G = [
    ("I want ___ a new language.", "to learn", "learning", "learn",
     "for learning"),
    ("She enjoys ___ in the mornings.", "studying", "to study", "study",
     "for study"),
    ("They decided ___ the course.", "to take", "taking", "take",
     "for taking"),
    ("We finished ___ the project last night.", "writing", "to write", "write",
     "for write"),
    ("He promised ___ on time.", "to arrive", "arriving", "arrive",
     "for arriving"),
    ("Do you mind ___ the window?", "opening", "to open", "open",
     "for open"),
    ("She's good at ___ problems.", "solving", "to solve", "solve",
     "solved of"),
    ("I'm looking forward to ___ you.", "seeing", "see", "to see", "saw"),
    ("Which is WRONG?", "I enjoy to read.", "I enjoy reading.",
     "I want to read.", "I like reading."),
    ("He avoided ___ the question.", "answering", "to answer", "answer",
     "for answer"),
    ("They agreed ___ the price.", "to pay", "paying", "pay", "for paying"),
    ("I can't stand ___ in queues.", "waiting", "to wait of", "wait",
     "for waiting"),
    ("She offered ___ me with my homework.", "to help", "helping", "help",
     "for helping"),
    ("Which verb is followed by -ing?", "suggest", "want", "decide", "hope"),
    ("Which verb is followed by to + infinitive?", "hope", "enjoy", "avoid",
     "finish"),
    ("We're thinking of ___ abroad next year.", "moving", "to move", "move",
     "moved"),
    ("Talking about learning: 'The best way ___ a language is to use it.'",
     "to learn", "of learn", "for learn", "learning of"),
    ("'I learn best by ___ things down.'", "writing", "write", "to write",
     "for write"),
    ("'I find it hard ___ new words.'", "to remember", "remembering of",
     "remember", "for remember"),
    ("'It ___ me about a year to get confident.'", "took", "spent", "lasted of",
     "made of"),
    ("'I make a ___ of reading ten minutes a day.'", "point", "habit to be",
     "rule of doing of", "custom of"),
    ("'Practice ___ perfect.'", "makes", "does", "gives", "takes"),
    ("'I've got into the ___ of listening to podcasts.'", "habit", "custom of",
     "routine to be", "practice of it"),
    ("'Don't be afraid ___ mistakes.'", "of making", "to making", "of make",
     "for make"),
    ("Which is the best learning advice?",
     "Study a little every day rather than a lot once a week.",
     "Study only before exams.", "Learn every word in the dictionary.",
     "Never write anything down."),
]

P10_AC_V = [
    ("look after", "take care of"),
    ("look for", "try to find"),
    ("look into", "investigate"),
    ("look up", "find information in a book or online"),
    ("take off", "remove clothing, or leave the ground"),
    ("take back", "return something to a shop"),
    ("take over", "get control of something"),
    ("put off", "delay to a later time"),
    ("put up with", "accept something unpleasant"),
    ("give back", "return something to its owner"),
    ("give in", "stop resisting"),
    ("get on with", "have a good relationship with"),
    ("get over", "recover from something"),
    ("get rid of", "remove something you do not want"),
    ("turn down", "refuse an offer, or lower the volume"),
    ("turn up", "arrive, often unexpectedly"),
    ("run out of", "have no more of something"),
    ("come across", "find by chance"),
    ("bring up", "raise a child, or mention a subject"),
    ("work out", "calculate, or exercise"),
    ("carry on", "continue"),
    ("set off", "begin a journey"),
    ("sort out", "solve or organise"),
    ("deal with", "take action about a problem"),
    ("find out", "discover information"),
]

P10_AC_G = [
    ("If I ___ rich, I'd travel the world.", "were", "am", "will be",
     "would be"),
    ("If she had more time, she ___ study Chinese.", "would", "will", "did",
     "would to"),
    ("What would you do if you ___ the lottery?", "won", "win", "would win",
     "will win"),
    ("If I were you, I ___ take that job.", "would", "will", "am", "would to"),
    ("He would help if he ___ how.", "knew", "knows", "would know",
     "will know"),
    ("Which is correct?", "If I had a car, I would drive there.",
     "If I would have a car, I would drive.", "If I have a car, I would drive.",
     "If I had a car, I will drive."),
    ("Which sentence is imaginary, not a real plan?",
     "If I lived in London, I'd go to the theatre every week.",
     "If I live in London, I'll go to the theatre.",
     "When I live in London, I'll go.", "I live in London and go."),
    ("We ___ buy a bigger flat if we could afford it.", "would", "will",
     "would to", "did"),
    ("Which is WRONG?", "If I would be you, I would wait.",
     "If I were you, I would wait.", "If I was you, I would wait.",
     "I would wait if I were you."),
    ("If they ___ earlier, they wouldn't be late.", "left", "leave",
     "would leave", "will leave"),
    ("She wouldn't say that if she ___ the truth.", "knew", "knows",
     "would know", "will know"),
    ("Which half has 'would'?", "the result half", "the if half",
     "both halves", "neither half"),
    ("If we ___ more staff, the work would be easier.", "had", "have",
     "would have", "will have"),
    ("I'd call him if I ___ his number.", "had", "have", "would have",
     "will have"),
    ("Which is a second conditional?", "If I saw her, I'd say hello.",
     "If I see her, I'll say hello.", "When I see her, I say hello.",
     "I see her and say hello."),
    ("Life ___ be easier if we lived nearer.", "would", "will", "would to",
     "did"),
    ("In a shop: 'I'd like to ___ this, please. It's faulty.'", "return",
     "give of back", "bring of", "change of it"),
    ("'Have you got the ___ ?' 'Yes, here it is.'", "receipt", "bill of pay",
     "ticket of money", "paper of shop"),
    ("'Would you like a refund or an ___ ?'", "exchange", "change of",
     "changing of", "exchanging to"),
    ("'I'm afraid it's ___ the thirty-day period.'", "outside", "out of time of",
     "over of", "past of it"),
    ("'I'd like to make a ___ .'", "complaint", "complain of", "complaining of",
     "complained of"),
    ("'Could I speak to the ___ , please?'", "manager", "chief of", "boss of it",
     "leader of shop"),
    ("'It stopped working after ___ days.'", "two", "second of", "twice of",
     "double of"),
    ("'I'm sorry about that. Let me ___ it for you.'", "sort out", "sort of",
     "sorting out of", "sorted of"),
    ("Which complaint is most likely to work?",
     "It stopped working after two days. Could I have a refund, please?",
     "This is rubbish.", "Give me my money.", "You sold me a bad thing."),
]

P10_BD_V = [
    ("bargain", "something bought cheaply"),
    ("brand", "the maker's name on a product"),
    ("customer service", "the help a shop gives buyers"),
    ("delivery", "bringing goods to your address"),
    ("faulty", "not working properly"),
    ("guarantee", "a promise to repair or replace"),
    ("purchase", "something you buy"),
    ("queue", "a line of people waiting"),
    ("refund", "money given back"),
    ("stock", "the goods a shop has"),
    ("out of stock", "not available at the moment"),
    ("trolley", "you push it round a supermarket"),
    ("receipt", "proof of purchase"),
    ("checkout", "where you pay in a shop"),
    ("online shopping", "buying over the internet"),
    ("special offer", "a temporary lower price"),
    ("advertisement", "a public message to sell something"),
    ("consumer", "a person who buys goods"),
    ("value for money", "worth what you paid"),
    ("second-hand", "owned by somebody before"),
    ("shopping list", "what you plan to buy"),
    ("spend", "use money"),
    ("save up", "collect money over time for something"),
    ("afford", "have enough money for"),
    ("waste", "spend badly, with no benefit"),
]

P10_BD_G = [
    ("There isn't ___ milk left.", "much", "many", "a lot", "few"),
    ("There aren't ___ shops in this street.", "many", "much", "a little",
     "a lot"),
    ("I've got ___ money, so I can pay.", "enough", "enough of", "too much of",
     "quite of"),
    ("This coffee is ___ hot to drink.", "too", "very much", "enough",
     "so much of"),
    ("The room isn't big ___ for twenty people.", "enough", "too", "so",
     "quite of"),
    ("We have ___ time. Let's hurry.", "too little", "too few", "not many of",
     "little of too"),
    ("There were ___ people that we couldn't move.", "so many", "so much",
     "too many of that", "such many"),
    ("Which goes with uncountable nouns?", "much", "many", "few", "a number of"),
    ("Which goes with countable nouns?", "few", "much", "a little",
     "a bit of"),
    ("Which is correct?", "I have too much work.", "I have too many work.",
     "I have too work much.", "I have work too much of."),
    ("Which is WRONG?", "There are too much cars.", "There are too many cars.",
     "There is too much traffic.", "There aren't many cars."),
    ("She spends ___ on clothes.", "too much", "too many", "much too of",
     "so many of"),
    ("Only a ___ shops open on Sunday.", "few", "little", "much", "bit of"),
    ("Add a ___ salt to the soup.", "little", "few", "many", "number of"),
    ("There's ___ food for everybody.", "enough", "enough of it", "too few",
     "quite of"),
    ("I don't have ___ friends here yet.", "many", "much", "a little",
     "a bit of"),
    ("An apology email begins: 'I'm writing to ___ for the delay.'",
     "apologise", "apology of", "sorry of", "apologising of"),
    ("'Please ___ my sincere apologies.'", "accept", "receive of", "take of it",
     "have of"),
    ("'It ___ not happen again.'", "will", "shall of", "does", "would of"),
    ("'We ___ the inconvenience this has caused.'", "regret", "sorry of",
     "apologise of", "regretting of"),
    ("'As a ___ of goodwill, we'll refund the delivery.'", "gesture",
     "sign of good", "mark of it", "show of us"),
    ("'Thank you for ___ this to our attention.'", "bringing", "taking",
     "putting of", "giving of"),
    ("'We are ___ into what went wrong.'", "looking", "seeing of", "watching of",
     "finding of"),
    ("Which is a full apology?",
     "I'm sorry for the mistake; here is what we will do about it.",
     "Sorry if you were upset.", "Mistakes happen.",
     "We apologise for any inconvenience possibly caused if any."),
    ("Which closing suits an apology email?", "Once again, my apologies,",
     "Deal with it,", "Whatever happens happens,", "Bye now,"),
]

P11_AC_V = [
    ("traffic jam", "a long line of cars that cannot move"),
    ("rush hour", "the time when most people travel to work"),
    ("car park", "a place to leave your car"),
    ("city centre", "the middle of a city"),
    ("railway station", "where trains stop"),
    ("bus stop", "where a bus picks people up"),
    ("post office", "where you send letters"),
    ("police station", "the base of the local police"),
    ("shopping centre", "a building with many shops"),
    ("swimming pool", "a place built for swimming"),
    ("football pitch", "the ground a match is played on"),
    ("credit card", "a card you pay with and settle later"),
    ("mobile phone", "a phone you carry with you"),
    ("text message", "a short written message by phone"),
    ("headache", "a pain in your head"),
    ("sunglasses", "dark glasses for bright light"),
    ("toothbrush", "what you clean your teeth with"),
    ("newspaper", "printed daily news"),
    ("timetable", "the list of times for transport or lessons"),
    ("alarm clock", "the clock that wakes you"),
    ("washing machine", "the machine that washes clothes"),
    ("living room", "the room where you relax"),
    ("dining room", "the room where you eat"),
    ("homework", "school work done at home"),
    ("weekend", "Saturday and Sunday"),
]

P11_AC_G = [
    ("The man ___ lives next door is a doctor.", "who", "which", "whose",
     "what"),
    ("This is the book ___ I told you about.", "that", "who", "whose", "what"),
    ("That's the woman ___ car was stolen.", "whose", "who's", "which",
     "that's"),
    ("The cafe ___ we met has closed.", "where", "which", "who", "when"),
    ("Do you remember the day ___ we first met?", "when", "which", "where",
     "who"),
    ("Which is correct?", "The film that we saw was great.",
     "The film what we saw was great.", "The film who we saw was great.",
     "The film whose we saw was great."),
    ("Which relative pronoun is for people?", "who", "which", "where", "when"),
    ("Which relative pronoun is for things?", "which", "who", "whose", "when"),
    ("She's the teacher ___ helped me most.", "who", "which", "whose", "whom of"),
    ("Which is WRONG?", "The house which I live is old.",
     "The house where I live is old.", "The house that I live in is old.",
     "The house I live in is old."),
    ("A dictionary is a book ___ explains words.", "that", "who", "whose",
     "where"),
    ("The shop ___ sells the best bread is on the corner.", "that", "who",
     "where", "what"),
    ("A compound noun is ___ .", "two nouns used as one word",
     "a noun plus an adjective always", "a verb with -ing",
     "a noun with an article"),
    ("Which is a compound noun?", "bus stop", "very fast", "quickly run",
     "beautiful house"),
    ("Where is the stress in 'POST office'?", "on the first word",
     "on the second word", "on both equally", "on neither"),
    ("Which is one word?", "toothbrush", "bus stop", "swimming pool",
     "credit card"),
    ("Asking directions: 'Could you tell me the way ___ the station?'", "to",
     "for", "at", "of"),
    ("'Go straight ___ until you reach the bank.'", "on", "at", "for", "to"),
    ("'Take the second turning ___ the right.'", "on", "at of", "to of",
     "in of"),
    ("'It's ___ the post office and the cafe.'", "between", "among",
     "in middle of", "next of"),
    ("'Sorry, did you say the second or the third ___ ?'", "turning",
     "turn of it", "corner of turn", "street of turn"),
    ("'So that's left at the lights, ___ ?'", "is it", "isn't it", "does it",
     "right of"),
    ("'Let me just check: the bank is opposite the park, ___ ?'", "right",
     "correct of it", "true of", "yes of it"),
    ("'You can't ___ it. It's the big blue building.'", "miss", "lose of",
     "fail of", "pass of"),
    ("Which is the clearest direction?",
     "Go straight on for two minutes, then turn left at the traffic lights.",
     "Go there somehow.", "It's over that way a bit.",
     "Near the thing you saw before."),
]

P11_BD_V = [
    ("luck", "good or bad things that happen by chance"),
    ("lucky", "having good things happen by chance"),
    ("unlucky", "having bad things happen by chance"),
    ("chance", "the possibility that something happens"),
    ("coincidence", "two things happening together by chance"),
    ("fortunately", "happily, as things turned out"),
    ("unfortunately", "sadly, as things turned out"),
    ("by chance", "not planned"),
    ("on purpose", "deliberately"),
    ("luckily", "it was good that this happened"),
    ("miss out on", "lose a chance to have something"),
    ("opportunity", "a good chance to do something"),
    ("risk", "the possibility of something bad"),
    ("take a risk", "do something that might go wrong"),
    ("succeed", "achieve what you tried to do"),
    ("fail", "not achieve what you tried to do"),
    ("win", "come first in a competition"),
    ("lose", "not win"),
    ("prize", "what a winner receives"),
    ("lottery", "a game where numbers win money"),
    ("guess", "give an answer without being sure"),
    ("predict", "say what will happen"),
    ("certain", "completely sure"),
    ("probably", "very likely"),
    ("possibly", "perhaps"),
]

P11_BD_G = [
    ("I bought ___ umbrella yesterday.", "an", "a", "the", "some of"),
    ("___ umbrella I bought is broken.", "The", "A", "An", "Some"),
    ("She's ___ engineer.", "an", "a", "the", "one of"),
    ("We went to ___ cinema last night.", "the", "a", "an", "some"),
    ("___ Tashkent is the capital.", "(no article)", "The", "A", "An"),
    ("He plays ___ guitar very well.", "the", "a", "an", "(no article)"),
    ("I go to ___ school by bus.", "(no article)", "the", "a", "an"),
    ("Which is correct?", "I had breakfast at eight.",
     "I had the breakfast at eight.", "I had a breakfast at eight.",
     "I had breakfasts at eight."),
    ("Which is WRONG?", "She is the engineer by profession.",
     "She is an engineer.", "She is the engineer we met.",
     "She works as an engineer."),
    ("Do you like ___ music?", "(no article)", "the", "a", "an"),
    ("___ sun is very strong today.", "The", "A", "An", "(no article)"),
    ("We stayed at ___ hotel near the station.", "a", "an", "the", "(no article)"),
    ("___ hotel was very comfortable.", "The", "A", "An", "(no article)"),
    ("He's ___ best teacher in the school.", "the", "a", "an", "(no article)"),
    ("I saw ___ interesting film last night.", "an", "a", "the", "(no article)"),
    ("Which noun usually takes no article when general?", "advice", "book",
     "chair", "idea"),
    ("'I ___ found a job through a friend.'", "luckily", "lucky", "luck of",
     "luckier of"),
    ("'It was pure ___ that we met.'", "chance", "chancy of", "lucky of",
     "chanced of"),
    ("'___ , the shop was still open.'", "Fortunately", "Fortunate of",
     "Fortune of", "Fortunately of it"),
    ("An opinion post states your view ___ .", "clearly at the start",
     "only at the very end", "never directly", "in the title only"),
    ("'In my ___ , online learning suits some people better.'", "opinion",
     "opinions of me", "thought of", "mind of"),
    ("'___ , not everybody has a good internet connection.'", "However",
     "But however of", "Although of", "Despite of"),
    ("'For ___ , my cousin studies at night after work.'", "example",
     "examples of", "instance of it", "sample of"),
    ("'To ___ up, I think both ways can work.'", "sum", "add of", "finish of",
     "close of it"),
    ("Which opening is strongest for an opinion post?",
     "Should students learn online? I believe they should, for two reasons.",
     "This is a post about online learning.",
     "Hello everybody, today I write.", "Online learning exists now."),
]

P12_AC_V = [
    ("relative", "a member of your family"),
    ("generation", "people born around the same time"),
    ("ancestor", "a family member from long ago"),
    ("cousin", "your aunt's or uncle's child"),
    ("niece", "your brother's or sister's daughter"),
    ("nephew", "your brother's or sister's son"),
    ("in-laws", "your husband's or wife's family"),
    ("grandchild", "your child's child"),
    ("adopt", "take a child into your family legally"),
    ("inherit", "receive something from somebody who died"),
    ("resemble", "look like somebody"),
    ("take after", "be like an older relative"),
    ("bring up", "look after a child until they grow up"),
    ("get married", "become husband and wife"),
    ("get divorced", "legally end a marriage"),
    ("argue", "disagree in an angry way"),
    ("make up", "become friends again after an argument"),
    ("support", "help somebody through difficulty"),
    ("close", "having a strong warm relationship"),
    ("distant", "not close, in family or feeling"),
    ("family tree", "a drawing showing how a family connects"),
    ("only child", "a child with no brothers or sisters"),
    ("twin", "one of two children born together"),
    ("household", "all the people living in one home"),
    ("upbringing", "the way you were raised"),
]

P12_AC_G = [
    ("When I arrived, they ___ already left.", "had", "have", "has", "were"),
    ("She couldn't get in because she ___ her key.", "had lost", "lost",
     "has lost", "was losing"),
    ("By the time we got there, the film ___ .", "had started", "started",
     "has started", "was starting"),
    ("He told me he ___ the book before.", "had read", "read then",
     "has read", "was reading"),
    ("I didn't recognise her because she ___ her hair.", "had cut",
     "cut then", "has cut", "was cutting"),
    ("Which happened first?", "the past perfect action",
     "the past simple action", "both together", "neither"),
    ("Which is correct?", "After he had finished, he went home.",
     "After he has finished, he went home.",
     "After he finished, he had gone home.",
     "After he had finished, he has gone home."),
    ("They ___ never been abroad before that trip.", "had", "have", "has",
     "were"),
    ("Which is WRONG?", "I had went home early.", "I had gone home early.",
     "I went home early.", "I had already gone home."),
    ("We were late because the bus ___ without us.", "had gone", "went then",
     "has gone", "was going"),
    ("When the police arrived, the thief ___ .", "had escaped", "escaped then",
     "has escaped", "was escaping then"),
    ("She said she ___ the email that morning.", "had sent", "sent then",
     "has sent", "was sending"),
    ("By 2020 he ___ three books.", "had written", "wrote then",
     "has written", "was writing"),
    ("I ___ the film before, so I knew the ending.", "had seen", "saw then",
     "have seen", "was seeing"),
    ("Which sentence needs the past perfect?",
     "He was tired because he had worked all night.",
     "He was tired and he worked all night together.",
     "He worked all night and was tired after.",
     "He is tired because he works all night."),
    ("Everything ___ changed by the time she came back.", "had", "have", "has",
     "was"),
    ("Agreeing: 'I couldn't ___ more.'", "agree", "agree of it", "be agree",
     "agreeing"),
    ("Disagreeing politely: 'I see your point, ___ I'm not sure.'", "but",
     "however of", "although of", "despite of"),
    ("'That's ___ true, but there's another side.'", "partly", "part of",
     "partial of", "partially of it"),
    ("'I'm afraid I ___ with you there.'", "disagree", "am disagree",
     "disagreeing of", "don't agree of it"),
    ("'Absolutely. That's ___ what I think.'", "exactly", "exact of",
     "exactness of", "exactly of it"),
    ("'Do you really ___ so?'", "think", "thinking of", "thought of",
     "believe of it"),
    ("'I'd say the ___ .'", "opposite", "opposed of", "contrary of it",
     "reverse of it"),
    ("Which is the politest disagreement?",
     "I take your point, but I see it differently.",
     "You're wrong.", "That makes no sense.", "No, that's rubbish."),
    ("Which shows strong agreement?", "That's exactly how I feel.",
     "Maybe, I don't know.", "If you say so.", "Possibly not."),
]

P12_BD_V = [
    ("news report", "a factual account of a recent event"),
    ("headline", "the title of a news story"),
    ("journalist", "somebody who reports the news"),
    ("witness", "somebody who saw an event"),
    ("source", "where information comes from"),
    ("evidence", "facts that show something is true"),
    ("investigate", "try to find out the facts"),
    ("announce", "tell the public officially"),
    ("claim", "say something is true without proof"),
    ("deny", "say something is not true"),
    ("admit", "agree that something is true"),
    ("report", "give an account of something"),
    ("broadcast", "send out on TV or radio"),
    ("update", "the newest information"),
    ("rumour", "an unconfirmed story"),
    ("front page", "the first page of a newspaper"),
    ("article", "a piece of writing in a paper"),
    ("editor", "the person in charge of a publication"),
    ("interview", "a conversation to get information"),
    ("statement", "an official written or spoken account"),
    ("emergency", "a dangerous situation needing fast action"),
    ("rescue", "save somebody from danger"),
    ("injured", "hurt in an accident"),
    ("survivor", "somebody still alive after a disaster"),
    ("eyewitness", "somebody who saw it happen"),
]

P12_BD_G = [
    ("She said she ___ tired.", "was", "is", "has been", "will be"),
    ("He told me he ___ call later.", "would", "will", "is going", "shall"),
    ("They said they ___ finished.", "had", "have", "has", "were"),
    ("She said she ___ in Tashkent.", "lived", "lives", "is living",
     "has lived"),
    ("He said he ___ see the film the next day.", "would", "will", "is",
     "shall"),
    ("Which is correct?", "He said he was busy.", "He said he is busy then.",
     "He said that he busy.", "He said he be busy."),
    ("'I'm going home,' she said. She said she ___ home.", "was going",
     "is going", "goes", "will go"),
    ("'I finished it,' he said. He said he ___ it.", "had finished",
     "has finished", "finished then", "was finishing"),
    ("She asked me where I ___ .", "lived", "live", "do live", "am living"),
    ("He asked if I ___ help.", "needed", "need", "do need", "am needing"),
    ("Which is WRONG?", "She asked me where do I live.",
     "She asked me where I lived.", "She asked where I lived.",
     "She asked me if I lived there."),
    ("'Don't be late,' he said. He told me ___ late.", "not to be",
     "to not be of", "don't be of", "that not be"),
    ("'Please sit down,' she said. She asked me ___ .", "to sit down",
     "sit down", "that sit down", "for sitting down"),
    ("In reported speech, 'tomorrow' usually becomes ___ .", "the next day",
     "yesterday", "that day before", "the day of before"),
    ("In reported speech, 'here' usually becomes ___ .", "there", "here still",
     "where of", "then"),
    ("Which verb introduces a question in reported speech?", "asked", "said",
     "told me that", "spoke"),
    ("A news report usually answers ___ .", "who, what, where and when",
     "only who", "only the writer's opinion", "the price of things"),
    ("'Police ___ the cause of the fire is unknown.'", "say", "says of",
     "saying of", "said of it that"),
    ("'The driver ___ to hospital with minor injuries.'", "was taken", "took",
     "is taking", "was taking"),
    ("'No one ___ seriously hurt.'", "was", "were", "has", "did"),
    ("'An eyewitness ___ she heard a loud noise.'", "said", "told", "spoke of",
     "says of it"),
    ("'The council ___ a statement this morning.'", "issued", "gave of out",
     "made of it out", "published of out"),
    ("Which sentence is neutral, as a report should be?",
     "Three people were injured in the accident.",
     "It was a horrible terrible accident.",
     "Somebody clearly drove badly.", "This shows the roads are awful."),
    ("'The road ___ closed for two hours.'", "remained", "stayed of",
     "kept of", "continued of"),
    ("Which is a good headline?", "Flood closes main road for two hours",
     "Something happened on a road", "Road news of today",
     "A report about a road that was closed by water for a time"),
]

LISTS = [
    ("Unit 9A&C · Vocabulary — cooking and eating", "vocab", 17, P9_AC_V),
    ("Unit 9A&C · Grammar — the first conditional, and phone calls", "grammar", 17, P9_AC_G),
    ("Unit 9B&D · Vocabulary — fame and success", "vocab", 18, P9_BD_V),
    ("Unit 9B&D · Grammar — verb patterns, and how you learn", "grammar", 18, P9_BD_G),
    ("Unit 10A&C · Vocabulary — multi-word verbs", "vocab", 19, P10_AC_V),
    ("Unit 10A&C · Grammar — the second conditional, and complaints", "grammar", 19, P10_AC_G),
    ("Unit 10B&D · Vocabulary — shopping", "vocab", 20, P10_BD_V),
    ("Unit 10B&D · Grammar — how much is enough, and apologies", "grammar", 20, P10_BD_G),
    ("Unit 11A&C · Vocabulary — compound nouns", "vocab", 21, P11_AC_V),
    ("Unit 11A&C · Grammar — relative clauses, and directions", "grammar", 21, P11_AC_G),
    ("Unit 11B&D · Vocabulary — luck and chance", "vocab", 22, P11_BD_V),
    ("Unit 11B&D · Grammar — a, an and the, and an opinion post", "grammar", 22, P11_BD_G),
    ("Unit 12A&C · Vocabulary — family", "vocab", 23, P12_AC_V),
    ("Unit 12A&C · Grammar — the past perfect, and agreeing", "grammar", 23, P12_AC_G),
    ("Unit 12B&D · Vocabulary — the news", "vocab", 24, P12_BD_V),
    ("Unit 12B&D · Grammar — reported speech, and news reports", "grammar", 24, P12_BD_G),
]
